import type { UnitLearningMaterials } from "./types";

/**
 * Learning materials are loaded per unit, on demand.
 *
 * There are hundreds of units and eight content blocks each; bundling them the
 * way `lessons.ts` bundles vocabulary would make every learner download all of
 * it to open one. A dynamic import keeps a unit's materials out of the main
 * bundle until someone opens that unit's Learn screen.
 *
 * GENERATED by scripts/build-learning-materials.mjs — do not hand-edit.
 * Units absent from this map have no materials in the design file yet;
 * callers get `null` and hide the entry point rather than showing an empty
 * screen.
 */
const LOADERS: Record<string, () => Promise<UnitLearningMaterials>> = {
  "3d-printer-lab": () => import("./units/3d-printer-lab").then((m) => m._3D_PRINTER_LAB_LEARNING),
  "amusement-park": () => import("./units/amusement-park").then((m) => m.AMUSEMENT_PARK_LEARNING),
  arctic: () => import("./units/arctic").then((m) => m.ARCTIC_LEARNING),
  bakery: () => import("./units/bakery").then((m) => m.BAKERY_LEARNING),
  barbershop: () => import("./units/barbershop").then((m) => m.BARBERSHOP_LEARNING),
  bathroom: () => import("./units/bathroom").then((m) => m.BATHROOM_LEARNING),
  bedroom: () => import("./units/bedroom").then((m) => m.BEDROOM_LEARNING),
  "bicycle-shop": () => import("./units/bicycle-shop").then((m) => m.BICYCLE_SHOP_LEARNING),
  "bird-sanctuary": () => import("./units/bird-sanctuary").then((m) => m.BIRD_SANCTUARY_LEARNING),
  "birthday-party": () => import("./units/birthday-party").then((m) => m.BIRTHDAY_PARTY_LEARNING),
  "bus-station": () => import("./units/bus-station").then((m) => m.BUS_STATION_LEARNING),
  "butterfly-garden": () =>
    import("./units/butterfly-garden").then((m) => m.BUTTERFLY_GARDEN_LEARNING),
  "camping-site": () => import("./units/camping-site").then((m) => m.CAMPING_SITE_LEARNING),
  "car-wash": () => import("./units/car-wash").then((m) => m.CAR_WASH_LEARNING),
  classroom: () => import("./units/classroom").then((m) => m.CLASSROOM_LEARNING),
  "coffee-shop": () => import("./units/coffee-shop").then((m) => m.COFFEE_SHOP_LEARNING),
  "community-center": () =>
    import("./units/community-center").then((m) => m.COMMUNITY_CENTER_LEARNING),
  "computer-lab": () => import("./units/computer-lab").then((m) => m.COMPUTER_LAB_LEARNING),
  "construction-site": () =>
    import("./units/construction-site").then((m) => m.CONSTRUCTION_SITE_LEARNING),
  "coral-reef": () => import("./units/coral-reef").then((m) => m.CORAL_REEF_LEARNING),
  "costume-shop": () => import("./units/costume-shop").then((m) => m.COSTUME_SHOP_LEARNING),
  courtroom: () => import("./units/courtroom").then((m) => m.COURTROOM_LEARNING),
  "dance-studio": () => import("./units/dance-studio").then((m) => m.DANCE_STUDIO_LEARNING),
  "data-center": () => import("./units/data-center").then((m) => m.DATA_CENTER_LEARNING),
  "dental-clinic": () => import("./units/dental-clinic").then((m) => m.DENTAL_CLINIC_LEARNING),
  dentist: () => import("./units/dentist").then((m) => m.DENTIST_LEARNING),
  desert: () => import("./units/desert").then((m) => m.DESERT_LEARNING),
  "drone-workshop": () => import("./units/drone-workshop").then((m) => m.DRONE_WORKSHOP_LEARNING),
  "electric-vehicle-station": () =>
    import("./units/electric-vehicle-station").then((m) => m.ELECTRIC_VEHICLE_STATION_LEARNING),
  embassy: () => import("./units/embassy").then((m) => m.EMBASSY_LEARNING),
  "eye-doctor": () => import("./units/eye-doctor").then((m) => m.EYE_DOCTOR_LEARNING),
  farm: () => import("./units/farm").then((m) => m.FARM_LEARNING),
  festival: () => import("./units/festival").then((m) => m.FESTIVAL_LEARNING),
  "first-aid-room": () => import("./units/first-aid-room").then((m) => m.FIRST_AID_ROOM_LEARNING),
  forest: () => import("./units/forest").then((m) => m.FOREST_LEARNING),
  garden: () => import("./units/garden").then((m) => m.GARDEN_LEARNING),
  "gas-station": () => import("./units/gas-station").then((m) => m.GAS_STATION_LEARNING),
  graduation: () => import("./units/graduation").then((m) => m.GRADUATION_LEARNING),
  gym: () => import("./units/gym").then((m) => m.GYM_LEARNING),
  "hair-salon": () => import("./units/hair-salon").then((m) => m.HAIR_SALON_LEARNING),
  harbor: () => import("./units/harbor").then((m) => m.HARBOR_LEARNING),
  hotel: () => import("./units/hotel").then((m) => m.HOTEL_LEARNING),
  "ice-cream-shop": () => import("./units/ice-cream-shop").then((m) => m.ICE_CREAM_SHOP_LEARNING),
  "insect-world": () => import("./units/insect-world").then((m) => m.INSECT_WORLD_LEARNING),
  jungle: () => import("./units/jungle").then((m) => m.JUNGLE_LEARNING),
  kitchen: () => import("./units/kitchen").then((m) => m.KITCHEN_LEARNING),
  laboratory: () => import("./units/laboratory").then((m) => m.LABORATORY_LEARNING),
  laundromat: () => import("./units/laundromat").then((m) => m.LAUNDROMAT_LEARNING),
  library: () => import("./units/library").then((m) => m.LIBRARY_LEARNING),
  "living-room": () => import("./units/living-room").then((m) => m.LIVING_ROOM_LEARNING),
  market: () => import("./units/market").then((m) => m.MARKET_LEARNING),
  mechanic: () => import("./units/mechanic").then((m) => m.MECHANIC_LEARNING),
  mountain: () => import("./units/mountain").then((m) => m.MOUNTAIN_LEARNING),
  "newspaper-office": () =>
    import("./units/newspaper-office").then((m) => m.NEWSPAPER_OFFICE_LEARNING),
  observatory: () => import("./units/observatory").then((m) => m.OBSERVATORY_LEARNING),
  orchestra: () => import("./units/orchestra").then((m) => m.ORCHESTRA_LEARNING),
  park: () => import("./units/park").then((m) => m.PARK_LEARNING),
  "pet-shop": () => import("./units/pet-shop").then((m) => m.PET_SHOP_LEARNING),
  pharmacy: () => import("./units/pharmacy").then((m) => m.PHARMACY_LEARNING),
  "photography-studio": () =>
    import("./units/photography-studio").then((m) => m.PHOTOGRAPHY_STUDIO_LEARNING),
  "pizza-shop": () => import("./units/pizza-shop").then((m) => m.PIZZA_SHOP_LEARNING),
  playground: () => import("./units/playground").then((m) => m.PLAYGROUND_LEARNING),
  "police-station": () => import("./units/police-station").then((m) => m.POLICE_STATION_LEARNING),
  "pottery-studio": () => import("./units/pottery-studio").then((m) => m.POTTERY_STUDIO_LEARNING),
  "radio-station": () => import("./units/radio-station").then((m) => m.RADIO_STATION_LEARNING),
  "reptile-house": () => import("./units/reptile-house").then((m) => m.REPTILE_HOUSE_LEARNING),
  river: () => import("./units/river").then((m) => m.RIVER_LEARNING),
  "robotics-lab": () => import("./units/robotics-lab").then((m) => m.ROBOTICS_LAB_LEARNING),
  savanna: () => import("./units/savanna").then((m) => m.SAVANNA_LEARNING),
  "shopping-mall": () => import("./units/shopping-mall").then((m) => m.SHOPPING_MALL_LEARNING),
  "smart-home": () => import("./units/smart-home").then((m) => m.SMART_HOME_LEARNING),
  "solar-farm": () => import("./units/solar-farm").then((m) => m.SOLAR_FARM_LEARNING),
  spa: () => import("./units/spa").then((m) => m.SPA_LEARNING),
  "space-station": () => import("./units/space-station").then((m) => m.SPACE_STATION_LEARNING),
  submarine: () => import("./units/submarine").then((m) => m.SUBMARINE_LEARNING),
  subway: () => import("./units/subway").then((m) => m.SUBWAY_LEARNING),
  supermarket: () => import("./units/supermarket").then((m) => m.SUPERMARKET_LEARNING),
  "tailor-shop": () => import("./units/tailor-shop").then((m) => m.TAILOR_SHOP_LEARNING),
  theater: () => import("./units/theater").then((m) => m.THEATER_LEARNING),
  "tv-studio": () => import("./units/tv-studio").then((m) => m.TV_STUDIO_LEARNING),
  "vet-clinic": () => import("./units/vet-clinic").then((m) => m.VET_CLINIC_LEARNING),
  volcano: () => import("./units/volcano").then((m) => m.VOLCANO_LEARNING),
  "weather-station": () =>
    import("./units/weather-station").then((m) => m.WEATHER_STATION_LEARNING),
  wedding: () => import("./units/wedding").then((m) => m.WEDDING_LEARNING),
};

const cache = new Map<string, UnitLearningMaterials>();

export function hasLearningMaterials(unitId: string): boolean {
  return unitId in LOADERS;
}

/** Unit ids with materials, for tests and for coverage reporting. */
export function unitsWithLearningMaterials(): string[] {
  return Object.keys(LOADERS);
}

export async function loadLearningMaterials(unitId: string): Promise<UnitLearningMaterials | null> {
  const cached = cache.get(unitId);
  if (cached) return cached;

  const loader = LOADERS[unitId];
  if (!loader) return null;

  const materials = await loader();
  cache.set(unitId, materials);
  return materials;
}
