// Learning materials for "The Amusement Park".
//
// GENERATED by scripts/build-learning-materials.mjs from figma-dump/amusement-park.json.
// Figma is the source of truth: edit the design file and re-run the sync,
// do not hand-edit this file.

import type { UnitLearningMaterials } from "../types";

export const AMUSEMENT_PARK_LEARNING: UnitLearningMaterials = {
  unitId: "amusement-park",
  subtopics: [
    {
      id: "thrill-rides",
      title: "Thrill Rides",
      wordIds: [
        "roller-coaster",
        "ferris-wheel",
        "drop-tower",
        "spinning-ride",
        "water-slide",
        "log-flume",
        "pirate-ship",
        "loop-ride",
        "launch-coaster",
        "pendulum-ride",
      ],
    },
    {
      id: "family-rides",
      title: "Family Rides",
      wordIds: [
        "carousel",
        "bumper-cars",
        "go-karts",
        "train-ride",
        "tea-cups",
        "flying-swings",
        "boat-ride",
        "monorail",
        "haunted-house",
        "fun-house",
      ],
    },
    {
      id: "games-prizes",
      title: "Games & Prizes",
      wordIds: [
        "ring-toss",
        "balloon-dart",
        "basketball-throw",
        "claw-machine",
        "whack-a-mole",
        "strength-test",
        "water-gun-game",
        "prize-booth",
        "stuffed-animal",
        "giant-teddy-bear",
      ],
    },
    {
      id: "park-food",
      title: "Park Food",
      wordIds: [
        "cotton-candy",
        "funnel-cake",
        "corn-dog",
        "popcorn",
        "candy-apple",
        "churro",
        "soft-pretzel",
        "ice-cream-cone",
        "lemonade",
        "snow-cone",
      ],
    },
    {
      id: "park-features",
      title: "Park Features",
      wordIds: [
        "entrance-gate",
        "ticket-booth",
        "map-board",
        "restroom",
        "first-aid",
        "lost-and-found",
        "souvenir-shop",
        "photo-spot",
        "stage",
        "fountain",
      ],
    },
    {
      id: "entertainment",
      title: "Entertainment",
      wordIds: [
        "parade",
        "fireworks",
        "mascot",
        "stilt-walker",
        "juggler",
        "face-painter",
        "street-performer",
        "magician",
        "dance-show",
        "marching-band",
        "go-kart",
        "swing-ride",
        "arcade",
        "photo-booth",
        "stage-show",
        "parade-float",
        "ticket",
        "wristband",
        "park-map",
        "souvenir",
      ],
    },
  ],
  passage: {
    title: "Reading Passage",
    level: "B1",
    text: "Thrills and Fun\n\nFor my birthday, my parents took me and two friends to an amusement park. We arrived when the gates opened at ten o'clock so we could make the most of the day.\n\nThe first ride we tried was the roller coaster. We waited in a queue for about twenty minutes before it was our turn. The ride started slowly as the car climbed to the top of the first hill. Then it dropped steeply and raced through loops, twists, and sharp turns. My friends screamed the whole time, but I just laughed.\n\nAfter that, we went on the bumper cars. Each person drives a small electric car and tries to bump into the other cars. It was chaotic but hilarious. We also tried the spinning teacups ride, which made us quite dizzy.\n\nAt lunchtime, we stopped at a food stall and bought burgers, chips, and lemonade. The prices were expensive, but we were too hungry to care. We sat on a bench near the Ferris wheel and watched it turn slowly against the blue sky.\n\nIn the afternoon, we visited the haunted house attraction. It was dark inside, with spooky sounds, flashing lights, and actors dressed as ghosts who jumped out to scare us. One of my friends grabbed my arm so tightly that he left a mark!\n\nBefore leaving, we played some carnival games. I tried to knock down tin cans with a ball and won a small stuffed bear. My friend tried the hook-a-duck game and won a goldfish in a bag.\n\nWe left the park at six o'clock, exhausted but happy. It was the best birthday I have ever had.",
    questions: [],
    openQuestions: [
      "Why did they arrive when the park opened?",
      "What happens on a roller coaster ride?",
      "What made the narrator dizzy?",
      "What happened in the haunted house?",
      "What prizes did they win at the carnival games?",
    ],
  },
  phrases: [
    {
      id: "amusement-park-a-roller-coaster-of-emotions",
      phrase: "a roller coaster of emotions",
      kind: "idiom",
      kindInferred: true,
      meaning: "a situation with many ups and downs",
      example:
        "The day was a roller coaster of emotions — thrilling on the roller coaster, scary on the drop tower, and dizzy on the spinning ride.",
    },
    {
      id: "amusement-park-go-for-a-spin",
      phrase: "go for a spin",
      kind: "idiom",
      kindInferred: true,
      meaning: "take a short drive or ride",
      example:
        "Let's go for a spin on the bumper cars — then we'll try the go-karts and the tea cups.",
    },
    {
      id: "amusement-park-take-someone-for-a-ride",
      phrase: "take someone for a ride",
      kind: "idiom",
      kindInferred: true,
      meaning: "deceive or cheat someone",
      example:
        "The claw machine took me for a ride — I spent ten coins and didn't win the stuffed animal or the giant teddy bear.",
    },
    {
      id: "amusement-park-have-a-blast",
      phrase: "have a blast",
      kind: "idiom",
      kindInferred: true,
      meaning: "have an extremely good time",
      example:
        "We had a blast on the Ferris wheel — we could see the pirate ship, the water slide, and the log flume from the top.",
    },
    {
      id: "amusement-park-ride-the-wave",
      phrase: "ride the wave",
      kind: "idiom",
      kindInferred: true,
      meaning: "enjoy a period of success or excitement",
      example:
        "Ride the wave of fun — try the loop ride, the launch coaster, and the pendulum ride before the park closes.",
    },
    {
      id: "amusement-park-come-full-circle",
      phrase: "come full circle",
      kind: "idiom",
      kindInferred: true,
      meaning: "return to the starting point or original situation",
      example:
        "The carousel came full circle — and my son wanted to ride it again with cotton candy in his hand.",
    },
    {
      id: "amusement-park-throw-your-hat-in-the-ring",
      phrase: "throw your hat in the ring",
      kind: "idiom",
      kindInferred: true,
      meaning: "enter a competition or challenge",
      example:
        "She threw her hat in the ring at the ring toss, the balloon dart, and the basketball throw — winning prizes at each.",
    },
    {
      id: "amusement-park-a-wild-ride",
      phrase: "a wild ride",
      kind: "idiom",
      kindInferred: true,
      meaning: "an exciting and unpredictable experience",
      example:
        "The haunted house was a wild ride — even scarier than the fun house and the flying swings.",
    },
    {
      id: "amusement-park-the-ride-of-your-life",
      phrase: "the ride of your life",
      kind: "idiom",
      kindInferred: true,
      meaning: "an extremely exciting experience",
      example: "That roller coaster was the ride of my life!",
    },
    {
      id: "amusement-park-wind-down",
      phrase: "wind down",
      kind: "phrasal-verb",
      kindInferred: true,
      meaning: "relax after excitement",
      example: "After the rides, we wound down with some ice cream.",
    },
  ],
  dialogue: {
    title: "Mini Dialogue",
    lines: [
      {
        speaker: "Scene: A family spends a day at the amusement park",
        text: "Dad:",
      },
      {
        speaker:
          "We're here! What do you want to ride first — the roller coaster or the Ferris wheel?",
        text: "Son:",
      },
      {
        speaker: "The roller coaster! Then the drop tower and the spinning ride!",
        text: "Daughter:",
      },
      {
        speaker: "I want the water slide and the log flume first. Then the pirate ship!",
        text: "Mom:",
      },
      {
        speaker:
          "Let's start together on the carousel. Then you two can try the loop ride and the launch coaster.",
        text: "Son:",
      },
      {
        speaker:
          "Can we do the bumper cars and the go-karts after? The pendulum ride looks amazing too!",
        text: "Dad:",
      },
      {
        speaker:
          "Sure. Your sister can try the tea cups, the flying swings, and the boat ride. The train ride and the monorail go around the whole park.",
        text: "Daughter:",
      },
      {
        speaker: "I want to see the haunted house and the fun house! Are they scary?",
        text: "Mom:",
      },
      {
        speaker:
          "A little — but you'll be fine. After that, let's play some games. The ring toss and the balloon dart are fun.",
        text: "Son:",
      },
      {
        speaker: "I want to try the basketball throw and the whack-a-mole! And the strength test!",
        text: "Dad:",
      },
    ],
  },
  mistakes: [
    {
      id: "amusement-park-we-went-to-an-amusement-park-a-theme-par",
      wrong: '"We went to a park of attractions."',
      right: '"We went to an amusement park." / "...a theme park."',
      note: "In English, use the compound noun 'amusement park' or 'theme park'. 'Park of attractions' is a translation from other languages.",
    },
    {
      id: "amusement-park-we-waited-in-the-queue-for-an-hour",
      wrong: '"The queue was very long. We waited on it for an hour."',
      right: '"We waited in the queue for an hour."',
      note: "British English: 'wait in a queue' / 'stand in a queue'. American English: 'wait in line' / 'stand in line'. Not 'wait on'.",
    },
    {
      id: "amusement-park-i-was-very-excited-about-by-the-ride",
      wrong: '"I was very excited with the ride."',
      right: '"I was very excited about/by the ride."',
      note: "Use 'excited about' (anticipation) or 'excited by' (reaction). Not 'excited with'.",
    },
    {
      id: "amusement-park-the-ride-was-a-lot-of-fun-the-ride-was-t",
      wrong: '"The ride was very funny."',
      right: '"The ride was a lot of fun." / "The ride was thrilling."',
      note: "'Funny' means it makes you laugh (comedy). 'Fun' means you enjoyed it. Rides are 'fun', 'exciting', or 'thrilling' — not usually 'funny'.",
    },
    {
      id: "amusement-park-we-paid-an-entrance-fee-we-paid-the-admi",
      wrong: '"We paid an entrance to the park."',
      right: '"We paid an entrance fee." / "We paid the admission price."',
      note: "'Entrance' alone is a noun meaning the doorway. The money you pay is the 'entrance fee' or 'admission price'.",
    },
  ],
  wordFormation: [
    {
      noun: "thrill / thriller",
      verb: "thrill",
      adjective: "thrilling",
      adverb: null,
      base: "thrill",
    },
    {
      noun: "amusement",
      verb: "amuse",
      adjective: "amusing / amused",
      adverb: null,
      base: "amuse",
    },
    {
      noun: "excitement",
      verb: "excite",
      adjective: "exciting / excited",
      adverb: null,
      base: "excite",
    },
    {
      noun: "scare / scarecrow",
      verb: "scare",
      adjective: "scary / scared",
      adverb: null,
      base: "scare",
    },
    {
      noun: "entertainment / entertainer",
      verb: "entertain",
      adjective: "entertaining",
      adverb: null,
      base: "entertain",
    },
    {
      noun: "attraction",
      verb: "attract",
      adjective: "attractive",
      adverb: null,
      base: "attract",
    },
    {
      noun: "admission / admittance",
      verb: "admit",
      adjective: "admitted",
      adverb: null,
      base: "admit",
    },
    {
      noun: "restriction",
      verb: "restrict",
      adjective: "restricted",
      adverb: null,
      base: "restrict",
    },
    {
      noun: "spin / spinner",
      verb: "spin",
      adjective: "spinning",
      adverb: null,
      base: "spin",
    },
    {
      noun: "dizziness",
      verb: null,
      adjective: "dizzy",
      adverb: null,
      base: "dizzy",
    },
  ],
  blankExercises: [
    {
      id: "amusement-park-b1",
      sentence: "The roller ____ was the most exciting ride in the park.",
      answer: "coaster",
    },
    {
      id: "amusement-park-b2",
      sentence: "We drove small electric cars on the ____ cars ride.",
      answer: "bumper",
    },
    {
      id: "amusement-park-b3",
      sentence: "The ____ wheel turns slowly and gives you a view of the whole park.",
      answer: "Ferris",
    },
    {
      id: "amusement-park-b4",
      sentence: "There is a height ____ — you must be at least 1.4 metres tall.",
      answer: "restriction",
    },
    {
      id: "amusement-park-b5",
      sentence: "The spinning teacups ride made us feel very ____.",
      answer: "dizzy",
    },
    {
      id: "amusement-park-b6",
      sentence: "We ____ up for twenty minutes before it was our turn.",
      answer: "queued",
    },
    {
      id: "amusement-park-b7",
      sentence: "The haunted ____ had actors dressed as ghosts to scare visitors.",
      answer: "house",
    },
    {
      id: "amusement-park-b8",
      sentence: "I won a stuffed bear at one of the ____ games.",
      answer: "carnival",
    },
    {
      id: "amusement-park-b9",
      sentence: "The ____ fee for the park was thirty-five pounds per person.",
      answer: "admission",
    },
    {
      id: "amusement-park-b10",
      sentence: "We bought candyfloss and lemonade from a food ____.",
      answer: "stall",
    },
  ],
  culturalNotes: [
    {
      id: "amusement-park-theme-parks-vs-amusement-parks",
      title: "Theme Parks vs Amusement Parks",
      body: "A 'theme park' has areas designed around specific themes (e.g. fantasy, adventure, movies). An 'amusement park' is more general — rides and games without a unifying theme. In practice, people often use the terms interchangeably.",
    },
    {
      id: "amusement-park-vs-terms",
      title: "🇬🇧 vs 🇺🇸 Terms",
      body: "British: 'candyfloss' / American: 'cotton candy'. British: 'dodgems' / American: 'bumper cars'. British: 'queue' / American: 'line'. British: 'funfair' / American: 'carnival' or 'fair'.",
    },
    {
      id: "amusement-park-famous-uk-theme-parks",
      title: "Famous UK Theme Parks",
      body: "Alton Towers, Thorpe Park, and Legoland Windsor are among the UK's most popular theme parks. Blackpool Pleasure Beach is one of the oldest amusement parks in the world, opening in 1896.",
    },
    {
      id: "amusement-park-funfairs-travelling-fairs",
      title: "Funfairs & Travelling Fairs",
      body: "A 'funfair' or 'travelling fair' is a temporary amusement park that moves from town to town. They often appear during bank holidays or local festivals, with rides, food stalls, and game booths.",
    },
    {
      id: "amusement-park-safety-vocabulary",
      title: "Safety Vocabulary",
      body: "Key safety phrases: 'height restriction', 'must be accompanied by an adult', 'keep your hands inside the ride', 'fasten your seatbelt', 'this ride is not suitable for people with heart conditions'.",
    },
  ],
  wordMeta: [
    {
      word: "roller coaster",
      partOfSpeech: "n",
      frequency: 3,
      collocations: ["ride a ~", "~ drop", "~ loop"],
    },
    {
      word: "Ferris wheel",
      partOfSpeech: "n",
      frequency: 2,
      collocations: ["ride the ~", "~ view", "giant ~"],
    },
    {
      word: "bumper cars",
      partOfSpeech: "n",
      frequency: 2,
      collocations: ["drive ~", "~ arena", "electric ~"],
    },
    {
      word: "carousel",
      partOfSpeech: "n",
      frequency: 2,
      collocations: ["~ horses", "ride the ~", "~ music"],
    },
    {
      word: "queue",
      partOfSpeech: "n",
      frequency: 3,
      collocations: ["join the ~", "long ~", "~ time"],
    },
    {
      word: "ticket",
      partOfSpeech: "n",
      frequency: 3,
      collocations: ["buy a ~", "day ~", "~ booth"],
    },
    {
      word: "ride",
      partOfSpeech: "n",
      frequency: 3,
      collocations: ["water ~", "scary ~", "~ pass"],
    },
    {
      word: "attraction",
      partOfSpeech: "n",
      frequency: 3,
      collocations: ["main ~", "tourist ~", "~ map"],
    },
    {
      word: "stall",
      partOfSpeech: "n",
      frequency: 2,
      collocations: ["food ~", "game ~", "market ~"],
    },
    {
      word: "souvenir",
      partOfSpeech: "n",
      frequency: 2,
      collocations: ["buy a ~", "~ shop", "~ photo"],
    },
  ],
};
