// Learning materials for "The Bakery".
//
// GENERATED by scripts/build-learning-materials.mjs from figma-dump/bakery.json.
// Figma is the source of truth: edit the design file and re-run the sync,
// do not hand-edit this file.

import type { UnitLearningMaterials } from "../types";

export const BAKERY_LEARNING: UnitLearningMaterials = {
  unitId: "bakery",
  subtopics: [
    {
      id: "breads",
      title: "Breads",
      wordIds: [
        "white-bread",
        "whole-wheat-bread",
        "baguette",
        "sourdough",
        "rye-bread",
        "pita",
        "focaccia",
        "ciabatta",
        "brioche",
        "flatbread",
      ],
    },
    {
      id: "pastries-sweet",
      title: "Pastries & Sweet",
      wordIds: [
        "croissant",
        "muffin",
        "donut",
        "danish",
        "cinnamon-roll",
        "clair",
        "scone",
        "strudel",
        "macaron",
        "profiterole",
      ],
    },
    {
      id: "cakes-pies",
      title: "Cakes & Pies",
      wordIds: [
        "birthday-cake",
        "wedding-cake",
        "cupcake",
        "cheesecake",
        "chocolate-cake",
        "carrot-cake",
        "apple-pie",
        "cherry-pie",
        "lemon-tart",
        "brownie",
      ],
    },
    {
      id: "cookies-biscuits",
      title: "Cookies & Biscuits",
      wordIds: [
        "chocolate-chip-cookie",
        "sugar-cookie",
        "gingerbread",
        "shortbread",
        "oatmeal-cookie",
        "wafer",
        "biscuit",
        "pretzel",
        "cracker",
        "granola-bar",
      ],
    },
    {
      id: "baking-ingredients",
      title: "Baking Ingredients",
      wordIds: [
        "flour",
        "sugar",
        "butter",
        "eggs",
        "yeast",
        "baking-powder",
        "chocolate",
        "vanilla",
        "cream",
        "cocoa-powder",
        "cinnamon",
        "honey",
      ],
    },
    {
      id: "bakery-equipment",
      title: "Bakery Equipment",
      wordIds: [
        "oven",
        "mixer",
        "rolling-pin",
        "baking-tray",
        "whisk",
        "spatula",
        "piping-bag",
        "muffin-tin",
        "cooling-rack",
        "bread-basket",
        "apron",
        "timer",
        "bread",
        "cake",
        "cookie",
        "pie",
        "egg",
      ],
    },
  ],
  passage: {
    title: "Reading Passage",
    level: "B1",
    text: "The Bakery on the Corner\n\nThere is a small bakery on the corner of our street. Every morning, the smell of fresh bread fills the air long before the shop opens at seven.\n\nThe baker, Mr Ahmad, starts work at four in the morning. He mixes flour, water, yeast, and salt to make the dough. After kneading it by hand, he lets it rise for about an hour. Then he shapes the dough into loaves, rolls, and baguettes before placing them in the large oven.\n\nBy the time the first customers arrive, the shelves are full. There are white bread loaves, wholemeal bread, sourdough, and flatbread. On one side of the counter, there are sweet pastries: croissants, Danish pastries, cinnamon rolls, and doughnuts glazed with sugar. The display case also has cakes — chocolate cake, carrot cake, and cheesecake — all made fresh daily.\n\nMr Ahmad's wife manages the front of the shop. She serves customers, wraps orders in paper bags, and operates the till. Regular customers often order birthday cakes or wedding cakes in advance.\n\nThe bakery also sells biscuits, muffins, and scones with jam and cream. On Fridays, they make a special olive bread that sells out within an hour.\n\nI go there every Saturday to buy a loaf of sourdough and two croissants. The bread is always warm, the crust is golden and crunchy, and the inside is soft. Nothing beats fresh bread from a local bakery.",
    questions: [],
    openQuestions: [
      "What time does Mr Ahmad start work?",
      "What ingredients does he use for the dough?",
      "What sweet items are on display?",
      "What does Mr Ahmad's wife do in the shop?",
      "What is special about Fridays at the bakery?",
    ],
  },
  phrases: [
    {
      id: "bakery-the-best-thing-since-sliced-bread",
      phrase: "the best thing since sliced bread",
      kind: "idiom",
      kindInferred: true,
      meaning: "an excellent invention or development",
      example:
        "This sourdough is the best thing since sliced bread — even better than the baguette and the ciabatta.",
    },
    {
      id: "bakery-a-piece-of-cake",
      phrase: "a piece of cake",
      kind: "idiom",
      kindInferred: true,
      meaning: "something very easy to do",
      example:
        "Making a cupcake is a piece of cake — but the wedding cake and the birthday cake take hours.",
    },
    {
      id: "bakery-that-s-the-way-the-cookie-crumbles",
      phrase: "that's the way the cookie crumbles",
      kind: "idiom",
      kindInferred: true,
      meaning: "that's how things happen; accept it",
      example:
        "The shortbread broke in half — well, that's the way the cookie crumbles. Try the chocolate chip cookie instead.",
    },
    {
      id: "bakery-have-your-cake-and-eat-it-too",
      phrase: "have your cake and eat it too",
      kind: "idiom",
      kindInferred: true,
      meaning: "want two incompatible things at once",
      example:
        "You can't have your cake and eat it too — you chose the cheesecake, so the lemon tart goes back on the shelf.",
    },
    {
      id: "bakery-bread-and-butter",
      phrase: "bread and butter",
      kind: "idiom",
      kindInferred: true,
      meaning: "a person's main source of income or basic needs",
      example:
        "White bread and whole wheat bread are the bakery's bread and butter — they sell hundreds every day.",
    },
    {
      id: "bakery-icing-on-the-cake",
      phrase: "icing on the cake",
      kind: "idiom",
      kindInferred: true,
      meaning: "something good added to an already good situation",
      example:
        "The free brownie was the icing on the cake — I already bought a croissant, a muffin, and a scone.",
    },
    {
      id: "bakery-sell-like-hot-cakes",
      phrase: "sell like hot cakes",
      kind: "idiom",
      kindInferred: true,
      meaning: "sell quickly in large quantities",
      example:
        "The cinnamon rolls sell like hot cakes every morning — the danish and the éclair are popular too.",
    },
    {
      id: "bakery-half-baked",
      phrase: "half-baked",
      kind: "idiom",
      kindInferred: true,
      meaning: "not fully thought out; poorly planned",
      example:
        "His half-baked plan was to open a bakery selling only profiterole and macaron — no bread at all!",
    },
    {
      id: "bakery-a-baker-s-dozen",
      phrase: "a baker's dozen",
      kind: "idiom",
      kindInferred: true,
      meaning: "thirteen (instead of twelve)",
      example: "He gave us a baker's dozen — thirteen rolls for the price of twelve.",
    },
    {
      id: "bakery-half-baked",
      phrase: "half-baked",
      kind: "idiom",
      kindInferred: true,
      meaning: "not fully thought through, poorly planned",
      example: "That's a half-baked idea — we need a better plan.",
    },
  ],
  dialogue: {
    title: "Mini Dialogue",
    lines: [
      {
        speaker: "Scene: A customer orders items for a family celebration at a local bakery",
        text: "Baker:",
      },
      {
        speaker: "Good morning! What can I get for you today?",
        text: "Customer:",
      },
      {
        speaker:
          "I need a birthday cake for my daughter. Do you have chocolate cake or carrot cake?",
        text: "Baker:",
      },
      {
        speaker:
          "Both! The chocolate cake is our most popular, but the cheesecake and the apple pie are wonderful too.",
        text: "Customer:",
      },
      {
        speaker:
          "I'll take the chocolate cake. Can I also get a dozen croissants and some muffins?",
        text: "Baker:",
      },
      {
        speaker:
          "Of course. The croissant is fresh from the oven. Would you like the blueberry muffin or the banana muffin?",
        text: "Customer:",
      },
      {
        speaker:
          "Blueberry, please. I also need a baguette and some sourdough for dinner. And maybe a pita and a focaccia.",
        text: "Baker:",
      },
      {
        speaker:
          "The whole wheat bread and the rye bread are freshly baked too. The ciabatta just came out — and the brioche is still warm.",
        text: "Customer:",
      },
      {
        speaker:
          "Everything smells amazing. What about pastries? The children love donuts and cinnamon rolls.",
        text: "Baker:",
      },
      {
        speaker:
          "I'll box up donuts, cinnamon rolls, and a danish. We also have éclairs, scones, and strudel if you want variety.",
        text: "Customer:",
      },
    ],
  },
  mistakes: [
    {
      id: "bakery-i-want-a-loaf-of-bread-please-i-want-som",
      wrong: '"I want a bread, please."',
      right: '"I want a loaf of bread, please." / "I want some bread."',
      note: "'Bread' is uncountable. Use 'a loaf of', 'a slice of', 'a piece of', or 'some bread'.",
    },
    {
      id: "bakery-the-cake-is-delicious",
      wrong: '"The cake is very delicious."',
      right: '"The cake is delicious."',
      note: "'Delicious' is already strong — don't add 'very'. Use 'absolutely delicious' for emphasis.",
    },
    {
      id: "bakery-she-has-been-baking-a-cake-for-three-hou",
      wrong: '"She baked a cake since three hours."',
      right: '"She has been baking a cake for three hours."',
      note: "Use 'for' + duration, not 'since'. 'Since' needs a point in time ('since 2 PM').",
    },
    {
      id: "bakery-i-like-bread-with-butter",
      wrong: '"I like breads with butter."',
      right: '"I like bread with butter."',
      note: "'Bread' doesn't have a plural form in general use. 'Breads' only refers to different types of bread.",
    },
    {
      id: "bakery-the-dough-is-soft-enough-now",
      wrong: '"The dough is enough soft now."',
      right: '"The dough is soft enough now."',
      note: "'Enough' follows the adjective: 'soft enough', 'warm enough'. Not 'enough soft'.",
    },
  ],
  wordFormation: [
    {
      noun: "baker / bakery",
      verb: "bake",
      adjective: "baked",
      adverb: null,
      base: "bake",
    },
    {
      noun: "kneading",
      verb: "knead",
      adjective: "kneaded",
      adverb: null,
      base: "knead",
    },
    {
      noun: "rise",
      verb: "rise",
      adjective: "risen / rising",
      adverb: null,
      base: "rise",
    },
    {
      noun: "mixture / mixer",
      verb: "mix",
      adjective: "mixed",
      adverb: null,
      base: "mix",
    },
    {
      noun: "frosting / frost",
      verb: "frost",
      adjective: "frosted / frosty",
      adverb: null,
      base: "frost",
    },
    {
      noun: "glaze",
      verb: "glaze",
      adjective: "glazed",
      adverb: null,
      base: "glaze",
    },
    {
      noun: "slice / slicer",
      verb: "slice",
      adjective: "sliced",
      adverb: null,
      base: "slice",
    },
    {
      noun: "roll / rolling",
      verb: "roll",
      adjective: "rolled",
      adverb: null,
      base: "roll",
    },
    {
      noun: "sweetener / sweetness",
      verb: "sweeten",
      adjective: "sweet",
      adverb: null,
      base: "sweeten",
    },
    {
      noun: "crust",
      verb: null,
      adjective: "crusty",
      adverb: null,
      base: "crust",
    },
  ],
  blankExercises: [
    {
      id: "bakery-b1",
      sentence: "The baker put the ____ in the oven to bake for 30 minutes.",
      answer: "loaves",
    },
    {
      id: "bakery-b2",
      sentence: "She ordered a chocolate ____ for her daughter's birthday.",
      answer: "cake",
    },
    {
      id: "bakery-b3",
      sentence: "I'll have two ____ and a coffee, please.",
      answer: "croissants",
    },
    {
      id: "bakery-b4",
      sentence: "He kneaded the ____ until it was smooth and elastic.",
      answer: "dough",
    },
    {
      id: "bakery-b5",
      sentence: "The ____ were glazed with sugar and filled with jam.",
      answer: "doughnuts",
    },
    {
      id: "bakery-b6",
      sentence: "A loaf of ____ bread is healthier than white bread.",
      answer: "wholemeal",
    },
    {
      id: "bakery-b7",
      sentence: "The ____ case was full of pastries, cakes, and tarts.",
      answer: "display",
    },
    {
      id: "bakery-b8",
      sentence: "She spread butter and ____ on a warm scone.",
      answer: "jam",
    },
    {
      id: "bakery-b9",
      sentence: "The baker uses ____ to make the bread rise.",
      answer: "yeast",
    },
    {
      id: "bakery-b10",
      sentence: "The golden ____ on the sourdough was perfectly crunchy.",
      answer: "crust",
    },
  ],
  culturalNotes: [
    {
      id: "bakery-bakery-vs-baker-s",
      title: "Bakery vs Baker's",
      body: "In British English, 'the baker's' (with possessive) is common: 'I'm going to the baker's.' In American English, 'bakery' is standard. Both are correct.",
    },
    {
      id: "bakery-vs-vocabulary",
      title: "🇬🇧 vs 🇺🇸 Vocabulary",
      body: "British: 'biscuit' / American: 'cookie'. British: 'scone' (rhymes with 'gone') / American: 'scone' (rhymes with 'bone'). British: 'icing' / American: 'frosting'.",
    },
    {
      id: "bakery-bread-culture",
      title: "Bread Culture",
      body: "The UK has a strong bread culture: white, wholemeal, granary, tiger bread, and sourdough are all common. Toast with butter is a breakfast staple. 'A sandwich' literally means food between two slices of bread.",
    },
    {
      id: "bakery-afternoon-tea",
      title: "Afternoon Tea",
      body: "'Afternoon tea' is a British tradition: small sandwiches, scones with clotted cream and jam, and cakes served with tea. 'Cream tea' is just scones, cream, and jam. The order — cream first or jam first — is a famous debate!",
    },
    {
      id: "bakery-artisan-and-sourdough-trend",
      title: "Artisan and Sourdough Trend",
      body: "'Artisan bread' (hand-crafted, small-batch) and 'sourdough' (naturally fermented) have become trendy in English-speaking countries. These words appear frequently on menus and in food media.",
    },
  ],
  wordMeta: [
    {
      word: "bread",
      partOfSpeech: "n",
      frequency: 3,
      collocations: ["loaf of ~", "~ roll", "fresh ~", "~ basket"],
    },
    {
      word: "cake",
      partOfSpeech: "n",
      frequency: 3,
      collocations: ["birthday ~", "~ slice", "~ tin"],
    },
    {
      word: "dough",
      partOfSpeech: "n",
      frequency: 2,
      collocations: ["~ ball", "roll the ~", "pizza ~"],
    },
    {
      word: "oven",
      partOfSpeech: "n",
      frequency: 3,
      collocations: ["preheat the ~", "in the ~", "~ temperature"],
    },
    {
      word: "flour",
      partOfSpeech: "n",
      frequency: 2,
      collocations: ["~ bag", "plain ~", "self-raising ~"],
    },
    {
      word: "croissant",
      partOfSpeech: "n",
      frequency: 2,
      collocations: ["butter ~", "fresh ~", "~ and coffee"],
    },
    {
      word: "yeast",
      partOfSpeech: "n",
      frequency: 2,
      collocations: ["~ dough", "dried ~", "~ packet"],
    },
    {
      word: "pastry",
      partOfSpeech: "n",
      frequency: 2,
      collocations: ["puff ~", "~ chef", "Danish ~"],
    },
    {
      word: "loaf",
      partOfSpeech: "n",
      frequency: 3,
      collocations: ["~ of bread", "sliced ~", "French ~"],
    },
    {
      word: "crust",
      partOfSpeech: "n",
      frequency: 2,
      collocations: ["bread ~", "pizza ~", "pie ~", "golden ~"],
    },
  ],
};
