// Learning materials for "Extended Family".
//
// GENERATED by scripts/build-learning-materials.mjs from figma-dump/extended-family.json.
// Figma is the source of truth: edit the design file and re-run the sync,
// do not hand-edit this file.

import type { UnitLearningMaterials } from "../types";

export const EXTENDED_FAMILY_LEARNING: UnitLearningMaterials = {
  unitId: "extended-family",
  subtopics: [
    {
      id: "grandparents",
      title: "Grandparents",
      wordIds: [
        "grandmother",
        "grandfather",
        "grandma",
        "grandpa",
        "great-grandmother",
        "great-grandfather",
        "nana",
        "papa",
        "granny",
        "grandparent",
      ],
    },
    {
      id: "aunts-uncles-cousins",
      title: "Aunts, Uncles & Cousins",
      wordIds: [
        "aunt",
        "uncle",
        "cousin",
        "first-cousin",
        "second-cousin",
        "great-aunt",
        "great-uncle",
        "niece",
        "nephew",
        "cousin-in-law",
      ],
    },
    {
      id: "in-laws",
      title: "In-Laws",
      wordIds: [
        "mother-in-law",
        "father-in-law",
        "sister-in-law",
        "brother-in-law",
        "son-in-law",
        "daughter-in-law",
        "in-laws",
        "spouse-s-family",
        "extended-in-laws",
        "family-in-law",
      ],
    },
    {
      id: "family-gatherings",
      title: "Family Gatherings",
      wordIds: [
        "reunion",
        "holiday-dinner",
        "thanksgiving",
        "christmas",
        "easter",
        "birthday-celebration",
        "anniversary",
        "barbecue",
        "picnic",
        "family-wedding",
      ],
    },
  ],
  passage: {
    title: "Reading Passage",
    level: "B1",
    text: "Beyond the nuclear family lies the extended family — a wider network of relatives connected by blood or marriage. Grandparents — a grandmother and grandfather — often play a central role, offering wisdom, childcare, and a sense of heritage. Aunts and uncles are the siblings of your parents, and their children are your cousins. These relationships create a web of support that many families rely on. In-laws enter the picture through marriage: a mother-in-law, father-in-law, sister-in-law, and brother-in-law become part of your family when you marry. A niece is the daughter of your sibling, and a nephew is the son. Great-grandparents sit at the top of the family tree, representing the oldest living generation. Family reunions bring these extended relatives together, strengthening bonds across generations. In many cultures, the extended family lives under one roof or in close proximity, sharing resources and responsibilities. Grandchildren bring joy to grandparents and complete the generational cycle. Understanding extended family vocabulary allows you to navigate family trees, describe relationships accurately, and participate in conversations about family heritage and kinship.",
    questions: [],
    openQuestions: [
      "Who are your cousins in relation to your parents?",
      "What is a mother-in-law?",
      "What is the difference between a niece and a nephew?",
      "What role do grandparents typically play in extended families?",
      "Why are family reunions important?",
    ],
  },
  phrases: [
    {
      id: "extended-family-the-family-tree",
      phrase: "the family tree",
      kind: "idiom",
      kindInferred: true,
      meaning:
        '(noun phrase) A diagram showing family relationships across generations. "She traced her family tree back five generations to her great-great-grandparents."',
      example: "",
    },
    {
      id: "extended-family-a-family-affair",
      phrase: "a family affair",
      kind: "idiom",
      meaning: "Something that involves or concerns the whole family.",
      example:
        "The wedding was a real family affair — aunts, uncles, cousins, and grandparents all attended.",
    },
    {
      id: "extended-family-kissing-cousins",
      phrase: "kissing cousins",
      kind: "idiom",
      meaning: "Relatives who are distantly related but still know each other.",
      example: "We're kissing cousins — our grandmothers were sisters.",
    },
    {
      id: "extended-family-the-in-laws",
      phrase: "the in-laws",
      kind: "idiom",
      kindInferred: true,
      meaning:
        "(noun phrase) The parents and family of one's spouse. \"We're visiting the in-laws this weekend — my mother-in-law is cooking a big dinner.\"",
      example: "",
    },
    {
      id: "extended-family-take-after-someone",
      phrase: "take after someone",
      kind: "phrasal-verb",
      meaning: "To resemble a family member.",
      example:
        "She takes after her grandmother — they have the same smile and the same stubborn streak.",
    },
    {
      id: "extended-family-kith-and-kin",
      phrase: "kith and kin",
      kind: "idiom",
      meaning: "Friends and relatives.",
      example:
        "She invited all her kith and kin to the celebration — cousins, aunts, uncles, and close friends.",
    },
    {
      id: "extended-family-a-family-resemblance",
      phrase: "a family resemblance",
      kind: "idiom",
      kindInferred: true,
      meaning:
        '(noun phrase) Physical similarity between family members. "There\'s a strong family resemblance — the nephew looks exactly like his uncle at that age."',
      example: "",
    },
    {
      id: "extended-family-born-with-a-silver-spoon",
      phrase: "born with a silver spoon",
      kind: "idiom",
      meaning: "Born into a wealthy family.",
      example:
        "Her grandfather was a successful merchant — she was born with a silver spoon in her mouth.",
    },
    {
      id: "extended-family-the-apple-of-someone-s-eye",
      phrase: "the apple of someone's eye",
      kind: "idiom",
      meaning: "A cherished family member.",
      example: "The youngest grandchild is the apple of her grandmother's eye.",
    },
    {
      id: "extended-family-keep-the-family-together",
      phrase: "keep the family together",
      kind: "idiom",
      kindInferred: true,
      meaning:
        '(phrase) Maintain family unity. "Despite living in different cities, the aunts and uncles work hard to keep the family together."',
      example: "",
    },
  ],
  dialogue: {
    title: "Planning a Family Reunion",
    lines: [
      {
        speaker: "Fatima",
        text: "We should organize a family reunion this summer. I haven't seen our extended family in ages.",
      },
      {
        speaker: "Khalid",
        text: "Great idea! We should invite Uncle Hassan and Aunt Mariam. And their children — our cousins Rami and Dina.",
      },
      {
        speaker: "Fatima",
        text: "Of course! And Grandmother insists on coming. She says she wants to see all her grandchildren together.",
      },
      {
        speaker: "Khalid",
        text: "What about the in-laws? Should we invite your mother-in-law and father-in-law?",
      },
      {
        speaker: "Fatima",
        text: "Definitely — they're family too! My sister-in-law Hana can help with the cooking. She's an amazing chef.",
      },
      {
        speaker: "Khalid",
        text: "Let's not forget our nephew Omar and niece Salma. They've grown so much since last year.",
      },
      {
        speaker: "Fatima",
        text: "I'll make a family tree chart for the kids — some of the younger cousins don't even know how everyone is related.",
      },
      {
        speaker: "Khalid",
        text: "Good thinking. Great-Grandma Zahra would have loved this — four generations of family under one roof.",
      },
    ],
  },
  mistakes: [
    {
      id: "extended-family-she-is-my-sister-in-law",
      wrong: '"She is my mother-in-law\'s daughter." (meaning sister-in-law)',
      right: '"She is my sister-in-law."',
      note: "Your mother-in-law's daughter (other than your spouse) is your sister-in-law. Use the direct term.",
    },
    {
      id: "extended-family-my-uncle-s-children-are-my-cousins",
      wrong: '"My uncle\'s children are my nephews."',
      right: '"My uncle\'s children are my cousins."',
      note: "Your uncle's/aunt's children are your cousins. Nephews/nieces are YOUR siblings' children.",
    },
    {
      id: "extended-family-she-is-my-great-aunt",
      wrong: '"She is my grand-aunt."',
      right: '"She is my great-aunt."',
      note: "In English, 'great-aunt' (not 'grand-aunt') is the standard term for your grandparent's sister.",
    },
    {
      id: "extended-family-i-have-two-male-cousins-i-have-two-cousi",
      wrong: '"I have two cousin brothers."',
      right: '"I have two male cousins." / "I have two cousins."',
      note: "'Cousin brother' is not standard English. Say 'male cousin' if gender matters, or just 'cousin'.",
    },
    {
      id: "extended-family-my-grandfather-s-father-is-my-great-gran",
      wrong: '"My grandfather\'s father is my old grandfather."',
      right: '"My grandfather\'s father is my great-grandfather."',
      note: "Use 'great-grandfather' (not 'old grandfather') for your grandparent's parent.",
    },
    {
      id: "extended-family-she-is-my-brother-s-daughter-my-niece",
      wrong: '"She is my brother\'s daughter — my cousin."',
      right: '"She is my brother\'s daughter — my niece."',
      note: "Your brother's or sister's daughter is your niece, not your cousin.",
    },
  ],
  wordFormation: [
    {
      noun: "grandparent",
      verb: null,
      adjective: "grandparental",
      adverb: null,
    },
    {
      noun: "uncle",
      verb: null,
      adjective: "avuncular",
      adverb: null,
    },
    {
      noun: "aunt",
      verb: null,
      adjective: null,
      adverb: null,
    },
    {
      noun: "cousin",
      verb: null,
      adjective: null,
      adverb: null,
    },
    {
      noun: "niece",
      verb: null,
      adjective: null,
      adverb: null,
    },
    {
      noun: "nephew",
      verb: null,
      adjective: null,
      adverb: null,
    },
    {
      noun: "kinship",
      verb: null,
      adjective: null,
      adverb: null,
    },
    {
      noun: "heritage",
      verb: null,
      adjective: null,
      adverb: null,
    },
    {
      noun: "generation",
      verb: "generate",
      adjective: "generational",
      adverb: "generationally",
    },
    {
      noun: "reunion",
      verb: "reunite",
      adjective: "reunited",
      adverb: null,
    },
  ],
  blankExercises: [
    {
      id: "extended-family-b1",
      sentence: "My mother's mother is my ____.",
      answer: "grandmother",
    },
    {
      id: "extended-family-b2",
      sentence: "My father's brother is my ____.",
      answer: "uncle",
    },
    {
      id: "extended-family-b3",
      sentence: "My aunt's children are my ____.",
      answer: "cousins",
    },
    {
      id: "extended-family-b4",
      sentence: "My sister's son is my ____.",
      answer: "nephew",
    },
    {
      id: "extended-family-b5",
      sentence: "When I married, my wife's mother became my ____.",
      answer: "mother-in-law",
    },
    {
      id: "extended-family-b6",
      sentence: "My grandfather's mother is my ____.",
      answer: "great-grandmother",
    },
    {
      id: "extended-family-b7",
      sentence: "My brother's daughter is my ____.",
      answer: "niece",
    },
    {
      id: "extended-family-b8",
      sentence:
        "The whole ____ family gathered for the holiday — aunts, uncles, cousins, and grandparents.",
      answer: "extended",
    },
    {
      id: "extended-family-b9",
      sentence: "There's a strong family ____ — all the grandchildren have the same eyes.",
      answer: "resemblance",
    },
    {
      id: "extended-family-b10",
      sentence:
        "We organized a family ____ to bring everyone together for the first time in five years.",
      answer: "reunion",
    },
  ],
  culturalNotes: [
    {
      id: "extended-family-in-law-relationships",
      title: "In-Law Relationships",
      body: "In English-speaking cultures, in-law relationships can be complex. 'Mother-in-law jokes' are a comedy staple. The relationship between a person and their in-laws varies widely — from very close to deliberately distant. Using first names vs 'Mum/Dad' for in-laws depends on the family.",
    },
    {
      id: "extended-family-cousins-degrees-and-removal",
      title: "Cousins: Degrees and Removal",
      body: "English has precise cousin terminology: 'first cousins' share grandparents, 'second cousins' share great-grandparents. 'Once removed' means one generation apart. These terms are rarely used in daily conversation but appear in legal and genealogy contexts.",
    },
    {
      id: "extended-family-grandparent-nicknames",
      title: "Grandparent Nicknames",
      body: "English has many affectionate names for grandparents: Grandma/Grandpa, Nana/Papa, Granny/Granddad, Nanny/Pop, Gran/Gramps. Each family chooses their own, and the choice often reflects regional or cultural background.",
    },
    {
      id: "extended-family-extended-family-living-arrangements",
      title: "Extended Family Living Arrangements",
      body: "While multigenerational households are common in many world cultures, they're less typical in English-speaking countries, where adult children usually move out. However, economic pressures and cultural shifts are making extended family living more common again.",
    },
    {
      id: "extended-family-family-trees-and-genealogy",
      title: "Family Trees and Genealogy",
      body: "Genealogy (tracing family history) is a popular hobby in English-speaking countries. Websites for researching ancestors are widely used. Terms like 'ancestry', 'lineage', 'heritage', and 'roots' are common in these discussions.",
    },
  ],
  wordMeta: [
    {
      word: "grandmother",
      partOfSpeech: "n",
      frequency: 3,
      collocations: ["maternal ~", "paternal ~", "great-~", "~'s house"],
    },
    {
      word: "grandfather",
      partOfSpeech: "n",
      frequency: 3,
      collocations: ["maternal ~", "paternal ~", "great-~", "~'s stories"],
    },
    {
      word: "uncle",
      partOfSpeech: "n",
      frequency: 3,
      collocations: ["~ and aunt", "great-~", "favourite ~", "rich ~"],
    },
    {
      word: "aunt",
      partOfSpeech: "n",
      frequency: 3,
      collocations: ["~ and uncle", "great-~", "favourite ~", "maiden ~"],
    },
    {
      word: "cousin",
      partOfSpeech: "n",
      frequency: 3,
      collocations: ["first ~", "distant ~", "~ once removed", "close ~"],
    },
    {
      word: "nephew",
      partOfSpeech: "n",
      frequency: 2,
      collocations: ["favourite ~", "baby ~", "young ~", "~ and niece"],
    },
    {
      word: "niece",
      partOfSpeech: "n",
      frequency: 2,
      collocations: ["favourite ~", "baby ~", "young ~", "~ and nephew"],
    },
    {
      word: "mother-in-law",
      partOfSpeech: "n",
      frequency: 2,
      collocations: ["my ~", "future ~", "~ jokes", "~ relationship"],
    },
    {
      word: "grandchild",
      partOfSpeech: "n",
      frequency: 2,
      collocations: ["first ~", "eldest ~", "youngest ~", "~ren"],
    },
    {
      word: "reunion",
      partOfSpeech: "n",
      frequency: 2,
      collocations: ["family ~", "class ~", "~ dinner", "annual ~"],
    },
  ],
};
