// Learning materials for "Financial Services".
//
// GENERATED by scripts/build-learning-materials.mjs from figma-dump/financial-services.json.
// Figma is the source of truth: edit the design file and re-run the sync,
// do not hand-edit this file.

import type { UnitLearningMaterials } from "../types";

export const FINANCIAL_SERVICES_LEARNING: UnitLearningMaterials = {
  unitId: "financial-services",
  subtopics: [
    {
      id: "loans-credit",
      title: "Loans & Credit",
      wordIds: [
        "mortgage",
        "auto-loan",
        "personal-loan",
        "student-loan",
        "line-of-credit",
        "credit-score",
        "interest-rate",
        "principal",
        "collateral",
        "co-signer",
      ],
    },
    {
      id: "insurance",
      title: "Insurance",
      wordIds: [
        "health-insurance",
        "car-insurance",
        "life-insurance",
        "home-insurance",
        "travel-insurance",
        "premium",
        "deductible",
        "coverage",
        "claim",
        "policy",
      ],
    },
    {
      id: "investment",
      title: "Investment",
      wordIds: [
        "stock",
        "bond",
        "mutual-fund",
        "etf",
        "portfolio",
        "dividend",
        "capital-gain",
        "risk",
        "return",
        "diversification",
      ],
    },
    {
      id: "retirement",
      title: "Retirement",
      wordIds: [
        "401k",
        "ira",
        "pension",
        "social-security",
        "annuity",
        "retirement-fund",
        "compound-interest",
        "contribution",
        "vesting",
        "beneficiary",
      ],
    },
  ],
  passage: {
    title: "Reading Passage",
    level: "C1",
    text: "Financial services encompass a vast industry that manages, invests, and protects money. Insurance is a contract where a company agrees to compensate for specific losses in exchange for regular premium payments. Types include life insurance (pays out on death), health insurance (covers medical costs), home insurance (property and contents), motor insurance (vehicle cover), and travel insurance. Investment services help individuals and companies grow their wealth through stocks (shares in companies), bonds (loans to governments or corporations), mutual funds (pooled investments managed professionally), and pensions (long-term retirement savings). Financial advisors help clients plan for major life events: buying a home, funding education, planning retirement, and managing inheritance. Tax planning involves understanding income tax, capital gains tax, VAT (Value Added Tax), and tax relief on pensions and charitable donations. Fintech — financial technology — has disrupted traditional banking with digital-only banks, peer-to-peer lending, cryptocurrency, robo-advisors, and budgeting apps. The Financial Conduct Authority (FCA) regulates UK financial services, ensuring consumer protection and market integrity. Key consumer protections include the Financial Services Compensation Scheme (FSCS), which guarantees deposits up to £85,000 per institution. Understanding financial services vocabulary empowers people to make informed decisions, avoid scams, and build long-term financial security.",
    questions: [],
    openQuestions: [
      "What types of insurance are mentioned in the passage?",
      "How do stocks differ from bonds as investments?",
      "What role do financial advisors play?",
      "How has fintech disrupted traditional banking?",
      "What consumer protections exist in UK financial services?",
    ],
  },
  phrases: [
    {
      id: "financial-services-a-safe-bet",
      phrase: "a safe bet",
      kind: "idiom",
      meaning: "A reliable, low-risk choice.",
      example: "Government bonds are a safe bet — lower returns but very little risk.",
    },
    {
      id: "financial-services-put-all-your-eggs-in-one-basket",
      phrase: "put all your eggs in one basket",
      kind: "idiom",
      meaning: "To risk everything on one option.",
      example: "Don't put all your eggs in one basket — diversify your investments.",
    },
    {
      id: "financial-services-cash-cow",
      phrase: "cash cow",
      kind: "idiom",
      meaning: "A reliable source of income.",
      example: "The rental property is their cash cow — steady income every month.",
    },
    {
      id: "financial-services-go-through-the-roof",
      phrase: "go through the roof",
      kind: "idiom",
      meaning: "To increase dramatically.",
      example:
        "House prices have gone through the roof — first-time buyers can't afford to get on the ladder.",
    },
    {
      id: "financial-services-the-bottom-line",
      phrase: "the bottom line",
      kind: "idiom",
      meaning: "The most important fact or final result.",
      example: "The bottom line is: we need to cut costs or the company won't survive.",
    },
    {
      id: "financial-services-get-your-money-s-worth",
      phrase: "get your money's worth",
      kind: "idiom",
      meaning: "To receive good value.",
      example: "The all-inclusive holiday was excellent — we definitely got our money's worth.",
    },
    {
      id: "financial-services-a-golden-handshake",
      phrase: "a golden handshake",
      kind: "idiom",
      meaning: "A large payment when leaving a job.",
      example: "The retiring CEO received a golden handshake of £2 million.",
    },
    {
      id: "financial-services-foot-the-bill",
      phrase: "foot the bill",
      kind: "idiom",
      meaning: "To pay for something.",
      example:
        "The company footed the bill for the entire conference — flights, hotels, everything.",
    },
    {
      id: "financial-services-in-the-long-run",
      phrase: "in the long run",
      kind: "idiom",
      meaning: "Over a long period of time.",
      example: "Investing in property is expensive now, but in the long run, it pays off.",
    },
    {
      id: "financial-services-make-ends-meet",
      phrase: "make ends meet",
      kind: "idiom",
      meaning: "To earn just enough to live on.",
      example: "With rising prices, many families are struggling to make ends meet.",
    },
  ],
  dialogue: {
    title: "Meeting a Financial Advisor",
    lines: [
      {
        speaker: "Advisor",
        text: "So you're looking to start investing for retirement. Have you got a workplace pension already?",
      },
      {
        speaker: "Client",
        text: "Yes, my employer contributes 5% and I add 3%. But I feel like I should be doing more.",
      },
      {
        speaker: "Advisor",
        text: "That's a good foundation. I'd recommend maximising your ISA allowance too — £20,000 per year, tax-free.",
      },
      {
        speaker: "Client",
        text: "Should I go for a Cash ISA or Stocks and Shares?",
      },
      {
        speaker: "Advisor",
        text: "At your age, a Stocks and Shares ISA makes more sense. Over the long term, equities tend to outperform cash significantly.",
      },
      {
        speaker: "Client",
        text: "Isn't that risky though? I don't want to lose my savings.",
      },
      {
        speaker: "Advisor",
        text: "All investment carries risk, but diversification helps — spreading across different asset classes, sectors, and regions reduces exposure.",
      },
      {
        speaker: "Client",
        text: "That makes sense. And what about life insurance? My partner and I just had a baby, so it feels more important now.",
      },
    ],
  },
  mistakes: [
    {
      id: "financial-services-i-took-out-insurance-on-my-car-i-got-car",
      wrong: '"I made an insurance for my car."',
      right: '"I took out insurance on my car." / "I got car insurance."',
      note: "You 'take out' insurance (not 'make'). 'Take out a policy', 'get insurance', 'be insured'. 'Make' is for claims: 'make an insurance claim'.",
    },
    {
      id: "financial-services-she-invested-her-money-in-stocks",
      wrong: '"She invested her money on stocks."',
      right: '"She invested her money in stocks."',
      note: "'Invest IN' something (stocks, property, bonds). Never 'invest on'. You put money 'into' investments. 'Invest on' doesn't exist in financial English.",
    },
    {
      id: "financial-services-the-insurance-premium-is-50-per-month",
      wrong: '"The premium of the insurance is £50 per month."',
      right: '"The insurance premium is £50 per month."',
      note: "'Insurance premium' (compound noun) is more natural than 'premium of the insurance'. Similarly: 'interest rate', 'tax rate', 'pension contribution'.",
    },
    {
      id: "financial-services-he-made-a-profit-of-10-he-earned-a-10-re",
      wrong: '"He gained a profit of 10%."',
      right: '"He made a profit of 10%." / "He earned a 10% return."',
      note: "You 'make a profit' (not 'gain'). 'Earn a return' is the investment term. 'Gain' works for 'capital gains' (increase in asset value) but not with 'a profit'.",
    },
    {
      id: "financial-services-she-made-a-claim-on-her-insurance-after-",
      wrong: '"She claimed the insurance after the accident."',
      right: '"She made a claim on her insurance after the accident."',
      note: "'Make a claim' or 'file a claim' (not 'claim the insurance'). You claim ON your insurance policy. The verb pattern is 'claim for damages/losses'.",
    },
    {
      id: "financial-services-tax-is-very-high-in-the-uk-the-tax-rate-",
      wrong: '"The tax is very expensive in the UK."',
      right: '"Tax is very high in the UK." / "The tax rate is high in the UK."',
      note: "Tax is 'high' or 'low', never 'expensive' or 'cheap'. Prices are expensive; tax rates are high. Also: 'heavy taxation', 'tax burden'.",
    },
  ],
  wordFormation: [
    {
      noun: "insurance",
      verb: "insure",
      adjective: "insured/insurable",
      adverb: null,
    },
    {
      noun: "investment",
      verb: "invest",
      adjective: "invested",
      adverb: null,
    },
    {
      noun: "retirement",
      verb: "retire",
      adjective: "retired",
      adverb: null,
    },
    {
      noun: "taxation",
      verb: "tax",
      adjective: "taxable",
      adverb: null,
    },
    {
      noun: "compensation",
      verb: "compensate",
      adjective: "compensatory",
      adverb: null,
    },
    {
      noun: "diversification",
      verb: "diversify",
      adjective: "diversified",
      adverb: null,
    },
    {
      noun: "regulation",
      verb: "regulate",
      adjective: "regulatory",
      adverb: null,
    },
    {
      noun: "inflation",
      verb: "inflate",
      adjective: "inflationary",
      adverb: null,
    },
    {
      noun: "premium",
      verb: null,
      adjective: "premium",
      adverb: null,
    },
    {
      noun: "liability",
      verb: null,
      adjective: "liable",
      adverb: null,
    },
  ],
  blankExercises: [
    {
      id: "financial-services-b1",
      sentence:
        "She took out a life ____ policy to protect her family in case anything happened to her.",
      answer: "insurance",
    },
    {
      id: "financial-services-b2",
      sentence: "The company's ____ fund has grown significantly over the past ten years.",
      answer: "pension/investment",
    },
    {
      id: "financial-services-b3",
      sentence:
        "He pays a monthly ____ of £45 for his car insurance — quite reasonable for his age.",
      answer: "premium",
    },
    {
      id: "financial-services-b4",
      sentence: "The financial ____ recommended diversifying across stocks, bonds, and property.",
      answer: "advisor",
    },
    {
      id: "financial-services-b5",
      sentence: "____ gains tax applies when you sell an asset for more than you paid for it.",
      answer: "Capital",
    },
    {
      id: "financial-services-b6",
      sentence: "The government raised the rate of ____ tax from 20% to 25% on higher earnings.",
      answer: "income",
    },
    {
      id: "financial-services-b7",
      sentence:
        "She made a ____ on her home insurance after the flooding damaged the ground floor.",
      answer: "claim",
    },
    {
      id: "financial-services-b8",
      sentence: "The ____ rate has risen to 6%, making it more expensive to borrow money.",
      answer: "interest",
    },
    {
      id: "financial-services-b9",
      sentence: "He ____ £5,000 in a Stocks and Shares ISA to grow his savings tax-free.",
      answer: "invested",
    },
    {
      id: "financial-services-b10",
      sentence: "The FCA ____ UK financial services to ensure fair treatment of consumers.",
      answer: "regulates",
    },
  ],
  culturalNotes: [
    {
      id: "financial-services-the-pension-triple-lock",
      title: "The Pension Triple Lock",
      body: "The UK's 'triple lock' guarantees state pensions rise by the highest of inflation, average earnings, or 2.5%. This political term appears constantly in news and debates. Understanding it helps follow UK economic discussions.",
    },
    {
      id: "financial-services-property-as-investment",
      title: "Property as Investment",
      body: "British culture places enormous value on property ownership. 'Getting on the property ladder', 'buy-to-let', 'stamp duty', and 'negative equity' are common vocabulary. Home ownership is seen as both financial security and social achievement.",
    },
    {
      id: "financial-services-premium-bonds",
      title: "Premium Bonds",
      body: "Premium Bonds — a uniquely British savings product from NS&I (National Savings & Investments) — don't pay interest. Instead, each bond enters a monthly prize draw. 'Have you won on the Premium Bonds?' is a common question.",
    },
    {
      id: "financial-services-financial-literacy",
      title: "Financial Literacy",
      body: "The UK government has pushed financial literacy education in schools. Terms like 'compound interest', 'budgeting', 'APR', 'credit score', and 'inflation' are now part of the curriculum, reflecting growing awareness of financial vocabulary's importance.",
    },
    {
      id: "financial-services-scam-awareness",
      title: "Scam Awareness",
      body: "Financial scam vocabulary is increasingly important: 'phishing' (fake emails), 'vishing' (phone scams), 'Ponzi scheme' (fraudulent investment), 'too good to be true'. Banks now use the phrase 'Take Five' — pause before making financial decisions.",
    },
  ],
  wordMeta: [
    {
      word: "insurance",
      partOfSpeech: "n",
      frequency: 3,
      collocations: ["life ~", "~ policy", "~ claim", "~ premium"],
    },
    {
      word: "investment",
      partOfSpeech: "n",
      frequency: 3,
      collocations: ["~ portfolio", "~ return", "~ fund", "foreign ~"],
    },
    {
      word: "pension",
      partOfSpeech: "n",
      frequency: 3,
      collocations: ["~ fund", "~ scheme", "state ~", "~ contribution"],
    },
    {
      word: "premium",
      partOfSpeech: "n",
      frequency: 3,
      collocations: ["insurance ~", "monthly ~", "~ rate", "at a ~"],
    },
    {
      word: "dividend",
      partOfSpeech: "n",
      frequency: 2,
      collocations: ["~ payment", "~ yield", "share ~", "annual ~"],
    },
    {
      word: "portfolio",
      partOfSpeech: "n",
      frequency: 2,
      collocations: ["investment ~", "~ manager", "diversified ~", "~ value"],
    },
    {
      word: "equity",
      partOfSpeech: "n",
      frequency: 2,
      collocations: ["home ~", "~ market", "~ fund", "private ~"],
    },
    {
      word: "inflation",
      partOfSpeech: "n",
      frequency: 3,
      collocations: ["~ rate", "~ rise", "fight ~", "~ target"],
    },
    {
      word: "liability",
      partOfSpeech: "n",
      frequency: 2,
      collocations: ["financial ~", "limited ~", "~ insurance", "tax ~"],
    },
    {
      word: "asset",
      partOfSpeech: "n",
      frequency: 3,
      collocations: ["~ management", "~ class", "liquid ~", "fixed ~"],
    },
  ],
};
