// Learning materials for "Formal & Business Wear".
//
// GENERATED by scripts/build-learning-materials.mjs from figma-dump/formal-business-wear.json.
// Figma is the source of truth: edit the design file and re-run the sync,
// do not hand-edit this file.

import type { UnitLearningMaterials } from "../types";

export const FORMAL_BUSINESS_WEAR_LEARNING: UnitLearningMaterials = {
  unitId: "formal-business-wear",
  subtopics: [
    {
      id: "men-s-formal",
      title: "Men's Formal",
      wordIds: [
        "suit",
        "dress-shirt",
        "tie",
        "bow-tie",
        "cufflinks",
        "pocket-square",
        "suspenders",
        "tuxedo",
        "vest",
        "dress-pants",
      ],
    },
    {
      id: "women-s-formal",
      title: "Women's Formal",
      wordIds: [
        "evening-gown",
        "cocktail-dress",
        "pencil-skirt",
        "blazer",
        "silk-blouse",
        "pantsuit",
        "wrap-dress",
        "shawl",
        "clutch-purse",
        "heels",
      ],
    },
    {
      id: "business-casual",
      title: "Business Casual",
      wordIds: [
        "chinos",
        "button-down",
        "loafers",
        "cardigan",
        "ankle-pants",
        "flats",
        "polo",
        "knit-top",
        "oxford-shoes",
      ],
    },
    {
      id: "workwear",
      title: "Workwear",
      wordIds: [
        "uniform",
        "scrubs",
        "lab-coat",
        "apron",
        "hard-hat",
        "safety-vest",
        "steel-toe-boots",
        "coveralls",
        "gloves",
        "name-tag",
      ],
    },
  ],
  passage: {
    title: "Reading Passage",
    level: "B1",
    text: "Formal and business wear communicates professionalism, respect, and occasion. For men, the foundation of formal dress is the suit — a matching jacket and trousers — paired with a dress shirt and a tie. A well-tailored suit in navy, charcoal, or black is considered appropriate for almost any professional or ceremonial occasion. Cufflinks, a pocket square, and polished leather shoes complete the look. For formal evening events, a tuxedo (dinner jacket) with a bow tie is the gold standard. Business casual is a step below: dress trousers with a collared shirt (no tie) or a blazer over a smart top. Women's formal options include a tailored suit with a blouse, a pencil skirt with a fitted jacket, or an elegant dress. A pantsuit offers a modern professional silhouette. For evening events, a gown or cocktail dress is appropriate. Business casual for women might include smart trousers with a blouse or a knee-length dress. Accessories like a belt, a watch, modest jewellery, and a structured handbag elevate any outfit. Understanding dress codes — 'black tie', 'business formal', 'smart casual', 'business casual' — is essential for professional and social success in English-speaking environments.",
    questions: [],
    openQuestions: [
      "What are the key components of a men's formal suit?",
      "When would someone wear a tuxedo?",
      "What is the difference between business formal and business casual?",
      "Name three women's formal wear options.",
      "Why is understanding dress codes important?",
    ],
  },
  phrases: [
    {
      id: "formal-business-wear-dressed-to-the-nines",
      phrase: "dressed to the nines",
      kind: "idiom",
      meaning: "Wearing very elegant, formal clothes.",
      example: "She arrived dressed to the nines — a stunning gown, pearls, and heels.",
    },
    {
      id: "formal-business-wear-suit-up",
      phrase: "suit up",
      kind: "phrasal-verb",
      meaning: "To put on formal business clothes.",
      example: "Time to suit up — the client meeting starts in an hour.",
    },
    {
      id: "formal-business-wear-power-dressing",
      phrase: "power dressing",
      kind: "idiom",
      kindInferred: true,
      meaning:
        '(noun phrase) Wearing formal clothes to project authority. "Her power dressing — tailored blazer, crisp blouse — commands respect in the boardroom."',
      example: "",
    },
    {
      id: "formal-business-wear-dress-to-impress",
      phrase: "dress to impress",
      kind: "idiom",
      meaning: "To wear your best clothes to make a strong impression.",
      example: "For the job interview, dress to impress — a clean suit and polished shoes.",
    },
    {
      id: "formal-business-wear-black-tie-affair",
      phrase: "black tie affair",
      kind: "idiom",
      kindInferred: true,
      meaning:
        '(noun phrase) A formal event requiring evening wear. "The charity gala is a black tie affair — you\'ll need a tuxedo or a formal gown."',
      example: "",
    },
    {
      id: "formal-business-wear-the-whole-nine-yards",
      phrase: "the whole nine yards",
      kind: "idiom",
      meaning: "Everything; the complete outfit.",
      example:
        "He wore the whole nine yards — suit, tie, cufflinks, pocket square, and shined shoes.",
    },
    {
      id: "formal-business-wear-cut-from-the-same-cloth",
      phrase: "cut from the same cloth",
      kind: "idiom",
      meaning: "Very similar in character.",
      example:
        "The two executives are cut from the same cloth — both sharp dressers in tailored suits.",
    },
    {
      id: "formal-business-wear-smart-casual",
      phrase: "smart casual",
      kind: "idiom",
      kindInferred: true,
      meaning:
        '(noun phrase) A dress code between formal and casual. "The invitation says smart casual — a blazer with chinos would be perfect."',
      example: "",
    },
    {
      id: "formal-business-wear-look-the-part",
      phrase: "look the part",
      kind: "idiom",
      meaning: "To dress appropriately for a role.",
      example: "If you want the promotion, you need to look the part — invest in a good suit.",
    },
    {
      id: "formal-business-wear-buttoned-up",
      phrase: "buttoned up",
      kind: "idiom",
      meaning: "Very formal and proper.",
      example:
        "He's always so buttoned up at work — pressed shirt, tie, never a hair out of place.",
    },
  ],
  dialogue: {
    title: "Shopping for a Business Event",
    lines: [
      {
        speaker: "Customer",
        text: "I need an outfit for a business conference. The dress code says 'business formal'. What do you recommend?",
      },
      {
        speaker: "Shop Assistant",
        text: "For business formal, I'd suggest a tailored suit in navy or charcoal. Would you like a two-piece or three-piece with a waistcoat?",
      },
      {
        speaker: "Customer",
        text: "Two-piece is fine. I'll need a dress shirt too — white or light blue. And a silk tie.",
      },
      {
        speaker: "Shop Assistant",
        text: "Excellent choices. What about accessories? Cufflinks and a leather belt would complete the look.",
      },
      {
        speaker: "Customer",
        text: "Good idea. There's also a gala dinner on the last night — the invitation says 'black tie'. Do I need a tuxedo?",
      },
      {
        speaker: "Shop Assistant",
        text: "Ideally, yes. A classic tuxedo with a bow tie and patent leather shoes would be perfect for black tie.",
      },
      {
        speaker: "Customer",
        text: "That's quite an investment. Can I use the blazer from the suit with smart trousers for a more relaxed evening?",
      },
      {
        speaker: "Shop Assistant",
        text: "That would work for smart casual, but not for a black tie event. I'd recommend renting a tuxedo if buying seems too much.",
      },
    ],
  },
  mistakes: [
    {
      id: "formal-business-wear-he-wore-a-tuxedo-dinner-jacket-to-the-pa",
      wrong: '"He wore a smoking to the party."',
      right: '"He wore a tuxedo / dinner jacket to the party."',
      note: "'Smoking' (from French/other languages) is not used in English. The correct term is 'tuxedo' (US) or 'dinner jacket' (UK).",
    },
    {
      id: "formal-business-wear-she-bought-a-new-suit-outfit-for-work",
      wrong: '"She bought a new costume for work."',
      right: '"She bought a new suit / outfit for work."',
      note: "In English, 'costume' means fancy dress or theatrical clothing. For work clothes, use 'suit' or 'outfit'.",
    },
    {
      id: "formal-business-wear-he-is-wearing-a-blue-suit-she-is-wearing",
      wrong: '"He is wearing a blue suit dress."',
      right: '"He is wearing a blue suit." / "She is wearing a blue dress."',
      note: "'Suit' (jacket + trousers/skirt) and 'dress' (one-piece garment) are different items. Don't combine them.",
    },
    {
      id: "formal-business-wear-she-tied-a-tie-she-wore-a-necktie",
      wrong: '"She tied a knot tie around her neck."',
      right: '"She tied a tie." / "She wore a necktie."',
      note: "A 'tie' or 'necktie' is the correct term. You 'tie a tie' or 'wear a tie'. 'Knot tie' isn't standard.",
    },
    {
      id: "formal-business-wear-black-tie-means-formal-evening-wear-typi",
      wrong: "\"The invitation says 'black tie' — I'll wear a black tie with my suit.\"",
      right: "\"'Black tie' means formal evening wear — typically a tuxedo with a bow tie.\"",
      note: "'Black tie' is a dress code, not a literal instruction to wear a black-coloured tie. It means tuxedo-level formality.",
    },
    {
      id: "formal-business-wear-she-wore-formal-attire-a-formal-outfit-f",
      wrong: '"She wore a formal for the interview."',
      right: '"She wore formal attire / a formal outfit for the interview."',
      note: "'Formal' is an adjective, not a noun for clothing. Say 'formal attire', 'formal wear', or 'a formal outfit'.",
    },
  ],
  wordFormation: [
    {
      noun: "formality",
      verb: "formalize",
      adjective: "formal",
      adverb: "formally",
    },
    {
      noun: "elegance",
      verb: null,
      adjective: "elegant",
      adverb: "elegantly",
    },
    {
      noun: "professionalism",
      verb: null,
      adjective: "professional",
      adverb: "professionally",
    },
    {
      noun: "tailoring",
      verb: "tailor",
      adjective: "tailored",
      adverb: null,
    },
    {
      noun: "sophistication",
      verb: "sophisticate",
      adjective: "sophisticated",
      adverb: null,
    },
    {
      noun: "attire",
      verb: "attire",
      adjective: "attired",
      adverb: null,
    },
    {
      noun: "refinement",
      verb: "refine",
      adjective: "refined",
      adverb: null,
    },
    {
      noun: "appropriateness",
      verb: null,
      adjective: "appropriate",
      adverb: "appropriately",
    },
    {
      noun: "smartness",
      verb: "smarten",
      adjective: "smart",
      adverb: "smartly",
    },
    {
      noun: "presentation",
      verb: "present",
      adjective: "presentable",
      adverb: "presentably",
    },
  ],
  blankExercises: [
    {
      id: "formal-business-wear-b1",
      sentence: "He wore a dark grey ____ with a white shirt and a silk tie to the interview.",
      answer: "suit",
    },
    {
      id: "formal-business-wear-b2",
      sentence: "For the charity gala, she chose an elegant evening ____.",
      answer: "gown/dress",
    },
    {
      id: "formal-business-wear-b3",
      sentence: "A ____ is the standard formal evening jacket worn with a bow tie.",
      answer: "tuxedo",
    },
    {
      id: "formal-business-wear-b4",
      sentence: "She paired her ____ with a fitted jacket for a professional look.",
      answer: "blouse",
    },
    {
      id: "formal-business-wear-b5",
      sentence: "His gold ____ added a touch of elegance to his French-cuff shirt.",
      answer: "cufflinks",
    },
    {
      id: "formal-business-wear-b6",
      sentence: "The invitation specifies a ____ dress code — no jeans or trainers allowed.",
      answer: "formal",
    },
    {
      id: "formal-business-wear-b7",
      sentence: "A navy ____ over a white T-shirt works perfectly for smart casual events.",
      answer: "blazer",
    },
    {
      id: "formal-business-wear-b8",
      sentence: "She always carries a structured ____ that matches her professional outfits.",
      answer: "handbag",
    },
    {
      id: "formal-business-wear-b9",
      sentence: "He folded a white ____ neatly into his suit jacket's breast pocket.",
      answer: "pocket square",
    },
    {
      id: "formal-business-wear-b10",
      sentence: "The ____ code at their office requires a collared shirt and dress trousers.",
      answer: "dress",
    },
  ],
  culturalNotes: [
    {
      id: "formal-business-wear-dress-code-hierarchy",
      title: "Dress Code Hierarchy",
      body: "From most to least formal: 'White Tie' (tailcoat, full-length gown) → 'Black Tie' (tuxedo, evening dress) → 'Business Formal' (suit and tie) → 'Business Casual' (blazer, no tie) → 'Smart Casual' (neat but relaxed) → 'Casual' (jeans, T-shirt).",
    },
    {
      id: "formal-business-wear-job-interview-attire",
      title: "Job Interview Attire",
      body: "In English-speaking countries, overdressing slightly for interviews is preferred. 'Dress one level above the job' is common advice. A clean, pressed suit (or equivalent) shows respect for the opportunity. Grooming and polished shoes are noticed.",
    },
    {
      id: "formal-business-wear-the-business-suit-tradition",
      title: "The Business Suit Tradition",
      body: "The modern business suit originated in 19th-century Britain. Savile Row in London remains famous for bespoke tailoring. In American English, a suit is called a 'two-piece' (jacket + trousers) or 'three-piece' (+ waistcoat/vest).",
    },
    {
      id: "formal-business-wear-women-s-professional-dress-evolution",
      title: "Women's Professional Dress Evolution",
      body: "Women's professional wear has evolved significantly. Pantsuits became popular in the 1970s; today, women have more options than men for business dress. Terms like 'power suit', 'sheath dress', and 'statement blazer' reflect this evolution.",
    },
    {
      id: "formal-business-wear-formal-wear-rental",
      title: "Formal Wear Rental",
      body: "Renting formal wear (especially tuxedos) is common and socially accepted in English-speaking countries. 'Hire a suit' (UK) or 'rent a tux' (US) are standard phrases. This is practical for events where you need specific dress codes.",
    },
  ],
  wordMeta: [
    {
      word: "suit",
      partOfSpeech: "n",
      frequency: 3,
      collocations: ["business ~", "three-piece ~", "~ jacket", "~ and tie"],
    },
    {
      word: "tuxedo",
      partOfSpeech: "n",
      frequency: 2,
      collocations: ["black ~", "rent a ~", "~ shirt", "~ jacket"],
    },
    {
      word: "blazer",
      partOfSpeech: "n",
      frequency: 2,
      collocations: ["navy ~", "casual ~", "~ and chinos", "~ button"],
    },
    {
      word: "blouse",
      partOfSpeech: "n",
      frequency: 2,
      collocations: ["silk ~", "cotton ~", "~ and skirt", "button-up ~"],
    },
    {
      word: "tie",
      partOfSpeech: "n",
      frequency: 3,
      collocations: ["silk ~", "bow ~", "~ clip", "~ knot"],
    },
    {
      word: "cufflinks",
      partOfSpeech: "n (pl)",
      frequency: 1,
      collocations: ["gold ~", "silver ~", "~ set", "formal ~"],
    },
    {
      word: "gown",
      partOfSpeech: "n",
      frequency: 2,
      collocations: ["evening ~", "ball ~", "~ length", "designer ~"],
    },
    {
      word: "dress code",
      partOfSpeech: "n",
      frequency: 3,
      collocations: ["strict ~", "~ policy", "~ violation", "office ~"],
    },
    {
      word: "waistcoat",
      partOfSpeech: "n",
      frequency: 2,
      collocations: ["formal ~", "~ and tie", "three-piece ~", "fitted ~"],
    },
    {
      word: "tailored",
      partOfSpeech: "adj",
      frequency: 2,
      collocations: ["~ suit", "~ fit", "~ jacket", "custom-~"],
    },
  ],
};
