// Learning materials for "Giving Directions".
//
// GENERATED by scripts/build-learning-materials.mjs from figma-dump/giving-directions.json.
// Figma is the source of truth: edit the design file and re-run the sync,
// do not hand-edit this file.

import type { UnitLearningMaterials } from "../types";

export const GIVING_DIRECTIONS_LEARNING: UnitLearningMaterials = {
  unitId: "giving-directions",
  subtopics: [
    {
      id: "basic-directions",
      title: "Basic Directions",
      wordIds: [
        "left",
        "right",
        "straight",
        "forward",
        "backward",
        "up",
        "down",
        "turn",
        "stop",
        "go",
      ],
    },
    {
      id: "cardinal-directions",
      title: "Cardinal Directions",
      wordIds: [
        "north",
        "south",
        "east",
        "west",
        "northeast",
        "northwest",
        "southeast",
        "southwest",
        "compass",
        "direction",
      ],
    },
    {
      id: "distance-location",
      title: "Distance & Location",
      wordIds: [
        "near",
        "far",
        "close",
        "nearby",
        "distant",
        "here",
        "there",
        "everywhere",
        "nowhere",
        "somewhere",
      ],
    },
    {
      id: "street-navigation",
      title: "Street Navigation",
      wordIds: [
        "intersection",
        "corner",
        "block",
        "crosswalk",
        "traffic-light",
        "roundabout",
        "one-way",
        "dead-end",
        "highway",
        "sidewalk",
      ],
    },
    {
      id: "landmarks",
      title: "Landmarks",
      wordIds: [
        "building",
        "bridge",
        "monument",
        "fountain",
        "statue",
        "tower",
        "church",
        "park",
        "school",
        "hospital",
      ],
    },
  ],
  passage: {
    title: "Reading Passage",
    level: "C1",
    text: "Giving and following directions is a fundamental skill that combines spatial vocabulary with clear, sequenced communication. In English, directions typically begin with an orientation: 'Go straight ahead', 'Head north', or 'Follow this road'. Turning instructions specify both direction and landmark: 'Turn left at the traffic lights', 'Take the second right after the roundabout', 'Bear left at the fork in the road'. Distance is expressed in various ways: 'It's about a five-minute walk', 'roughly 200 metres', 'just past the bridge', or 'a stone's throw from here'. Key landmark vocabulary includes crossroads (where two roads cross), junction (where roads meet), roundabout (circular intersection), pedestrian crossing (zebra crossing in British English), and underpass or flyover (under or over a main road). British and American English diverge significantly here: pavement vs sidewalk, high street vs main street, car park vs parking lot, motorway vs highway, dual carriageway vs divided highway. Giving effective directions also requires hedging and checking: 'If I'm not mistaken, it's on your left', 'You can't miss it', 'If you get to the church, you've gone too far'. In the age of GPS and smartphones, asking for directions is less common, but understanding them remains essential — especially when technology fails or when navigating inside buildings, campuses, and unfamiliar venues.",
    questions: [],
    openQuestions: [
      "How do English directions typically begin?",
      "What is the difference between a crossroads and a junction?",
      "Name three British/American English differences for road vocabulary.",
      "What hedging phrases are used when giving directions?",
      "Why is direction vocabulary still important in the age of GPS?",
    ],
  },
  phrases: [
    {
      id: "giving-directions-you-can-t-miss-it",
      phrase: "you can't miss it",
      kind: "idiom",
      kindInferred: true,
      meaning:
        "(phrase) It's very obvious and easy to find. \"Turn left at the church — the shop has a big red sign. You can't miss it.\"",
      example: "",
    },
    {
      id: "giving-directions-just-around-the-corner",
      phrase: "just around the corner",
      kind: "idiom",
      kindInferred: true,
      meaning:
        '(phrase) Very nearby. "The pharmacy is just around the corner — two minutes\' walk at most."',
      example: "",
    },
    {
      id: "giving-directions-a-stone-s-throw-away",
      phrase: "a stone's throw away",
      kind: "idiom",
      meaning: "Very close.",
      example:
        "The beach is a stone's throw from our hotel — we can hear the waves from the balcony.",
    },
    {
      id: "giving-directions-take-a-shortcut",
      phrase: "take a shortcut",
      kind: "idiom",
      kindInferred: true,
      meaning:
        '(phrase) To use a quicker, alternative route. "If we take a shortcut through the park, we\'ll save ten minutes."',
      example: "",
    },
    {
      id: "giving-directions-off-the-beaten-track",
      phrase: "off the beaten track",
      kind: "idiom",
      meaning: "In a remote, less-travelled area.",
      example: "The best cafés are off the beaten track — away from the tourist streets.",
    },
    {
      id: "giving-directions-go-the-wrong-way",
      phrase: "go the wrong way",
      kind: "idiom",
      kindInferred: true,
      meaning:
        '(phrase) To travel in the incorrect direction. "We went the wrong way at the roundabout and ended up miles from where we needed to be."',
      example: "",
    },
    {
      id: "giving-directions-dead-end",
      phrase: "dead end",
      kind: "idiom",
      kindInferred: true,
      meaning:
        "(phrase) A road with no exit. \"Don't go down there — it's a dead end. You'll have to turn around and come back.\"",
      example: "",
    },
    {
      id: "giving-directions-make-a-u-turn",
      phrase: "make a U-turn",
      kind: "idiom",
      kindInferred: true,
      meaning:
        '(phrase) To turn completely around. "We missed the turning, so we made a U-turn at the next roundabout."',
      example: "",
    },
    {
      id: "giving-directions-lose-your-bearings",
      phrase: "lose your bearings",
      kind: "idiom",
      meaning: "To become disoriented.",
      example: "I completely lost my bearings in the old town — every street looked the same.",
    },
    {
      id: "giving-directions-know-your-way-around",
      phrase: "know your way around",
      kind: "idiom",
      meaning: "To be familiar with a place.",
      example: "She knows her way around London like the back of her hand.",
    },
  ],
  dialogue: {
    title: "Asking for Directions",
    lines: [
      {
        speaker: "Tourist",
        text: "Excuse me, could you tell me how to get to the National Gallery from here?",
      },
      {
        speaker: "Local",
        text: "Of course. Go straight ahead along this road until you reach the traffic lights. Then turn right onto King Street.",
      },
      {
        speaker: "Tourist",
        text: "Right at the traffic lights — got it. And then?",
      },
      {
        speaker: "Local",
        text: "Follow King Street for about five minutes. You'll pass a large church on your left — keep going past it.",
      },
      {
        speaker: "Tourist",
        text: "Past the church. Is it much further after that?",
      },
      {
        speaker: "Local",
        text: "No — take the second left after the church. That brings you to Trafalgar Square. The Gallery is directly opposite, across the square.",
      },
      {
        speaker: "Tourist",
        text: "Wonderful. So: straight ahead, right at the lights, past the church, second left — and it's there?",
      },
      {
        speaker: "Local",
        text: "Exactly. You can't miss it — it's a huge building with columns at the front. About a ten-minute walk altogether.",
      },
    ],
  },
  mistakes: [
    {
      id: "giving-directions-go-straight-ahead-and-turn-left-turn-to-",
      wrong: '"Go straight and turn in the left."',
      right: '"Go straight ahead and turn left." / "Turn to the left."',
      note: "'Turn left' (no preposition needed) or 'turn to the left' (with 'to'). Never 'turn in the left'. 'Left' and 'right' work as adverbs of direction.",
    },
    {
      id: "giving-directions-it-s-opposite-the-bank",
      wrong: '"It\'s in the opposite of the bank."',
      right: '"It\'s opposite the bank."',
      note: "'Opposite' works as a preposition — no 'in the' or 'of' needed. 'The shop is opposite the bank.' Simple and direct.",
    },
    {
      id: "giving-directions-go-straight-on-carry-on-until-the-end-of",
      wrong: '"Continue straight until the end of the road."',
      right:
        '"Go straight on / carry on until the end of the road." / "Continue to the end of the road."',
      note: "'Continue straight' mixes register. Use 'go straight on' (natural spoken English), 'carry on' (British informal), or 'continue along/to' (more formal).",
    },
    {
      id: "giving-directions-cross-the-road-at-the-pedestrian-crossin",
      wrong: '"Cross the road in the pedestrian crossing."',
      right: '"Cross the road at the pedestrian crossing."',
      note: "Use 'at' for specific crossing points: 'at the pedestrian crossing', 'at the traffic lights', 'at the roundabout'. 'In' is for enclosed spaces.",
    },
    {
      id: "giving-directions-the-museum-is-near-the-station-the-museu",
      wrong: '"The museum is near to the station."',
      right: '"The museum is near the station." / "The museum is close to the station."',
      note: "'Near' doesn't need 'to' — 'near the station' is correct. But 'close' does need 'to': 'close to the station'. Don't mix the patterns.",
    },
    {
      id: "giving-directions-take-the-road-that-leads-to-the-park",
      wrong: '"Take the road who goes to the park."',
      right: '"Take the road that leads to the park."',
      note: "'Who' is for people only. Roads use 'that' or 'which'. Also, roads 'lead to' places (not 'go to') in direction-giving register.",
    },
  ],
  wordFormation: [
    {
      noun: "direction",
      verb: "direct",
      adjective: "direct",
      adverb: "directly",
    },
    {
      noun: "crossing",
      verb: "cross",
      adjective: null,
      adverb: null,
    },
    {
      noun: "turning",
      verb: "turn",
      adjective: null,
      adverb: null,
    },
    {
      noun: "junction",
      verb: null,
      adjective: null,
      adverb: null,
    },
    {
      noun: "intersection",
      verb: "intersect",
      adjective: "intersecting",
      adverb: null,
    },
    {
      noun: "navigation",
      verb: "navigate",
      adjective: "navigational",
      adverb: null,
    },
    {
      noun: "destination",
      verb: null,
      adjective: null,
      adverb: null,
    },
    {
      noun: "route",
      verb: "route/reroute",
      adjective: null,
      adverb: null,
    },
    {
      noun: "orientation",
      verb: "orient/orientate",
      adjective: "oriented",
      adverb: null,
    },
    {
      noun: "landmark",
      verb: null,
      adjective: null,
      adverb: null,
    },
  ],
  blankExercises: [
    {
      id: "giving-directions-b1",
      sentence: "Go ____ ahead for 200 metres, then turn right at the T-junction.",
      answer: "straight",
    },
    {
      id: "giving-directions-b2",
      sentence: "The supermarket is ____ the road from the bank — directly facing it.",
      answer: "across/opposite",
    },
    {
      id: "giving-directions-b3",
      sentence: "Take the first ____ on the left and you'll see the entrance to the car park.",
      answer: "turning",
    },
    {
      id: "giving-directions-b4",
      sentence: "If you reach the church, you've gone too ____. Turn back and look for the alley.",
      answer: "far",
    },
    {
      id: "giving-directions-b5",
      sentence: "The café is just a ____ throw from the station — less than a minute's walk.",
      answer: "stone's",
    },
    {
      id: "giving-directions-b6",
      sentence: "At the ____, take the third exit towards the city centre.",
      answer: "roundabout",
    },
    {
      id: "giving-directions-b7",
      sentence: "We took a ____ through the park to avoid the traffic on the main road.",
      answer: "shortcut",
    },
    {
      id: "giving-directions-b8",
      sentence: "She completely lost her ____ in the old market — every street looked identical.",
      answer: "bearings",
    },
    {
      id: "giving-directions-b9",
      sentence: "The hotel is ____ to the museum — you can walk there in under two minutes.",
      answer: "next/close",
    },
    {
      id: "giving-directions-b10",
      sentence: "Cross at the ____ crossing where the green light shows — it's much safer.",
      answer: "pedestrian",
    },
  ],
  culturalNotes: [
    {
      id: "giving-directions-british-politeness-in-asking",
      title: "British Politeness in Asking",
      body: "In Britain, asking for directions starts with extreme politeness: 'Excuse me, I'm terribly sorry to bother you, but could you possibly tell me the way to...?' A simple 'Where is the station?' can sound abrupt. Adding 'please' and hedging shows good manners.",
    },
    {
      id: "giving-directions-street-naming-systems",
      title: "Street Naming Systems",
      body: "British streets have names like Road, Street, Lane, Avenue, Close, Crescent, Drive, Way, and Terrace — each originally describing the road's character. American subdivisions often use thematic naming (all trees, all presidents). Knowing these helps with navigation.",
    },
    {
      id: "giving-directions-roundabouts",
      title: "Roundabouts",
      body: "Roundabouts are far more common in Britain than in America. Giving directions involving roundabouts uses specific language: 'take the first/second/third exit', 'go all the way round', 'it's the exit signed for...'. American drivers often find roundabouts confusing.",
    },
    {
      id: "giving-directions-indoor-directions",
      title: "Indoor Directions",
      body: "Navigating buildings has its own vocabulary: 'ground floor' (British) vs 'first floor' (American — causing constant confusion), 'lift' vs 'elevator', 'corridor' vs 'hallway', 'reception' vs 'lobby'. University campuses add: 'quad', 'wing', 'block'.",
    },
    {
      id: "giving-directions-compass-points",
      title: "Compass Points",
      body: "British people rarely use compass directions in everyday conversation (unlike Americans who commonly say 'head north'). British directions rely on landmarks: 'past the pub', 'opposite the church'. Compass points are reserved for maps and formal navigation.",
    },
  ],
  wordMeta: [
    {
      word: "roundabout",
      partOfSpeech: "n",
      frequency: 3,
      collocations: ["at the ~", "~ exit", "mini ~", "traffic ~"],
    },
    {
      word: "junction",
      partOfSpeech: "n",
      frequency: 3,
      collocations: ["T-~", "road ~", "motorway ~", "at the ~"],
    },
    {
      word: "crossroads",
      partOfSpeech: "n",
      frequency: 2,
      collocations: ["at the ~", "reach the ~", "~ of life", "busy ~"],
    },
    {
      word: "pedestrian",
      partOfSpeech: "n/adj",
      frequency: 3,
      collocations: ["~ crossing", "~ zone", "~ bridge", "~ area"],
    },
    {
      word: "pavement",
      partOfSpeech: "n",
      frequency: 3,
      collocations: ["on the ~ (UK)", "~ café", "~ artist", "cracked ~"],
    },
    {
      word: "shortcut",
      partOfSpeech: "n",
      frequency: 2,
      collocations: ["take a ~", "keyboard ~", "no ~s", "~ through"],
    },
    {
      word: "landmark",
      partOfSpeech: "n",
      frequency: 2,
      collocations: ["famous ~", "use as a ~", "~ building", "historical ~"],
    },
    {
      word: "destination",
      partOfSpeech: "n",
      frequency: 3,
      collocations: ["final ~", "reach your ~", "popular ~", "holiday ~"],
    },
    {
      word: "detour",
      partOfSpeech: "n",
      frequency: 2,
      collocations: ["make a ~", "traffic ~", "take a ~", "scenic ~"],
    },
    {
      word: "route",
      partOfSpeech: "n",
      frequency: 3,
      collocations: ["bus ~", "scenic ~", "~ map", "escape ~"],
    },
  ],
};
