// Learning materials for "The Human Body (Head & Face)".
//
// Structured module covering vocabulary for head, eyes, ears, mouth, teeth, and facial features.

import type { UnitLearningMaterials } from "../types";

export const HUMAN_BODY_HEAD_AND_FACE_LEARNING: UnitLearningMaterials = {
  unitId: "human-body-head-and-face",
  subtopics: [
    {
      id: "human-body-head-and-face-1",
      title: "Head & Facial Structure",
      wordIds: [
        "head",
        "skull",
        "scalp",
        "temple",
        "crown",
        "forehead",
        "jaw",
        "chin",
        "neck",
        "throat",
        "eye",
        "eyebrow",
        "eyelid",
        "eyelash",
        "pupil",
      ],
    },
    {
      id: "human-body-head-and-face-2",
      title: "Eyes & Nose Anatomy",
      wordIds: [
        "iris",
        "retina",
        "cornea",
        "tear-duct",
        "eye-socket",
        "nose",
        "nostril",
        "bridge-of-nose",
        "mouth",
        "lip",
        "upper-lip",
        "lower-lip",
        "tongue",
        "palate",
        "gums",
      ],
    },
    {
      id: "human-body-head-and-face-3",
      title: "Ears & Dental Anatomy",
      wordIds: [
        "ear",
        "earlobe",
        "ear-canal",
        "eardrum",
        "inner-ear",
        "outer-ear",
        "hearing",
        "sound-wave",
        "balance",
        "cochlea",
        "tooth",
        "incisor",
        "canine",
        "molar",
        "premolar",
      ],
    },
    {
      id: "human-body-head-and-face-4",
      title: "Teeth, Hair & Facial Styles",
      wordIds: [
        "wisdom-tooth",
        "baby-tooth",
        "enamel",
        "root",
        "hair",
        "hairline",
        "part",
        "strand",
        "beard",
        "mustache",
        "sideburns",
        "stubble",
        "goatee",
        "braid",
      ],
    },
  ],
  passage: {
    title: "The Architecture of the Human Face",
    level: "B1",
    text: "The human head and face house our most vital sensory organs and serve as the primary center for nonverbal communication. Beneath the skin and scalp, the hard bone of the skull protects the brain, while the jaw and chin frame the lower face.\n\nOur eyes are intricate optical instruments. Light enters through the cornea and pupil, while the colored iris controls the amount of light before images reach the retina at the back of the eye. Delicate eyelids and eyelashes shield the eyes from dust, and tear ducts supply moisture.\n\nNearby, the nose warms and filters inhaled air through each nostril. In the mouth, strong enamel protects each tooth, including incisors for cutting food and molars for chewing. The tongue and palate work together to form speech sounds and taste food.\n\nOn the sides of the head, the outer ear collects sound waves and directs them down the ear canal to the eardrum. Beyond hearing, structures inside the inner ear maintain our sense of physical balance. Finally, facial hair such as a beard, mustache, or sideburns adds distinctive personal character to our appearance.",
    questions: [],
    openQuestions: [
      "Which bone protects the human brain?",
      "What is the function of the iris in the eye?",
      "How do the incisors and molars differ in function?",
      "Which part of the ear helps maintain physical balance?",
      "How do eyelids and eyelashes protect the eye?",
    ],
  },
  phrases: [
    {
      id: "head-face-keep-an-eye-on",
      phrase: "keep an eye on",
      kind: "idiom",
      meaning: "to watch or supervise someone or something carefully",
      example: "Please keep an eye on the soup so it doesn't boil over on the stove.",
    },
    {
      id: "head-face-see-eye-to-eye",
      phrase: "see eye to eye",
      kind: "idiom",
      meaning: "to agree fully with someone",
      example: "They rarely see eye to eye when choosing new furniture for the office.",
    },
    {
      id: "head-face-catch-someone-s-eye",
      phrase: "catch someone's eye",
      kind: "idiom",
      meaning: "to attract someone's visual attention",
      example: "The bright portrait in the museum caught my eye immediately.",
    },
    {
      id: "head-face-by-word-of-mouth",
      phrase: "by word of mouth",
      kind: "idiom",
      meaning: "spread through spoken communication between people",
      example: "The new dental clinic became popular entirely by word of mouth.",
    },
    {
      id: "head-face-keep-your-chin-up",
      phrase: "keep your chin up",
      kind: "idiom",
      meaning: "stay cheerful and optimistic during a difficult situation",
      example: "Keep your chin up! You will do much better on the next exam.",
    },
    {
      id: "head-face-sweet-tooth",
      phrase: "have a sweet tooth",
      kind: "idiom",
      meaning: "to enjoy eating sugary foods and desserts",
      example: "He has a sweet tooth and always orders dessert after dinner.",
    },
    {
      id: "head-face-turn-a-deaf-ear",
      phrase: "turn a deaf ear",
      kind: "idiom",
      meaning: "to refuse to listen to advice or a request",
      example: "The company turned a deaf ear to customer complaints about the app.",
    },
    {
      id: "head-face-head-over-heels",
      phrase: "head over heels",
      kind: "idiom",
      meaning: "deeply and completely in love",
      example: "They were head over heels in love and decided to get married.",
    },
  ],
  dialogue: {
    title: "At the Health Clinic",
    scene: "A patient describes symptoms to a physician during an annual health check",
    lines: [
      {
        speaker: "Doctor",
        text: "Good morning. What symptoms are you experiencing today?",
      },
      {
        speaker: "Patient",
        text: "I've had a dull headache near my temples and some soreness in my throat.",
      },
      {
        speaker: "Doctor",
        text: "Let's take a look. Please tilt your head back so I can check your eyes and pupils.",
      },
      {
        speaker: "Patient",
        text: "My eyes have felt slightly dry too, especially after working on the computer.",
      },
      {
        speaker: "Doctor",
        text: "Your cornea and eyelids look healthy. Now open your mouth wide and say 'ah' so I can check your palate and throat.",
      },
      {
        speaker: "Patient",
        text: "Ahhh. Is there any sign of infection around my gums or teeth?",
      },
      {
        speaker: "Doctor",
        text: "Your gums and molars look fine, but your throat is slightly irritated. Let's also inspect your ear canal and eardrum with the otoscope.",
      },
      {
        speaker: "Patient",
        text: "Thank you, doctor. I appreciate the thorough check.",
      },
    ],
  },
  mistakes: [
    {
      id: "head-face-comb-my-hair",
      wrong: '"I need to comb my hairs before going out."',
      right: '"I need to comb my hair before going out."',
      note: "'Hair' is uncountable when referring to the hair on your head as a whole. Use singular 'hair'.",
    },
    {
      id: "head-face-my-head-hurts",
      wrong: '"My head is paining very much."',
      right: '"My head hurts very much." / "I have a bad headache."',
      note: "In natural English, use 'hurts' or 'have a headache' rather than 'is paining'.",
    },
    {
      id: "head-face-cover-ears",
      wrong: '"He closed his ears with his fingers."',
      right: '"He covered his ears with his hands/fingers."',
      note: "You 'close' your eyes, but you 'cover' your ears since ears cannot close on their own.",
    },
    {
      id: "head-face-tooth-plural",
      wrong: '"He brushed all his tooths."',
      right: '"He brushed all his teeth."',
      note: "The plural of 'tooth' is the irregular form 'teeth'.",
    },
    {
      id: "head-face-look-in-the-eye",
      wrong: '"She looked me in the eyes directly."',
      right: '"She looked me in the eye." / "She made eye contact."',
      note: "The idiom is 'look someone in the eye' (singular) when describing direct, honest gaze.",
    },
  ],
  wordFormation: [
    {
      base: "eye",
      noun: "eyesight",
      verb: "eye",
      adjective: "eyeless",
      adverb: null,
    },
    {
      base: "tooth",
      noun: "dentist",
      verb: "indent",
      adjective: "dental",
      adverb: "dentally",
    },
    {
      base: "hear",
      noun: "hearing",
      verb: "hear",
      adjective: "audible",
      adverb: "audibly",
    },
    {
      base: "face",
      noun: "facial",
      verb: "face",
      adjective: "facial",
      adverb: "facially",
    },
  ],
  blankExercises: [
    {
      id: "b1",
      sentence: "The hard bone of the ____ protects the brain from external injury.",
      answer: "skull",
    },
    {
      id: "b2",
      sentence: "Light enters the eye through the circular opening called the ____.",
      answer: "pupil",
    },
    {
      id: "b3",
      sentence: "The doctor used an instrument to inspect the patient's ____ and eardrum.",
      answer: "ear-canal",
    },
    {
      id: "b4",
      sentence: "Brushing regularly helps remove plaque and protect your tooth ____.",
      answer: "enamel",
    },
    {
      id: "b5",
      sentence: "He grew a neat ____ and mustache over the winter holidays.",
      answer: "beard",
    },
  ],
  culturalNotes: [
    {
      id: "cn1",
      title: "Eye Contact Across Cultures",
      body: "In many Western cultures, direct eye contact signifies confidence, attentiveness, and honesty. In contrast, in some Asian and Middle Eastern cultures, prolonged direct eye contact with elders or superiors can be perceived as disrespectful or overly assertive.",
    },
    {
      id: "cn2",
      title: "Head Gestures & Nodding",
      body: "In most countries, nodding up and down signals agreement ('yes') while shaking side to side means disagreement ('no'). However, in Bulgaria and parts of Greece, a single head tilt upwards often means 'no', and a side-to-side head wobble in South Asia communicates acknowledgment.",
    },
  ],
  wordMeta: [
    {
      word: "skull",
      partOfSpeech: "noun",
      frequency: 3,
      collocations: ["human skull", "fractured skull", "skull and crossbones"],
    },
    {
      word: "cornea",
      partOfSpeech: "noun",
      frequency: 2,
      collocations: ["corneal transplant", "cornea surgery", "clear cornea"],
    },
    {
      word: "eardrum",
      partOfSpeech: "noun",
      frequency: 2,
      collocations: ["perforated eardrum", "ruptured eardrum", "eardrum vibration"],
    },
    {
      word: "enamel",
      partOfSpeech: "noun",
      frequency: 2,
      collocations: ["tooth enamel", "protect enamel", "erode enamel"],
    },
  ],
};
