// Learning materials for "The Meeting Room".
//
// GENERATED by scripts/build-learning-materials.mjs from figma-dump/meeting-room.json.
// Figma is the source of truth: edit the design file and re-run the sync,
// do not hand-edit this file.

import type { UnitLearningMaterials } from "../types";

export const MEETING_ROOM_LEARNING: UnitLearningMaterials = {
  unitId: "meeting-room",
  subtopics: [
    {
      id: "meeting-equipment",
      title: "Meeting Equipment",
      wordIds: [
        "projector-screen",
        "laser-pointer",
        "microphone",
        "speaker",
        "camera",
        "flip-chart",
        "marker",
        "remote-clicker",
        "name-plate",
        "agenda",
      ],
    },
    {
      id: "meeting-types",
      title: "Meeting Types",
      wordIds: [
        "staff-meeting",
        "board-meeting",
        "one-on-one",
        "brainstorm",
        "stand-up",
        "town-hall",
        "workshop",
        "webinar",
        "kick-off",
        "retrospective",
      ],
    },
    {
      id: "presentation-tools",
      title: "Presentation Tools",
      wordIds: [
        "slide-deck",
        "handout",
        "report",
        "chart",
        "graph",
        "diagram",
        "flowchart",
        "timeline",
        "spreadsheet",
        "dashboard",
      ],
    },
    {
      id: "meeting-actions",
      title: "Meeting Actions",
      wordIds: [
        "present",
        "discuss",
        "vote",
        "approve",
        "reject",
        "table",
        "follow-up",
        "assign",
        "minute",
        "adjourn",
      ],
    },
    {
      id: "virtual-meetings",
      title: "Virtual Meetings",
      wordIds: [
        "zoom",
        "teams",
        "screen-share",
        "mute",
        "unmute",
        "chat",
        "breakout-room",
        "waiting-room",
        "recording",
        "virtual-background",
      ],
    },
  ],
  passage: {
    title: "Reading Passage",
    level: "C1",
    text: "The meeting room is where decisions are made, ideas are debated, and strategies are shaped. Effective meetings follow a structured format: the chairperson (or chair) opens the meeting, follows an agenda (a list of topics to discuss), manages contributions from attendees, and ensures action items are recorded in the minutes (official written record). Meetings can be formal (board meetings, annual general meetings) or informal (catch-ups, brainstorming sessions, stand-ups). The language of meetings is highly codified: 'Shall we begin?', 'Moving on to the next item...', 'Does anyone have anything to add?', 'Let's wrap up.' Participants propose ideas ('I'd like to suggest...'), second motions ('I support that proposal'), raise concerns ('I have some reservations about...'), and table items for later discussion ('Let's park that for now'). Voting may be by show of hands, voice vote, or formal ballot. Technology has transformed meetings: video conferencing, screen sharing, virtual whiteboards, and chat functions now supplement or replace in-person gatherings. The hybrid meeting — some attendees in the room, others joining remotely — has introduced new challenges around inclusion and etiquette. Common complaints about meetings include poor time management, lack of clear outcomes, and the dreaded 'meeting that could have been an email'. Understanding meeting vocabulary and conventions is crucial for professional success in English-speaking workplaces.",
    questions: [],
    openQuestions: [
      "What is the role of the chairperson in a meeting?",
      "What are 'minutes' in a meeting context?",
      "How do formal and informal meetings differ?",
      "What phrases are used to manage meeting discussions?",
      "What challenges do hybrid meetings create?",
    ],
  },
  phrases: [
    {
      id: "meeting-room-let-s-wrap-up",
      phrase: "let's wrap up",
      kind: "phrasal-verb",
      kindInferred: true,
      meaning:
        "(phrase) To finish a meeting or discussion. \"We're running over time — let's wrap up. Any final comments?\"",
      example: "",
    },
    {
      id: "meeting-room-park-that-idea",
      phrase: "park that idea",
      kind: "idiom",
      kindInferred: true,
      meaning:
        "(phrase) To postpone discussing something. \"That's interesting, but let's park that idea for now and come back to it next week.\"",
      example: "",
    },
    {
      id: "meeting-room-take-the-floor",
      phrase: "take the floor",
      kind: "idiom",
      meaning: "To speak in a meeting.",
      example: "Sarah, would you like to take the floor and present the Q3 figures?",
    },
    {
      id: "meeting-room-play-devil-s-advocate",
      phrase: "play devil's advocate",
      kind: "idiom",
      meaning: "To argue the opposite side deliberately.",
      example:
        "Let me play devil's advocate — what if the product doesn't sell as well as we expect?",
    },
    {
      id: "meeting-room-bring-someone-up-to-speed",
      phrase: "bring someone up to speed",
      kind: "idiom",
      meaning: "To update someone on progress.",
      example: "Can you bring the new director up to speed on where the project stands?",
    },
    {
      id: "meeting-room-circle-back",
      phrase: "circle back",
      kind: "phrasal-verb",
      kindInferred: true,
      meaning:
        "(phrase) To return to a topic later. \"Let's circle back to that point after we've heard the budget update.\"",
      example: "",
    },
    {
      id: "meeting-room-hammer-out-the-details",
      phrase: "hammer out the details",
      kind: "idiom",
      meaning: "To negotiate and agree on specifics.",
      example: "We've agreed on the concept — now we need to hammer out the details.",
    },
    {
      id: "meeting-room-go-round-in-circles",
      phrase: "go round in circles",
      kind: "idiom",
      meaning: "To discuss without making progress.",
      example: "We've been going round in circles for an hour — someone needs to make a decision.",
    },
    {
      id: "meeting-room-raise-a-point",
      phrase: "raise a point",
      kind: "idiom",
      kindInferred: true,
      meaning:
        "(phrase) To bring up a topic for discussion. \"I'd like to raise a point about the timeline — I think it's too tight.\"",
      example: "",
    },
    {
      id: "meeting-room-table-a-motion",
      phrase: "table a motion",
      kind: "idiom",
      kindInferred: true,
      meaning:
        '(phrase) To propose formally (UK) or postpone (US). "I\'d like to table a motion to increase the budget by 10%. (UK: propose / US: delay)"',
      example: "",
    },
  ],
  dialogue: {
    title: "A Team Meeting",
    lines: [
      {
        speaker: "Chair",
        text: "Right, shall we begin? The agenda today has three items: the project update, the budget review, and any other business.",
      },
      {
        speaker: "Marketing Lead",
        text: "Before we start, could someone bring me up to speed on last week's action items? I was on leave.",
      },
      {
        speaker: "Chair",
        text: "Of course. The client approved the proposal, and the design team submitted the first draft. Both items from the minutes are closed.",
      },
      {
        speaker: "Developer",
        text: "I'd like to raise a point about the timeline. We're behind schedule because the API integration took longer than expected.",
      },
      {
        speaker: "Chair",
        text: "How much time do you need? Can we discuss this under the project update item?",
      },
      {
        speaker: "Developer",
        text: "Two extra weeks would be realistic. I don't want to overpromise and underdeliver.",
      },
      {
        speaker: "Chair",
        text: "Noted. Let's hammer out the revised timeline after this meeting. Moving on to the budget — Sarah, would you like to take the floor?",
      },
      {
        speaker: "Finance Manager",
        text: "Thanks. In brief: we're 5% under budget for Q3, which gives us some flexibility. I'll circulate the full breakdown after the meeting.",
      },
    ],
  },
  mistakes: [
    {
      id: "meeting-room-we-discussed-the-budget",
      wrong: '"We discussed about the budget."',
      right: '"We discussed the budget."',
      note: "'Discuss' is transitive — no 'about'. You discuss something (direct object). However, 'We had a discussion about the budget' is correct — 'discussion' takes 'about'.",
    },
    {
      id: "meeting-room-the-meeting-will-be-on-monday",
      wrong: '"The meeting will be in Monday."',
      right: '"The meeting will be on Monday."',
      note: "'On' for days: 'on Monday', 'on the 15th'. 'In' for months/years: 'in January', 'in 2024'. 'At' for times: 'at 3 pm'. These prepositions are fixed.",
    },
    {
      id: "meeting-room-she-suggested-postponing-the-meeting-she",
      wrong: '"She suggested to postpone the meeting."',
      right:
        '"She suggested postponing the meeting." / "She suggested that we postpone the meeting."',
      note: "'Suggest' takes a gerund (suggest + -ing) or a that-clause (suggest that...). Never 'suggest to do'. Same rule applies to 'recommend' and 'propose'.",
    },
    {
      id: "meeting-room-who-is-going-to-take-the-minutes",
      wrong: '"Who is going to do the minutes?" (unclear)',
      right: '"Who is going to take the minutes?"',
      note: "You 'take minutes' (record them during the meeting). 'Do the minutes' is understood but less precise. Also: 'circulate the minutes' (share them afterward).",
    },
    {
      id: "meeting-room-i-agree-with-this-proposal-i-second-it",
      wrong: '"I agree with this proposal. I am also supporting it."',
      right: '"I agree with this proposal. I second it."',
      note: "In formal meetings, 'second' means to formally support a proposal. 'I second that' is the standard phrase. 'I am also supporting it' is grammatically correct but not meeting convention.",
    },
    {
      id: "meeting-room-let-s-arrange-a-meeting-next-week-let-s-",
      wrong: '"Let\'s arrange a meeting in next week."',
      right: '"Let\'s arrange a meeting next week." / "Let\'s arrange a meeting for next week."',
      note: "'Next week' doesn't need 'in': 'I'll see you next week.' But 'for next week' works when scheduling: 'The meeting is scheduled for next Tuesday.'",
    },
  ],
  wordFormation: [
    {
      noun: "agenda",
      verb: null,
      adjective: null,
      adverb: null,
    },
    {
      noun: "minutes",
      verb: "minute",
      adjective: null,
      adverb: null,
    },
    {
      noun: "proposal",
      verb: "propose",
      adjective: "proposed",
      adverb: null,
    },
    {
      noun: "decision",
      verb: "decide",
      adjective: "decisive",
      adverb: "decisively",
    },
    {
      noun: "agreement",
      verb: "agree",
      adjective: "agreeable",
      adverb: "agreeably",
    },
    {
      noun: "negotiation",
      verb: "negotiate",
      adjective: "negotiable",
      adverb: null,
    },
    {
      noun: "attendance",
      verb: "attend",
      adjective: "attendant",
      adverb: null,
    },
    {
      noun: "contribution",
      verb: "contribute",
      adjective: "contributory",
      adverb: null,
    },
    {
      noun: "discussion",
      verb: "discuss",
      adjective: null,
      adverb: null,
    },
    {
      noun: "presentation",
      verb: "present",
      adjective: null,
      adverb: null,
    },
  ],
  blankExercises: [
    {
      id: "meeting-room-b1",
      sentence:
        "The ____ opened the meeting and welcomed everyone, then outlined the topics for discussion.",
      answer: "chair/chairperson",
    },
    {
      id: "meeting-room-b2",
      sentence:
        "Could you send out the ____ before the meeting so everyone knows what we'll be covering?",
      answer: "agenda",
    },
    {
      id: "meeting-room-b3",
      sentence: "Who's going to take the ____ today? We need a written record of all decisions.",
      answer: "minutes",
    },
    {
      id: "meeting-room-b4",
      sentence: "I'd like to ____ a point about the delivery timeline — I think we need more time.",
      answer: "raise",
    },
    {
      id: "meeting-room-b5",
      sentence: "Let's ____ that topic for now and come back to it when we have more data.",
      answer: "park/table",
    },
    {
      id: "meeting-room-b6",
      sentence: "She made a ____ to increase the marketing budget, and two colleagues seconded it.",
      answer: "proposal/motion",
    },
    {
      id: "meeting-room-b7",
      sentence: "Can you ____ the new team members up to speed on what we agreed last week?",
      answer: "bring",
    },
    {
      id: "meeting-room-b8",
      sentence: "We've been going round in ____ — someone needs to make a final decision.",
      answer: "circles",
    },
    {
      id: "meeting-room-b9",
      sentence: "The meeting is scheduled ____ Tuesday at 10 am in the large conference room.",
      answer: "for",
    },
    {
      id: "meeting-room-b10",
      sentence:
        "Let's ____ up — we're five minutes over time. I'll circulate the action items by email.",
      answer: "wrap",
    },
  ],
  culturalNotes: [
    {
      id: "meeting-room-table-means-opposite-things",
      title: "'Table' Means Opposite Things",
      body: "In British English, to 'table' a motion means to put it forward for discussion NOW. In American English, to 'table' means to POSTPONE or shelve it. This is one of the most dangerous false friends in transatlantic business communication.",
    },
    {
      id: "meeting-room-meeting-culture-differences",
      title: "Meeting Culture Differences",
      body: "British meetings tend to be more indirect: 'I wonder if we might consider...' (I think we should). American meetings are often more direct: 'I think we need to...' Understanding these registers prevents misinterpretation in international teams.",
    },
    {
      id: "meeting-room-aob-any-other-business",
      title: "AOB — Any Other Business",
      body: "British meeting agendas always end with 'AOB' (Any Other Business) — a final item for raising topics not on the agenda. It's standard format, and knowing the abbreviation shows familiarity with British professional culture.",
    },
    {
      id: "meeting-room-stand-up-meetings",
      title: "Stand-Up Meetings",
      body: "Agile workplaces use 'stand-ups' — brief daily meetings where everyone stands (to keep it short). Each person answers: 'What did I do yesterday?', 'What am I doing today?', 'Are there any blockers?' This vocabulary comes from software development.",
    },
    {
      id: "meeting-room-virtual-meeting-etiquette",
      title: "Virtual Meeting Etiquette",
      body: "Video call etiquette has its own vocabulary: 'You're on mute', 'Can you share your screen?', 'Let's go round the room', 'Drop it in the chat', 'Sorry, you froze for a second'. These phrases are now as common as traditional meeting language.",
    },
  ],
  wordMeta: [
    {
      word: "agenda",
      partOfSpeech: "n",
      frequency: 3,
      collocations: ["meeting ~", "~ item", "on the ~", "hidden ~"],
    },
    {
      word: "minutes",
      partOfSpeech: "n",
      frequency: 3,
      collocations: ["take ~", "meeting ~", "read the ~", "approve ~"],
    },
    {
      word: "chairperson",
      partOfSpeech: "n",
      frequency: 2,
      collocations: ["~ of the meeting", "act as ~", "elect a ~", "~'s report"],
    },
    {
      word: "proposal",
      partOfSpeech: "n",
      frequency: 3,
      collocations: ["make a ~", "accept a ~", "reject a ~", "budget ~"],
    },
    {
      word: "action item",
      partOfSpeech: "n",
      frequency: 2,
      collocations: ["assign an ~", "~ list", "outstanding ~", "complete an ~"],
    },
    {
      word: "brainstorm",
      partOfSpeech: "n/v",
      frequency: 2,
      collocations: ["~ session", "~ ideas", "~ meeting", "~ together"],
    },
    {
      word: "consensus",
      partOfSpeech: "n",
      frequency: 2,
      collocations: ["reach ~", "general ~", "build ~", "~ view"],
    },
    {
      word: "stakeholder",
      partOfSpeech: "n",
      frequency: 2,
      collocations: ["key ~", "~ meeting", "~ engagement", "~ analysis"],
    },
    {
      word: "outcome",
      partOfSpeech: "n",
      frequency: 3,
      collocations: ["meeting ~", "positive ~", "~ report", "desired ~"],
    },
    {
      word: "quorum",
      partOfSpeech: "n",
      frequency: 1,
      collocations: ["reach a ~", "~ present", "~ required", "lack a ~"],
    },
  ],
};
