// Learning materials for "Moving & Settling In".
//
// GENERATED by scripts/build-learning-materials.mjs from figma-dump/moving-settling-in.json.
// Figma is the source of truth: edit the design file and re-run the sync,
// do not hand-edit this file.

import type { UnitLearningMaterials } from "../types";

export const MOVING_SETTLING_IN_LEARNING: UnitLearningMaterials = {
  unitId: "moving-settling-in",
  subtopics: [
    {
      id: "moving-supplies",
      title: "Moving Supplies",
      wordIds: [
        "moving-box",
        "packing-tape",
        "bubble-wrap",
        "packing-paper",
        "marker",
        "moving-blanket",
        "dolly",
        "hand-truck",
        "rope",
        "zip-tie",
      ],
    },
    {
      id: "moving-process",
      title: "Moving Process",
      wordIds: [
        "pack",
        "load",
        "unload",
        "unpack",
        "label",
        "sort",
        "donate",
        "discard",
        "disassemble",
        "reassemble",
      ],
    },
    {
      id: "setting-up",
      title: "Setting Up",
      wordIds: [
        "change-address",
        "transfer-utilities",
        "install-internet",
        "register-vehicle",
        "update-license",
        "find-doctor",
        "enroll-in-school",
        "meet-neighbors",
        "explore-area",
        "housewarming",
      ],
    },
    {
      id: "furniture",
      title: "Furniture",
      wordIds: [
        "sofa",
        "bed-frame",
        "mattress",
        "dining-table",
        "dresser",
        "nightstand",
        "bookcase",
        "desk",
        "coffee-table",
        "tv-stand",
      ],
    },
  ],
  passage: {
    title: "Reading Passage",
    level: "C1",
    text: "Moving house is consistently ranked among life's most stressful experiences — alongside divorce and bereavement. The process begins weeks before the actual move: decluttering, packing boxes, labelling rooms, and arranging removal services. Most people hire a removal company — professional movers who load, transport, and unload belongings. The alternative is a DIY move with a hired van, help from friends, and a lot of pizza as payment. On moving day itself, the removal team arrives early. Furniture is wrapped in protective blankets, boxes are stacked in the van, and fragile items are handled with extra care. The old home must be left clean and empty — estate agents or landlords typically conduct a final inspection. Arriving at the new home, priorities include checking utilities (gas, electricity, water), locating the fuse box and stopcock, and setting up essential rooms — bedroom, kitchen, and bathroom — first. Over the following weeks, settling in involves unpacking, arranging furniture, hanging pictures, and gradually making the space feel like home. Meeting the neighbours is an important social step — in Britain, a friendly wave, a brief chat over the garden fence, or offering a cup of tea establishes a positive relationship. Registering with a new GP, updating your address with banks and the DVLA, and redirecting post are administrative tasks easily forgotten in the chaos of moving.",
    questions: [],
    openQuestions: [
      "Why is moving house considered so stressful?",
      "What does a removal company typically do?",
      "What are the first priorities when arriving at a new home?",
      "How do British people typically introduce themselves to new neighbours?",
      "What administrative tasks must be completed after moving?",
    ],
  },
  phrases: [
    {
      id: "moving-settling-in-move-in-move-out",
      phrase: "move in / move out",
      kind: "phrasal-verb",
      meaning: "To begin/stop living somewhere.",
      example:
        "We moved in on Saturday and spent the whole weekend unpacking — we didn't move out of the old flat until Friday evening.",
    },
    {
      id: "moving-settling-in-housewarming",
      phrase: "housewarming",
      kind: "idiom",
      kindInferred: true,
      meaning:
        '(noun) A party to celebrate moving into a new home. "They threw a housewarming the weekend after moving in — friends brought wine, plants, and scented candles."',
      example: "",
    },
    {
      id: "moving-settling-in-settle-in",
      phrase: "settle in",
      kind: "phrasal-verb",
      meaning: "To become comfortable in a new place.",
      example:
        "It took a few weeks to settle in — finding our favourite shops, learning the bus routes, making the place feel like home.",
    },
    {
      id: "moving-settling-in-live-out-of-boxes",
      phrase: "live out of boxes",
      kind: "idiom",
      meaning: "To not have unpacked yet.",
      example:
        "Three weeks after moving, we're still living out of boxes — the kitchen is done, but the rest is chaos.",
    },
    {
      id: "moving-settling-in-the-removal-men",
      phrase: "the removal men",
      kind: "idiom",
      kindInferred: true,
      meaning:
        '(phrase, British) Professional movers. "The removal men arrived at seven sharp — by lunchtime, the entire house was packed into the van."',
      example: "",
    },
    {
      id: "moving-settling-in-change-of-address",
      phrase: "change of address",
      kind: "idiom",
      kindInferred: true,
      meaning:
        '(phrase) Updating your registered address. "Don\'t forget your change of address — banks, GP, dentist, DVLA, subscriptions, and the electoral register."',
      example: "",
    },
    {
      id: "moving-settling-in-turn-the-key",
      phrase: "turn the key",
      kind: "idiom",
      meaning: "The moment of first entering a new home.",
      example:
        "Turning the key for the first time was emotional — after months of stress, it was finally theirs.",
    },
    {
      id: "moving-settling-in-over-the-garden-fence",
      phrase: "over the garden fence",
      kind: "idiom",
      kindInferred: true,
      meaning:
        '(phrase, British) Chatting casually with neighbours. "Most neighbourhood friendships start over the garden fence — a wave, a comment about the weather, and it builds from there."',
      example: "",
    },
    {
      id: "moving-settling-in-put-down-roots",
      phrase: "put down roots",
      kind: "idiom",
      meaning: "To establish yourself permanently in a place.",
      example:
        "After years of renting and moving, they were ready to put down roots — somewhere they could call home for good.",
    },
    {
      id: "moving-settling-in-the-joys-of-home-ownership",
      phrase: "the joys of home ownership",
      kind: "idiom",
      kindInferred: true,
      meaning:
        '(ironic phrase) The unexpected costs and tasks of owning a home. "The boiler broke on day three — welcome to the joys of home ownership."',
      example: "",
    },
  ],
  dialogue: {
    title: "Moving Day",
    lines: [
      {
        speaker: "Partner A",
        text: "The removal van's here — they're starting to load the big furniture first. Have you labelled all the kitchen boxes?",
      },
      {
        speaker: "Partner B",
        text: "Done — every box has the room name on it. I've packed the kettle and mugs separately so we can make tea the moment we arrive.",
      },
      {
        speaker: "Partner A",
        text: "Priorities! Have you turned off the gas and water? And cancelled the broadband?",
      },
      {
        speaker: "Partner B",
        text: "Gas and water are off. Broadband switches to the new address on Monday — we'll have to use mobile data for the weekend.",
      },
      {
        speaker: "Partner A",
        text: "The new neighbours sent a message through the estate agent — said they'd leave out milk and biscuits for us. That's so kind.",
      },
      {
        speaker: "Partner B",
        text: "Classic British welcome. We should take them a bottle of wine once we're settled. Have you updated our address with the council tax?",
      },
      {
        speaker: "Partner A",
        text: "Not yet — that's on my list along with the GP, the dentist, and the DVLA. I'll do it all on Monday once the chaos calms down.",
      },
      {
        speaker: "Partner B",
        text: "Right — for now, let's just get the beds set up and the kitchen unpacked. Everything else can wait.",
      },
    ],
  },
  mistakes: [
    {
      id: "moving-settling-in-we-moved-into-a-new-house-yesterday",
      wrong: "\"We moved to a new house yesterday.\" (when meaning 'moved in')",
      right: '"We moved into a new house yesterday."',
      note: "'Move to' = relocate to a place. 'Move into' = physically enter and begin living in a new home. 'Move in' = start living there. 'Move out' = leave. The preposition matters.",
    },
    {
      id: "moving-settling-in-i-need-to-pack-my-stuff-my-belongings",
      wrong: '"I need to pack my stuffs."',
      right: '"I need to pack my stuff." / "...my belongings."',
      note: "'Stuff' is uncountable — no 's'. For more formal contexts, use 'belongings', 'possessions', or 'personal effects'. 'Things' also works informally.",
    },
    {
      id: "moving-settling-in-the-removal-company-quoted-us-1-200",
      wrong: '"The removals company charged us a high price."',
      right: '"The removal company quoted us £1,200."',
      note: "'Removal company' (singular, no 's' on removal). 'Quote' is more precise than 'charge a high price' — removal firms give quotes (estimates) before the move.",
    },
    {
      id: "moving-settling-in-we-threw-a-housewarming-party-we-had-a-h",
      wrong: '"We made a house warming party."',
      right: '"We threw a housewarming party." / "We had a housewarming."',
      note: "'Throw a party', 'have a party', or 'host a party' — never 'make a party'. 'Housewarming' is one word (or hyphenated). It can stand alone: 'come to our housewarming'.",
    },
    {
      id: "moving-settling-in-i-registered-with-a-new-gp",
      wrong: '"I registered in a new doctor."',
      right: '"I registered with a new GP."',
      note: "'Register WITH a GP' — not 'in' or 'at'. 'GP' (General Practitioner) is the British term for family doctor. 'Sign up with a GP' also works.",
    },
    {
      id: "moving-settling-in-we-need-to-update-our-address-with-the-b",
      wrong: '"We need to change our direction at the bank."',
      right: '"We need to update our address with the bank."',
      note: "'Address' not 'direction'. 'Update your address', 'change of address', 'notify them of your new address'. 'Direction' means guidance or a route — not a home address.",
    },
  ],
  wordFormation: [
    {
      noun: "removal",
      verb: "remove",
      adjective: "removable",
      adverb: null,
    },
    {
      noun: "settlement",
      verb: "settle",
      adjective: "settled/unsettled",
      adverb: null,
    },
    {
      noun: "relocation",
      verb: "relocate",
      adjective: "relocated",
      adverb: null,
    },
    {
      noun: "unpacking",
      verb: "unpack",
      adjective: "unpacked",
      adverb: null,
    },
    {
      noun: "registration",
      verb: "register",
      adjective: "registered",
      adverb: null,
    },
    {
      noun: "occupation",
      verb: "occupy",
      adjective: "occupied/occupant",
      adverb: null,
    },
    {
      noun: "belongings",
      verb: "belong",
      adjective: null,
      adverb: null,
    },
    {
      noun: "decoration",
      verb: "decorate",
      adjective: "decorative",
      adverb: "decoratively",
    },
    {
      noun: "neighbourhood",
      verb: "neighbour",
      adjective: "neighbouring",
      adverb: null,
    },
    {
      noun: "establishment",
      verb: "establish",
      adjective: "established",
      adverb: null,
    },
  ],
  blankExercises: [
    {
      id: "moving-settling-in-b1",
      sentence: "The ____ company loaded everything into the van by midday — incredibly efficient.",
      answer: "removal",
    },
    {
      id: "moving-settling-in-b2",
      sentence: "They threw a ____ party the weekend after moving in to celebrate with friends.",
      answer: "housewarming",
    },
    {
      id: "moving-settling-in-b3",
      sentence: "It took a month to fully ____ in — unpacking, decorating, and learning the area.",
      answer: "settle",
    },
    {
      id: "moving-settling-in-b4",
      sentence: "Don't forget to ____ with a new GP within the first few weeks of moving.",
      answer: "register",
    },
    {
      id: "moving-settling-in-b5",
      sentence:
        "She spent the week before the move ____ — donating clothes, selling furniture, and throwing away years of clutter.",
      answer: "decluttering",
    },
    {
      id: "moving-settling-in-b6",
      sentence: "The first thing he did was locate the ____ box in case of an electrical fault.",
      answer: "fuse",
    },
    {
      id: "moving-settling-in-b7",
      sentence:
        "They redirected their ____ through Royal Mail to make sure nothing went to the old address.",
      answer: "post",
    },
    {
      id: "moving-settling-in-b8",
      sentence:
        "Meeting the ____ was easier than expected — a wave, a smile, and a chat about bins.",
      answer: "neighbours",
    },
    {
      id: "moving-settling-in-b9",
      sentence:
        "After years of renting, they were ready to put down ____ and buy somewhere permanent.",
      answer: "roots",
    },
    {
      id: "moving-settling-in-b10",
      sentence:
        "Every box was ____ with the room name — 'Kitchen', 'Main Bedroom', 'Study' — to speed up unpacking.",
      answer: "labelled",
    },
  ],
  culturalNotes: [
    {
      id: "moving-settling-in-the-kettle-goes-last-in-first-out",
      title: "The Kettle Goes Last In, First Out",
      body: "In Britain, the kettle is the most important item when moving. It's packed last into the van and unpacked first at the new home. 'I can't function until the kettle's plugged in' is only half a joke — a cup of tea is the universal British coping mechanism for stress.",
    },
    {
      id: "moving-settling-in-royal-mail-redirection",
      title: "Royal Mail Redirection",
      body: "Royal Mail offers a paid postal redirection service — all mail addressed to your old home is forwarded to the new one for 3, 6, or 12 months. 'Have you set up a redirect?' is a standard moving checklist question. Forgetting to redirect post can mean missed bills and bank statements.",
    },
    {
      id: "moving-settling-in-bin-collection-days",
      title: "Bin Collection Days",
      body: "One of the first things new residents learn is which day the bins are collected and which colour bin goes out when. Green for garden waste, blue for recycling, black for general — but colours vary by council. Getting the wrong bin out on the wrong day is a minor social embarrassment.",
    },
    {
      id: "moving-settling-in-council-tax-registration",
      title: "Council Tax Registration",
      body: "Council tax — a local property tax — must be registered at your new address immediately. Rates vary by 'band' (A–H), determined by the property's value. 'What band is it?' is a common question when house-hunting — band A is cheapest, band H is most expensive.",
    },
    {
      id: "moving-settling-in-the-neighbours-welcome",
      title: "The Neighbours' Welcome",
      body: "In many British neighbourhoods, new arrivals may receive a card, a plant, or an offer of help from neighbours — though this varies by area. In return, introducing yourself with a wave, a smile, and perhaps a bottle of wine or box of chocolates for immediate neighbours is considered good manners.",
    },
  ],
  wordMeta: [
    {
      word: "removal company",
      partOfSpeech: "n",
      frequency: 3,
      collocations: ["hire a ~", "~ quote", "~ van", "~ team"],
    },
    {
      word: "housewarming",
      partOfSpeech: "n",
      frequency: 2,
      collocations: ["~ party", "~ gift", "throw a ~", "~ invitation"],
    },
    {
      word: "settle in",
      partOfSpeech: "phr v",
      frequency: 3,
      collocations: ["~ quickly", "~ well", "still settling ~", "help ~ ~"],
    },
    {
      word: "declutter",
      partOfSpeech: "v",
      frequency: 2,
      collocations: ["~ the house", "~ before moving", "~ your wardrobe", "~ sale"],
    },
    {
      word: "belongings",
      partOfSpeech: "n (pl)",
      frequency: 3,
      collocations: ["personal ~", "pack your ~", "~ in storage", "household ~"],
    },
    {
      word: "fuse box",
      partOfSpeech: "n",
      frequency: 2,
      collocations: ["locate the ~", "~ tripped", "~ switch", "consumer unit"],
    },
    {
      word: "stopcock",
      partOfSpeech: "n",
      frequency: 2,
      collocations: ["turn off the ~", "~ location", "mains ~", "internal ~"],
    },
    {
      word: "redirect",
      partOfSpeech: "v/n",
      frequency: 2,
      collocations: ["~ post", "mail ~", "~ service", "set up a ~"],
    },
    {
      word: "council tax",
      partOfSpeech: "n",
      frequency: 3,
      collocations: ["~ band", "~ bill", "~ registration", "~ discount"],
    },
    {
      word: "neighbour",
      partOfSpeech: "n",
      frequency: 3,
      collocations: ["next-door ~", "new ~", "~hood", "~ly"],
    },
  ],
};
