// Learning materials for "Office Supplies".
//
// GENERATED by scripts/build-learning-materials.mjs from figma-dump/office-supplies.json.
// Figma is the source of truth: edit the design file and re-run the sync,
// do not hand-edit this file.

import type { UnitLearningMaterials } from "../types";

export const OFFICE_SUPPLIES_LEARNING: UnitLearningMaterials = {
  unitId: "office-supplies",
  subtopics: [
    {
      id: "writing-supplies",
      title: "Writing Supplies",
      wordIds: [
        "pen",
        "pencil",
        "highlighter",
        "marker",
        "eraser",
        "mechanical-pencil",
        "fountain-pen",
        "felt-tip-pen",
        "correction-tape",
        "whiteboard-marker",
      ],
    },
    {
      id: "paper-products",
      title: "Paper Products",
      wordIds: [
        "paper",
        "notebook",
        "legal-pad",
        "sticky-note",
        "index-card",
        "envelope",
        "folder",
        "binder",
        "manila-folder",
        "label",
      ],
    },
    {
      id: "fasteners-clips",
      title: "Fasteners & Clips",
      wordIds: [
        "stapler",
        "paper-clip",
        "binder-clip",
        "rubber-band",
        "pushpin",
        "thumbtack",
        "tape",
        "glue-stick",
        "fastener",
        "magnet",
      ],
    },
    {
      id: "desk-accessories",
      title: "Desk Accessories",
      wordIds: [
        "desk-organizer",
        "pencil-cup",
        "tape-dispenser",
        "letter-tray",
        "desk-lamp",
        "mouse-pad",
        "wrist-rest",
        "monitor-stand",
        "cable-organizer",
        "desk-calendar",
      ],
    },
    {
      id: "mailing-supplies",
      title: "Mailing Supplies",
      wordIds: [
        "stamp",
        "shipping-label",
        "packing-tape",
        "bubble-wrap",
        "box",
        "padded-envelope",
        "return-label",
        "postage-meter",
        "mail-slot",
        "letter-opener",
      ],
    },
  ],
  passage: {
    title: "Reading Passage",
    level: "C1",
    text: "Office supplies — the everyday tools of professional life — carry a surprisingly rich vocabulary in English. Writing instruments include ballpoint pens, fountain pens, felt-tip markers, highlighters, and mechanical pencils. Paper products encompass notebooks, notepads, sticky notes (Post-its), index cards, envelopes, and letterheads. Filing and organisation rely on ring binders, lever arch files, folders, dividers, paper clips, bulldog clips, staples, and rubber bands. Adhesives include glue sticks, sticky tape (Sellotape in British English, Scotch tape in American), and correction fluid (Tipp-Ex in Britain, Wite-Out in America). Cutting tools range from scissors to craft knives and paper trimmers. Desktop accessories include pen holders, desk organisers, mouse mats, monitor stands, and cable tidies. The stationery cupboard — that shared resource guarded with varying degrees of strictness — is a feature of every British office. Digital tools have replaced many physical supplies: cloud storage instead of filing cabinets, digital signatures instead of stamps, shared documents instead of photocopies. Yet paper persists: diaries, planners, wall calendars, and the humble notebook remain essential for many workers. British and American vocabulary differs notably: 'rubber' (eraser) versus 'eraser', 'drawing pin' versus 'thumbtack', 'Sellotape' versus 'Scotch tape'. These small differences matter in professional communication.",
    questions: [],
    openQuestions: [
      "What writing instruments are commonly found in offices?",
      "How do British and American English differ for office supplies?",
      "What filing and organisation supplies are mentioned?",
      "How have digital tools replaced physical office supplies?",
      "Why does paper persist despite digital alternatives?",
    ],
  },
  phrases: [
    {
      id: "office-supplies-put-pen-to-paper",
      phrase: "put pen to paper",
      kind: "idiom",
      meaning: "To begin writing.",
      example:
        "She finally put pen to paper and started the letter she'd been putting off for weeks.",
    },
    {
      id: "office-supplies-cut-through-the-red-tape",
      phrase: "cut through the red tape",
      kind: "idiom",
      meaning: "To bypass bureaucracy.",
      example:
        "We need to cut through the red tape — there are too many forms and approvals slowing us down.",
    },
    {
      id: "office-supplies-a-paper-trail",
      phrase: "a paper trail",
      kind: "idiom",
      kindInferred: true,
      meaning:
        "(phrase) A series of documents that provide evidence. \"Always keep a paper trail — if there's a dispute, you'll need proof.\"",
      example: "",
    },
    {
      id: "office-supplies-back-to-the-drawing-board",
      phrase: "back to the drawing board",
      kind: "idiom",
      meaning: "To start planning again.",
      example: "The design was rejected, so it's back to the drawing board for the whole team.",
    },
    {
      id: "office-supplies-on-file",
      phrase: "on file",
      kind: "idiom",
      kindInferred: true,
      meaning:
        '(phrase) Recorded and stored. "We have your details on file — we\'ll contact you if a position opens up."',
      example: "",
    },
    {
      id: "office-supplies-rubber-stamp-something",
      phrase: "rubber-stamp something",
      kind: "idiom",
      meaning: "To approve without real consideration.",
      example: "The committee just rubber-stamped the proposal — no one actually read it.",
    },
    {
      id: "office-supplies-file-something-away",
      phrase: "file something away",
      kind: "phrasal-verb",
      meaning: "To store documents for future reference.",
      example: "File this report away under 'Completed Projects' — we might need it later.",
    },
    {
      id: "office-supplies-pencil-something-in",
      phrase: "pencil something in",
      kind: "phrasal-verb",
      meaning: "To schedule tentatively.",
      example: "Let's pencil in a meeting for Thursday — we can confirm closer to the time.",
    },
    {
      id: "office-supplies-dot-the-i-s-and-cross-the-t-s",
      phrase: "dot the i's and cross the t's",
      kind: "idiom",
      meaning: "To pay attention to every detail.",
      example: "Before we submit, let's dot the i's and cross the t's — no mistakes.",
    },
    {
      id: "office-supplies-on-a-shoestring",
      phrase: "on a shoestring",
      kind: "idiom",
      meaning: "With very little money.",
      example: "The department runs on a shoestring — we can't even afford new pens.",
    },
  ],
  dialogue: {
    title: "Ordering Office Supplies",
    lines: [
      {
        speaker: "Office Manager",
        text: "I'm doing the stationery order. Does anyone need anything before I submit it?",
      },
      {
        speaker: "Designer",
        text: "We're running low on marker pens — the thick ones for the whiteboard. And could we get some more sticky notes?",
      },
      {
        speaker: "Office Manager",
        text: "Whiteboard markers and sticky notes — noted. What colours do you need?",
      },
      {
        speaker: "Designer",
        text: "Black and blue markers mainly. And the sticky notes — a mix of yellow and the neon ones, if possible.",
      },
      {
        speaker: "Accountant",
        text: "Could I get a new lever arch file? Mine is falling apart. And some dividers — the A4 tabbed ones.",
      },
      {
        speaker: "Office Manager",
        text: "Of course. Anyone else? We're also low on printer paper and ink cartridges — I'll add those automatically.",
      },
      {
        speaker: "Intern",
        text: "Is it possible to get a desk organiser? My stationery is everywhere — pens, clips, everything mixed together.",
      },
      {
        speaker: "Office Manager",
        text: "Absolutely. I'll order a desktop tidy for you. Right — I'll submit the order this afternoon. It usually arrives within two days.",
      },
    ],
  },
  mistakes: [
    {
      id: "office-supplies-can-i-borrow-an-eraser-in-american-engli",
      wrong: '"Can I borrow a rubber?" (in American context)',
      right: '"Can I borrow an eraser?" (in American English)',
      note: "In British English, 'rubber' = eraser. In American English, 'rubber' is slang for condom — a highly embarrassing false friend. Always use 'eraser' with American speakers.",
    },
    {
      id: "office-supplies-i-need-some-scotch-tape-i-need-some-stic",
      wrong: '"I need a scotch tape."',
      right: '"I need some Scotch tape." / "I need some sticky tape."',
      note: "'Scotch tape' and 'Sellotape' are brand names used generically (like 'Hoover' for vacuum). They're uncountable — 'some tape', not 'a tape'. 'Sticky tape' is the generic British term.",
    },
    {
      id: "office-supplies-she-stapled-the-papers-she-used-a-staple",
      wrong: '"She stapled the papers with a stapler machine."',
      right: '"She stapled the papers." / "She used a stapler."',
      note: "'Staple' works as a verb — no need to mention the stapler. If you do, just say 'stapler' (not 'stapler machine'). Similarly: 'she photocopied it' (not 'used the photocopy machine').",
    },
    {
      id: "office-supplies-put-it-in-the-ring-binder-put-it-in-the-",
      wrong: '"Put it in the binder folder."',
      right: '"Put it in the ring binder." / "Put it in the folder."',
      note: "A 'ring binder' (with metal rings) and a 'folder' (flat, no rings) are different items. Don't combine them. 'Lever arch file' is the large ring binder with a lever mechanism.",
    },
    {
      id: "office-supplies-i-need-to-cut-the-paper-with-scissors-i-",
      wrong: '"I need to cut the paper with a scissor."',
      right: '"I need to cut the paper with scissors." / "I need a pair of scissors."',
      note: "'Scissors' is always plural — never 'a scissor'. Use 'a pair of scissors' for the singular countable form. Same for: glasses, trousers, tongs, pliers.",
    },
    {
      id: "office-supplies-she-wrote-with-a-pencil-she-wrote-with-a",
      wrong: '"She wrote with a pencil pen."',
      right: '"She wrote with a pencil." / "She wrote with a pen."',
      note: "'Pencil' and 'pen' are different instruments — pencils use graphite (erasable), pens use ink (permanent). 'Pencil pen' doesn't exist. A 'mechanical pencil' uses replaceable lead.",
    },
  ],
  wordFormation: [
    {
      noun: "stationery",
      verb: null,
      adjective: null,
      adverb: null,
    },
    {
      noun: "adhesive",
      verb: "adhere",
      adjective: "adhesive",
      adverb: "adhesively",
    },
    {
      noun: "correction",
      verb: "correct",
      adjective: "corrective",
      adverb: "correctively",
    },
    {
      noun: "filing",
      verb: "file",
      adjective: "filed",
      adverb: null,
    },
    {
      noun: "organisation",
      verb: "organise",
      adjective: "organisational",
      adverb: "organisationally",
    },
    {
      noun: "sharpener",
      verb: "sharpen",
      adjective: "sharp",
      adverb: "sharply",
    },
    {
      noun: "binding",
      verb: "bind",
      adjective: "bound",
      adverb: null,
    },
    {
      noun: "printing",
      verb: "print",
      adjective: "printed",
      adverb: null,
    },
    {
      noun: "lamination",
      verb: "laminate",
      adjective: "laminated",
      adverb: null,
    },
    {
      noun: "storage",
      verb: "store",
      adjective: "stored",
      adverb: null,
    },
  ],
  blankExercises: [
    {
      id: "office-supplies-b1",
      sentence: "She used a ____ to mark the important paragraphs in yellow so they'd stand out.",
      answer: "highlighter",
    },
    {
      id: "office-supplies-b2",
      sentence: "Could you pass me the ____? I need to attach these pages together.",
      answer: "stapler",
    },
    {
      id: "office-supplies-b3",
      sentence: "He wrote a reminder on a ____ note and stuck it to his computer monitor.",
      answer: "sticky/Post-it",
    },
    {
      id: "office-supplies-b4",
      sentence: "The documents are organised in a ____ arch file with labelled dividers.",
      answer: "lever",
    },
    {
      id: "office-supplies-b5",
      sentence: "She sealed the ____ and posted the letter to the client that afternoon.",
      answer: "envelope",
    },
    {
      id: "office-supplies-b6",
      sentence: "I need some ____ tape to wrap the parcel — where's the dispenser?",
      answer: "sticky/packing",
    },
    {
      id: "office-supplies-b7",
      sentence: "He sharpened his ____ before sketching the initial design on paper.",
      answer: "pencil",
    },
    {
      id: "office-supplies-b8",
      sentence: "The ____ is out of ink again — we need to order new cartridges.",
      answer: "printer",
    },
    {
      id: "office-supplies-b9",
      sentence: "She used ____ fluid to cover the mistake before photocopying the document.",
      answer: "correction",
    },
    {
      id: "office-supplies-b10",
      sentence: "All employee records are kept ____ in the HR department's filing cabinet.",
      answer: "on file",
    },
  ],
  culturalNotes: [
    {
      id: "office-supplies-stationery-obsession",
      title: "Stationery Obsession",
      body: "British people have a notable affection for stationery. Shops like Paperchase and sections in WHSmith attract devoted customers. 'Stationery haul' videos are popular online. A new notebook or quality pen brings genuine joy — it's a minor cultural phenomenon.",
    },
    {
      id: "office-supplies-brand-names-as-generic-terms",
      title: "Brand Names as Generic Terms",
      body: "Several office supply brand names have become generic in British English: 'Sellotape' (any sticky tape), 'Tipp-Ex' (any correction fluid), 'Biro' (any ballpoint pen), 'Post-it' (any sticky note). Using these shows cultural fluency.",
    },
    {
      id: "office-supplies-the-stationery-cupboard",
      title: "The Stationery Cupboard",
      body: "The office stationery cupboard occupies a special place in British workplace culture. It may be locked (with the key held by the office manager), rationed ('only two pens per person'), or a source of gentle office politics ('who keeps taking all the good pens?').",
    },
    {
      id: "office-supplies-paper-vs-digital",
      title: "Paper vs Digital",
      body: "Despite the 'paperless office' dream, British workplaces still use significant paper. The phrase 'Can you print that out for me?' remains common, and many people prefer physical notebooks for meetings. The UK uses A4 paper (not US Letter size).",
    },
    {
      id: "office-supplies-environmental-awareness",
      title: "Environmental Awareness",
      body: "Recycling vocabulary is now standard in offices: 'recycling bin', 'paper shredder', 'double-sided printing', 'reuse envelopes', 'refillable pens'. Environmental consciousness has added a new layer of vocabulary to office supply discussions.",
    },
  ],
  wordMeta: [
    {
      word: "stapler",
      partOfSpeech: "n",
      frequency: 3,
      collocations: ["desk ~", "~ remover", "heavy-duty ~", "~ refill"],
    },
    {
      word: "highlighter",
      partOfSpeech: "n",
      frequency: 3,
      collocations: ["yellow ~", "~ pen", "~ colour", "text ~"],
    },
    {
      word: "envelope",
      partOfSpeech: "n",
      frequency: 3,
      collocations: ["sealed ~", "~ address", "window ~", "padded ~"],
    },
    {
      word: "scissors",
      partOfSpeech: "n",
      frequency: 3,
      collocations: ["pair of ~", "~ cut", "paper ~", "craft ~"],
    },
    {
      word: "folder",
      partOfSpeech: "n",
      frequency: 3,
      collocations: ["file ~", "~ tab", "~ label", "document ~"],
    },
    {
      word: "clipboard",
      partOfSpeech: "n",
      frequency: 3,
      collocations: ["on the ~", "~ survey", "~ holder", "copy to ~"],
    },
    {
      word: "rubber band",
      partOfSpeech: "n",
      frequency: 2,
      collocations: ["stretch a ~", "~ ball", "~ snap", "elastic ~"],
    },
    {
      word: "paper clip",
      partOfSpeech: "n",
      frequency: 3,
      collocations: ["~ holder", "~ chain", "attach with a ~", "metal ~"],
    },
    {
      word: "sticky note",
      partOfSpeech: "n",
      frequency: 3,
      collocations: ["write on a ~", "~ pad", "~ reminder", "coloured ~"],
    },
    {
      word: "ink cartridge",
      partOfSpeech: "n",
      frequency: 2,
      collocations: ["printer ~", "replace the ~", "~ refill", "~ pack"],
    },
  ],
};
