// Learning materials for "L5 Post Office".
//
// GENERATED by scripts/build-learning-materials.mjs from figma-dump/post-office.json.
// Figma is the source of truth: edit the design file and re-run the sync,
// do not hand-edit this file.

import type { UnitLearningMaterials } from "../types";

export const POST_OFFICE_LEARNING: UnitLearningMaterials = {
  unitId: "post-office",
  passage: {
    title: "Reading Passage",
    level: "B1",
    text: "Sending a Parcel\n\nYesterday, I went to the post office to send a birthday present to my cousin in another city. It was my first time sending a parcel, so I was not sure what to do.\n\nWhen I arrived, there was a short queue at the counter. While I waited, I looked around. There were shelves with padded envelopes, cardboard boxes, packing tape, and bubble wrap. I picked up a medium-sized box and some tape.\n\nAt the counter, the postal worker weighed my parcel on a scale. It was just under two kilograms. She asked if I wanted to send it by standard delivery or express delivery. Standard takes three to five working days; express arrives the next day but costs more. I chose standard.\n\nShe gave me a form to fill in with the sender's address and the recipient's address. I also wrote the postcode carefully because, she explained, an incorrect postcode can delay the delivery.\n\nI paid the postage fee and she stuck stamps and a tracking label on the box. She gave me a receipt with a tracking number so I could follow the parcel online.\n\nBefore I left, I also bought a book of stamps for regular letters and posted two letters in the postbox outside. The red pillar box had two slots: one for local mail and one for everything else.\n\nSending a parcel was easier than I expected. My cousin received it two days later and called to say thank you.",
    questions: [],
    openQuestions: [
      "Why did the writer go to the post office?",
      "What packaging supplies were available?",
      "What is the difference between standard and express delivery?",
      "Why is the postcode important?",
      "How could the writer track the parcel?",
    ],
  },
  phrases: [
    {
      id: "post-office-return-to-sender",
      phrase: "return to sender",
      kind: "idiom",
      kindInferred: true,
      meaning: "send something back to the person who sent it",
      example:
        "The letter had no return address or zip code, so the clerk stamped it return to sender.",
    },
    {
      id: "post-office-get-the-message",
      phrase: "get the message",
      kind: "idiom",
      kindInferred: true,
      meaning: "understand what someone is trying to say",
      example:
        "After three postcards and a registered mail notice, she finally got the message — pay the bill!",
    },
    {
      id: "post-office-deliver-the-goods",
      phrase: "deliver the goods",
      kind: "idiom",
      kindInferred: true,
      meaning: "do what is expected; meet expectations",
      example:
        "The mail carrier always delivers the goods — every package, parcel, and envelope arrives on time.",
    },
    {
      id: "post-office-signed-sealed-and-delivered",
      phrase: "signed, sealed, and delivered",
      kind: "idiom",
      kindInferred: true,
      meaning: "completely finished and official",
      example:
        "The contract was signed, sealed, and delivered — she put the stamp on the envelope and dropped it in the mailbox.",
    },
    {
      id: "post-office-a-stamp-of-approval",
      phrase: "a stamp of approval",
      kind: "idiom",
      kindInferred: true,
      meaning: "official permission or endorsement",
      example:
        "The postmaster gave his stamp of approval — the new express mail system was ready to launch.",
    },
    {
      id: "post-office-go-postal",
      phrase: "go postal",
      kind: "idiom",
      kindInferred: true,
      meaning: "become extremely angry (informal)",
      example:
        "The customer almost went postal when the delivery driver lost his parcel with the tracking number.",
    },
    {
      id: "post-office-drop-someone-a-line",
      phrase: "drop someone a line",
      kind: "idiom",
      kindInferred: true,
      meaning: "send a short letter or message",
      example:
        "Drop me a line — just write your address on the label, put a sticker on it, and use the slot in the post box.",
    },
    {
      id: "post-office-lost-in-the-mail",
      phrase: "lost in the mail",
      kind: "idiom",
      kindInferred: true,
      meaning: "something that was sent but never arrived",
      example:
        "My birthday card must have been lost in the mail — the sorter couldn't find it in the mail bag or on the cart.",
    },
    {
      id: "post-office-through-the-post",
      phrase: "through the post",
      kind: "idiom",
      kindInferred: true,
      meaning: "sent by mail",
      example: "I received the documents through the post this morning.",
    },
    {
      id: "post-office-wrap-up",
      phrase: "wrap up",
      kind: "phrasal-verb",
      kindInferred: true,
      meaning: "finish something; also: cover with paper",
      example: "Wrap up the gift before putting it in the box.",
    },
  ],
  dialogue: {
    title: "Mini Dialogue",
    lines: [
      {
        speaker: "Scene: A customer sends several items at the post office",
        text: "Customer:",
      },
      {
        speaker: "Hello, I need to send a letter, a postcard, and a package today.",
        text: "Clerk:",
      },
      {
        speaker: "Sure. Let's start with the letter. Do you have an envelope and a stamp?",
        text: "Customer:",
      },
      {
        speaker:
          "I have the envelope, but I need to buy a stamp. I also need a label and a sticker for the package.",
        text: "Clerk:",
      },
      {
        speaker:
          "No problem. Write the address and the return address clearly. Don't forget the zip code.",
        text: "Customer:",
      },
      {
        speaker: "Can I send the package by express mail? I need a tracking number for it.",
        text: "Clerk:",
      },
      {
        speaker:
          "Yes — express mail or certified mail both come with a tracking number. Let me put the parcel on the scale to check the weight.",
        text: "Customer:",
      },
      {
        speaker:
          "How about registered mail? My grandmother sent me something by registered mail last month — I had to give my signature at the counter for pickup.",
        text: "Clerk:",
      },
      {
        speaker:
          "Registered mail requires a signature on delivery. The mail carrier or the delivery driver will ask for it at the door.",
        text: "Customer:",
      },
      {
        speaker: "Where do I drop the postcard? In the mailbox outside or the post box inside?",
        text: "Clerk:",
      },
    ],
  },
  mistakes: [
    {
      id: "post-office-i-sent-him-a-letter-an-email-yesterday",
      wrong: '"I sent him a mail yesterday."',
      right: '"I sent him a letter / an email yesterday."',
      note: "In British English, 'mail' is uncountable (some mail). A single item is 'a letter', 'a parcel', or 'an email'. American English allows 'a mail'.",
    },
    {
      id: "post-office-i-posted-the-letter-at-the-post-office-i",
      wrong: '"I posted the letter in the post office."',
      right: '"I posted the letter at the post office." / "I posted it in the postbox."',
      note: "You post a letter 'at' the post office (the building) or 'in' the postbox (the slot).",
    },
    {
      id: "post-office-the-package-arrived-three-days-ago-the-p",
      wrong: '"The package arrived after three days ago."',
      right: '"The package arrived three days ago." / "The package arrived after three days."',
      note: "Don't combine 'after' and 'ago'. Choose one: 'three days ago' (from now) or 'after three days' (from sending).",
    },
    {
      id: "post-office-she-stuck-the-stamp-on-the-envelope",
      wrong: '"She sticked the stamp on the envelope."',
      right: '"She stuck the stamp on the envelope."',
      note: "'Stick' is irregular: stick–stuck–stuck. There is no 'sticked'.",
    },
    {
      id: "post-office-write-the-recipient-s-address",
      wrong: '"Write the address of the destinatary."',
      right: '"Write the recipient\'s address."',
      note: "The English word is 'recipient' (person receiving), not 'destinatary'. The sender is the person sending.",
    },
  ],
  wordFormation: [
    {
      noun: "delivery / deliverer",
      verb: "deliver",
      adjective: "delivered",
      adverb: null,
      base: "deliver",
    },
    {
      noun: "post / postage",
      verb: "post",
      adjective: "postal",
      adverb: null,
      base: "post",
    },
    {
      noun: "sender / sending",
      verb: "send",
      adjective: "sent",
      adverb: null,
      base: "send",
    },
    {
      noun: "receiver / receipt",
      verb: "receive",
      adjective: "received",
      adverb: null,
      base: "receive",
    },
    {
      noun: "wrap / wrapper",
      verb: "wrap",
      adjective: "wrapped",
      adverb: null,
      base: "wrap",
    },
    {
      noun: "stamp",
      verb: "stamp",
      adjective: "stamped",
      adverb: null,
      base: "stamp",
    },
    {
      noun: "tracking / tracker",
      verb: "track",
      adjective: "tracked",
      adverb: null,
      base: "track",
    },
    {
      noun: "sorting / sorter",
      verb: "sort",
      adjective: "sorted",
      adverb: null,
      base: "sort",
    },
    {
      noun: "weight / scale",
      verb: "weigh",
      adjective: "weighed",
      adverb: null,
      base: "weigh",
    },
    {
      noun: "collection / collector",
      verb: "collect",
      adjective: "collected",
      adverb: null,
      base: "collect",
    },
  ],
  blankExercises: [
    {
      id: "post-office-b1",
      sentence: "I need to buy some ____ before I can post this letter.",
      answer: "stamps",
    },
    {
      id: "post-office-b2",
      sentence: "The postal worker ____ the parcel to check the delivery cost.",
      answer: "weighed",
    },
    {
      id: "post-office-b3",
      sentence: "Please write the ____ address clearly on the front of the envelope.",
      answer: "recipient's",
    },
    {
      id: "post-office-b4",
      sentence: "I chose express ____ so the gift would arrive on time.",
      answer: "delivery",
    },
    {
      id: "post-office-b5",
      sentence: "She wrapped the present in ____ wrap to protect it.",
      answer: "bubble",
    },
    {
      id: "post-office-b6",
      sentence: "I dropped the letters in the red ____ outside the shop.",
      answer: "postbox",
    },
    {
      id: "post-office-b7",
      sentence: "The ____ number lets you follow your parcel online.",
      answer: "tracking",
    },
    {
      id: "post-office-b8",
      sentence: "He filled in the ____ with both the sender and recipient details.",
      answer: "form",
    },
    {
      id: "post-office-b9",
      sentence: "Standard postage for a letter is eighty ____.",
      answer: "pence",
    },
    {
      id: "post-office-b10",
      sentence: "The ____ office is open from 9 AM to 5 PM on weekdays.",
      answer: "post",
    },
  ],
  culturalNotes: [
    {
      id: "post-office-royal-mail-vs-usps",
      title: "Royal Mail vs USPS",
      body: "UK post is handled by Royal Mail (red vans, red postboxes). US post is handled by USPS (blue mailboxes). Both have first-class (fast) and second-class/standard (slower, cheaper) options.",
    },
    {
      id: "post-office-vs-vocabulary",
      title: "🇬🇧 vs 🇺🇸 Vocabulary",
      body: "British: 'post' / American: 'mail'. British: 'postbox' / American: 'mailbox'. British: 'postcode' / American: 'zip code'. British: 'parcel' / American: 'package'.",
    },
    {
      id: "post-office-the-red-pillar-box",
      title: "The Red Pillar Box",
      body: "The UK's iconic red pillar boxes have been used since 1852. They have the royal cipher of the reigning monarch at the time they were made. Some very old ones still have Queen Victoria's initials!",
    },
    {
      id: "post-office-signed-for-vs-recorded-delivery",
      title: "Signed For vs Recorded Delivery",
      body: "'Signed for' delivery requires someone to sign when the parcel arrives. 'Tracked' delivery shows the parcel's journey online. These options cost extra but provide proof of delivery.",
    },
    {
      id: "post-office-christmas-post",
      title: "Christmas Post",
      body: "In the UK, Royal Mail announces a 'last posting date' for Christmas cards and parcels. Sending cards by post is still a strong tradition, even in the digital age.",
    },
  ],
  wordMeta: [
    {
      word: "stamp",
      partOfSpeech: "n",
      frequency: 3,
      collocations: ["postage ~", "~ collection", "~ book"],
    },
    {
      word: "parcel",
      partOfSpeech: "n",
      frequency: 2,
      collocations: ["send a ~", "~ delivery", "~ tracking"],
    },
    {
      word: "envelope",
      partOfSpeech: "n",
      frequency: 3,
      collocations: ["padded ~", "seal an ~", "~ flap"],
    },
    {
      word: "postbox",
      partOfSpeech: "n",
      frequency: 2,
      collocations: ["red ~", "post in the ~", "~ collection"],
    },
    {
      word: "delivery",
      partOfSpeech: "n",
      frequency: 3,
      collocations: ["express ~", "~ driver", "next-day ~"],
    },
    {
      word: "postcode",
      partOfSpeech: "n",
      frequency: 2,
      collocations: ["~ area", "write the ~", "correct ~"],
    },
    {
      word: "counter",
      partOfSpeech: "n",
      frequency: 3,
      collocations: ["at the ~", "~ service", "~ clerk"],
    },
    {
      word: "receipt",
      partOfSpeech: "n",
      frequency: 3,
      collocations: ["keep the ~", "~ number", "printed ~"],
    },
    {
      word: "address",
      partOfSpeech: "n",
      frequency: 3,
      collocations: ["home ~", "return ~", "~ label"],
    },
    {
      word: "letter",
      partOfSpeech: "n",
      frequency: 3,
      collocations: ["post a ~", "~ box", "~ writing"],
    },
  ],
};
