// Learning materials for "L7 Science Lab".
//
// GENERATED by scripts/build-learning-materials.mjs from figma-dump/science-lab.json.
// Figma is the source of truth: edit the design file and re-run the sync,
// do not hand-edit this file.

import type { UnitLearningMaterials } from "../types";

export const SCIENCE_LAB_LEARNING: UnitLearningMaterials = {
  unitId: "science-lab",
  passage: {
    title: "Reading Passage",
    level: "B1",
    text: "Experiment Day\n\nToday was experiment day in the science lab. Our teacher, Mr Hassan, told us we would be testing how acids and bases react with each other.\n\nBefore we started, we put on our safety equipment: lab coats, safety goggles, and rubber gloves. Mr Hassan reminded us never to taste or smell chemicals directly, and always to wash our hands after the experiment.\n\nEach pair of students had a workstation with test tubes, a test tube rack, a beaker, a measuring cylinder, and a dropper. On the bench, there were bottles of vinegar (an acid) and baking soda (a base).\n\nFirst, we measured fifty millilitres of vinegar using the measuring cylinder and poured it into the beaker. Then, we added a spoonful of baking soda. Immediately, the mixture started to fizz and bubble. This reaction produces carbon dioxide gas, which is why the mixture bubbles.\n\nWe used litmus paper to test the solution before and after the reaction. The blue litmus paper turned red in the acid, confirming it was acidic. After the reaction, the solution was closer to neutral.\n\nMr Hassan explained that this type of reaction is called neutralisation. It happens when an acid and a base combine to form water and a salt.\n\nWe recorded our observations in our lab notebooks, including the measurements, the colour changes, and what we noticed. At the end, we cleaned our equipment, washed the beakers, and returned everything to the storage cupboard.\n\nScience experiments make learning much more exciting than just reading from a textbook.",
    questions: [],
    openQuestions: [
      "What safety equipment did the students put on?",
      "What two substances were used in the experiment?",
      "Why did the mixture fizz and bubble?",
      "What did the litmus paper show about the vinegar?",
      "What is 'neutralisation'?",
    ],
  },
  phrases: [
    {
      id: "science-lab-it-s-not-rocket-science",
      phrase: "it's not rocket science",
      kind: "idiom",
      kindInferred: true,
      meaning: "it's not difficult to understand",
      example: "Making toast isn't rocket science.",
    },
    {
      id: "science-lab-the-acid-test",
      phrase: "the acid test",
      kind: "idiom",
      kindInferred: true,
      meaning: "a decisive test that proves something's value",
      example: "The real acid test for the product is whether people will buy it.",
    },
    {
      id: "science-lab-mix-up",
      phrase: "mix up",
      kind: "phrasal-verb",
      kindInferred: true,
      meaning: "confuse two things; also: combine ingredients",
      example: "I always mix up 'affect' and 'effect'.",
    },
    {
      id: "science-lab-blow-up",
      phrase: "blow up",
      kind: "phrasal-verb",
      kindInferred: true,
      meaning: "explode; also: become very angry",
      example: "The chemicals could blow up if mixed incorrectly.",
    },
    {
      id: "science-lab-break-down",
      phrase: "break down",
      kind: "phrasal-verb",
      kindInferred: true,
      meaning: "separate into smaller parts; also: stop working",
      example: "Water can be broken down into hydrogen and oxygen.",
    },
    {
      id: "science-lab-figure-out",
      phrase: "figure out",
      kind: "phrasal-verb",
      kindInferred: true,
      meaning: "find the answer to a problem",
      example: "We need to figure out why the experiment failed.",
    },
    {
      id: "science-lab-carry-out",
      phrase: "carry out",
      kind: "phrasal-verb",
      kindInferred: true,
      meaning: "perform or complete (an experiment, task)",
      example: "The scientists carried out the experiment three times.",
    },
    {
      id: "science-lab-heat-up",
      phrase: "heat up",
      kind: "phrasal-verb",
      kindInferred: true,
      meaning: "make something hotter",
      example: "Heat up the solution to sixty degrees.",
    },
    {
      id: "science-lab-back-to-the-drawing-board",
      phrase: "back to the drawing board",
      kind: "idiom",
      kindInferred: true,
      meaning: "start over because a plan failed",
      example: "The experiment didn't work — back to the drawing board.",
    },
    {
      id: "science-lab-trial-and-error",
      phrase: "trial and error",
      kind: "idiom",
      kindInferred: true,
      meaning: "learning by trying and making mistakes",
      example: "We found the right formula through trial and error.",
    },
  ],
  dialogue: {
    title: "Mini Dialogue",
    lines: [
      {
        speaker: "Scene: Students working together in the science lab",
        text: "Omar:",
      },
      {
        speaker: "Can you pass me the measuring cylinder?",
        text: "Yusuf:",
      },
      {
        speaker: "Here. How much vinegar do we need?",
        text: "Omar:",
      },
      {
        speaker: "Fifty millilitres. Make sure you read it at eye level.",
        text: "Yusuf:",
      },
      {
        speaker: "Right. Now I'll add the baking soda.",
        text: "Omar:",
      },
      {
        speaker: "Wait — put your goggles on first!",
        text: "Yusuf:",
      },
      {
        speaker: "Oh, thanks. Safety first. Okay, adding it now...",
        text: "Omar:",
      },
      {
        speaker: "Look at it fizzing! That's the carbon dioxide being released.",
        text: "Yusuf:",
      },
      {
        speaker: "Should I test it with litmus paper?",
        text: "Omar:",
      },
      {
        speaker: "Yes. Use the blue one — if it turns red, it's acidic.",
        text: "Yusuf:",
      },
    ],
  },
  mistakes: [
    {
      id: "science-lab-we-did-carried-out-conducted-an-experime",
      wrong: '"We made an experiment in the lab."',
      right: '"We did / carried out / conducted an experiment in the lab."',
      note: "In English, you 'do', 'carry out', or 'conduct' an experiment — not 'make'. 'Make' is used with things you create: make a cake, make a decision.",
    },
    {
      id: "science-lab-the-liquid-is-boiling-at-100-degrees",
      wrong: '"The liquid is boiling in 100 degrees."',
      right: '"The liquid is boiling at 100 degrees."',
      note: "Use 'at' for specific temperatures: 'at 100°C', 'at room temperature'. Not 'in' or 'on'.",
    },
    {
      id: "science-lab-pour-the-chemical-slowly-into-the-beaker",
      wrong: '"Pour the chemical slow into the beaker."',
      right: '"Pour the chemical slowly into the beaker."',
      note: "'Slowly' is the adverb (modifies a verb). 'Slow' is the adjective (modifies a noun). You pour slowly, but it's a slow pour.",
    },
    {
      id: "science-lab-the-microscope-makes-things-bigger-much-",
      wrong: '"The microscope makes things more bigger."',
      right: '"The microscope makes things bigger." / "...much bigger."',
      note: "Don't use 'more' with '-er' comparatives. 'Bigger' already means 'more big'. Use 'much bigger' for emphasis.",
    },
    {
      id: "science-lab-the-scientist-discovered-a-new-species",
      wrong: '"The scientist discovered a new specie."',
      right: '"The scientist discovered a new species."',
      note: "'Species' is the same in singular and plural: 'one species', 'many species'. There is no 'specie' (except as an old word for coin money).",
    },
  ],
  wordFormation: [
    {
      noun: "experiment / experimenter",
      verb: "experiment",
      adjective: "experimental",
      adverb: null,
      base: "experiment",
    },
    {
      noun: "reaction / reactant",
      verb: "react",
      adjective: "reactive",
      adverb: null,
      base: "react",
    },
    {
      noun: "measurement",
      verb: "measure",
      adjective: "measured",
      adverb: null,
      base: "measure",
    },
    {
      noun: "observation / observer",
      verb: "observe",
      adjective: "observable",
      adverb: null,
      base: "observe",
    },
    {
      noun: "dissolution / solvent",
      verb: "dissolve",
      adjective: "dissolved",
      adverb: null,
      base: "dissolve",
    },
    {
      noun: "heat / heater",
      verb: "heat",
      adjective: "heated",
      adverb: null,
      base: "heat",
    },
    {
      noun: "boiling point",
      verb: "boil",
      adjective: "boiling",
      adverb: null,
      base: "boil",
    },
    {
      noun: "neutralisation",
      verb: "neutralise",
      adjective: "neutral",
      adverb: null,
      base: "neutralise",
    },
    {
      noun: "magnification / magnifier",
      verb: "magnify",
      adjective: "magnified",
      adverb: null,
      base: "magnify",
    },
    {
      noun: "contamination / contaminant",
      verb: "contaminate",
      adjective: "contaminated",
      adverb: null,
      base: "contaminate",
    },
  ],
  blankExercises: [
    {
      id: "science-lab-b1",
      sentence: "Always wear safety ____ to protect your eyes in the lab.",
      answer: "goggles",
    },
    {
      id: "science-lab-b2",
      sentence: "We measured the liquid using a measuring ____.",
      answer: "cylinder",
    },
    {
      id: "science-lab-b3",
      sentence: "When you mix an acid and a base, you get a ____ reaction.",
      answer: "neutralisation",
    },
    {
      id: "science-lab-b4",
      sentence: "The ____ paper turned red, showing the solution was acidic.",
      answer: "litmus",
    },
    {
      id: "science-lab-b5",
      sentence: "We poured the liquid into a glass ____.",
      answer: "beaker",
    },
    {
      id: "science-lab-b6",
      sentence: "The students wore lab ____ and rubber gloves for protection.",
      answer: "coats",
    },
    {
      id: "science-lab-b7",
      sentence: "The mixture started to ____ and bubble when we added baking soda.",
      answer: "fizz",
    },
    {
      id: "science-lab-b8",
      sentence: "We used a ____ to look at cells up close.",
      answer: "microscope",
    },
    {
      id: "science-lab-b9",
      sentence: "Write all your observations in your lab ____.",
      answer: "notebook",
    },
    {
      id: "science-lab-b10",
      sentence: "Carbon ____ is the gas produced when vinegar reacts with baking soda.",
      answer: "dioxide",
    },
  ],
  culturalNotes: [
    {
      id: "science-lab-vs-spelling-in-science",
      title: "🇬🇧 vs 🇺🇸 Spelling in Science",
      body: "British: 'neutralisation', 'crystallise', 'analyse' / American: 'neutralization', 'crystallize', 'analyze'. British uses '-ise'/'-isation'; American uses '-ize'/'-ization'. Both are accepted in international scientific journals.",
    },
    {
      id: "science-lab-lab-safety-culture",
      title: "Lab Safety Culture",
      body: "In English-speaking schools, lab safety is taken very seriously. Students must follow strict rules: no eating or drinking, tie back long hair, report spills immediately. Breaking safety rules can result in being asked to leave the lab.",
    },
    {
      id: "science-lab-the-scientific-method",
      title: "The Scientific Method",
      body: "English learners often encounter these steps: 1. Ask a question, 2. Do background research, 3. Form a hypothesis, 4. Test with an experiment, 5. Analyse results, 6. Draw a conclusion. This vocabulary appears frequently in B1–B2 exams.",
    },
    {
      id: "science-lab-famous-scientists-in-english-culture",
      title: "Famous Scientists in English Culture",
      body: "Names like Newton, Darwin, and Faraday appear often in English educational texts. Understanding basic references to their work helps with reading comprehension in science-related passages.",
    },
    {
      id: "science-lab-metric-vs-imperial",
      title: "Metric vs Imperial",
      body: "UK science uses metric (Celsius, litres, grams). Everyday UK life mixes both: miles for distance, pints for milk, but kilograms for body weight. The US uses Fahrenheit and imperial measures more widely.",
    },
  ],
  wordMeta: [
    {
      word: "beaker",
      partOfSpeech: "n",
      frequency: 2,
      collocations: ["glass ~", "pour into a ~", "~ of liquid"],
    },
    {
      word: "test tube",
      partOfSpeech: "n",
      frequency: 2,
      collocations: ["~ rack", "heat a ~", "fill a ~"],
    },
    {
      word: "microscope",
      partOfSpeech: "n",
      frequency: 2,
      collocations: ["look through a ~", "~ slide", "electron ~"],
    },
    {
      word: "goggles",
      partOfSpeech: "n",
      frequency: 2,
      collocations: ["safety ~", "lab ~", "~ strap"],
    },
    {
      word: "experiment",
      partOfSpeech: "n",
      frequency: 3,
      collocations: ["carry out an ~", "~ results", "science ~"],
    },
    {
      word: "chemical",
      partOfSpeech: "n",
      frequency: 2,
      collocations: ["~ reaction", "~ formula", "~ compound"],
    },
    {
      word: "hypothesis",
      partOfSpeech: "n",
      frequency: 2,
      collocations: ["test a ~", "form a ~", "~ statement"],
    },
    {
      word: "solution",
      partOfSpeech: "n",
      frequency: 3,
      collocations: ["~ mixture", "chemical ~", "dissolve in ~"],
    },
    {
      word: "thermometer",
      partOfSpeech: "n",
      frequency: 2,
      collocations: ["read the ~", "~ scale", "digital ~"],
    },
    {
      word: "specimen",
      partOfSpeech: "n",
      frequency: 2,
      collocations: ["~ jar", "~ slide", "collect a ~"],
    },
  ],
};
