// Learning materials for "Seasonings & Condiments".
//
// GENERATED by scripts/build-learning-materials.mjs from figma-dump/seasonings-condiments.json.
// Figma is the source of truth: edit the design file and re-run the sync,
// do not hand-edit this file.

import type { UnitLearningMaterials } from "../types";

export const SEASONINGS_CONDIMENTS_LEARNING: UnitLearningMaterials = {
  unitId: "seasonings-condiments",
  subtopics: [
    {
      id: "common-spices",
      title: "Common Spices",
      wordIds: [
        "salt",
        "black-pepper",
        "paprika",
        "cinnamon",
        "cumin",
        "turmeric",
        "chili-powder",
        "nutmeg",
        "clove",
        "cardamom",
      ],
    },
    {
      id: "herbs",
      title: "Herbs",
      wordIds: [
        "basil",
        "oregano",
        "thyme",
        "rosemary",
        "parsley",
        "cilantro",
        "dill",
        "mint",
        "bay-leaf",
        "sage",
      ],
    },
    {
      id: "sauces",
      title: "Sauces",
      wordIds: [
        "ketchup",
        "mustard",
        "mayonnaise",
        "soy-sauce",
        "hot-sauce",
        "worcestershire",
        "barbecue-sauce",
        "teriyaki",
        "pesto",
        "salsa",
      ],
    },
    {
      id: "oils-vinegars",
      title: "Oils & Vinegars",
      wordIds: [
        "olive-oil",
        "vegetable-oil",
        "coconut-oil",
        "sesame-oil",
        "balsamic-vinegar",
        "red-wine-vinegar",
        "apple-cider-vinegar",
        "rice-vinegar",
        "white-vinegar",
        "truffle-oil",
      ],
    },
    {
      id: "sweeteners-spreads",
      title: "Sweeteners & Spreads",
      wordIds: [
        "sugar",
        "honey",
        "maple-syrup",
        "jam",
        "jelly",
        "peanut-butter",
        "nutella",
        "marmalade",
        "molasses",
        "agave",
      ],
    },
  ],
  passage: {
    title: "Reading Passage",
    level: "C1",
    text: "Seasonings and condiments transform plain food into flavourful meals. Seasonings are added during cooking to enhance flavour. The most basic are salt and pepper — found on every dining table and in every kitchen. Herbs are the leaves of aromatic plants: basil, oregano, thyme, rosemary, parsley, coriander (cilantro), and mint each bring distinct flavours. Spices come from seeds, bark, roots, and fruits: cumin, cinnamon, turmeric, paprika, chilli powder, and nutmeg add depth and warmth. Garlic and ginger, though technically vegetables, function as essential seasonings. Condiments are prepared sauces and accompaniments served alongside food. Ketchup, mustard, and mayonnaise are the classic trio for sandwiches and burgers. Soy sauce, fish sauce, and oyster sauce are staples in Asian cooking. Vinegar, olive oil, and lemon juice form the base of most salad dressings. Hot sauce and chilli paste add heat for those who enjoy spicy food. Relishes, chutneys, and pickles offer tangy, sweet, or savoury accompaniments. Understanding the distinction between seasonings (added during cooking) and condiments (served at the table) is important. A well-stocked pantry with a variety of seasonings and condiments empowers any cook to create diverse, flavourful dishes from around the world.",
    questions: [],
    openQuestions: [
      "What is the difference between seasonings and condiments?",
      "Name three common herbs and three common spices.",
      "What are the 'classic trio' of condiments for sandwiches?",
      "Which sauces are staples in Asian cooking?",
      "What forms the base of most salad dressings?",
    ],
  },
  phrases: [
    {
      id: "seasonings-condiments-the-spice-of-life",
      phrase: "the spice of life",
      kind: "idiom",
      meaning: "What makes life interesting.",
      example: "Variety is the spice of life — try new seasonings and cuisines!",
    },
    {
      id: "seasonings-condiments-take-it-with-a-pinch-of-salt",
      phrase: "take it with a pinch of salt",
      kind: "idiom",
      meaning: "Don't believe everything.",
      example: "He says his curry is the best in town — take it with a pinch of salt.",
    },
    {
      id: "seasonings-condiments-sugar-coat",
      phrase: "sugar-coat",
      kind: "idiom",
      meaning: "To make something unpleasant seem better.",
      example: "Don't sugar-coat the truth — the sauce was too salty and we both know it.",
    },
    {
      id: "seasonings-condiments-in-a-pickle",
      phrase: "in a pickle",
      kind: "idiom",
      meaning: "In a difficult situation.",
      example:
        "We're in a pickle — we forgot the mustard for the barbecue and the shops are closed.",
    },
    {
      id: "seasonings-condiments-cut-the-mustard",
      phrase: "cut the mustard",
      kind: "idiom",
      meaning: "To meet the required standard.",
      example: "This cheap ketchup just doesn't cut the mustard — we need the real thing.",
    },
    {
      id: "seasonings-condiments-rub-salt-in-the-wound",
      phrase: "rub salt in the wound",
      kind: "idiom",
      meaning: "To make a bad situation worse.",
      example: "Don't rub salt in the wound — she already knows she over-seasoned the dish.",
    },
    {
      id: "seasonings-condiments-worth-one-s-salt",
      phrase: "worth one's salt",
      kind: "idiom",
      meaning: "Competent; deserving of one's pay.",
      example: "Any chef worth their salt knows the difference between cumin and coriander.",
    },
    {
      id: "seasonings-condiments-add-fuel-to-the-fire",
      phrase: "add fuel to the fire",
      kind: "idiom",
      meaning: "To worsen an argument.",
      example:
        "Criticising her cooking was like adding fuel to the fire — she was already upset about the burnt sauce.",
    },
    {
      id: "seasonings-condiments-a-bitter-pill-to-swallow",
      phrase: "a bitter pill to swallow",
      kind: "idiom",
      meaning: "Something unpleasant to accept.",
      example:
        "Losing the cooking competition was a bitter pill to swallow — her chutney was excellent.",
    },
    {
      id: "seasonings-condiments-the-salt-of-the-earth",
      phrase: "the salt of the earth",
      kind: "idiom",
      meaning: "A very good, honest person.",
      example:
        "Grandma is the salt of the earth — she shares her recipes with everyone in the village.",
    },
  ],
  dialogue: {
    title: "Shopping for Spices",
    lines: [
      {
        speaker: "Customer",
        text: "I'm making a curry tonight. I need cumin, turmeric, and some chilli powder.",
      },
      {
        speaker: "Shopkeeper",
        text: "Here's our spice section. We have ground cumin and whole cumin seeds — which do you prefer?",
      },
      {
        speaker: "Customer",
        text: "Ground, please. And fresh coriander if you have it — not dried, I need the leaves for garnish.",
      },
      {
        speaker: "Shopkeeper",
        text: "Fresh coriander is in the herb section, next to the basil and mint. What else do you need?",
      },
      {
        speaker: "Customer",
        text: "Some ginger — fresh root ginger, not the powdered kind. And do you have any mango chutney?",
      },
      {
        speaker: "Shopkeeper",
        text: "Yes, we have two brands of mango chutney — sweet and spicy. Both are excellent with curry.",
      },
      {
        speaker: "Customer",
        text: "I'll take the spicy one. Oh, and soy sauce — I'm making a stir-fry tomorrow.",
      },
      {
        speaker: "Shopkeeper",
        text: "Light soy or dark soy? Light is saltier and thinner — better for seasoning. Dark is thicker — better for colour and marinades.",
      },
    ],
  },
  mistakes: [
    {
      id: "seasonings-condiments-she-added-salt-to-the-soup-she-added-a-p",
      wrong: '"She added a salt to the soup."',
      right: '"She added salt to the soup." / "She added a pinch of salt."',
      note: "'Salt' is uncountable. Say 'salt', 'some salt', or 'a pinch of salt' — not 'a salt'.",
    },
    {
      id: "seasonings-condiments-he-put-spices-in-the-curry-he-added-some",
      wrong: '"He put spice in the curry."',
      right: '"He put spices in the curry." / "He added some spice."',
      note: "'Spice' (singular) means flavour in general. 'Spices' (plural) refers to individual seasoning ingredients.",
    },
    {
      id: "seasonings-condiments-she-used-a-recipe-to-make-the-cake",
      wrong: '"She used receipt to make the cake."',
      right: '"She used a recipe to make the cake."',
      note: "'Receipt' is proof of payment. 'Recipe' is cooking instructions. They sound similar but mean completely different things.",
    },
    {
      id: "seasonings-condiments-the-food-was-very-spicy-the-food-was-wel",
      wrong: '"The food was very spiced."',
      right: '"The food was very spicy." / "The food was well-seasoned."',
      note: "'Spicy' (adjective) describes hot food. 'Spiced' means spices were added. 'Very spiced' isn't natural — say 'heavily spiced'.",
    },
    {
      id: "seasonings-condiments-pass-the-tomato-sauce-pass-the-ketchup",
      wrong: '"Pass the sauce of tomato."',
      right: '"Pass the tomato sauce." / "Pass the ketchup."',
      note: "In English, the modifier comes first: 'tomato sauce', not 'sauce of tomato'. 'Ketchup' is the specific condiment name.",
    },
    {
      id: "seasonings-condiments-she-seasoned-the-dish-with-vinegar",
      wrong: '"She seasoned the dish with a vinegar."',
      right: '"She seasoned the dish with vinegar."',
      note: "'Vinegar' is uncountable. Say 'vinegar', 'some vinegar', or 'a splash of vinegar'.",
    },
  ],
  wordFormation: [
    {
      noun: "season",
      verb: "season",
      adjective: "seasoned",
      adverb: "seasonally",
    },
    {
      noun: "spice",
      verb: "spice",
      adjective: "spicy",
      adverb: "spicily",
    },
    {
      noun: "salt",
      verb: "salt",
      adjective: "salty",
      adverb: null,
    },
    {
      noun: "sweet",
      verb: "sweeten",
      adjective: "sweet",
      adverb: "sweetly",
    },
    {
      noun: "bitterness",
      verb: null,
      adjective: "bitter",
      adverb: "bitterly",
    },
    {
      noun: "sourness",
      verb: "sour",
      adjective: "sour",
      adverb: "sourly",
    },
    {
      noun: "flavour",
      verb: "flavour",
      adjective: "flavourful",
      adverb: null,
    },
    {
      noun: "herb",
      verb: null,
      adjective: "herbal",
      adverb: "herbally",
    },
    {
      noun: "marinade",
      verb: "marinate",
      adjective: "marinated",
      adverb: null,
    },
    {
      noun: "preservation",
      verb: "preserve",
      adjective: "preserved",
      adverb: null,
    },
  ],
  blankExercises: [
    {
      id: "seasonings-condiments-b1",
      sentence: "Add a pinch of ____ and pepper to the soup for basic seasoning.",
      answer: "salt",
    },
    {
      id: "seasonings-condiments-b2",
      sentence: "____ gives curry its distinctive yellow colour.",
      answer: "Turmeric",
    },
    {
      id: "seasonings-condiments-b3",
      sentence: "She garnished the dish with fresh ____ leaves for a burst of green.",
      answer: "coriander/parsley",
    },
    {
      id: "seasonings-condiments-b4",
      sentence: "The ____ on the table included ketchup, mustard, and mayonnaise.",
      answer: "condiments",
    },
    {
      id: "seasonings-condiments-b5",
      sentence: "He grated fresh ____ into the stir-fry for a warm, spicy kick.",
      answer: "ginger",
    },
    {
      id: "seasonings-condiments-b6",
      sentence: "Italian dishes often use ____, oregano, and thyme as key herbs.",
      answer: "basil",
    },
    {
      id: "seasonings-condiments-b7",
      sentence: "The mango ____ was the perfect sweet accompaniment to the spicy curry.",
      answer: "chutney",
    },
    {
      id: "seasonings-condiments-b8",
      sentence: "She drizzled ____ oil and lemon juice over the salad as a dressing.",
      answer: "olive",
    },
    {
      id: "seasonings-condiments-b9",
      sentence: "He added too much ____ powder and the dish became unbearably hot.",
      answer: "chilli",
    },
    {
      id: "seasonings-condiments-b10",
      sentence: "____ sauce is an essential condiment in Japanese and Chinese cooking.",
      answer: "Soy",
    },
  ],
  culturalNotes: [
    {
      id: "seasonings-condiments-coriander-vs-cilantro",
      title: "Coriander vs Cilantro",
      body: "British English uses 'coriander' for both the leaf and the seed. American English uses 'cilantro' for the leaf and 'coriander' for the seed. This is one of the most confusing UK/US food vocabulary differences.",
    },
    {
      id: "seasonings-condiments-the-british-love-of-condiments",
      title: "The British Love of Condiments",
      body: "Britain has a strong condiment culture: HP Sauce (brown sauce), Branston Pickle, Marmite, English mustard, mint sauce (for lamb), and horseradish sauce (for beef). Knowing these helps understand British food culture and restaurant menus.",
    },
    {
      id: "seasonings-condiments-spice-trade-history",
      title: "Spice Trade History",
      body: "Many English spice words come from Arabic, Hindi, and Malay — reflecting centuries of spice trade. 'Cumin' (Arabic: kamun), 'turmeric' (Latin/Arabic), 'ginger' (Sanskrit), 'saffron' (Arabic: za'faran). This linguistic heritage enriches English vocabulary.",
    },
    {
      id: "seasonings-condiments-hot-sauce-culture",
      title: "Hot Sauce Culture",
      body: "Hot sauce has its own vocabulary: 'Scoville scale' measures heat, 'ghost pepper' and 'Carolina Reaper' are extremely hot varieties. In the UK, 'Nando's' popularised 'peri-peri' sauce. Americans love 'Tabasco' and 'Sriracha'.",
    },
    {
      id: "seasonings-condiments-herbs-fresh-vs-dried",
      title: "Herbs: Fresh vs Dried",
      body: "English distinguishes between 'fresh herbs' (living/recently cut) and 'dried herbs' (dehydrated). Recipes specify which to use because flavour intensity differs. A common rule: use 1/3 the amount of dried herbs compared to fresh.",
    },
  ],
  wordMeta: [
    {
      word: "salt",
      partOfSpeech: "n (unc)",
      frequency: 3,
      collocations: ["pinch of ~", "sea ~", "~ shaker", "~ and pepper"],
    },
    {
      word: "pepper",
      partOfSpeech: "n (unc)",
      frequency: 3,
      collocations: ["black ~", "~ mill", "~ grinder", "ground ~"],
    },
    {
      word: "cinnamon",
      partOfSpeech: "n (unc)",
      frequency: 2,
      collocations: ["~ stick", "~ powder", "~ roll", "~ flavour"],
    },
    {
      word: "cumin",
      partOfSpeech: "n (unc)",
      frequency: 2,
      collocations: ["ground ~", "~ seeds", "~ powder", "~ flavour"],
    },
    {
      word: "ketchup",
      partOfSpeech: "n (unc)",
      frequency: 3,
      collocations: ["tomato ~", "~ bottle", "~ sachet", "squirt of ~"],
    },
    {
      word: "mustard",
      partOfSpeech: "n (unc)",
      frequency: 3,
      collocations: ["English ~", "Dijon ~", "~ seed", "~ pot"],
    },
    {
      word: "soy sauce",
      partOfSpeech: "n (unc)",
      frequency: 3,
      collocations: ["light ~", "dark ~", "~ bottle", "~ marinade"],
    },
    {
      word: "vinegar",
      partOfSpeech: "n (unc)",
      frequency: 3,
      collocations: ["balsamic ~", "wine ~", "~ dressing", "apple cider ~"],
    },
    {
      word: "chutney",
      partOfSpeech: "n",
      frequency: 2,
      collocations: ["mango ~", "tomato ~", "~ jar", "spicy ~"],
    },
    {
      word: "turmeric",
      partOfSpeech: "n (unc)",
      frequency: 2,
      collocations: ["ground ~", "~ powder", "~ root", "~ latte"],
    },
  ],
};
