// Learning materials for "Spatial Relations".
//
// GENERATED by scripts/build-learning-materials.mjs from figma-dump/spatial-relations.json.
// Figma is the source of truth: edit the design file and re-run the sync,
// do not hand-edit this file.

import type { UnitLearningMaterials } from "../types";

export const SPATIAL_RELATIONS_LEARNING: UnitLearningMaterials = {
  unitId: "spatial-relations",
  subtopics: [
    {
      id: "size-relations",
      title: "Size Relations",
      wordIds: [
        "big",
        "small",
        "large",
        "tiny",
        "huge",
        "enormous",
        "miniature",
        "medium",
        "wide",
        "narrow",
      ],
    },
    {
      id: "distance-relations",
      title: "Distance Relations",
      wordIds: [
        "close",
        "far-away",
        "adjacent",
        "distant",
        "nearby",
        "remote",
        "proximate",
        "within-reach",
        "out-of-reach",
        "arm-s-length",
      ],
    },
    {
      id: "height-depth",
      title: "Height & Depth",
      wordIds: [
        "high",
        "low",
        "tall",
        "short",
        "deep",
        "shallow",
        "elevated",
        "sunken",
        "level",
        "flat",
      ],
    },
    {
      id: "arrangement",
      title: "Arrangement",
      wordIds: [
        "horizontal",
        "vertical",
        "diagonal",
        "parallel",
        "perpendicular",
        "aligned",
        "scattered",
        "clustered",
        "stacked",
        "layered",
      ],
    },
  ],
  passage: {
    title: "Reading Passage",
    level: "C1",
    text: "Spatial relations describe how objects are positioned relative to one another, and English expresses these relationships with remarkable precision. Horizontal relations use terms like 'adjacent' (immediately next to), 'adjoining' (sharing a boundary), 'parallel' (running side by side at equal distance), and 'perpendicular' (meeting at a right angle). Vertical relations include 'overhead' (directly above), 'elevated' (raised higher), 'sunken' (lowered below the surrounding level), and 'level with' (at the same height). Containment and enclosure use 'within' (inside the boundaries of), 'enclosed by' (completely surrounded), 'surrounded by' (encircled), and 'embedded in' (fixed firmly within). Proximity ranges from 'immediate' (right next to) through 'nearby' and 'in the vicinity' to 'remote' and 'distant'. Alignment describes how things line up: 'centred', 'offset', 'flush with' (perfectly aligned on the same plane), and 'staggered' (arranged in an alternating pattern). Overlap and intersection use 'overlapping' (partially covering), 'intersecting' (crossing each other), and 'converging' (meeting at a point). These terms appear constantly in architecture, design, urban planning, interior decorating, and technical writing. Mastering spatial vocabulary allows learners to describe environments precisely, follow technical instructions accurately, and communicate about physical arrangements with the clarity that advanced English demands.",
    questions: [],
    openQuestions: [
      "What is the difference between 'adjacent' and 'adjoining'?",
      "How do 'parallel' and 'perpendicular' differ?",
      "What terms describe containment relationships?",
      "Explain the difference between 'flush with' and 'staggered'.",
      "In which fields is spatial vocabulary especially important?",
    ],
  },
  phrases: [
    {
      id: "spatial-relations-side-by-side",
      phrase: "side by side",
      kind: "idiom",
      kindInferred: true,
      meaning:
        '(phrase) Next to each other. "The two houses stand side by side — identical in design but different in colour."',
      example: "",
    },
    {
      id: "spatial-relations-on-the-outskirts",
      phrase: "on the outskirts",
      kind: "idiom",
      kindInferred: true,
      meaning:
        '(phrase) On the edge of a town or city. "They live on the outskirts of Manchester — peaceful but far from the centre."',
      example: "",
    },
    {
      id: "spatial-relations-within-reach",
      phrase: "within reach",
      kind: "idiom",
      kindInferred: true,
      meaning:
        '(phrase) Close enough to touch or access. "Keep the first aid kit within reach — you never know when you\'ll need it."',
      example: "",
    },
    {
      id: "spatial-relations-miles-apart",
      phrase: "miles apart",
      kind: "idiom",
      meaning: "Very different (figuratively).",
      example: "Their opinions on education are miles apart — they can never agree.",
    },
    {
      id: "spatial-relations-in-close-proximity",
      phrase: "in close proximity",
      kind: "idiom",
      kindInferred: true,
      meaning:
        '(phrase) Very near to. "The school is in close proximity to the park, which is convenient for outdoor lessons."',
      example: "",
    },
    {
      id: "spatial-relations-at-the-heart-of",
      phrase: "at the heart of",
      kind: "idiom",
      kindInferred: true,
      meaning:
        '(phrase) At the centre or most important part. "The old cathedral is at the heart of the city — everything radiates outward from it."',
      example: "",
    },
    {
      id: "spatial-relations-on-the-fringes",
      phrase: "on the fringes",
      kind: "idiom",
      kindInferred: true,
      meaning:
        '(phrase) On the edges, often marginal. "The experimental art gallery operates on the fringes of the mainstream art world."',
      example: "",
    },
    {
      id: "spatial-relations-worlds-apart",
      phrase: "worlds apart",
      kind: "idiom",
      meaning: "Extremely different.",
      example:
        "Life in rural Scotland and central London are worlds apart — completely different experiences.",
    },
    {
      id: "spatial-relations-back-to-back",
      phrase: "back to back",
      kind: "phrasal-verb",
      kindInferred: true,
      meaning:
        '(phrase) With backs facing each other, or consecutively. "The terraced houses are built back to back — sharing a rear wall."',
      example: "",
    },
    {
      id: "spatial-relations-spread-out",
      phrase: "spread out",
      kind: "phrasal-verb",
      meaning: "Distributed over a wide area.",
      example: "The village is very spread out — the shop is a mile from the school.",
    },
  ],
  dialogue: {
    title: "Arranging Furniture",
    lines: [
      {
        speaker: "Interior Designer",
        text: "Where would you like the sofa? I'd suggest positioning it opposite the fireplace, centred on the wall.",
      },
      {
        speaker: "Homeowner",
        text: "Could we angle it slightly? If it's parallel to the window, we lose the garden view.",
      },
      {
        speaker: "Interior Designer",
        text: "Good point. Let's place it perpendicular to the window instead — so you can see both the fire and the garden.",
      },
      {
        speaker: "Homeowner",
        text: "And the coffee table? It needs to be within reach of the sofa but not blocking the walkway.",
      },
      {
        speaker: "Interior Designer",
        text: "I'll position it adjacent to the sofa, flush with the front edge. That leaves enough clearance to walk past.",
      },
      {
        speaker: "Homeowner",
        text: "What about the bookshelves? I was thinking either side of the fireplace — symmetrical.",
      },
      {
        speaker: "Interior Designer",
        text: "Perfect. Flanking the fireplace with matching shelves creates balance. I'll make sure they're level with each other.",
      },
      {
        speaker: "Homeowner",
        text: "And the reading lamp should go between the bookshelf and the sofa — in that gap. Close enough to read by but not in the way.",
      },
    ],
  },
  mistakes: [
    {
      id: "spatial-relations-the-table-is-in-the-middle-of-the-room",
      wrong: '"The table is in the middle from the room."',
      right: '"The table is in the middle of the room."',
      note: "'In the middle of' — always 'of', never 'from'. This is a fixed compound preposition. Same for: 'in front of', 'on top of', 'at the back of'.",
    },
    {
      id: "spatial-relations-the-buildings-are-parallel-to-each-other",
      wrong: '"The buildings are paralleled to each other."',
      right: '"The buildings are parallel to each other."',
      note: "'Parallel' is the adjective — no '-ed' needed. 'The roads run parallel to each other.' 'Paralleled' exists but means 'matched' or 'mirrored'.",
    },
    {
      id: "spatial-relations-she-sat-in-front-of-the-tv",
      wrong: '"She sat in front from the TV."',
      right: '"She sat in front of the TV."',
      note: "'In front of' uses 'of', never 'from'. 'From' would mean movement away from the front. Position = 'in front of'.",
    },
    {
      id: "spatial-relations-the-park-is-near-the-school-about-500-me",
      wrong: '"The park is near to the school, about 500 meters."',
      right: '"The park is near the school, about 500 metres away."',
      note: "'Near' needs no 'to'. Add 'away' after the distance: '500 metres away'. Also note: British spelling is 'metres', American is 'meters'.",
    },
    {
      id: "spatial-relations-put-the-chair-beside-the-desk",
      wrong: '"Put the chair besides the desk."',
      right: '"Put the chair beside the desk."',
      note: "'Beside' = next to (preposition of place). 'Besides' = in addition to / moreover (different word entirely). Don't add 's' for spatial meaning.",
    },
    {
      id: "spatial-relations-the-picture-hangs-above-over-the-sofa",
      wrong: '"The picture hangs over the sofa at a high position."',
      right: '"The picture hangs above/over the sofa."',
      note: "'Above' or 'over' already conveys the higher position — 'at a high position' is redundant. If you need to specify height, say 'high above the sofa'.",
    },
  ],
  wordFormation: [
    {
      noun: "adjacency",
      verb: null,
      adjective: "adjacent",
      adverb: "adjacently",
    },
    {
      noun: "proximity",
      verb: null,
      adjective: "proximate",
      adverb: "proximately",
    },
    {
      noun: "elevation",
      verb: "elevate",
      adjective: "elevated",
      adverb: null,
    },
    {
      noun: "alignment",
      verb: "align",
      adjective: "aligned",
      adverb: null,
    },
    {
      noun: "symmetry",
      verb: null,
      adjective: "symmetrical",
      adverb: "symmetrically",
    },
    {
      noun: "distance",
      verb: "distance",
      adjective: "distant",
      adverb: "distantly",
    },
    {
      noun: "convergence",
      verb: "converge",
      adjective: "convergent",
      adverb: null,
    },
    {
      noun: "intersection",
      verb: "intersect",
      adjective: "intersecting",
      adverb: null,
    },
    {
      noun: "enclosure",
      verb: "enclose",
      adjective: "enclosed",
      adverb: null,
    },
    {
      noun: "periphery",
      verb: null,
      adjective: "peripheral",
      adverb: "peripherally",
    },
  ],
  blankExercises: [
    {
      id: "spatial-relations-b1",
      sentence: "The two buildings stand ____ to each other, sharing a common wall.",
      answer: "adjacent/adjoining",
    },
    {
      id: "spatial-relations-b2",
      sentence: "The motorway runs ____ to the railway line — they never cross.",
      answer: "parallel",
    },
    {
      id: "spatial-relations-b3",
      sentence: "The old village is ____ by farmland on all sides — completely isolated.",
      answer: "surrounded",
    },
    {
      id: "spatial-relations-b4",
      sentence: "Place the shelf so it's ____ with the top of the window — perfectly aligned.",
      answer: "flush/level",
    },
    {
      id: "spatial-relations-b5",
      sentence: "The car park is ____ to the supermarket — right next door.",
      answer: "adjacent/next",
    },
    {
      id: "spatial-relations-b6",
      sentence: "The new housing estate is on the ____ of the town, far from the centre.",
      answer: "outskirts/periphery",
    },
    {
      id: "spatial-relations-b7",
      sentence: "The roads ____ at a busy junction where five streets meet.",
      answer: "converge/intersect",
    },
    {
      id: "spatial-relations-b8",
      sentence: "The swimming pool is ____ — set lower than the surrounding ground level.",
      answer: "sunken",
    },
    {
      id: "spatial-relations-b9",
      sentence: "Keep all emergency exits ____ reach — no more than 30 metres from any point.",
      answer: "within",
    },
    {
      id: "spatial-relations-b10",
      sentence:
        "The tiles are arranged in a ____ pattern — alternating positions rather than straight rows.",
      answer: "staggered",
    },
  ],
  culturalNotes: [
    {
      id: "spatial-relations-terraced-housing",
      title: "Terraced Housing",
      body: "Britain's iconic terraced houses are built 'side by side' in continuous rows. Describing them uses spatial vocabulary: 'adjoining walls', 'back-to-back yards', 'front-facing bay windows'. This housing style defines many British cities and towns.",
    },
    {
      id: "spatial-relations-garden-design",
      title: "Garden Design",
      body: "British garden design uses precise spatial language: 'borders' (edges), 'beds' (planting areas), 'paths winding through', 'pergola over', 'trellis along'. The concept of 'rooms' within a garden — distinct spaces separated by hedges — is quintessentially English.",
    },
    {
      id: "spatial-relations-football-pitch-positions",
      title: "Football Pitch Positions",
      body: "Football (soccer) commentary uses spatial terms extensively: 'on the wing', 'in the box', 'at the near post', 'across the face of goal', 'on the edge of the area'. Understanding these terms helps follow English sports commentary.",
    },
    {
      id: "spatial-relations-urban-planning",
      title: "Urban Planning",
      body: "British town planning vocabulary includes: 'green belt' (protected land around cities), 'brownfield' (previously developed land), 'conservation area' (protected historic zones). These terms appear in news, property listings, and everyday conversation.",
    },
    {
      id: "spatial-relations-personal-space",
      title: "Personal Space",
      body: "British culture has strong spatial norms: an 'arm's length' of personal space, queuing with gaps between people, not sitting directly next to a stranger when other seats are available. Violating these unwritten spatial rules causes visible discomfort.",
    },
  ],
  wordMeta: [
    {
      word: "adjacent",
      partOfSpeech: "adj",
      frequency: 2,
      collocations: ["~ to", "~ room", "~ building", "~ land"],
    },
    {
      word: "parallel",
      partOfSpeech: "adj/n",
      frequency: 3,
      collocations: ["~ to", "~ lines", "run ~", "~ universe"],
    },
    {
      word: "perpendicular",
      partOfSpeech: "adj",
      frequency: 2,
      collocations: ["~ to", "~ lines", "~ angle", "~ wall"],
    },
    {
      word: "symmetrical",
      partOfSpeech: "adj",
      frequency: 2,
      collocations: ["~ design", "~ pattern", "~ face", "perfectly ~"],
    },
    {
      word: "elevated",
      partOfSpeech: "adj",
      frequency: 2,
      collocations: ["~ position", "~ platform", "~ levels", "~ road"],
    },
    {
      word: "enclosed",
      partOfSpeech: "adj",
      frequency: 2,
      collocations: ["~ space", "~ garden", "fully ~", "~ area"],
    },
    {
      word: "overlapping",
      partOfSpeech: "adj",
      frequency: 2,
      collocations: ["~ circles", "~ schedules", "~ areas", "~ tiles"],
    },
    {
      word: "staggered",
      partOfSpeech: "adj",
      frequency: 2,
      collocations: ["~ rows", "~ hours", "~ pattern", "~ approach"],
    },
    {
      word: "peripheral",
      partOfSpeech: "adj",
      frequency: 2,
      collocations: ["~ vision", "~ area", "~ device", "~ role"],
    },
    {
      word: "converging",
      partOfSpeech: "adj",
      frequency: 1,
      collocations: ["~ lines", "~ paths", "~ opinions", "~ roads"],
    },
  ],
};
