// Learning materials for "The Vineyard".
//
// GENERATED by scripts/build-learning-materials.mjs from figma-dump/vineyard.json.
// Figma is the source of truth: edit the design file and re-run the sync,
// do not hand-edit this file.

import type { UnitLearningMaterials } from "../types";

export const VINEYARD_LEARNING: UnitLearningMaterials = {
  unitId: "vineyard",
  subtopics: [
    {
      id: "grape-varieties",
      title: "Grape Varieties",
      wordIds: [
        "cabernet-sauvignon",
        "merlot",
        "chardonnay",
        "pinot-noir",
        "sauvignon-blanc",
        "riesling",
        "syrah",
        "malbec",
        "tempranillo",
        "zinfandel",
      ],
    },
    {
      id: "vineyard-features",
      title: "Vineyard Features",
      wordIds: [
        "vine",
        "trellis",
        "row",
        "terroir",
        "slope",
        "irrigation",
        "canopy",
        "root-stock",
        "grafting",
        "pruning",
      ],
    },
    {
      id: "seasons-harvest",
      title: "Seasons & Harvest",
      wordIds: [
        "bud-break",
        "flowering",
        "veraison",
        "harvest",
        "crush",
        "growing-season",
        "dormancy",
        "frost-protection",
        "netting",
        "hand-picking",
      ],
    },
    {
      id: "vineyard-workers",
      title: "Vineyard Workers",
      wordIds: [
        "vintner",
        "viticulturist",
        "cellar-master",
        "sommelier",
        "vineyard-manager",
        "winemaker",
        "harvest-crew",
        "enologist",
        "cooper",
        "n-gociant",
      ],
    },
  ],
  passage: {
    title: "Reading Passage",
    level: "C1",
    text: "A vineyard is a plantation of grapevines cultivated for winemaking, and the English wine industry has experienced a remarkable renaissance over the past two decades. The chalky soils of southern England — particularly in Kent, Sussex, Surrey, and Hampshire — share geological similarities with the Champagne region of France, making them ideal for sparkling wine production. Vines are planted in neat rows along south-facing slopes to maximise sun exposure and drainage. The annual cycle begins with pruning in winter, when dormant vines are cut back to control growth. Spring brings bud break — the first green shoots emerging after months of bare wood. Throughout summer, vineyard workers manage the canopy, thinning leaves to allow sunlight to reach the developing grape clusters. Flowering occurs in early summer; each tiny flower, if successfully pollinated, becomes a grape. The growing season is a constant battle against frost, disease, and unpredictable British weather. Harvest — known as 'vintage' — typically takes place in October, when sugar levels in the grapes reach the ideal balance with acidity. Grapes are picked by hand or by machine, then transported immediately to the winery for pressing. English sparkling wines have won international blind tastings against established Champagne houses, proving that terroir — the unique combination of soil, climate, and geography — matters more than latitude.",
    questions: [],
    openQuestions: [
      "Why is southern England suitable for growing wine grapes?",
      "What happens during the pruning stage?",
      "What is 'bud break'?",
      "What challenges do English vineyard workers face?",
      "What does 'terroir' mean in winemaking?",
    ],
  },
  phrases: [
    {
      id: "vineyard-terroir",
      phrase: "terroir",
      kind: "idiom",
      kindInferred: true,
      meaning:
        '(French loanword) The complete natural environment affecting grape character. "The terroir here — chalk soil, maritime climate, south-facing slopes — gives the wine its distinctive minerality."',
      example: "",
    },
    {
      id: "vineyard-vintage",
      phrase: "vintage",
      kind: "idiom",
      kindInferred: true,
      meaning:
        '(noun) The year\'s grape harvest; also the wine produced from it. "The 2022 vintage was exceptional — a long, warm summer produced grapes with outstanding ripeness."',
      example: "",
    },
    {
      id: "vineyard-on-the-vine",
      phrase: "on the vine",
      kind: "idiom",
      kindInferred: true,
      meaning:
        '(phrase) Still growing; not yet harvested. "The grapes are still on the vine — we\'ll wait another two weeks for the sugar levels to peak."',
      example: "",
    },
    {
      id: "vineyard-bear-fruit",
      phrase: "bear fruit",
      kind: "idiom",
      meaning: "To produce positive results after effort.",
      example:
        "Years of investment in the vineyard are finally bearing fruit — both literally and commercially.",
    },
    {
      id: "vineyard-a-good-year",
      phrase: "a good year",
      kind: "idiom",
      kindInferred: true,
      meaning:
        '(phrase) A year with excellent growing conditions. "2018 was a good year — warm and dry from June to September, perfect for ripening."',
      example: "",
    },
    {
      id: "vineyard-sour-grapes",
      phrase: "sour grapes",
      kind: "idiom",
      meaning: "Pretending not to want something you can't have.",
      example:
        "When he didn't win the wine award, he said the competition was rigged — pure sour grapes.",
    },
    {
      id: "vineyard-wither-on-the-vine",
      phrase: "wither on the vine",
      kind: "idiom",
      meaning: "To fail through neglect.",
      example: "The project withered on the vine — no funding, no attention, no progress.",
    },
    {
      id: "vineyard-cultivate",
      phrase: "cultivate",
      kind: "idiom",
      kindInferred: true,
      meaning:
        '(verb, also figurative) To develop carefully over time. "She cultivated relationships with local restaurants — now they exclusively stock her wines."',
      example: "",
    },
    {
      id: "vineyard-harvest-time",
      phrase: "harvest time",
      kind: "idiom",
      kindInferred: true,
      meaning:
        '(phrase) The period when grapes are picked. "Harvest time is all hands on deck — everyone helps, from dawn until the last crate is pressed."',
      example: "",
    },
    {
      id: "vineyard-root-and-branch",
      phrase: "root and branch",
      kind: "idiom",
      meaning: "Thorough and complete.",
      example:
        "The vineyard underwent a root-and-branch transformation — new vines, new drainage, new winemaking facilities.",
    },
  ],
  dialogue: {
    title: "Touring an English Vineyard",
    lines: [
      {
        speaker: "Guide",
        text: "Welcome to the vineyard. We're standing in our oldest plot — Chardonnay vines planted in 2006 on pure chalk soil.",
      },
      {
        speaker: "Visitor",
        text: "The rows are incredibly neat. How far apart are the vines planted?",
      },
      {
        speaker: "Guide",
        text: "One metre between vines, two metres between rows. That spacing allows airflow — essential for preventing mildew in our damp climate.",
      },
      {
        speaker: "Visitor",
        text: "When do you harvest?",
      },
      {
        speaker: "Guide",
        text: "Usually mid-October. We test the sugar and acid levels daily from September. Picking too early gives thin wine; too late risks rot if the autumn rains come.",
      },
      {
        speaker: "Visitor",
        text: "Is everything picked by hand?",
      },
      {
        speaker: "Guide",
        text: "For our sparkling wines, yes — hand-picking means whole bunches arrive at the press undamaged. Machine harvesting is faster but rougher on the fruit.",
      },
      {
        speaker: "Visitor",
        text: "English sparkling wine has won some serious awards, hasn't it?",
      },
    ],
  },
  mistakes: [
    {
      id: "vineyard-the-vineyard-grows-grapes-the-vineyard-p",
      wrong: '"The vineyard grows wines."',
      right: '"The vineyard grows grapes." / "The vineyard produces wine."',
      note: "Vineyards grow grapes (the fruit); wineries produce wine (the drink). You can't 'grow' wine — it's made/produced. 'The estate produces 50,000 bottles annually.'",
    },
    {
      id: "vineyard-we-visited-a-vineyard",
      wrong: '"We visited a grape garden."',
      right: '"We visited a vineyard."',
      note: "'Vineyard' is the specific English word — not 'grape garden', 'grape farm', or 'wine garden'. Pronounced 'VIN-yard' (two syllables, not three).",
    },
    {
      id: "vineyard-the-wine-reflects-its-terroir-you-can-ta",
      wrong: '"The wine has a taste of the earth terroir."',
      right: '"The wine reflects its terroir." / "You can taste the terroir."',
      note: "'Terroir' already encompasses soil, climate, and geography — don't add 'earth' before it. It's a loanword used as-is: 'The terroir is exceptional', 'terroir-driven wines'.",
    },
    {
      id: "vineyard-this-is-a-2020-vintage-this-wine-is-from",
      wrong: '"This wine is from a 2020 vintage year."',
      right: '"This is a 2020 vintage." / "This wine is from the 2020 vintage."',
      note: "'Vintage' already means the year — 'vintage year' is redundant unless emphasising it was an exceptionally good year ('2018 was a vintage year for English wine').",
    },
    {
      id: "vineyard-the-grapes-are-ripening-on-the-vine",
      wrong: '"The grapes are maturating on the vine."',
      right: '"The grapes are ripening on the vine."',
      note: "'Ripen' is the standard verb for fruit developing maturity. 'Mature' is used for wine ageing in barrels/bottles — not for grapes growing. 'Maturate' exists but sounds clinical.",
    },
    {
      id: "vineyard-he-works-in-a-vineyard-he-works-among-th",
      wrong: '"He works in a vine field."',
      right: '"He works in a vineyard." / "He works among the vines."',
      note: "'Vineyard' not 'vine field'. 'Vine' alone refers to the plant. 'Row of vines', 'the vines are dormant', 'vine management' — but the place is always 'vineyard'.",
    },
  ],
  wordFormation: [
    {
      noun: "cultivation",
      verb: "cultivate",
      adjective: "cultivated",
      adverb: null,
    },
    {
      noun: "harvest",
      verb: "harvest",
      adjective: "harvested",
      adverb: null,
    },
    {
      noun: "fermentation",
      verb: "ferment",
      adjective: "fermented",
      adverb: null,
    },
    {
      noun: "pruning",
      verb: "prune",
      adjective: "pruned",
      adverb: null,
    },
    {
      noun: "ripeness",
      verb: "ripen",
      adjective: "ripe/unripe",
      adverb: null,
    },
    {
      noun: "viticulture",
      verb: null,
      adjective: "viticultural",
      adverb: null,
    },
    {
      noun: "drainage",
      verb: "drain",
      adjective: "drained",
      adverb: null,
    },
    {
      noun: "pollination",
      verb: "pollinate",
      adjective: "pollinated",
      adverb: null,
    },
    {
      noun: "plantation",
      verb: "plant",
      adjective: "planted",
      adverb: null,
    },
    {
      noun: "acidity",
      verb: "acidify",
      adjective: "acidic",
      adverb: null,
    },
  ],
  blankExercises: [
    {
      id: "vineyard-b1",
      sentence:
        "The ____ are planted in neat rows along south-facing slopes for maximum sun exposure.",
      answer: "vines",
    },
    {
      id: "vineyard-b2",
      sentence:
        "____ takes place in winter — cutting back dormant vines to control the next season's growth.",
      answer: "Pruning",
    },
    {
      id: "vineyard-b3",
      sentence: "Bud ____ in spring marks the first signs of new growth after the cold months.",
      answer: "break",
    },
    {
      id: "vineyard-b4",
      sentence: "The ____ — the annual grape harvest — usually happens in October in England.",
      answer: "vintage",
    },
    {
      id: "vineyard-b5",
      sentence:
        "English sparkling wines thrive on ____ soil, geologically similar to France's Champagne region.",
      answer: "chalk",
    },
    {
      id: "vineyard-b6",
      sentence:
        "____ is the unique combination of soil, climate, and geography that shapes a wine's character.",
      answer: "Terroir",
    },
    {
      id: "vineyard-b7",
      sentence: "The grapes need time to ____ — developing the right balance of sugar and acidity.",
      answer: "ripen",
    },
    {
      id: "vineyard-b8",
      sentence:
        "Vineyard workers thin the ____ to allow sunlight to reach the developing grape clusters.",
      answer: "canopy",
    },
    {
      id: "vineyard-b9",
      sentence:
        "The science of grape-growing is called ____ — distinct from winemaking (oenology).",
      answer: "viticulture",
    },
    {
      id: "vineyard-b10",
      sentence:
        "Hand-____ ensures whole bunches arrive at the press undamaged for premium sparkling wine.",
      answer: "picking",
    },
  ],
  culturalNotes: [
    {
      id: "vineyard-the-english-wine-revolution",
      title: "The English Wine Revolution",
      body: "England now has over 900 vineyards and 200 wineries. English sparkling wine regularly beats Champagne in blind tastings. Major Champagne houses (Taittinger, Pommery) have even bought land in southern England — the ultimate validation of English terroir and a direct consequence of climate change.",
    },
    {
      id: "vineyard-wine-tourism",
      title: "Wine Tourism",
      body: "Vineyard tours and tastings have become a major tourist attraction in southern England — comparable to visiting stately homes. 'Wine trails' through Kent, Sussex, and Hampshire offer guided tastings, vineyard walks, and restaurant pairings. It's a growing agritourism sector.",
    },
    {
      id: "vineyard-grape-varieties",
      title: "Grape Varieties",
      body: "The dominant English grape varieties are Chardonnay, Pinot Noir, and Pinot Meunier — the same trio used in Champagne. Bacchus (a German cross) is England's signature still white wine grape, producing aromatic wines compared to Sauvignon Blanc. These names appear on every English wine label.",
    },
    {
      id: "vineyard-winegb",
      title: "WineGB",
      body: "WineGB (formerly the English & Welsh Wine Producers) is the industry body promoting British wine. 'English Wine Week' in June is an annual celebration with open vineyards, tastings, and promotions. Note: 'English wine' (made from English-grown grapes) differs from 'British wine' (made from imported concentrate).",
    },
    {
      id: "vineyard-vineyard-volunteer-harvesting",
      title: "Vineyard Volunteer Harvesting",
      body: "Many English vineyards rely on volunteer pickers during harvest — offering a free lunch, wine tasting, and a bottle to take home in exchange for a day's manual grape-picking. It's become a popular social event: 'picking day' at a local vineyard is a quintessentially English autumn experience.",
    },
  ],
  wordMeta: [
    {
      word: "vineyard",
      partOfSpeech: "n",
      frequency: 3,
      collocations: ["English ~", "~ tour", "~ owner", "~ slope"],
    },
    {
      word: "vine",
      partOfSpeech: "n",
      frequency: 3,
      collocations: ["grape~", "~ row", "dormant ~", "~ canopy"],
    },
    {
      word: "terroir",
      partOfSpeech: "n",
      frequency: 2,
      collocations: ["unique ~", "chalk ~", "~-driven", "express the ~"],
    },
    {
      word: "vintage",
      partOfSpeech: "n/adj",
      frequency: 3,
      collocations: ["2022 ~", "good ~", "~ year", "~ wine"],
    },
    {
      word: "harvest",
      partOfSpeech: "n/v",
      frequency: 3,
      collocations: ["grape ~", "~ season", "~ time", "hand-~ed"],
    },
    {
      word: "pruning",
      partOfSpeech: "n",
      frequency: 2,
      collocations: ["winter ~", "~ shears", "~ technique", "canopy ~"],
    },
    {
      word: "sparkling wine",
      partOfSpeech: "n",
      frequency: 3,
      collocations: ["English ~", "~ production", "~ method", "~ bottle"],
    },
    {
      word: "chalk soil",
      partOfSpeech: "n",
      frequency: 2,
      collocations: ["~ drainage", "~ terroir", "~ hillside", "pure ~"],
    },
    {
      word: "viticulture",
      partOfSpeech: "n",
      frequency: 2,
      collocations: ["English ~", "~ course", "~ technique", "cool-climate ~"],
    },
    {
      word: "ripening",
      partOfSpeech: "n",
      frequency: 2,
      collocations: ["grape ~", "~ period", "~ season", "slow ~"],
    },
  ],
};
