const PRONUNCIATION_SOURCE_NAMES = [
  "lesson-01-same-or-different",
  "lesson-02-sheep-or-ship-spec-frame",
  "lesson-03-pin-or-pen-spec-frame",
  "lesson-04-pen-or-pan-spec-frame",
  "lesson-05-cap-or-cup",
  "lesson-06-full-or-fool-spec-frame",
  "lesson-07-pig-or-big-spec-frame",
  "lesson-08-sound-detective-challenge-spec-frame",
  "lesson-09-air-and-voice-make-p-and-b-spec-frame",
  "lesson-10-air-and-voice-make-f-and-v-spec-frame",
  "lesson-11-make-t-and-d-spec-frame",
  "lesson-12-make-k-and-g-spec-frame",
  "lesson-13-make-s-and-z-spec-frame",
  "lesson-14-make-and-t-spec-frame",
  "lesson-15-make-and-s-spec-frame",
  "lesson-16-specification",
  "lesson-17-specification",
  "lesson-18-specification",
  "lesson-19-specification",
  "lesson-20-specification",
  "lesson-21-vowel-shape-i-and-spec",
  "lesson-22-front-vowel-map-and",
  "lesson-23-central-back-vowels-u",
  "lesson-24-make-the-sounds-capstone",
  "lesson-25-contrast-lab-i-vs",
  "lesson-26-vowel-shape-contrast-versus",
  "lesson-27-vowel-shape-contrast-versus",
  "lesson-28-vowel-shape-contrast-versus",
  "lesson-29-back-vowel-space-versus-u",
  "lesson-30-mixed-vowel-transfer-challenge",
  "lesson-31-sound-contrast-spec",
  "lesson-32-sound-contrast-spec",
  "lesson-33-sound-contrast-spec",
  "lesson-34-sound-contrast-spec",
  "lesson-35-sound-contrast-spec",
  "lesson-36-sound-contrast-spec",
  "lesson-37-sound-contrast-spec",
  "lesson-38-category-lab-spec",
  "lesson-39-syllable-beats-spec",
  "lesson-40-unstressed-schwa-spec",
  "lesson-41-sound-contrast-spec",
  "lesson-42-sound-contrast-spec",
  "lesson-43-sound-contrast-spec",
  "lesson-44-sound-contrast-spec",
  "lesson-45-sound-contrast-spec",
  "lesson-46-sound-contrast-spec",
  "lesson-47-sound-contrast-spec",
  "lesson-48-sound-contrast-spec",
  "lesson-49-sound-contrast-spec",
  "lesson-50-sound-contrast-spec",
  "lesson-51-sound-contrast-spec",
  "lesson-52-sound-contrast-spec",
  "lesson-53-sound-contrast-spec",
  "lesson-54-sound-contrast-spec",
  "lesson-55-sound-contrast-spec",
  "lesson-56-sound-contrast-spec",
  "lesson-57-sound-contrast-spec",
  "lesson-58-sound-contrast-spec",
  "lesson-59-sound-contrast-spec",
  "lesson-60-sound-contrast-spec",
  "lesson-61-pronunciation-spec",
  "lesson-62-pronunciation-spec",
  "lesson-63-pronunciation-spec",
  "lesson-64-pronunciation-spec",
  "lesson-65-pronunciation-spec",
  "lesson-66-pronunciation-spec",
  "lesson-67-pronunciation-spec",
  "lesson-68-pronunciation-spec",
] as const;

export const PRONUNCIATION_LESSON_COUNT = PRONUNCIATION_SOURCE_NAMES.length;

export function getPronunciationLessonMetadata(number: number) {
  const sourceName = PRONUNCIATION_SOURCE_NAMES[number - 1];
  if (!sourceName) throw new Error(`Unknown Figma pronunciation lesson: ${number}`);
  return {
    number,
    sourceName,
  };
}
