import {
  masteryLevelSchema,
  masterySkillSchema,
  masteryWordSchema,
  type MasteryLevel,
  type MasterySkill,
  type MasteryWord,
} from "./masteryTypes";

export const MASTERY_SKILLS: readonly MasterySkill[] = [
  masterySkillSchema.parse({
    id: "phoneme_isolation",
    name: "Phoneme Isolation",
    skillType: "phoneme_isolation",
    description: "Hear and identify individual sounds in spoken words.",
  }),
  masterySkillSchema.parse({
    id: "sound_letter_matching",
    name: "Sound to Letter",
    skillType: "sound_letter_matching",
    description: "Connect phonemes to their corresponding letters and graphemes.",
  }),
  masterySkillSchema.parse({
    id: "blending",
    name: "Sound Blending",
    skillType: "blending",
    description: "Combine individual sounds smoothly into whole words.",
  }),
  masterySkillSchema.parse({
    id: "segmenting",
    name: "Sound Segmenting",
    skillType: "segmenting",
    description: "Separate whole spoken words into their constituent sounds.",
  }),
  masterySkillSchema.parse({
    id: "reading",
    name: "Word Reading",
    skillType: "reading",
    description: "Decode and read printed words accurately.",
  }),
  masterySkillSchema.parse({
    id: "spelling",
    name: "Word Spelling",
    skillType: "spelling",
    description: "Encode spoken sounds into correct written letters.",
  }),
  masterySkillSchema.parse({
    id: "contrast",
    name: "Sound & Word Contrast",
    skillType: "contrast",
    description: "Discriminate between minimal sound and spelling differences.",
  }),
  masterySkillSchema.parse({
    id: "pronunciation",
    name: "Pronunciation Mastery",
    skillType: "pronunciation",
    description: "Produce clear, accurate phoneme and word articulation.",
  }),
];

export const MASTERY_WORDS: readonly MasteryWord[] = [
  masteryWordSchema.parse({
    id: "cat",
    text: "cat",
    phonemes: ["k", "æ", "t"],
    graphemes: ["c", "a", "t"],
    soundBoxes: ["c", "a", "t"],
    vowelType: "short",
    pattern: "CVC",
    wordFamily: "-at",
    contrastPairs: ["cap", "cut", "hat", "mat"],
    difficultyLevel: 1,
    meaningSnippet: "A small domesticated feline animal",
  }),
  masteryWordSchema.parse({
    id: "cap",
    text: "cap",
    phonemes: ["k", "æ", "p"],
    graphemes: ["c", "a", "p"],
    soundBoxes: ["c", "a", "p"],
    vowelType: "short",
    pattern: "CVC",
    wordFamily: "-ap",
    contrastPairs: ["cat", "cup", "map", "tap"],
    difficultyLevel: 1,
    meaningSnippet: "A close-fitting head covering",
  }),
  masteryWordSchema.parse({
    id: "cut",
    text: "cut",
    phonemes: ["k", "ʌ", "t"],
    graphemes: ["c", "u", "t"],
    soundBoxes: ["c", "u", "t"],
    vowelType: "short",
    pattern: "CVC",
    wordFamily: "-ut",
    contrastPairs: ["cat", "cup"],
    difficultyLevel: 2,
    meaningSnippet: "To divide something using a sharp edge",
  }),
  masteryWordSchema.parse({
    id: "pen",
    text: "pen",
    phonemes: ["p", "ɛ", "n"],
    graphemes: ["p", "e", "n"],
    soundBoxes: ["p", "e", "n"],
    vowelType: "short",
    pattern: "CVC",
    wordFamily: "-en",
    contrastPairs: ["pin", "pan", "hen", "ten"],
    difficultyLevel: 1,
    meaningSnippet: "An instrument for writing with ink",
  }),
  masteryWordSchema.parse({
    id: "pin",
    text: "pin",
    phonemes: ["p", "ɪ", "n"],
    graphemes: ["p", "i", "n"],
    soundBoxes: ["p", "i", "n"],
    vowelType: "short",
    pattern: "CVC",
    wordFamily: "-in",
    contrastPairs: ["pen", "pan"],
    difficultyLevel: 2,
    meaningSnippet: "A small thin piece of metal used for fastening",
  }),
  masteryWordSchema.parse({
    id: "pan",
    text: "pan",
    phonemes: ["p", "æ", "n"],
    graphemes: ["p", "a", "n"],
    soundBoxes: ["p", "a", "n"],
    vowelType: "short",
    pattern: "CVC",
    wordFamily: "-an",
    contrastPairs: ["pen", "pin"],
    difficultyLevel: 1,
    meaningSnippet: "A metal container used for cooking food",
  }),
  masteryWordSchema.parse({
    id: "hat",
    text: "hat",
    phonemes: ["h", "æ", "t"],
    graphemes: ["h", "a", "t"],
    soundBoxes: ["h", "a", "t"],
    vowelType: "short",
    pattern: "CVC",
    wordFamily: "-at",
    contrastPairs: ["cat", "mat"],
    difficultyLevel: 1,
    meaningSnippet: "A shaped covering for the head",
  }),
  masteryWordSchema.parse({
    id: "mat",
    text: "mat",
    phonemes: ["m", "æ", "t"],
    graphemes: ["m", "a", "t"],
    soundBoxes: ["m", "a", "t"],
    vowelType: "short",
    pattern: "CVC",
    wordFamily: "-at",
    contrastPairs: ["hat", "cat", "map"],
    difficultyLevel: 1,
    meaningSnippet: "A piece of fabric placed on the floor",
  }),
  masteryWordSchema.parse({
    id: "map",
    text: "map",
    phonemes: ["m", "æ", "p"],
    graphemes: ["m", "a", "p"],
    soundBoxes: ["m", "a", "p"],
    vowelType: "short",
    pattern: "CVC",
    wordFamily: "-ap",
    contrastPairs: ["mat", "cap", "tap"],
    difficultyLevel: 1,
    meaningSnippet: "A visual diagram of an area of land or sea",
  }),
  masteryWordSchema.parse({
    id: "tap",
    text: "tap",
    phonemes: ["t", "æ", "p"],
    graphemes: ["t", "a", "p"],
    soundBoxes: ["t", "a", "p"],
    vowelType: "short",
    pattern: "CVC",
    wordFamily: "-ap",
    contrastPairs: ["cap", "map", "ten"],
    difficultyLevel: 1,
    meaningSnippet: "A device that controls the flow of liquid",
  }),
  masteryWordSchema.parse({
    id: "hen",
    text: "hen",
    phonemes: ["h", "ɛ", "n"],
    graphemes: ["h", "e", "n"],
    soundBoxes: ["h", "e", "n"],
    vowelType: "short",
    pattern: "CVC",
    wordFamily: "-en",
    contrastPairs: ["pen", "ten", "men"],
    difficultyLevel: 1,
    meaningSnippet: "A female domestic bird",
  }),
  masteryWordSchema.parse({
    id: "ten",
    text: "ten",
    phonemes: ["t", "ɛ", "n"],
    graphemes: ["t", "e", "n"],
    soundBoxes: ["t", "e", "n"],
    vowelType: "short",
    pattern: "CVC",
    wordFamily: "-en",
    contrastPairs: ["hen", "pen", "men"],
    difficultyLevel: 1,
    meaningSnippet: "The number following nine",
  }),
  masteryWordSchema.parse({
    id: "men",
    text: "men",
    phonemes: ["m", "ɛ", "n"],
    graphemes: ["m", "e", "n"],
    soundBoxes: ["m", "e", "n"],
    vowelType: "short",
    pattern: "CVC",
    wordFamily: "-en",
    contrastPairs: ["hen", "ten", "pen"],
    difficultyLevel: 1,
    meaningSnippet: "Plural form of adult male humans",
  }),
  masteryWordSchema.parse({
    id: "sit",
    text: "sit",
    phonemes: ["s", "ɪ", "t"],
    graphemes: ["s", "i", "t"],
    soundBoxes: ["s", "i", "t"],
    vowelType: "short",
    pattern: "CVC",
    wordFamily: "-it",
    contrastPairs: ["set"],
    difficultyLevel: 2,
    meaningSnippet: "To adopt or be in a position supported by a seat",
  }),
  masteryWordSchema.parse({
    id: "set",
    text: "set",
    phonemes: ["s", "ɛ", "t"],
    graphemes: ["s", "e", "t"],
    soundBoxes: ["s", "e", "t"],
    vowelType: "short",
    pattern: "CVC",
    wordFamily: "-et",
    contrastPairs: ["sit"],
    difficultyLevel: 2,
    meaningSnippet: "A group of things belonging together",
  }),
  masteryWordSchema.parse({
    id: "sun",
    text: "sun",
    phonemes: ["s", "ʌ", "n"],
    graphemes: ["s", "u", "n"],
    soundBoxes: ["s", "u", "n"],
    vowelType: "short",
    pattern: "CVC",
    wordFamily: "-un",
    contrastPairs: ["cup", "cut"],
    difficultyLevel: 2,
    meaningSnippet: "The star that provides light and warmth to Earth",
  }),
  masteryWordSchema.parse({
    id: "cup",
    text: "cup",
    phonemes: ["k", "ʌ", "p"],
    graphemes: ["c", "u", "p"],
    soundBoxes: ["c", "u", "p"],
    vowelType: "short",
    pattern: "CVC",
    wordFamily: "-up",
    contrastPairs: ["cap", "cut"],
    difficultyLevel: 2,
    meaningSnippet: "A small bowl-shaped container used for drinking",
  }),
];

const masteryWordMap = new Map(MASTERY_WORDS.map((word) => [word.id, word]));

export function getMasteryWord(wordId: string): MasteryWord | undefined {
  return masteryWordMap.get(wordId);
}

export const LEVEL_ONE: MasteryLevel = masteryLevelSchema.parse({
  id: "level-1",
  levelNumber: 1,
  title: "First Sounds & Letters",
  subtitle: "Connect early phonemes to their printed letters",
  description:
    "Learn the foundational sound-to-letter correspondences: /s/, /æ/, /t/, /p/, /ɪ/, /n/.",
  units: [
    {
      id: "sound-set-1",
      levelId: "level-1",
      order: 1,
      name: "Sound Set: s, a, t, p",
      description: "Introduce initial consonants and short-a phoneme.",
      targetSounds: ["/s/", "/æ/", "/t/", "/p/"],
      targetLetters: ["s", "a", "t", "p"],
      words: ["tap", "mat", "hat", "cap"],
      lessons: [
        {
          id: "hear-satp",
          unitId: "sound-set-1",
          order: 1,
          title: "Hear the First Sounds",
          skillId: "phoneme_isolation",
          targetWords: ["tap", "mat", "hat"],
          activityTypes: ["ListenCard", "SoundChoice"],
          prerequisites: [],
        },
        {
          id: "connect-satp",
          unitId: "sound-set-1",
          order: 2,
          title: "Connect Sounds to Letters",
          skillId: "sound_letter_matching",
          targetWords: ["tap", "cap", "mat"],
          activityTypes: ["LetterSound", "BlendBuilder"],
          prerequisites: ["hear-satp"],
        },
        {
          id: "blend-at-words",
          unitId: "sound-set-1",
          order: 3,
          title: "Blend Words with -at",
          skillId: "blending",
          targetWords: ["cat", "hat", "mat"],
          activityTypes: ["BlendBuilder", "WordBuilder"],
          prerequisites: ["connect-satp"],
        },
      ],
    },
  ],
});

export const LEVEL_TWO: MasteryLevel = masteryLevelSchema.parse({
  id: "level-2",
  levelNumber: 2,
  title: "VC and CVC Word Building",
  subtitle: "Build, segment, and read three-sound words",
  description:
    "Progress from blending to segmenting and spelling common CVC words with short vowels.",
  units: [
    {
      id: "cvc-short-a",
      levelId: "level-2",
      order: 1,
      name: "CVC Short A Words",
      description: "Master decoding and encoding CVC words with /æ/.",
      targetSounds: ["/æ/", "/k/", "/t/", "/p/", "/m/"],
      targetLetters: ["c", "a", "t", "p", "m"],
      words: ["cat", "cap", "mat", "map", "tap"],
      lessons: [
        {
          id: "cvc-a-read",
          unitId: "cvc-short-a",
          order: 1,
          title: "Read Short-A CVC Words",
          skillId: "reading",
          targetWords: ["cat", "cap", "mat", "map", "tap"],
          activityTypes: ["ListenCard", "SoundBoxes", "WordBuilder"],
          prerequisites: [],
        },
        {
          id: "cvc-a-segment",
          unitId: "cvc-short-a",
          order: 2,
          title: "Segment Sounds in Short-A",
          skillId: "segmenting",
          targetWords: ["cat", "cap", "hat", "mat", "map"],
          activityTypes: ["SoundBoxes", "WordBuilder"],
          prerequisites: ["cvc-a-read"],
        },
        {
          id: "cvc-a-spell",
          unitId: "cvc-short-a",
          order: 3,
          title: "Spell Short-A Words from Audio",
          skillId: "spelling",
          targetWords: ["cat", "cap", "tap"],
          activityTypes: ["SpellFromAudio", "QuickReview"],
          prerequisites: ["cvc-a-segment"],
        },
      ],
    },
    {
      id: "cvc-short-e",
      levelId: "level-2",
      order: 2,
      name: "CVC Short E Words",
      description: "Master decoding and contrasting CVC words with /ɛ/.",
      targetSounds: ["/ɛ/", "/p/", "/n/", "/h/", "/t/", "/m/"],
      targetLetters: ["p", "e", "n", "h", "t", "m"],
      words: ["pen", "hen", "ten", "men", "set"],
      lessons: [
        {
          id: "cvc-e-read",
          unitId: "cvc-short-e",
          order: 1,
          title: "Read Short-E Words",
          skillId: "reading",
          targetWords: ["pen", "hen", "ten", "men"],
          activityTypes: ["ListenCard", "SoundBoxes"],
          prerequisites: [],
        },
        {
          id: "cvc-e-contrast",
          unitId: "cvc-short-e",
          order: 2,
          title: "Contrast e/i/a Pairs",
          skillId: "contrast",
          targetWords: ["pen", "pin", "pan"],
          activityTypes: ["MinimalPair", "SoundChoice"],
          prerequisites: ["cvc-e-read"],
        },
        {
          id: "cvc-e-spell",
          unitId: "cvc-short-e",
          order: 3,
          title: "Spell Short-E Words",
          skillId: "spelling",
          targetWords: ["pen", "ten", "men"],
          activityTypes: ["SpellFromAudio", "QuickReview"],
          prerequisites: ["cvc-e-contrast"],
        },
      ],
    },
  ],
});

export const MASTERY_LEVELS: readonly MasteryLevel[] = [LEVEL_ONE, LEVEL_TWO];

const masteryLevelMap = new Map(MASTERY_LEVELS.map((level) => [level.id, level]));

export function getMasteryLevel(levelId: string): MasteryLevel | undefined {
  return masteryLevelMap.get(levelId);
}
