// scripts/append_garden_data.cjs
const fs = require('fs');
const path = require('path');

const lessonsPath = path.resolve('src/app/data/lessons.ts');
let content = fs.readFileSync(lessonsPath, 'utf8');

const gardenData = `
// --- GARDEN DATA ---

export const GARDEN_TOPICS: TopicCategory[] = [
  { id: "flowers", name: "Flowers", itemsCount: 10 },
  { id: "trees-shrubs", name: "Trees & Shrubs", itemsCount: 10 },
  { id: "garden-tools", name: "Garden Tools", itemsCount: 12 },
  { id: "parts-of-a-plant", name: "Parts of a Plant", itemsCount: 10 },
  { id: "garden-creatures", name: "Garden Creatures", itemsCount: 10 },
  { id: "garden-features", name: "Garden Features", itemsCount: 10 },
];

export const GARDEN_GROUPS: Lesson[] = [
  {
    id: "flowers",
    name: "Flowers",
    topicId: "flowers",
    wordIds: [
      "rose",
      "tulip",
      "sunflower",
      "daisy",
      "lily",
      "daffodil",
      "violet",
      "orchid",
      "carnation",
      "lavender",
    ],
    description: "Learn about flowers.",
    story:
      "In the sunny courtyard, a fragrant rose bloomed beside a bright yellow sunflower and a pink tulip. Maya noticed a white daisy and a sweet lily near the stone border. Purple violet and blue orchid blossoms opened beneath the hedge, while a red carnation, a cheerful daffodil, and sweet lavender filled the morning air with perfume.",
  },
  {
    id: "trees-shrubs",
    name: "Trees & Shrubs",
    topicId: "trees-shrubs",
    wordIds: [
      "oak-tree",
      "pine-tree",
      "apple-tree",
      "cherry-tree",
      "palm-tree",
      "hedge",
      "bush",
      "ivy",
      "vine",
      "fern",
    ],
    description: "Learn about trees & shrubs.",
    story:
      "A tall oak tree and a majestic pine tree provided shade near the apple tree and flowering cherry tree. Maya rested under a palm tree beside a trimmed hedge and a green bush. Clinging ivy and trailing vine grew along the wall, while a delicate fern flourished in the cool shadow.",
  },
  {
    id: "garden-tools",
    name: "Garden Tools",
    topicId: "garden-tools",
    wordIds: [
      "shovel",
      "rake",
      "watering-can",
      "wheelbarrow",
      "hose",
      "garden-gloves",
      "pruner",
      "trowel",
      "lawn-mower",
      "spade",
      "pitchfork",
      "sprinkler",
    ],
    description: "Learn about garden tools.",
    story:
      "Maya picked up the shovel, spade, and trowel to dig planting holes, while Omar used the rake and pitchfork to clear leaves and mulch. They filled the wheelbarrow with soil, carried the watering can, connected the long hose, and turned on the sprinkler. After wearing garden gloves, Maya pruned branches with a sharp pruner and trimmed the grass with a lawn mower.",
  },
  {
    id: "parts-of-a-plant",
    name: "Parts of a Plant",
    topicId: "parts-of-a-plant",
    wordIds: [
      "root",
      "stem",
      "leaf",
      "petal",
      "branch",
      "bark",
      "bud",
      "seed",
      "thorn",
      "berry",
    ],
    description: "Learn about parts of a plant.",
    story:
      "Omar examined a deep root buried in soil and followed the sturdy stem up to a green leaf and a colorful petal. High above, a thick branch covered in rough bark held a tiny bud and a ripe seed. He avoided a sharp thorn while picking a sweet berry.",
  },
  {
    id: "garden-creatures",
    name: "Garden Creatures",
    topicId: "garden-creatures",
    wordIds: [
      "butterfly",
      "ladybug",
      "bee",
      "worm",
      "snail",
      "ant",
      "caterpillar",
      "spider",
      "dragonfly",
      "grasshopper",
    ],
    description: "Learn about garden creatures.",
    story:
      "A bright butterfly fluttered near a spotted ladybug and a buzzing bee. In the damp soil, a worm moved past a slow snail and a busy ant. A green caterpillar nibbled on leaves while a spider spun its web. Overhead, a dragonfly darted across the lawn and a grasshopper jumped into the tall grass.",
  },
  {
    id: "garden-features",
    name: "Garden Features",
    topicId: "garden-features",
    wordIds: [
      "lawn",
      "flower-bed",
      "path",
      "fence",
      "gate",
      "greenhouse",
      "bird-feeder",
      "garden-shed",
      "birdbath",
      "compost-bin",
    ],
    description: "Learn about garden features.",
    story:
      "Maya walked across the green lawn to admire the colorful flower bed. She followed the stone path to the wooden fence and pushed open the iron gate. Near the glass greenhouse, a bird feeder hung above a stone birdbath. She stored her tools inside the garden shed and placed dry clippings into the compost bin.",
  },
];

export const GARDEN_VOCABULARY: VocabularyItem[] = [
  // Flowers
  {
    id: "rose",
    label: "Rose",
    phonetic: "roʊz",
    img: \`\${LOCAL_WORD_IMAGES}/garden/rose.webp\`,
    topic: "flowers",
    description: "A fragrant red or pink blossom on a prickly stalk.",
  },
  {
    id: "tulip",
    label: "Tulip",
    phonetic: "ˈtuːlɪp",
    img: \`\${LOCAL_WORD_IMAGES}/garden/tulip.webp\`,
    topic: "flowers",
    description: "A brightly colored cup-shaped spring blossom with smooth upright petals.",
  },
  {
    id: "sunflower",
    label: "Sunflower",
    phonetic: "ˈsʌnˌflaʊər",
    img: \`\${LOCAL_WORD_IMAGES}/garden/sunflower.webp\`,
    topic: "flowers",
    description: "A tall plant with a large golden head of yellow petals that faces the daylight.",
  },
  {
    id: "daisy",
    label: "Daisy",
    phonetic: "ˈdeɪzi",
    img: \`\${LOCAL_WORD_IMAGES}/garden/daisy.webp\`,
    topic: "flowers",
    description: "A small simple blossom with white petals surrounding a bright yellow center.",
  },
  {
    id: "lily",
    label: "Lily",
    phonetic: "ˈlɪli",
    img: \`\${LOCAL_WORD_IMAGES}/garden/lily.webp\`,
    topic: "flowers",
    description: "A graceful trumpet-shaped blossom with prominent stamens and sweet fragrance.",
  },
  {
    id: "daffodil",
    label: "Daffodil",
    phonetic: "ˈdæfədɪl",
    img: \`\${LOCAL_WORD_IMAGES}/garden/daffodil.webp\`,
    topic: "flowers",
    description: "A bright yellow trumpet-shaped spring bloom that emerges early in the season.",
  },
  {
    id: "violet",
    label: "Violet",
    phonetic: "ˈvaɪələt",
    img: \`\${LOCAL_WORD_IMAGES}/garden/violet.webp\`,
    topic: "flowers",
    description: "A small delicate purple blossom with five petals growing low in shaded spots.",
  },
  {
    id: "orchid",
    label: "Orchid",
    phonetic: "ˈɔːrkɪd",
    img: \`\${LOCAL_WORD_IMAGES}/garden/orchid.webp\`,
    topic: "flowers",
    description: "An exotic and intricate bloom with complex symmetry and vibrant patterns.",
  },
  {
    id: "carnation",
    label: "Carnation",
    phonetic: "kɑːrˈneɪʃən",
    img: \`\${LOCAL_WORD_IMAGES}/garden/carnation.webp\`,
    topic: "flowers",
    description: "A ruffled aromatic blossom with fringed petals popular in bouquets.",
  },
  {
    id: "lavender",
    label: "Lavender",
    phonetic: "ˈlævəndər",
    img: \`\${LOCAL_WORD_IMAGES}/garden/lavender.webp\`,
    topic: "flowers",
    description: "Fragrant pale purple flower spikes known for their calming herbal aroma.",
  },

  // Trees & Shrubs
  {
    id: "oak-tree",
    label: "Oak Tree",
    phonetic: "oʊk triː",
    img: \`\${LOCAL_WORD_IMAGES}/garden/oak-tree.webp\`,
    topic: "trees-shrubs",
    description: "A massive sturdy woodland perennial known for broad crowns and acorns.",
  },
  {
    id: "pine-tree",
    label: "Pine Tree",
    phonetic: "paɪn triː",
    img: \`\${LOCAL_WORD_IMAGES}/garden/pine-tree.webp\`,
    topic: "trees-shrubs",
    description: "An evergreen conifer with needle-like foliage and woody cones.",
  },
  {
    id: "apple-tree",
    label: "Apple Tree",
    phonetic: "ˈæpəl triː",
    img: \`\${LOCAL_WORD_IMAGES}/garden/apple-tree.webp\`,
    topic: "trees-shrubs",
    description: "A domestic orchard perennial bearing sweet round crisp orchard produce.",
  },
  {
    id: "cherry-tree",
    label: "Cherry Tree",
    phonetic: "ˈtʃɛri triː",
    img: \`\${LOCAL_WORD_IMAGES}/garden/cherry-tree.webp\`,
    topic: "trees-shrubs",
    description: "A blossom-bearing orchard plant producing clusters of small round stone fruits.",
  },
  {
    id: "palm-tree",
    label: "Palm Tree",
    phonetic: "pɑːm triː",
    img: \`\${LOCAL_WORD_IMAGES}/garden/palm-tree.webp\`,
    topic: "trees-shrubs",
    description: "A tall tropical unbranched growth with a crown of long feathered fronds.",
  },
  {
    id: "hedge",
    label: "Hedge",
    phonetic: "hɛdʒ",
    img: \`\${LOCAL_WORD_IMAGES}/garden/hedge.webp\`,
    topic: "trees-shrubs",
    description: "A dense continuous row of closely planted shrubs forming a boundary.",
  },
  {
    id: "bush",
    label: "Bush",
    phonetic: "bʊʃ",
    img: \`\${LOCAL_WORD_IMAGES}/garden/bush.webp\`,
    topic: "trees-shrubs",
    description: "A low dense woody perennial plant with many branches rising from the soil.",
  },
  {
    id: "ivy",
    label: "Ivy",
    phonetic: "ˈaɪvi",
    img: \`\${LOCAL_WORD_IMAGES}/garden/ivy.webp\`,
    topic: "trees-shrubs",
    description: "A climbing evergreen creeper with glossy lobed leaves clinging to walls.",
  },
  {
    id: "vine",
    label: "Vine",
    phonetic: "vaɪn",
    img: \`\${LOCAL_WORD_IMAGES}/garden/vine.webp\`,
    topic: "trees-shrubs",
    description: "A flexible climbing or creeping plant with long slender trailing stalks.",
  },
  {
    id: "fern",
    label: "Fern",
    phonetic: "fɜːrn",
    img: \`\${LOCAL_WORD_IMAGES}/garden/fern.webp\`,
    topic: "trees-shrubs",
    description: "A non-flowering leafy green plant with delicate feathery fronds.",
  },

  // Garden Tools
  {
    id: "shovel",
    label: "Shovel",
    phonetic: "ˈʃʌvəl",
    img: \`\${LOCAL_WORD_IMAGES}/garden/shovel.webp\`,
    topic: "garden-tools",
    description: "A broad-scooped tool with a long handle for moving piles of earth.",
  },
  {
    id: "rake",
    label: "Rake",
    phonetic: "reɪk",
    img: \`\${LOCAL_WORD_IMAGES}/garden/rake.webp\`,
    topic: "garden-tools",
    description: "A long-handled tool with a row of metal prongs for clearing fallen foliage.",
  },
  {
    id: "watering-can",
    label: "Watering Can",
    phonetic: "ˈwɔːtərɪŋ kæn",
    img: \`\${LOCAL_WORD_IMAGES}/garden/watering-can.webp\`,
    topic: "garden-tools",
    description: "A portable container with a spout and handle for showering potted plants.",
  },
  {
    id: "wheelbarrow",
    label: "Wheelbarrow",
    phonetic: "ˈwiːlˌbæroʊ",
    img: \`\${LOCAL_WORD_IMAGES}/garden/wheelbarrow.webp\`,
    topic: "garden-tools",
    description: "A single-tired hand cart with two handles for hauling heavy soil.",
  },
  {
    id: "hose",
    label: "Hose",
    phonetic: "hoʊz",
    img: \`\${LOCAL_WORD_IMAGES}/garden/hose.webp\`,
    topic: "garden-tools",
    description: "A flexible rubber tube for directing pressurized liquid to planting beds.",
  },
  {
    id: "garden-gloves",
    label: "Garden Gloves",
    phonetic: "ˈɡɑːrdən ɡlʌvz",
    img: \`\${LOCAL_WORD_IMAGES}/garden/garden-gloves.webp\`,
    topic: "garden-tools",
    description: "Padded protective hand coverings worn to prevent prickles and blisters.",
  },
  {
    id: "pruner",
    label: "Pruner",
    phonetic: "ˈpruːnər",
    img: \`\${LOCAL_WORD_IMAGES}/garden/pruner.webp\`,
    topic: "garden-tools",
    description: "Handheld spring-loaded shears used for snipping twigs and dead branches.",
  },
  {
    id: "trowel",
    label: "Trowel",
    phonetic: "ˈtraʊəl",
    img: \`\${LOCAL_WORD_IMAGES}/garden/trowel.webp\`,
    topic: "garden-tools",
    description: "A small handheld curved metal scoop for digging small planting holes.",
  },
  {
    id: "lawn-mower",
    label: "Lawn Mower",
    phonetic: "ˈlɔːn ˌmoʊər",
    img: \`\${LOCAL_WORD_IMAGES}/garden/lawn-mower.webp\`,
    topic: "garden-tools",
    description: "A wheeled machine with revolving blades for trimming turf to uniform height.",
  },
  {
    id: "spade",
    label: "Spade",
    phonetic: "speɪd",
    img: \`\${LOCAL_WORD_IMAGES}/garden/spade.webp\`,
    topic: "garden-tools",
    description: "A sharp flat-edged digging tool for edging turf and cutting through roots.",
  },
  {
    id: "pitchfork",
    label: "Pitchfork",
    phonetic: "ˈpɪtʃfɔːrk",
    img: \`\${LOCAL_WORD_IMAGES}/garden/pitchfork.webp\`,
    topic: "garden-tools",
    description: "A long-handled tool with four pointed tines for lifting compost and mulch.",
  },
  {
    id: "sprinkler",
    label: "Sprinkler",
    phonetic: "ˈsprɪŋklər",
    img: \`\${LOCAL_WORD_IMAGES}/garden/sprinkler.webp\`,
    topic: "garden-tools",
    description: "A rotating nozzle device that showers droplets across the turf.",
  },

  // Parts of a Plant
  {
    id: "root",
    label: "Root",
    phonetic: "ruːt",
    img: \`\${LOCAL_WORD_IMAGES}/garden/root.webp\`,
    topic: "parts-of-a-plant",
    description: "The underground anchor system that absorbs moisture and nutrients from soil.",
  },
  {
    id: "stem",
    label: "Stem",
    phonetic: "stɛm",
    img: \`\${LOCAL_WORD_IMAGES}/garden/stem.webp\`,
    topic: "parts-of-a-plant",
    description: "The central stalk that supports foliage and channels sap upward.",
  },
  {
    id: "leaf",
    label: "Leaf",
    phonetic: "liːf",
    img: \`\${LOCAL_WORD_IMAGES}/garden/leaf.webp\`,
    topic: "parts-of-a-plant",
    description: "A flat thin green outgrowth that converts sunlight into chemical energy.",
  },
  {
    id: "petal",
    label: "Petal",
    phonetic: "ˈpɛtəl",
    img: \`\${LOCAL_WORD_IMAGES}/garden/petal.webp\`,
    topic: "parts-of-a-plant",
    description: "One of the brightly colored segments that form the corolla of a blossom.",
  },
  {
    id: "branch",
    label: "Branch",
    phonetic: "bræntʃ",
    img: \`\${LOCAL_WORD_IMAGES}/garden/branch.webp\`,
    topic: "parts-of-a-plant",
    description: "A woody division extending outward from the main trunk of a woody perennial.",
  },
  {
    id: "bark",
    label: "Bark",
    phonetic: "bɑːrk",
    img: \`\${LOCAL_WORD_IMAGES}/garden/bark.webp\`,
    topic: "parts-of-a-plant",
    description: "The rugged protective outer layer covering the woody trunk of a timber giant.",
  },
  {
    id: "bud",
    label: "Bud",
    phonetic: "bʌd",
    img: \`\${LOCAL_WORD_IMAGES}/garden/bud.webp\`,
    topic: "parts-of-a-plant",
    description: "A small compact swelling containing an undeveloped blossom or shoot.",
  },
  {
    id: "seed",
    label: "Seed",
    phonetic: "siːd",
    img: \`\${LOCAL_WORD_IMAGES}/garden/seed.webp\`,
    topic: "parts-of-a-plant",
    description: "A small embryonic plant enclosed in a protective coat ready for germination.",
  },
  {
    id: "thorn",
    label: "Thorn",
    phonetic: "θɔːrn",
    img: \`\${LOCAL_WORD_IMAGES}/garden/thorn.webp\`,
    topic: "parts-of-a-plant",
    description: "A sharp stiff woody point protruding from the woody stalk of some shrubs.",
  },
  {
    id: "berry",
    label: "Berry",
    phonetic: "ˈbɛri",
    img: \`\${LOCAL_WORD_IMAGES}/garden/berry.webp\`,
    topic: "parts-of-a-plant",
    description: "A small fleshy juicy fruit containing pips and grown on wild brambles.",
  },

  // Garden Creatures
  {
    id: "butterfly",
    label: "Butterfly",
    phonetic: "ˈbʌtərflaɪ",
    img: \`\${LOCAL_WORD_IMAGES}/garden/butterfly.webp\`,
    topic: "garden-creatures",
    description: "A winged insect with colorful patterned wings that glides between blossoms.",
  },
  {
    id: "ladybug",
    label: "Ladybug",
    phonetic: "ˈleɪdibʌɡ",
    img: \`\${LOCAL_WORD_IMAGES}/garden/ladybug.webp\`,
    topic: "garden-creatures",
    description: "A small round red beetle with dark spots that feeds on garden pests.",
  },
  {
    id: "bee",
    label: "Bee",
    phonetic: "biː",
    img: \`\${LOCAL_WORD_IMAGES}/garden/bee.webp\`,
    topic: "garden-creatures",
    description: "A striped buzzing pollinator that gathers nectar and produces sweet honey.",
  },
  {
    id: "worm",
    label: "Worm",
    phonetic: "wɜːrm",
    img: \`\${LOCAL_WORD_IMAGES}/garden/worm.webp\`,
    topic: "garden-creatures",
    description: "A soft slender burrowing creature that aerates soil and creates rich compost.",
  },
  {
    id: "snail",
    label: "Snail",
    phonetic: "sneɪl",
    img: \`\${LOCAL_WORD_IMAGES}/garden/snail.webp\`,
    topic: "garden-creatures",
    description: "A slow-moving mollusk with a spiral protective shell on its back.",
  },
  {
    id: "ant",
    label: "Ant",
    phonetic: "ænt",
    img: \`\${LOCAL_WORD_IMAGES}/garden/ant.webp\`,
    topic: "garden-creatures",
    description: "A tiny industrious social crawler that works in colonies and builds mounds.",
  },
  {
    id: "caterpillar",
    label: "Caterpillar",
    phonetic: "ˈkætərˌpɪlər",
    img: \`\${LOCAL_WORD_IMAGES}/garden/caterpillar.webp\`,
    topic: "garden-creatures",
    description: "A soft segmented larval creature that chews foliage before metamorphosis.",
  },
  {
    id: "spider",
    label: "Spider",
    phonetic: "ˈspaɪdər",
    img: \`\${LOCAL_WORD_IMAGES}/garden/spider.webp\`,
    topic: "garden-creatures",
    description: "An eight-legged arachnid that spins intricate silken webs to catch prey.",
  },
  {
    id: "dragonfly",
    label: "Dragonfly",
    phonetic: "ˈdræɡənflaɪ",
    img: \`\${LOCAL_WORD_IMAGES}/garden/dragonfly.webp\`,
    topic: "garden-creatures",
    description: "A fast aerial insect with transparent wings and an iridescent slender body.",
  },
  {
    id: "grasshopper",
    label: "Grasshopper",
    phonetic: "ˈɡræsˌhɑːpər",
    img: \`\${LOCAL_WORD_IMAGES}/garden/grasshopper.webp\`,
    topic: "garden-creatures",
    description: "A leaping insect with powerful hind legs that makes a chirping sound in turf.",
  },

  // Garden Features
  {
    id: "lawn",
    label: "Lawn",
    phonetic: "lɔːn",
    img: \`\${LOCAL_WORD_IMAGES}/garden/lawn.webp\`,
    topic: "garden-features",
    description: "An area of manicured green turf maintained around a house or park.",
  },
  {
    id: "flower-bed",
    label: "Flower Bed",
    phonetic: "ˈflaʊər bɛd",
    img: \`\${LOCAL_WORD_IMAGES}/garden/flower-bed.webp\`,
    topic: "garden-features",
    description: "A prepared plot of cultivated soil dedicated to ornamental plantings.",
  },
  {
    id: "path",
    label: "Path",
    phonetic: "pæθ",
    img: \`\${LOCAL_WORD_IMAGES}/garden/path.webp\`,
    topic: "garden-features",
    description: "A designated walkway surfaced with gravel, stone, or stepping pavers.",
  },
  {
    id: "fence",
    label: "Fence",
    phonetic: "fɛns",
    img: \`\${LOCAL_WORD_IMAGES}/garden/fence.webp\`,
    topic: "garden-features",
    description: "An upright wooden or metal enclosure that marks an outdoor boundary.",
  },
  {
    id: "gate",
    label: "Gate",
    phonetic: "ɡeɪt",
    img: \`\${LOCAL_WORD_IMAGES}/garden/gate.webp\`,
    topic: "garden-features",
    description: "A movable hinged barrier in a boundary wall providing an entrance.",
  },
  {
    id: "greenhouse",
    label: "Greenhouse",
    phonetic: "ˈɡriːnhaʊs",
    img: \`\${LOCAL_WORD_IMAGES}/garden/greenhouse.webp\`,
    topic: "garden-features",
    description: "A glass structure that traps warmth for cultivating delicate seedlings.",
  },
  {
    id: "bird-feeder",
    label: "Bird Feeder",
    phonetic: "ˈbɜːrd ˌfiːdər",
    img: \`\${LOCAL_WORD_IMAGES}/garden/bird-feeder.webp\`,
    topic: "garden-features",
    description: "A hanging dispenser filled with grain to attract wild avian visitors.",
  },
  {
    id: "garden-shed",
    label: "Garden Shed",
    phonetic: "ˈɡɑːrdən ʃɛd",
    img: \`\${LOCAL_WORD_IMAGES}/garden/garden-shed.webp\`,
    topic: "garden-features",
    description: "A small wooden outbuilding used for storing outdoor equipment and potting pots.",
  },
  {
    id: "birdbath",
    label: "Birdbath",
    phonetic: "ˈbɜːrdbæθ",
    img: \`\${LOCAL_WORD_IMAGES}/garden/birdbath.webp\`,
    topic: "garden-features",
    description: "A shallow stone basin on a pedestal filled with water for feathered visitors.",
  },
  {
    id: "compost-bin",
    label: "Compost Bin",
    phonetic: "ˈkɑːmpoʊst bɪn",
    img: \`\${LOCAL_WORD_IMAGES}/garden/compost-bin.webp\`,
    topic: "garden-features",
    description: "A ventilated container where organic plant clippings decompose into fertilizer.",
  },
];
`;

const courseUnitEntry = `  garden: {
    id: "garden",
    name: "The Garden",
    description:
      "Explore real-life garden flowers, trees & shrubs, garden tools, plant parts, garden creatures, and features through 2D scene discovery, audio practice, recall matching, and sentence building.",
    heroImage: \`\${LOCAL_SCENE_IMAGES}/garden-hero.webp\`,
    topics: GARDEN_TOPICS,
    groups: GARDEN_GROUPS,
    vocabulary: GARDEN_VOCABULARY,
  },
};`;

// Insert gardenData before export const COURSE_UNITS
if (!content.includes('GARDEN_TOPICS')) {
  content = content.replace('export const COURSE_UNITS: Record<string, CourseUnit> = {', gardenData + '\nexport const COURSE_UNITS: Record<string, CourseUnit> = {');
  content = content.replace(/\n\s*farm:\s*\{[\s\S]*?\n\s*\},\n\};/, (match) => {
    return match.replace(/\n\};/, ',\n' + courseUnitEntry);
  });
  fs.writeFileSync(lessonsPath, content, 'utf8');
  console.log('Successfully updated lessons.ts with Garden unit data!');
} else {
  console.log('Garden unit data already in lessons.ts');
}
