const fs = require('node:fs');

const pipelinePath = 'output/illustrations/generation_batches_pipeline.json';
const pipeline = JSON.parse(fs.readFileSync(pipelinePath, 'utf8'));
const b1 = pipeline.batches?.[0];
if (!b1 || !Array.isArray(b1.items)) {
  throw new Error("The local illustration pipeline must contain a first batch with items.");
}

const cleanPrompts = {
  'kitchen-3-usage-scene-2': 'Bright, sparkling clean documentary food photography of a pristine white porcelain soup bowl on a spotless, sunlit light oak dining table. Clear, appetizing golden vegetable broth with finely diced carrots, celery, and fresh green herbs sits inside the gleaming clean bowl. Gentle fragrant steam rises from the soup. A polished silver spoon rests neatly beside the bowl on a crisp white folded napkin. In the soft-focus background, a clean clear glass tumbler of water and a modern white ceramic mug. Elegant, hygienic, appetizing, spotless modern kitchen dining atmosphere with natural daylight. Zero dirt, zero grime, completely clean tableware with zero text, zero brand logos, zero graphic overlays.',
  'kitchen-5-usage-scene-2': 'Bright, clean, modern kitchen photography of a clear glass cooking oil bottle with a polished stainless steel pour spout on a spotless white quartz countertop. Golden, crystal-clear olive oil sparkles inside the clean bottle under bright morning sunlight. Next to the bottle sit a clean porcelain salt cellar with pure white sea salt and a pristine clear glass sugar jar. A freshly washed, folded cotton tea towel rests neatly nearby. Spotless, hygienic, contemporary culinary setting. Completely clean unbranded glass with zero text, zero brand logos, zero graphic overlays.',
  'kitchen-5-usage-scene-3': 'Crisp, bright kitchen culinary photography of an elegant smooth wooden pepper grinder on a clean, light-colored wooden cutting board. Freshly cracked coarse black peppercorns rest neatly in a small culinary pinch, showing vivid texture and freshness. Nearby sit a clean glass container of white flour and a small sparkling cruet of vinegar. High-end, bright, appetizing, spotless kitchen environment with soft natural lighting. Zero clutter, completely hygienic and clean, zero text, zero brand logos, zero graphic overlays.',
  'kitchen-5-usage-scene-4': 'Bright, appetizing, sunny breakfast scene focusing on a clear glass jar of golden honey on a spotless kitchen breakfast bar. A clean wooden honey dipper rests across the jar with a clear, gleaming ribbon of amber honey dripping smoothly onto a slice of golden toasted sourdough bread on a clean ceramic plate. Beside it sits a fresh crisp green apple and a glass of freshly squeezed orange juice. Bright morning daylight, clean, mouth-watering, premium and hygienic. Zero text, zero brand logos, zero graphic overlays.',
  'living-room-1-usage-scene-1': 'Bright, elegant interior photography of a modern wooden coffee table centered in a clean, inviting living room. On the smooth, polished surface rests a ceramic cup of hot tea with a saucer and a glass of chilled water with a lemon slice on a cork coaster. In the background, a comfortable, neatly arranged sofa with soft cushions and an armchair. Clean natural daylight streaming through a large window, warm and tidy Scandinavian living room aesthetic. Zero clutter, zero text on blank decorative books, zero brand logos, zero graphic overlays.',
  'living-room-1-usage-scene-2': 'Clean, bright, stylish living room photography focusing on a plush upholstered round ottoman in warm neutral fabric, placed in front of a modern armchair. A neatly folded soft knitted throw blanket rests on the ottoman. Beside the chair is a clean minimal side table. Warm sunlight, tidy hardwood flooring, serene and cozy modern home aesthetic. Spotless and well-kept. Zero text, zero brand logos, zero graphic overlays.',
  'living-room-1-usage-scene-3': 'Bright, contemporary open-plan dining and living space featuring a smooth solid wood dining bench tucked neatly along one side of a light oak dining table. On the other side are clean minimalist dining chairs. The table is neatly set with clean ceramic plates and glasses. Bright airy daylight, clean Scandinavian interior design, spotless wooden floors. Zero text, zero brand logos, zero graphic overlays.',
  'living-room-2-usage-scene-3': 'Clean, close-up photograph of a sleek black TV remote control resting neatly on the smooth fabric armrest of a modern grey living room sofa. In the soft-focus background, a clean entertainment console with a compact soundbar speaker. Warm, cozy ambient living room lighting, tidy and dust-free environment. Blank remote with clean geometric buttons and no brand names or text labels, zero graphic overlays.',
  'living-room-3-usage-scene-1': 'Bright, tasteful living room corner featuring a tall, slender brass arched floor lamp with a clean linen drum shade standing beside a modern fabric sofa. The lamp casts a warm, soft ambient glow into the reading nook. A tidy small end table holds a clean table lamp nearby. Crisp, spotless, elegant contemporary interior design with soft natural lighting. Zero clutter, zero text, zero brand logos, zero graphic overlays.',
  'living-room-3-usage-scene-3': 'Clean, elegant home decor photograph of a minimalist matte brass candle holder holding a tall, unscented cream taper candle on a clean wooden sideboard or mantel. Warm subtle glow, with delicate decorative string lights softly twinkling in the background and a clean wooden picture frame with an abstract minimalist art print. Spotless, cozy, refined interior setting. Zero text, zero brand logos, zero graphic overlays.',
  'living-room-3-usage-scene-5': 'Bright, high-angle interior shot of a clean, beautifully woven geometric wool area rug centered on polished light hardwood flooring in a modern living room. The edge of a contemporary sofa and the legs of a wooden coffee table frame the rug naturally. Spotless, immaculate room with crisp daylight filtering through sheer curtains. Zero clutter, zero text, zero brand logos, zero graphic overlays.',
  'living-room-4-usage-scene-3': 'Crisp, bright daylight photograph of a contemporary ceramic flower vase filled with fresh, vibrant pastel flowers on a clean living room credenza. Beside the vase sits a clean standing photo frame, and a soft watercolor landscape painting hangs neatly on the wall above. Fresh, airy, spotless spring living room interior. Zero text, zero brand logos, zero graphic overlays.',
  'living-room-5-usage-scene-2': 'Clean, high-detail photograph of premium over-ear headphones resting neatly on a clean wooden side table beside a comfortable living room sofa. A smartphone connected to a neat white charging cable lies beside it on the table. Tidy, modern home living room with soft ambient light. Completely unbranded headphones and electronics with zero logos, zero text, zero graphic overlays.',
  'living-room-5-usage-scene-3': 'Cozy, bright living room scene of an adult peacefully reading a hardcover book with completely blank, unprinted linen cover, seated in a comfortable armchair by a sunlit window. A warm ceramic mug rests on a clean side table nearby. Serene, clean, dust-free home environment with potted green houseplant. Zero readable text on pages or cover, zero brand logos, zero graphic overlays.',
  'living-room-5-usage-scene-4': 'Warm, welcoming, spotless living room where two friends sit comfortably on a modern fabric sofa, engaged in a cheerful conversation over tea. Modest clothing with neat hijab for female figures. A clean coffee table with two ceramic tea mugs sits in front of them. Bright, airy, immaculate living room with natural daylight. Zero text, zero brand logos, zero graphic overlays.',
  'living-room-5-usage-scene-5': 'Serene, peaceful living room scene of an adult taking a quiet afternoon nap on a long, comfortable fabric sofa, resting their head on a soft clean pillow with a light neutral cotton blanket draped over them. Soft diffused daylight coming through sheer curtains, calm, spotless, tidy and restful home interior. Zero clutter, zero text, zero brand logos, zero graphic overlays.'
};

let count = 0;
b1.items.forEach(item => {
  if (cleanPrompts[item.sceneId]) {
    item.optimizedPrompt = cleanPrompts[item.sceneId];
    if (item.sceneId === 'kitchen-3-usage-scene-2') {
      item.status = 'PENDING_REDO_CLEAN';
    }
    count++;
  }
});

fs.writeFileSync(pipelinePath, JSON.stringify(pipeline, null, 2), 'utf8');
console.log(`Updated ${count} items with clean, pristine aesthetic prompts.`);
