// Generated by scripts/shard_learning_content.mjs. Do not edit.
import type { LexiconEntry } from "../lexiconCore";
export const entries: Record<string, LexiconEntry> = {
  "toilet-paper": {
    id: "toilet-paper",
    arabic: "ورق تواليت",
    sentences: [],
    collocations: ["use the toilet paper", "clean the toilet paper", "buy a toilet paper"],
    phrasalVerbs: [],
    partOfSpeech: "noun",
    audio: "/audio/en-US/toilet-paper.mp3",
    meanings: [
      {
        en: "Soft paper in a long roll used for cleaning oneself after using the toilet.",
        ar: "",
        sentences: [],
      },
    ],
  },
  plunger: {
    id: "plunger",
    arabic: "مكبس",
    sentences: [],
    collocations: ["use the plunger", "clean the plunger", "buy a plunger"],
    phrasalVerbs: [],
    partOfSpeech: "noun",
    audio: "/audio/en-US/plunger.mp3",
    meanings: [
      {
        en: "A tool with a rubber cup on a handle, used to unblock pipes.",
        ar: "",
        sentences: [],
      },
    ],
  },
  hanger: {
    id: "hanger",
    arabic: "شَمَّاعَةُ مَلابِس",
    partOfSpeech: "noun",
    phonetic: "ˈhæŋ.ər",
    pronunciationTip: "Soft 'ng' sound (/ŋ/) without a hard 'g' sound.",
    collocations: [
      "clothes hanger",
      "wooden hanger",
      "coat hanger",
      "hang on a hanger",
      "plastic hanger",
      "wardrobe hanger",
    ],
    phrasalVerbs: [
      {
        phrase: "hang up",
        meaning: "put clothes on a hanger in a closet",
        arabic: "يُعَلِّقُ المَلابِس",
        example: "Hang up your freshly ironed shirt on a wooden hanger.",
      },
      {
        phrase: "take off",
        meaning: "remove an item from a hanger",
        arabic: "يَنْزِعُ عَنِ الشَّمَّاعَة",
        example: "She took her favorite dress off the hanger.",
      },
    ],
    sentences: [
      {
        context: "Laundry Care",
        en: "Hang your jackets on sturdy wooden hangers to preserve their shoulder shape.",
        ar: "عَلِّقْ سُتْرَاتِكَ عَلَى شَمَّاعَاتٍ خَشَبِيَّةٍ مَتِينَةٍ لِلْحِفَاظِ عَلَى شَكْلِ الأَكْتَافِ.",
      },
      {
        context: "Closet Organization",
        en: "She bought a pack of non-slip velvet hangers for her silk blouses.",
        ar: "اشْتَرَتْ مَجْمُوعَةً مِنْ شَمَّاعَاتِ المَخْمَلِ المَانِعَةِ لِلاِنْزِلاقِ لِقُمْصَانِهَا الحَرِيرِيَّةِ.",
      },
      {
        context: "Wardrobe Tidiness",
        en: "Keep spare empty hangers neatly grouped at one side of the wardrobe.",
        ar: "احْتَفِظْ بِالشَّمَّاعَاتِ الفَارِغَةِ مُرَتَّبَةً فِي جَانِبٍ وَاحِدٍ مِنْ خِزَانَةِ المَلابِسِ.",
      },
    ],
    exampleSentence: "Hang your jackets on sturdy wooden hangers to preserve their shoulder shape.",
    exampleArabic:
      "عَلِّقْ سُتْرَاتِكَ عَلَى شَمَّاعَاتٍ خَشَبِيَّةٍ مَتِينَةٍ لِلْحِفَاظِ عَلَى شَكْلِ الأَكْتَافِ.",
  },
  "light-bulb": {
    id: "light-bulb",
    arabic: "مِصْبَاحٌ كَهْرَبَائِيّ (لَمْبَة)",
    partOfSpeech: "noun",
    phonetic: "ˈlaɪt ˌbʌlb",
    pronunciationTip: "Compound noun: 'LIGHT' (/laɪt/) + 'BULB' (/bʌlb/).",
    collocations: [
      "LED light bulb",
      "change the light bulb",
      "energy-saving light bulb",
      "burnt-out light bulb",
      "screw in a light bulb",
      "warm light bulb",
    ],
    phrasalVerbs: [
      {
        phrase: "screw in",
        meaning: "install a new light bulb by turning",
        arabic: "يَرْبِطُ / يُرَكِّبُ اللَّمْبَة",
        example: "Screw in a warm white LED bulb into the desk lamp.",
      },
      {
        phrase: "burn out",
        meaning: "stop functioning after long use",
        arabic: "تَحْتَرِقُ اللَّمْبَة",
        example: "The old hallway light bulb burned out after two years of use.",
      },
    ],
    sentences: [
      {
        context: "Home Maintenance",
        en: "He unscrewed the burnt-out incandescent bulb and installed an energy-efficient LED light bulb.",
        ar: "فَكَّ اللَّمْبَةَ القَدِيمَةَ التَّالِفَةَ وَرَكَّبَ مِصْبَاحَ LED مُوَفِّراً لِلطَّاقَةِ.",
      },
      {
        context: "Color Temperature",
        en: "Warm white light bulbs create a cozy, welcoming atmosphere in living spaces.",
        ar: "تَخْلُقُ المَصَابِيحُ ذَاتُ الضَّوْءِ الأَبْيَضِ الدَّافِئِ أَجْوَاءً مَنْزِلِيَّةً مُرِيحَةً وَجَذَّابَةً.",
      },
      {
        context: "Safety",
        en: "Always make sure the lamp is unplugged and cool before touching the light bulb.",
        ar: "تَأَكَّدْ دَائِماً مِنْ فَصْلِ المِصْبَاحِ وَبُرُودَتِهِ قَبْلَ لَمْسِ اللَّمْبَةِ الكَهْرَبَائِيَّةِ.",
      },
    ],
    exampleSentence:
      "He unscrewed the burnt-out incandescent bulb and installed an energy-efficient LED light bulb.",
    exampleArabic:
      "فَكَّ اللَّمْبَةَ القَدِيمَةَ التَّالِفَةَ وَرَكَّبَ مِصْبَاحَ LED مُوَفِّراً لِلطَّاقَةِ.",
  },
  sheet: {
    id: "sheet",
    arabic: "شَرْشَف / مِلايَةُ السَّرِير",
    partOfSpeech: "noun",
    phonetic: "ʃiːt",
    pronunciationTip: "Long 'ee' sound (/iː/). Distinct from 'sit'.",
    collocations: [
      "clean sheets",
      "change the sheets",
      "fitted sheet",
      "bed sheet",
      "cotton sheets",
      "fold the sheets",
    ],
    phrasalVerbs: [
      {
        phrase: "tuck in",
        meaning: "tuck the edges of a sheet under the mattress",
        arabic: "يُدْخِلُ أَطْرَافَ الشَّرْشَف",
        example: "Tuck in the bed sheet tightly under the mattress corners.",
      },
      {
        phrase: "strip off",
        meaning: "remove sheets for washing",
        arabic: "يَنْزِعُ المِلايَاتِ لِلْغَسِيل",
        example: "She stripped off the bed sheets to put them in the laundry.",
      },
    ],
    sentences: [
      {
        context: "Hygiene",
        en: "It feels wonderful to sleep on freshly washed cotton sheets.",
        ar: "مِنَ الرَّائِعِ جِدّاً النَّوْمُ عَلَى مِلايَاتٍ قُطْنِيَّةٍ مَغْسُولَةٍ حَدِيثاً.",
      },
      {
        context: "Household Chores",
        en: "They change the bed sheets every Sunday morning.",
        ar: "يَقُومُونَ بِتَغْيِيرِ شَرَاشِفِ السَّرِيرِ كُلَّ صَبَاحِ أَحَدٍ.",
      },
      {
        context: "Bed Making",
        en: "The elastic corners of the fitted sheet keep it firmly in place.",
        ar: "تُحَافِظُ الزَّوَايَا المَطَّاطِيَّةُ لِلشَّرْشَفِ عَلَى ثَبَاتِهِ فِي مَكَانِهِ.",
      },
    ],
    exampleSentence: "It feels wonderful to sleep on freshly washed cotton sheets.",
    exampleArabic:
      "مِنَ الرَّائِعِ جِدّاً النَّوْمُ عَلَى مِلايَاتٍ قُطْنِيَّةٍ مَغْسُولَةٍ حَدِيثاً.",
  },
  "bulletin-board": {
    id: "bulletin-board",
    arabic: "لَوْحَةُ إِعْلَانَات (لَوْحَةُ مَعْلُومَات)",
    partOfSpeech: "noun",
    phonetic: "ˈbʊlətɪn bɔːrd",
    pronunciationTip: "Pronounce 'BULL-uh-tin bord' (/ˈbʊl.ə.tɪn bɔːrd/).",
    collocations: [
      "cork bulletin board",
      "pin to a bulletin board",
      "classroom bulletin board",
      "announcements on the board",
      "colorful bulletin board",
    ],
    phrasalVerbs: [
      {
        phrase: "pin up",
        meaning: "attach announcements using push pins",
        arabic: "يُعَلِّقُ بِدَبَابِيسَ عَلَى اللَّوْحَة",
        example: "The teacher pinned up the weekly honor roll on the cork bulletin board.",
      },
    ],
    sentences: [
      {
        context: "School Announcements",
        en: "The teacher pinned student artwork and the weekly calendar on the cork bulletin board.",
        ar: "عَلَّقَ المُعَلِّمُ أَعْمَالَ الطُّلَّابِ الفَنِّيَّةَ وَالتَّقْوِيمَ الأُسْبُوعِيَّ عَلَى لَوْحَةِ الإِعْلَانَاتِ الفِلِّينِيَّةِ.",
      },
      {
        context: "Displaying Honors",
        en: "Important club meeting notices and field trip forms are posted on the main board.",
        ar: "تُنْشَرُ إِشْعَارَاتُ اجْتِمَاعَاتِ الأَنْشِطَةِ الهَامَّةِ وَنَمَاذِجُ الرِّحْلَاتِ عَلَى لَوْحَةِ المَعْلُومَاتِ الرَّئِيسِيَّةِ.",
      },
      {
        context: "Classroom Decor",
        en: "A decorative scalloped border frames the colorful classroom bulletin board.",
        ar: "يُحِيطُ إِطَارٌ مُزَخْرَفٌ مُتَمَوِّجٌ بِلَوْحَةِ إِعْلَانَاتِ الفَصْلِ المُلَوَّنَةِ.",
      },
    ],
    exampleSentence:
      "The teacher pinned student artwork and the weekly calendar on the cork bulletin board.",
    exampleArabic:
      "عَلَّقَ المُعَلِّمُ أَعْمَالَ الطُّلَّابِ الفَنِّيَّةَ وَالتَّقْوِيمَ الأُسْبُوعِيَّ عَلَى لَوْحَةِ الإِعْلَانَاتِ الفِلِّينِيَّةِ.",
  },
  focaccia: {
    id: "focaccia",
    arabic: "فُوكَاتْشْيَا (خُبْزٌ إِيطَالِيٌّ بِزَيْتِ الزَّيْتُونِ وَالأَعْشَاب)",
    partOfSpeech: "noun",
    phonetic: "foʊˈkɑːtʃə",
    pronunciationTip: "Pronounce 'foh-KAH-chuh' (/foʊˈkɑː.tʃə/).",
    collocations: [
      "rosemary focaccia",
      "olive oil focaccia",
      "dimpled focaccia",
      "sea salt focaccia",
      "warm focaccia",
    ],
    phrasalVerbs: [
      {
        phrase: "dimple with",
        meaning: "press fingertip indentations across dough",
        arabic: "يَصْنَعُ نُقَرًا بِأَصَابِعِهِ فِي العَجِين",
        example: "Dimple the dough with your fingertips to create wells for fragrant olive oil.",
      },
    ],
    sentences: [
      {
        context: "Italian Flatbread",
        en: "Golden Italian focaccia is baked in olive oil and topped with fresh rosemary sprigs and sea salt.",
        ar: "يُخْبَزُ خُبْزُ الفُوكَاتْشْيَا الإِيطَالِيُّ الذَّهَبِيُّ بِزَيْتِ الزَّيْتُونِ وَيُغَطَّى بِإِكْلِيلِ الجَبَلِ وَالمِلْحِ.",
      },
      {
        context: "Bakery Aroma",
        en: "The scent of garlic, cherry tomatoes, and warm olive oil wafted from fresh pans of focaccia.",
        ar: "فَاحَتْ رَائِحَةُ الثَّوْمِ وَالطَّمَاطِمِ وَزَيْتِ الزَّيْتُونِ مِنْ صَوَانِي الفُوكَاتْشْيَا الطَّازَجَةِ.",
      },
      {
        context: "Sandwich Base",
        en: "Sliced horizontally, thick herb focaccia makes a robust base for prosciutto and mozzarella panini.",
        ar: "عِنْدَ تَقْطِيعِهِ أُفُقِيًّا، يُشَكِّلُ خُبْزُ الفُوكَاتْشْيَا قَاعِدَةً قَوِيَّةً لِشَطَائِرِ البَانِينِي.",
      },
    ],
    exampleSentence:
      "Golden Italian focaccia is baked in olive oil and topped with fresh rosemary sprigs and sea salt.",
    exampleArabic:
      "يُخْبَزُ خُبْزُ الفُوكَاتْشْيَا الإِيطَالِيُّ الذَّهَبِيُّ بِزَيْتِ الزَّيْتُونِ وَيُغَطَّى بِإِكْلِيلِ الجَبَلِ وَالمِلْحِ.",
  },
  flatbread: {
    id: "flatbread",
    arabic: "خُبْزٌ مَفْرُود (خُبْزٌ مُسَطَّح)",
    partOfSpeech: "noun",
    phonetic: "ˈflætbrɛd",
    pronunciationTip: "Pronounce 'FLAT-bred' (/ˈflæt.brɛd/).",
    collocations: [
      "grilled flatbread",
      "warm flatbread",
      "artisan flatbread",
      "flatbread pizza",
      "seasoned flatbread",
    ],
    phrasalVerbs: [
      {
        phrase: "roll out",
        meaning: "flatten dough into thin disks",
        arabic: "يَفْرِدُ الخُبْزَ رَقِيقًا",
        example:
          "Roll out the unleavened dough on a floured surface before searing it on a hot griddle.",
      },
    ],
    sentences: [
      {
        context: "Global Staple",
        en: "Flatbread is a simple staple made of flour, water, and salt, baked quickly on a blistering hot surface.",
        ar: "الخُبْزُ المَفْرُودُ هُوَ طَعَامٌ أَسَاسِيٌّ بَسِيطٌ مِنَ الدَّقِيقِ وَالمَاءِ، يُخْبَزُ سَرِيعًا عَلَى صَاجٍ سَاخِنٍ.",
      },
      {
        context: "Appetizer Platter",
        en: "Warm grilled flatbread brushed with garlic oil accompanied the Mediterranean dip assortment.",
        ar: "رَافَقَ الخُبْزُ المُسَطَّحُ المَشْوِيُّ المَدْهُونُ بِزَيْتِ الثَّوْمِ تَشْكِيلَةَ المُقَبِّلَاتِ.",
      },
      {
        context: "Culinary Varieties",
        en: "From Indian naan to Mexican tortillas, flatbreads are essential to culinary traditions worldwide.",
        ar: "مِنْ خُبْزِ النَّان الهِنْدِيِّ إِلَى التُّورْتِيلَا، تُعَدُّ الأَخْبَازُ المُسَطَّحَةُ أَسَاسِيَّةً عَالَمِيًّا.",
      },
    ],
    exampleSentence:
      "Flatbread is a simple staple made of flour, water, and salt, baked quickly on a blistering hot surface.",
    exampleArabic:
      "الخُبْزُ المَفْرُودُ هُوَ طَعَامٌ أَسَاسِيٌّ بَسِيطٌ مِنَ الدَّقِيقِ وَالمَاءِ، يُخْبَزُ سَرِيعًا عَلَى صَاجٍ سَاخِنٍ.",
  },
  macaron: {
    id: "macaron",
    arabic: "مَاكَارُون (حَلْوَى اللَّوْزِ الفَرَنْسِيَّة)",
    partOfSpeech: "noun",
    phonetic: "ˌmækəˈrɒn",
    pronunciationTip: "Pronounce 'mak-uh-ROHN' (/ˌmæk.əˈrɒn/).",
    collocations: [
      "french macaron",
      "box of macarons",
      "colorful macarons",
      "pistachio macaron",
      "macaron shells",
    ],
    phrasalVerbs: [
      {
        phrase: "sandwich together",
        meaning: "press two delicate meringue shells with filling between",
        arabic: "يُلْصِقُ طَبَقَتَيْنِ مَعًا بِالحَشْوَة",
        example: "Sandwich together the matching pink almond shells with raspberry ganache.",
      },
    ],
    sentences: [
      {
        context: "Parisian Patisserie",
        en: "The boutique showcase presented rainbow rows of delicate almond macarons with ganache fillings.",
        ar: "عَرَضَتْ خِزَانَةُ المَتْجَرِ صُفُوفًا قَوْسِيَّةً مِنْ حَلْوَى المَاكَارُون الرَّقِيقَةِ بِاللَّوْزِ.",
      },
      {
        context: "Meringue Shells",
        en: "Mastering the smooth domed top and ruffled feet of a French macaron requires baking precision.",
        ar: "يَتَطَلَّبُ إِتْقَانُ السَّطْحِ المَصْقُولِ وَالحَوَافِّ لِلْمَاكَارُون الفَرَنْسِيِّ دِقَّةً فِي الخَبْزِ.",
      },
      {
        context: "Gift Box",
        en: "He gave her a luxury pastel gift box filled with salted caramel and lavender macarons.",
        ar: "قَدَّمَ لَهَا صُنْدُوقَ هَدَايَا فَاخِرًا مَلِيئًا بِمَاكَارُون الكَرَامِيلِ وَالخُزَامَى.",
      },
    ],
    exampleSentence:
      "The boutique showcase presented rainbow rows of delicate almond macarons with ganache fillings.",
    exampleArabic:
      "عَرَضَتْ خِزَانَةُ المَتْجَرِ صُفُوفًا قَوْسِيَّةً مِنْ حَلْوَى المَاكَارُون الرَّقِيقَةِ بِاللَّوْزِ.",
  },
  "flip-flops": {
    id: "flip-flops",
    arabic: "صَنْدَلُ الشَّاطِئ (خُفُّ الإِصْبَع / شِبْشِبُ البَحْر)",
    partOfSpeech: "noun",
    phonetic: "ˈflɪpflɒps",
    pronunciationTip: "Pronounce 'FLIP-flops' (/ˈflɪp.flɒps/).",
    collocations: [
      "pair of flip-flops",
      "rubber flip-flops",
      "wear flip-flops",
      "slip on flip-flops",
      "beach flip-flops",
    ],
    phrasalVerbs: [
      {
        phrase: "kick off",
        meaning: "remove open sandals easily with foot motion",
        arabic: "يَخْلَعُ الصَّنْدَلَ سَرِيعًا",
        example: "He kicked off his rubber flip-flops before running down into the ocean foam.",
      },
    ],
    sentences: [
      {
        context: "Beach Footwear",
        en: "Rubber flip-flops are the quintessential summer footwear for walking comfortably across sunbaked sands.",
        ar: "تُعَدُّ صَنَادِلُ الشَّاطِئِ المَطَّاطِيَّةُ الحِذَاءَ الصَّيْفِيَّ المِثَالِيَّ لِلْمَشْيِ عَلَى الرِّمَالِ السَّاخِنَةِ.",
      },
      {
        context: "Boardwalk Stroll",
        en: "She slipped into a bright pair of waterproof flip-flops to stroll from the changing room to the shore.",
        ar: "ارْتَدَتْ صَنْدَلَ شَاطِئٍ مُقَاوِمًا لِلْمَاءِ لِتَسِيرَ مِنْ غُرْفَةِ تَبْدِيلِ المَلَابِسِ إِلَى الشَّاطِئِ.",
      },
    ],
    exampleSentence:
      "Rubber flip-flops are the quintessential summer footwear for walking comfortably across sunbaked sands.",
    exampleArabic:
      "تُعَدُّ صَنَادِلُ الشَّاطِئِ المَطَّاطِيَّةُ الحِذَاءَ الصَّيْفِيَّ المِثَالِيَّ لِلْمَشْيِ عَلَى الرِّمَالِ السَّاخِنَةِ.",
  },
  backstroke: {
    id: "backstroke",
    arabic: "سِبَاحَةُ الظَّهْر (نَمَطُ السِّبَاحَةِ عَلَى الظَّهْر)",
    partOfSpeech: "noun",
    phonetic: "ˈbækstroʊk",
    pronunciationTip: "Pronounce 'BAK-strohk'.",
    collocations: ["swim backstroke", "backstroke race", "backstroke technique"],
    phrasalVerbs: [
      {
        phrase: "glide through",
        meaning: "move backwards across pool surface",
        arabic: "يَسْبَحُ عَلَى الظَّهْر",
        example: "He glided through the water doing the backstroke.",
      },
    ],
    sentences: [
      {
        context: "Swim Stroke",
        en: "In the backstroke, the swimmer stays on their back and alternates continuous arm circles.",
        ar: "فِي سِبَاحَةِ الظَّهْرِ، يَسْتَلْقِي السَّبَّاحُ عَلَى ظَهْرِهِ وَيُحَرِّكُ ذِرَاعَيْهِ بِتَتَابُعٍ.",
      },
      {
        context: "Flags",
        en: "Overhead backstroke flags warn swimmers when they are five meters from the wall.",
        ar: "تُحَذِّرُ أَعْلَامُ سِبَاحَةِ الظَّهْرِ السَّبَّاحِينَ عِنْدَ اقْتِرَابِهِمْ ٥ أَمْتَارٍ مِنَ الحَائِطِ.",
      },
      {
        context: "Breathing",
        en: "Backstroke allows easy breathing since the swimmer's face remains out of the water.",
        ar: "تُتِيحُ سِبَاحَةُ الظَّهْرِ تَنَفُّسًا سَهْلًا لِبَقَاءِ الوَجْهِ خَارِجَ المَاءِ.",
      },
    ],
    exampleSentence:
      "In the backstroke, the swimmer stays on their back and alternates continuous arm circles.",
    exampleArabic:
      "فِي سِبَاحَةِ الظَّهْرِ، يَسْتَلْقِي السَّبَّاحُ عَلَى ظَهْرِهِ وَيُحَرِّكُ ذِرَاعَيْهِ بِتَتَابُعٍ.",
  },
  doctor: {
    id: "doctor",
    arabic: "طَبِيب (طَبِيبٌ مُعَالِج)",
    partOfSpeech: "noun",
    phonetic: "ˈdɒktər",
    pronunciationTip: "Pronounce 'DOK-ter' (/ˈdɒk.tər/).",
    collocations: ["see a doctor", "medical doctor", "family doctor", "consult a doctor"],
    phrasalVerbs: [
      {
        phrase: "look after",
        meaning: "provide medical care to patients",
        arabic: "يَعْتَنِي بِالمَرِيض",
        example: "The doctor looked after her recovering patients.",
      },
    ],
    sentences: [
      {
        context: "Medical Care",
        en: "The family doctor examined the patient carefully and answered all questions.",
        ar: "فَحَصَ طَبِيبُ الأُسْرَةِ المَرِيضَ بِعِنَايَةٍ وَأَجَابَ عَنْ جَمِيعِ الأَسْئِلَةِ.",
      },
      {
        context: "Consultation",
        en: "You should see a doctor if your high fever persists for more than two days.",
        ar: "يَجِبُ عَلَيْكَ اسْتِشَارَةُ طَبِيبٍ إِذَا اسْتَمَرَّتِ الحُمَّى لِأَكْثَرَ مِنْ يَوْمَيْنِ.",
      },
      {
        context: "Hospital Ward",
        en: "Doctors and nurses conducted their morning rounds together across the ward.",
        ar: "أَجْرَى الأَطِبَّاءُ وَالمُمَرِّضُونَ جَوْلَتَهُمُ الصَّبَاحِيَّةَ فِي جَنَاحِ المَسْتَشْفَى.",
      },
    ],
    exampleSentence: "The family doctor examined the patient carefully and answered all questions.",
    exampleArabic:
      "فَحَصَ طَبِيبُ الأُسْرَةِ المَرِيضَ بِعِنَايَةٍ وَأَجَابَ عَنْ جَمِيعِ الأَسْئِلَةِ.",
  },
  stitches: {
    id: "stitches",
    arabic: "غُرَزٌ جِرَاحِيَّة (خِيَاطَةُ الجُرُوحِ الطِّبِّيَّة)",
    partOfSpeech: "noun",
    phonetic: "ˈstɪtʃɪz",
    pronunciationTip: "Pronounce 'STICH-iz' (/ˈstɪtʃ.ɪz/).",
    collocations: ["get stitches", "remove stitches", "dissolvable stitches", "surgical stitches"],
    phrasalVerbs: [
      {
        phrase: "sew up with",
        meaning: "close wound edges using sterile surgical thread",
        arabic: "يُخَيِّطُ الجُرْحَ بِالغُرَز",
        example: "The surgeon sewed up the deep laceration with stitches.",
      },
    ],
    sentences: [
      {
        context: "Wound Closure",
        en: "The emergency room doctor placed five neat stitches to close the deep cut on his forehead.",
        ar: "وَضَعَ طَبِيبُ الطَّوَارِئِ ٥ غُرَزٍ جِرَاحِيَّةٍ لِإِغْلَاقِ الجُرْحِ العَمِيقِ فِي الجَبِينِ.",
      },
      {
        context: "Dissolvable Sutures",
        en: "Many internal surgical procedures use dissolvable stitches that absorb naturally over time.",
        ar: "تَسْتَخْدِمُ الجِرَاحَاتُ الدَّاخِلِيَّةُ غُرَزًا قَابِلَةً لِلذَّوَبَانِ تَمْتَصُّهَا الأَنْسِجَةُ.",
      },
      {
        context: "Removal",
        en: "After ten days of clean healing, the nurse removed the external stitches smoothly.",
        ar: "بَعْدَ ١٠ أَيَّامٍ مِنَ الِالْتِئَامِ، أَزَالَتِ المُمَرِّضَةُ الغُرَزَ الخَارِجِيَّةَ بِسَلَاسَةٍ.",
      },
    ],
    exampleSentence:
      "The emergency room doctor placed five neat stitches to close the deep cut on his forehead.",
    exampleArabic:
      "وَضَعَ طَبِيبُ الطَّوَارِئِ ٥ غُرَزٍ جِرَاحِيَّةٍ لِإِغْلَاقِ الجُرْحِ العَمِيقِ فِي الجَبِينِ.",
  },
  menu: {
    id: "menu",
    arabic: "قَائِمَةُ الطَّعَام (مِنْيُو / لَائِحَةُ المَأْكُولَات)",
    partOfSpeech: "noun",
    phonetic: "ˈmɛnjuː",
    pronunciationTip: "Pronounce 'MEN-yoo'.",
    collocations: ["dessert menu", "tasting menu", "dinner menu"],
    phrasalVerbs: [
      {
        phrase: "browse through",
        meaning: "read through food offerings leisurely",
        arabic: "يَتَصَفَّحُ قَائِمَةَ الطَّعَام",
        example: "We browsed through the leather-bound menu.",
      },
    ],
    sentences: [
      {
        context: "Ordering",
        en: "The server handed each guest a laminated dinner menu.",
        ar: "سَلَّمَ النَّادِلُ كُلَّ ضَيْفٍ قَائِمَةَ طَعَامٍ مَغَلَّفَةً.",
      },
      {
        context: "Dietary",
        en: "The restaurant menu clearly labeled vegan and gluten-free items.",
        ar: "حَدَّدَتْ قَائِمَةُ المَطْعَمِ الخِيَارَاتِ النَّبَاتِيَّةَ بِوُضُوحٍ.",
      },
      {
        context: "Tasting Menu",
        en: "The chef designed an exquisite five-course tasting menu.",
        ar: "صَمَّمَ الطَّاهِي قَائِمَةَ تَذَوُّقٍ رَائِعَةً مِنْ خَمْسَةِ أَطْبَاقٍ.",
      },
    ],
    exampleSentence: "The server handed each guest a laminated dinner menu.",
    exampleArabic: "سَلَّمَ النَّادِلُ كُلَّ ضَيْفٍ قَائِمَةَ طَعَامٍ مَغَلَّفَةً.",
  },
  seasoning: {
    id: "seasoning",
    arabic: "تَوَابِل (بُهَارَاتٌ وَمُنَكِّهَاتُ الطَّعَام)",
    partOfSpeech: "noun",
    phonetic: "ˈsiːzənɪŋ",
    pronunciationTip: "Pronounce 'SEE-zən-ing' (/ˈsiː.zən.ɪŋ/).",
    collocations: ["seasoning blend", "add seasoning", "adjust the seasoning"],
    phrasalVerbs: [
      {
        phrase: "season with",
        meaning: "enhance food flavor with herbs and spices",
        arabic: "يُتَبِّلُ بِالتَّوَابِل",
        example: "The cook seasoned the vegetables with garlic powder and sea salt.",
      },
    ],
    sentences: [
      {
        context: "Flavor Enhancement",
        en: "The chef tasted the broth and adjusted the seasoning with a dash of sea salt.",
        ar: "تَذَوَّقَ الطَّاهِي المَرَقَ وَعَدَّلَ التَّوَابِلَ بِرَشَّةٍ مِنْ مِلْحِ البَحْرِ.",
      },
      {
        context: "Spice Blend",
        en: "A balanced seasoning of crushed pepper and thyme brought the roast to life.",
        ar: "أَبْرَزَتْ تَوِيفَةُ التَّوَابِلِ مِنَ الفُلْفُلِ وَالأَعْشَابِ نَكْهَةَ اللَّحْمِ المَشْوِيِّ.",
      },
      {
        context: "Kitchen Technique",
        en: "Proper seasoning during cooking ensures every layer of the dish is flavorful.",
        ar: "يَضْمَنُ التَّتْبِيلُ الصَّحِيحُ أَثْنَاءَ الطَّبْخِ اكْتِسَابَ كُلِّ طَبَقَةٍ نَكْهَةً مُمَيَّزَةً.",
      },
    ],
    exampleSentence:
      "The chef tasted the broth and adjusted the seasoning with a dash of sea salt.",
    exampleArabic:
      "تَذَوَّقَ الطَّاهِي المَرَقَ وَعَدَّلَ التَّوَابِلَ بِرَشَّةٍ مِنْ مِلْحِ البَحْرِ.",
  },
  "train-conductor": {
    id: "train-conductor",
    arabic: "مُحَصِّلُ التَّذَاكِر",
    partOfSpeech: "noun",
    collocations: ["use regularly", "check carefully", "keep handy"],
    sentences: [
      {
        context: "Fare Inspection",
        en: "The uniformed official punched a hole in each passenger's ticket.",
        ar: "ثَقَبَ المَسْؤُولُ ذُو الزِّيِّ الرَّسْمِيِّ تِذْكَرَةَ كُلِّ رَاكِب.",
      },
      {
        context: "Passenger Safety",
        en: "The rail manager blew the whistle to signal the train departure.",
        ar: "أَطْلَقَ مَسْؤُولُ القِطَارِ الصَّفَّارَةَ لِلإِعْلَانِ عَنْ مُغَادَرَةِ القِطَار.",
      },
      {
        context: "Route Guidance",
        en: "The conductor answered travel questions about the upcoming junction.",
        ar: "أَجَابَ المُحَصِّلُ عَنْ أَسْئِلَةِ السَّفَرِ حَوْلَ التَّقَاطُعِ القَادِم.",
      },
    ],
    exampleSentence: "The uniformed official punched a hole in each passenger's ticket.",
    exampleArabic: "ثَقَبَ المَسْؤُولُ ذُو الزِّيِّ الرَّسْمِيِّ تِذْكَرَةَ كُلِّ رَاكِب.",
  },
};
