// Generated by scripts/shard_learning_content.mjs. Do not edit.
import type { LexiconEntry } from "../lexiconCore";
export const entries: Record<string, LexiconEntry> = {
  colander: {
    id: "colander",
    arabic: "مِصْفَاة (مِصْفَاةُ مَعْكَرُونَة)",
    partOfSpeech: "noun",
    phonetic: "ˈkɑː.lən.dər",
    pronunciationTip: "Three syllables: 'COL-an-der' (/ˈkɑː.lən.dər/).",
    collocations: [
      "drain in a colander",
      "pasta colander",
      "rinse in a colander",
      "stainless steel colander",
      "mesh colander",
      "colander in the sink",
    ],
    phrasalVerbs: [
      {
        phrase: "drain off",
        meaning: "pour off water using a colander",
        arabic: "يُصَفِّي المَاء",
        example: "Drain off the boiling cooking water through the colander.",
      },
      {
        phrase: "rinse out",
        meaning: "wash fruit with water in a colander",
        arabic: "يَشْطُفُ",
        example: "Rinse out the fresh berries under cold tap water in the colander.",
      },
    ],
    sentences: [
      {
        context: "Cooking Pasta",
        en: "He poured the cooked spaghetti into a stainless steel colander in the sink to drain.",
        ar: "سَكَبَ المَعْكَرُونَةَ المَطْبُوخَةَ فِي مِصْفَاةِ سْتَانْلِس دَاخِلَ الحَوْضِ لِتَصْفِيَتِهَا.",
      },
      {
        context: "Washing Produce",
        en: "Wash fresh spinach and grapes thoroughly under cold running water in the colander.",
        ar: "اغْسِلِ السَّبَانِخَ وَالعِنَبَ جَيِّداً تَحْتَ مَاءِ الصَّنْبُورِ البَارِدِ فِي المِصْفَاةِ.",
      },
      {
        context: "Storage",
        en: "Rest the colander over a large bowl to collect drained vegetable broth.",
        ar: "ضَعِ المِصْفَاةَ فَوْقَ وِعَاءٍ كَبِيرٍ لِتَجْمِيعِ مَرَقِ الخُضَارِ المُصَفَّى.",
      },
    ],
    exampleSentence:
      "He poured the cooked spaghetti into a stainless steel colander in the sink to drain.",
    exampleArabic:
      "سَكَبَ المَعْكَرُونَةَ المَطْبُوخَةَ فِي مِصْفَاةِ سْتَانْلِس دَاخِلَ الحَوْضِ لِتَصْفِيَتِهَا.",
  },
  painting: {
    id: "painting",
    arabic: "لَوْحَةٌ فَنِّيَّة (رَسْمَة)",
    partOfSpeech: "noun",
    phonetic: "ˈpeɪn.tɪŋ",
    pronunciationTip: "Two syllables: 'PAINT-ing' (/ˈpeɪn.tɪŋ/).",
    collocations: [
      "oil painting",
      "framed painting",
      "hang a painting",
      "landscape painting",
      "abstract painting",
      "original painting",
    ],
    phrasalVerbs: [
      {
        phrase: "hang up",
        meaning: "mount an art piece on a wall",
        arabic: "يُعَلِّقُ اللَّوْحَة",
        example: "They hung up the original oil painting above the living room sofa.",
      },
    ],
    sentences: [
      {
        context: "Art in the Home",
        en: "A vibrant abstract oil painting in shades of blue and gold brightens the white wall.",
        ar: "تُضْفِي لَوْحَةٌ زَيْتِيَّةٌ تَجْرِيدِيَّةٌ بَدِيعَةٌ بِدَرَجَاتِ الأَزْرَقِ وَالذَّهَبِ حَيَوِيَّةً عَلَى الجِدَارِ.",
      },
      {
        context: "Gallery Exhibition",
        en: "The art gallery displayed famous landscape paintings by local Impressionist artists.",
        ar: "عَرَضَتْ صَالَةُ الفَنِّ لَوْحَاتٍ طَبِيعِيَّةً شَهِيرَةً لِفَنَّانِينَ تَأَثُّرِيِّينَ مَحَلِّيِّينَ.",
      },
      {
        context: "Lighting Art",
        en: "Install a dedicated brass picture light above the painting to highlight its brushstrokes.",
        ar: "ثَبِّتْ إِضَاءَةً نُحَاسِيَّةً مُخَصَّصَةً فَوْقَ اللَّوْحَةِ لِإِبْرَازِ تَفَاصِيلِ رَسْمِهَا.",
      },
    ],
    exampleSentence:
      "A vibrant abstract oil painting in shades of blue and gold brightens the white wall.",
    exampleArabic:
      "تُضْفِي لَوْحَةٌ زَيْتِيَّةٌ تَجْرِيدِيَّةٌ بَدِيعَةٌ بِدَرَجَاتِ الأَزْرَقِ وَالذَّهَبِ حَيَوِيَّةً عَلَى الجِدَارِ.",
  },
  rug: {
    id: "rug",
    arabic: "سَجَّادَةٌ صَغِيرَة (مَشَّايَة)",
    partOfSpeech: "noun",
    phonetic: "rʌɡ",
    pronunciationTip: "Short 'u' vowel sound /ʌ/ as in 'hug', 'mug', or 'cup'.",
    collocations: [
      "area rug",
      "soft rug",
      "bedside rug",
      "woven rug",
      "step on the rug",
      "wool rug",
    ],
    phrasalVerbs: [
      {
        phrase: "lay down",
        meaning: "place a rug flat on the floor",
        arabic: "يَفْرِشُ سَجَّادَة",
        example: "They laid down a soft wool rug beside the bed.",
      },
      {
        phrase: "roll up",
        meaning: "roll a rug for moving or cleaning",
        arabic: "يَطْوِي / يَلُفُّ السَّجَّادَة",
        example: "Roll up the rug before painting the bedroom walls.",
      },
    ],
    sentences: [
      {
        context: "Morning Comfort",
        en: "A soft fluffy rug keeps your bare feet warm when stepping out of bed.",
        ar: "تُحَافِظُ السَّجَّادَةُ الصَّغِيرَةُ النَّاعِمَةُ عَلَى دِفْءِ قَدَمَيْكَ عِنْدَ النُّزُولِ مِنَ السَّرِيرِ.",
      },
      {
        context: "Room Accents",
        en: "The colorful Persian rug adds character and warmth to the wooden floor.",
        ar: "تُضِيفُ السَّجَّادَةُ الفَارِسِيَّةُ المُلَوَّنَةُ طَابَعاً مُمَيَّزاً وَدِفْئاً عَلَى الأَرْضِيَّةِ الخَشَبِيَّةِ.",
      },
      {
        context: "Cleaning",
        en: "She shook the dust out of the bedside rug on the balcony.",
        ar: "نَفَضَتِ الغُبَارَ عَنْ سَجَّادَةِ جَانِبِ السَّرِيرِ فِي الشُّرْفَةِ.",
      },
    ],
    exampleSentence: "A soft fluffy rug keeps your bare feet warm when stepping out of bed.",
    exampleArabic:
      "تُحَافِظُ السَّجَّادَةُ الصَّغِيرَةُ النَّاعِمَةُ عَلَى دِفْءِ قَدَمَيْكَ عِنْدَ النُّزُولِ مِنَ السَّرِيرِ.",
  },
  "wall-clock": {
    id: "wall-clock",
    arabic: "سَاعَةُ حَائِط",
    partOfSpeech: "noun",
    phonetic: "ˈwɔːl ˌklɑːk",
    pronunciationTip: "Compound noun: 'WALL' (/wɔːl/) + 'CLOCK' (/klɑːk/).",
    collocations: [
      "large wall clock",
      "wooden wall clock",
      "hang a wall clock",
      "check the wall clock",
      "silent wall clock",
      "modern wall clock",
    ],
    phrasalVerbs: [
      {
        phrase: "hang up",
        meaning: "mount clock on wall",
        arabic: "يُعَلِّقُ السَّاعَةَ عَلَى الجِدَار",
        example: "Hang up the decorative wall clock above the fireplace mantel.",
      },
    ],
    sentences: [
      {
        context: "Living Room Focal Point",
        en: "A large vintage industrial wall clock hangs prominently above the fireplace mantel.",
        ar: "تُعَلَّقُ سَاعَةُ حَائِطٍ كَبِيرَةٌ كِلاسِيكِيَّةٌ بِشَكْلٍ بَارِزٍ فَوْقَ رَفِّ المِدْفَأَةِ.",
      },
      {
        context: "Quiet Operation",
        en: "She chose a silent quartz wall clock so the continuous ticking wouldn't distract her studying.",
        ar: "اخْتَارَتْ سَاعَةَ حَائِطٍ صَامِتَةً حَتَّى لا تُشَتِّتَ دَقَّاتُهَا تَرْكِيزَهَا فِي الدِّرَاسَةِ.",
      },
      {
        context: "Time Check",
        en: "He glanced quickly at the wall clock to see if dinner was ready.",
        ar: "أَلْقَى نَظْرَةً سَرِيعَةً عَلَى سَاعَةِ الحَائِطِ لِمَعْرِفَةِ مَا إِذَا كَانَ العَشَاءُ جَاهِزاً.",
      },
    ],
    exampleSentence:
      "A large vintage industrial wall clock hangs prominently above the fireplace mantel.",
    exampleArabic:
      "تُعَلَّقُ سَاعَةُ حَائِطٍ كَبِيرَةٌ كِلاسِيكِيَّةٌ بِشَكْلٍ بَارِزٍ فَوْقَ رَفِّ المِدْفَأَةِ.",
  },
  "bird-feeder": {
    id: "bird-feeder",
    arabic: "مِطْعَمُ الطُّيُور (مِعْلَفَةُ الطُّيُور)",
    partOfSpeech: "noun",
    phonetic: "ˈbɜːrd ˌfiːdər",
    pronunciationTip: "Compound: 'BIRD fee-der' (/ˈbɜːrd ˌfiː.dər/).",
    collocations: [
      "hanging bird feeder",
      "wooden bird feeder",
      "fill the bird feeder",
      "seed bird feeder",
      "suet bird feeder",
      "clean the bird feeder",
    ],
    phrasalVerbs: [
      {
        phrase: "flock to",
        meaning: "gather in large numbers around",
        arabic: "يَتَوَافَدُ إِلَى",
        example: "Wild finches and chickadees flock to the seed bird feeder every morning.",
      },
    ],
    sentences: [
      {
        context: "Attracting Avian Life",
        en: "A cedar bird feeder hanging from the oak tree drew colorful goldfinches and cardinals.",
        ar: "جَذَبَ مِطْعَمُ طُيُورٍ خَشَبِيٌّ مُعَلَّقٌ عَلَى شَجَرَةِ البَلُّوطِ طُيُوراً مُلَوَّنَةً.",
      },
      {
        context: "Winter Sustenance",
        en: "Keep the bird feeder generously stocked with sunflower seeds during freezing weather.",
        ar: "احْرِصْ عَلَى مَلْءِ مِطْعَمِ الطُّيُورِ بِبُذُورِ عَبَّادِ الشَّمْسِ خِلالَ البَرْدِ الشَّدِيدِ.",
      },
      {
        context: "Observation Window",
        en: "We placed the bird feeder outside the kitchen window to watch birds over breakfast.",
        ar: "وَضَعْنَا مِطْعَمَ الطُّيُورِ خَارِجَ نَافِذَةِ المَطْبَخِ لِمُشَاهَدَةِ الطُّيُورِ أَثْنَاءَ الفُطُورِ.",
      },
    ],
    exampleSentence: "Two blue jays squabbled over the perch on the wooden bird feeder.",
    exampleArabic:
      "تَنَازَعَ طَائِرَانِ زَرْقَاوَانِ عَلَى مَكَانِ الوُقُوفِ فِي مِطْعَمِ الطُّيُورِ الخَشَبِيِّ.",
  },
  sand: {
    id: "sand",
    arabic: "رَمْل (رِمَالُ الشَّاطِئ)",
    partOfSpeech: "noun",
    phonetic: "sænd",
    pronunciationTip: "Short 'a' sound /æ/: 'SAND' (/sænd/).",
    collocations: [
      "golden sand",
      "soft warm sand",
      "white sand beach",
      "walk on the sand",
      "grain of sand",
    ],
    phrasalVerbs: [
      {
        phrase: "sink into",
        meaning: "press down deeply into soft loose granules",
        arabic: "يَغُوصُ فِي الرِّمَالِ النَّاعِمَة",
        example: "Our bare feet sank into the soft warm sand as we strolled by the water.",
      },
    ],
    sentences: [
      {
        context: "Beach Landscape",
        en: "Children dug deep moats and sculpted towers in the damp golden sand along the coast.",
        ar: "حَفَرَ الأَطْفَالُ خَنَادِقَ عَمِيقَةً وَنَحَتُوا أَبْرَاجًا فِي الرِّمَالِ الذَّهَبِيَّةِ الرَّطْبَةِ.",
      },
      {
        context: "Sunny Afternoon",
        en: "The midday sun heated the dry powdery sand until walking barefoot required quick steps.",
        ar: "سَخَّنَتْ شَمْسُ الظَّهِيرَةِ الرِّمَالَ النَّاعِمَةَ الجَافَّةَ حَتَّى تَطَلَّبَ المَشْيُ حَافِيًا خُطُوَاتٍ سَرِيعَةً.",
      },
      {
        context: "Coastal Geology",
        en: "Ocean waves continually crush seashells and mineral rocks into fine shoreline sand.",
        ar: "تَسْحَقُ أَمْوَاجُ المُحِيطِ أَصْدَافَ البَحْرِ وَالصُّخُورَ بِاسْتِمْرَارٍ لِتُحَوِّلَهَا إِلَى رِمَالٍ شَاطِئِيَّةٍ.",
      },
    ],
    exampleSentence:
      "Children dug deep moats and sculpted towers in the damp golden sand along the coast.",
    exampleArabic:
      "حَفَرَ الأَطْفَالُ خَنَادِقَ عَمِيقَةً وَنَحَتُوا أَبْرَاجًا فِي الرِّمَالِ الذَّهَبِيَّةِ الرَّطْبَةِ.",
  },
  flush: {
    id: "flush",
    arabic: "شَطْفُ المِرْحَاض (سَحْبُ السَّيْفُون)",
    partOfSpeech: "verb",
    phonetic: "flʌʃ",
    pronunciationTip: "Short 'u' sound /ʌ/ ending in 'sh' (/ʃ/): 'FLUSH' (/flʌʃ/).",
    collocations: [
      "flush the toilet",
      "dual flush button",
      "automatic flush",
      "press the lever to flush",
      "flush with water",
      "remember to flush",
    ],
    phrasalVerbs: [
      {
        phrase: "flush away",
        meaning: "cleanse ceramic bowl by discharging water",
        arabic: "يَشْطُفُ وَيُصَرِّف",
        example: "Push down the chrome handle to flush away waste instantly.",
      },
    ],
    sentences: [
      {
        context: "Restroom Etiquette",
        en: "Remember to flush the toilet after every use to maintain cleanliness.",
        ar: "تَذَكَّرْ شَطْفَ المِرْحَاضِ بَعْدَ كُلِّ اسْتِخْدَامٍ لِلْحِفَاظِ عَلَى النَّظَافَةِ.",
      },
      {
        context: "Water Conservation",
        en: "Modern dual-flush systems provide a half-flush option to conserve water.",
        ar: "تُوَفِّرُ أَنْظِمَةُ الشَّطْفِ المُزْدَوَجِ الحَدِيثَةُ خِيَارَ نِصْفِ شَطْفٍ لِتَوْفِيرِ المِيَاهِ.",
      },
      {
        context: "Plumbing Operation",
        en: "Pressing the chrome button releases a powerful swirling stream of clean water.",
        ar: "يُؤَدِّي الضَّغْطُ عَلَى الزِّرِّ المَطْلِيِّ بِالكُرُومِ إِلَى إِطْلاقِ تَدَفُّقٍ قَوِيٍّ لِلْمَاءِ النَّظِيفِ.",
      },
    ],
    exampleSentence: "Remember to flush the toilet after every use to maintain cleanliness.",
    exampleArabic:
      "تَذَكَّرْ شَطْفَ المِرْحَاضِ بَعْدَ كُلِّ اسْتِخْدَامٍ لِلْحِفَاظِ عَلَى النَّظَافَةِ.",
  },
  "comic-book": {
    id: "comic-book",
    arabic: "كِتَابُ قِصَصٍ مُصَوَّرَة (كُومِكْس)",
    partOfSpeech: "noun",
    phonetic: "ˈkɑːmɪk bʊk",
    pronunciationTip: "Pronounce 'KAH-mik book' (/ˈkɑː.mɪk bʊk/).",
    collocations: [
      "superhero comic book",
      "comic book series",
      "vintage comic book",
      "collect comic books",
      "comic book panels",
    ],
    phrasalVerbs: [
      {
        phrase: "read through",
        meaning: "browse illustrated storyline panels",
        arabic: "يَقْرَأُ فُصُولَ القِصَّةِ المُصَوَّرَة",
        example: "He read through three issues of the superhero comic book in one afternoon.",
      },
    ],
    sentences: [
      {
        context: "Recreational Reading",
        en: "He eagerly turned the vibrant glossy pages of the superhero comic book to follow the adventure.",
        ar: "قَلَّبَ بِشَغَفٍ الصَّفَحَاتِ اللَّامِعَةَ الزَّاهِيَةَ لِكِتَابِ القِصَصِ المُصَوَّرَةِ لِمُتَابَعَةِ المُغَامَرَةِ.",
      },
      {
        context: "Graphic Storytelling",
        en: "Comic books combine dynamic artwork with dialogue bubbles to tell exciting visual narratives.",
        ar: "تَجْمَعُ كُتُبُ الكُومِكْسِ بَيْنَ الرُّسُومِ الدِّينَامِيكِيَّةِ وَفَقَاعَاتِ الحِوَارِ لِسَرْدِ قِصَصٍ بَصَرِيَّةٍ مُثِيرَةٍ.",
      },
      {
        context: "Young Adult Section",
        en: "The teen lounge features dedicated racks for popular comic book series and manga.",
        ar: "تَضُمُّ اسْتِرَاحَةُ الشَّبَابِ حَوَامِلَ مُخَصَّصَةً لِسَلَاسِلِ القِصَصِ المُصَوَّرَةِ الشَّهِيرَةِ وَالمَانْغَا.",
      },
    ],
    exampleSentence:
      "He eagerly turned the vibrant glossy pages of the superhero comic book to follow the adventure.",
    exampleArabic:
      "قَلَّبَ بِشَغَفٍ الصَّفَحَاتِ اللَّامِعَةَ الزَّاهِيَةَ لِكِتَابِ القِصَصِ المُصَوَّرَةِ لِمُتَابَعَةِ المُغَامَرَةِ.",
  },
  spinach: {
    id: "spinach",
    arabic: "سَبَانِخ",
    partOfSpeech: "noun",
    phonetic: "ˈspɪnɪtʃ",
    pronunciationTip: "Pronounce 'SPIN-itch' (/ˈspɪn.ɪtʃ/).",
    collocations: [
      "baby spinach",
      "steamed spinach",
      "fresh spinach leaves",
      "spinach salad",
      "creamed spinach",
      "sauteed spinach",
    ],
    phrasalVerbs: [
      {
        phrase: "wilt down",
        meaning: "cook leafy greens until collapsed and tender",
        arabic: "يَذْبُلُ بِالحَرَارَةِ فِي المِقْلَاة",
        example: "Wilt down the fresh baby spinach leaves in olive oil and minced garlic.",
      },
    ],
    sentences: [
      {
        context: "Leafy Greens",
        en: "She selected a bag of tender baby spinach leaves for her daily breakfast smoothie.",
        ar: "اخْتَارَتْ كِيسًا مِنْ أَوْرَاقِ السَّبَانِخِ الصَّغِيرَةِ الطَّرِيَّةِ لِعَصِيرِ الإِفْطَارِ اليَوْمِيِّ.",
      },
      {
        context: "Nutrient Rich",
        en: "Spinach is packed with iron, calcium, and vitamins that support energy levels.",
        ar: "تَزْخَرُ السَّبَانِخُ بِالحَدِيدِ وَالكَالْسْيُومِ وَالفِيتَامِينَاتِ الَّتِي تَدْعَمُ مُسْتَوَيَاتِ الطَّاقَةِ.",
      },
      {
        context: "Mediterranean Pastry",
        en: "Flaky phyllo pastry stuffed with spinach and feta cheese makes a traditional Greek pie.",
        ar: "تُشَكِّلُ عَجِينَةُ الفِيلُو الهَشَّةُ المَحْشُوَّةُ بِالسَّبَانِخِ وَجُبْنِ الفِيتَا فَطِيرَةً يُونَانِيَّةً تَقْلِيدِيَّةً.",
      },
    ],
    exampleSentence:
      "She selected a bag of tender baby spinach leaves for her daily breakfast smoothie.",
    exampleArabic:
      "اخْتَارَتْ كِيسًا مِنْ أَوْرَاقِ السَّبَانِخِ الصَّغِيرَةِ الطَّرِيَّةِ لِعَصِيرِ الإِفْطَارِ اليَوْمِيِّ.",
  },
  aisle: {
    id: "aisle",
    arabic: "مَمَر (مَمَرُّ التَّسَوُّق)",
    partOfSpeech: "noun",
    phonetic: "aɪl",
    pronunciationTip: "Silent 's': 'EYE-ul' (/aɪl/).",
    collocations: [
      "supermarket aisle",
      "cereal aisle",
      "aisle number",
      "walk down the aisle",
      "wide aisle",
      "clean aisle",
    ],
    phrasalVerbs: [
      {
        phrase: "head down",
        meaning: "walk along a passageway",
        arabic: "يَتَوَجَّهُ عَبْرَ المَمَر",
        example: "Head down aisle four to find organic pasta sauces and olive oils.",
      },
    ],
    sentences: [
      {
        context: "Supermarket Layout",
        en: "Overhead numbered signs indicate which products are stocked along each brightly lit aisle.",
        ar: "تُشِيرُ اللَّافِتَاتُ المَرْقُومَةُ المُعَلَّقَةُ إِلَى المُنْتَجَاتِ المَخْزُونَةِ فِي كُلِّ مَمَرٍّ مُضَاءٍ.",
      },
      {
        context: "Shopping Flow",
        en: "She steered her shopping cart smoothly down the breakfast cereal aisle.",
        ar: "وَجَّهَتْ عَرَبَةَ التَّسَوُّقِ بِسَلَاسَةٍ عَبْرَ مَمَرِّ حُبُوبِ الإِفْطَارِ.",
      },
      {
        context: "Store Maintenance",
        en: "Staff members restock dry pantry goods and sweep the polished aisles during quiet hours.",
        ar: "يُعِيدُ المُوَظَّفُونَ مَلْءَ البَضَائِعِ وَيَكْنُسُونَ المَمَرَّاتِ المَصْقُولَةَ فِي أَوْقَاتِ الهُدُوءِ.",
      },
    ],
    exampleSentence:
      "Overhead numbered signs indicate which products are stocked along each brightly lit aisle.",
    exampleArabic:
      "تُشِيرُ اللَّافِتَاتُ المَرْقُومَةُ المُعَلَّقَةُ إِلَى المُنْتَجَاتِ المَخْزُونَةِ فِي كُلِّ مَمَرٍّ مُضَاءٍ.",
  },
  umbrella: {
    id: "umbrella",
    arabic: "مِظَلَّة (شَمْسِيَّةُ الشَّاطِئ)",
    partOfSpeech: "noun",
    phonetic: "ʌmˈbrɛlə",
    pronunciationTip: "Pronounce 'um-BREL-uh' (/ʌmˈbrɛl.ə/).",
    collocations: [
      "beach umbrella",
      "colorful umbrella",
      "open an umbrella",
      "shade under the umbrella",
      "umbrella anchor",
    ],
    phrasalVerbs: [
      {
        phrase: "put up",
        meaning: "erect and secure shade canopy in sand",
        arabic: "يَنْصِبُ شَمْسِيَّةَ الشَّاطِئ",
        example: "He put up a large striped beach umbrella and secured its pole in the deep sand.",
      },
    ],
    sentences: [
      {
        context: "Beach Comfort",
        en: "We opened a wide colorful beach umbrella to create cool shade from the intense midday heat.",
        ar: "فَتَحْنَا مِظَلَّةَ شَاطِئٍ كَبِيرَةً مُلَوَّنَةً لِخَلْقِ ظِلٍّ بَارِدٍ مِنَ الحَرَارَةِ الشَّدِيدَةِ.",
      },
      {
        context: "Wind Security",
        en: "Using a spiral sand anchor prevents gusts of coastal wind from blowing your beach umbrella away.",
        ar: "يَمْنَعُ اسْتِخْدَامُ مِرْسَاةِ الرِّمَالِ اللَّوْلَبِيَّةِ هَبَّاتِ الرِّيَاحِ مِنْ تَطْيِيرِ شَمْسِيَّةِ الشَّاطِئِ.",
      },
      {
        context: "Shoreline Panorama",
        en: "Dozens of bright yellow and blue beach umbrellas dotted the crowded coastline like cheerful flowers.",
        ar: "نَثَرَتْ عَشَرَاتُ مِظَلَّاتِ الشَّاطِئِ الصَّفْرَاءِ وَالزَّرْقَاءِ أَلْوَانَهَا كَالزُّهُورِ عَلَى السَّاحِلِ.",
      },
    ],
    exampleSentence:
      "We opened a wide colorful beach umbrella to create cool shade from the intense midday heat.",
    exampleArabic:
      "فَتَحْنَا مِظَلَّةَ شَاطِئٍ كَبِيرَةً مُلَوَّنَةً لِخَلْقِ ظِلٍّ بَارِدٍ مِنَ الحَرَارَةِ الشَّدِيدَةِ.",
  },
  windsurfing: {
    id: "windsurfing",
    arabic: "رُكُوبُ الأَمْوَاجِ شِرَاعِيًّا (التَّزَلُّجُ الشِّرَاعِيُّ عَلَى المَاءِ)",
    partOfSpeech: "noun",
    phonetic: "ˈwɪndsɜːrfɪŋ",
    pronunciationTip: "Pronounce 'WIND-surf-ing' (/ˈwɪnd.sɜːr.fɪŋ/).",
    collocations: [
      "go windsurfing",
      "windsurfing board and rig",
      "windsurfing harness",
      "windsurfing champion",
      "windsurfing in the bay",
    ],
    phrasalVerbs: [
      {
        phrase: "tack against",
        meaning: "change heading relative to oncoming air currents",
        arabic: "يُغَيِّرُ مَسَارَ الشِّرَاعِ ضِدَّ الرِّيَاح",
        example: "He tacked against the brisk onshore breeze to maintain speed across the water.",
      },
    ],
    sentences: [
      {
        context: "Hybrid Water Sport",
        en: "Windsurfing combines elements of surfing and sailing, using a handheld sail mounted to a pivoting board.",
        ar: "يَجْمَعُ التَّزَلُّجُ الشِّرَاعِيُّ بَيْنَ رُكُوبِ الأَمْوَاجِ وَالإِبْحَارِ بِشِرَاعٍ يَدَوِيٍّ مُثَبَّتٍ عَلَى لَوْحٍ.",
      },
      {
        context: "Breezy Bay",
        en: "The windy coastal bay is a renowned hotspot where enthusiasts practice speed windsurfing.",
        ar: "يُعَدُّ الخَلِيجُ السَّاحِلِيُّ العَاصِفُ مَرْكَزًا شَهِيرًا يُمَارِسُ فِيهِ الهُوَاةُ التَّزَلُّجَ الشِّرَاعِيَّ.",
      },
      {
        context: "Physical Mastery",
        en: "Mastering the boom grip and footstraps allows windsurfers to jump over wave crests at high speed.",
        ar: "يُتِيحُ التَّحَكُّمُ فِي سَاعِدِ الشِّرَاعِ وَأَحْزِمَةِ القَدَمِ لِلْمُتَزَلِّجِينَ القَفْزَ فَوْقَ قِمَمِ الأَمْوَاجِ.",
      },
    ],
    exampleSentence:
      "Windsurfing combines elements of surfing and sailing, using a handheld sail mounted to a pivoting board.",
    exampleArabic:
      "يَجْمَعُ التَّزَلُّجُ الشِّرَاعِيُّ بَيْنَ رُكُوبِ الأَمْوَاجِ وَالإِبْحَارِ بِشِرَاعٍ يَدَوِيٍّ مُثَبَّتٍ عَلَى لَوْحٍ.",
  },
  pharmacist: {
    id: "pharmacist",
    arabic: "صَيْدَلِيّ (خَبِيرُ الأَدْوِيَةِ وَالعِلَاج)",
    partOfSpeech: "noun",
    phonetic: "ˈfɑːrməsɪst",
    pronunciationTip: "Pronounce 'FAR-muh-sist' (/ˈfɑːr.mə.sɪst/).",
    collocations: ["licensed pharmacist", "consult the pharmacist", "hospital pharmacist"],
    phrasalVerbs: [
      {
        phrase: "dispense to",
        meaning: "provide prescribed medicines with dosage instructions",
        arabic: "يَصْرِفُ الدَّوَاءَ لِلْمَرِيض",
        example: "The pharmacist dispensed the antibiotics to the patient.",
      },
    ],
    sentences: [
      {
        context: "Medication Guidance",
        en: "The licensed pharmacist explained how to take the prescribed medication with meals.",
        ar: "شَرَحَ الصَّيْدَلِيُّ المُرَخَّصُ كَيْفِيَّةَ تَنَاوُلِ الدَّوَاءِ المَوْصُوفِ مَعَ الوَجَبَاتِ.",
      },
      {
        context: "Safety Check",
        en: "Hospital pharmacists review prescriptions carefully to verify dosages and drug interactions.",
        ar: "يُرَاجِعُ صَيَادِلَةُ المُسْتَشْفَى الوَصَفَاتِ لِضَمَانِ عَدَمِ تَعَارُضِ الأَدْوِيَةِ.",
      },
      {
        context: "Pharmacy Advice",
        en: "Patients can ask the friendly neighborhood pharmacist for guidance on over-the-counter remedies.",
        ar: "يُمْكِنُ لِلْمَرْضَى اسْتِشَارَةُ الصَّيْدَلِيِّ بِشَأْنِ أَدْوِيَةِ الزُّكَامِ وَالصُّدَاعِ.",
      },
    ],
    exampleSentence:
      "The licensed pharmacist explained how to take the prescribed medication with meals.",
    exampleArabic:
      "شَرَحَ الصَّيْدَلِيُّ المُرَخَّصُ كَيْفِيَّةَ تَنَاوُلِ الدَّوَاءِ المَوْصُوفِ مَعَ الوَجَبَاتِ.",
  },
  bone: {
    id: "bone",
    arabic: "عَظْم (الهَيْكَلُ العَظْمِيُّ الصَّلْبُ لِلْجِسْم)",
    partOfSpeech: "noun",
    phonetic: "boʊn",
    pronunciationTip: "Long 'o' sound /oʊ/: 'BOHN' (/boʊn/).",
    collocations: ["broken bone", "strong bones", "bone density", "calcium for bones"],
    phrasalVerbs: [
      {
        phrase: "heal over",
        meaning: "fuse and regenerate after skeletal fracture",
        arabic: "يَلْتَئِمُ العَظْمُ بَعْدَ الكَسْر",
        example: "The fractured bone healed over six weeks.",
      },
    ],
    sentences: [
      {
        context: "Skeletal System",
        en: "Calcium and vitamin D are essential nutrients for building strong and dense bones.",
        ar: "يُعَدُّ الكَالْسِيُوم وَفِيتَامِين د مِنْ العَنَاصِرِ الأَسَاسِيَّةِ لِبِنَاءِ عِظَامٍ قَوِيَّةٍ.",
      },
      {
        context: "Fracture",
        en: "The doctor reviewed the radiograph to check whether the arm bone had healed correctly.",
        ar: "فَحَصَ الطَّبِيبُ صُورَةَ الأَشِعَّةِ لِلتَّأَكُّدِ مِنِ التِئَامِ عَظْمِ الذِّرَاعِ تَمَامًا.",
      },
      {
        context: "Structure",
        en: "The adult human skeleton is composed of two hundred and six individual bones.",
        ar: "يَتَكَوَّنُ الهَيْكَلُ العَظْمِيُّ لِلْبَالِغِينَ مِنْ ٢٠٦ عِظَامٍ مُنْفَصِلَةٍ.",
      },
    ],
    exampleSentence:
      "Calcium and vitamin D are essential nutrients for building strong and dense bones.",
    exampleArabic:
      "يُعَدُّ الكَالْسِيُوم وَفِيتَامِين د مِنْ العَنَاصِرِ الأَسَاسِيَّةِ لِبِنَاءِ عِظَامٍ قَوِيَّةٍ.",
  },
  fever: {
    id: "fever",
    arabic: "حُمَّى (ارْتِفَاعُ دَرَجَةِ حَرَارَةِ الجِسْم)",
    partOfSpeech: "noun",
    phonetic: "ˈfiːvər",
    pronunciationTip: "Long 'ee' sound: 'FEE-ver' (/ˈfiː.vər/).",
    collocations: ["high fever", "break a fever", "run a fever", "fever reducer"],
    phrasalVerbs: [
      {
        phrase: "come down",
        meaning: "decrease temperature back to normal",
        arabic: "تَنْخَفِضُ الحَرَارَة",
        example: "Her fever came down after taking medicine.",
      },
    ],
    sentences: [
      {
        context: "Immune Response",
        en: "A fever is the body's natural defense mechanism fighting off viral or bacterial infections.",
        ar: "الحُمَّى هِيَ اسْتِجَابَةُ الجِسْمِ الطَّبِيعِيَّةُ لِمُحَارَبَةِ العَدْوَى الفِيرُوسِيَّةِ أَوِ البَكْتِيرِيَّةِ.",
      },
      {
        context: "Treatment",
        en: "Drink plenty of water, rest in bed, and take acetaminophen to reduce a high fever.",
        ar: "اشْرَبِ الكَثِيرَ مِنَ المَاءِ وَاسْتَرِحْ لِتَخْفِيضِ دَرَجَةِ الحَرَارَةِ المُرْتَفِعَةِ.",
      },
      {
        context: "Thermometer",
        en: "The digital thermometer showed thirty-nine degrees, indicating a moderate fever.",
        ar: "أَظْهَرَ مِقْيَاسُ الحَرَارَةِ ٣٩ دَرَجَةً مِئَوِيَّةً مِمَّا يَدُلُّ عَلَى وُجُودِ حُمَّى.",
      },
    ],
    exampleSentence:
      "A fever is the body's natural defense mechanism fighting off viral or bacterial infections.",
    exampleArabic:
      "الحُمَّى هِيَ اسْتِجَابَةُ الجِسْمِ الطَّبِيعِيَّةُ لِمُحَارَبَةِ العَدْوَى الفِيرُوسِيَّةِ أَوِ البَكْتِيرِيَّةِ.",
  },
  rash: {
    id: "rash",
    arabic: "طَفْحٌ جِلْدِيّ (احْمِرَارٌ وَتَهَيُّجٌ فِي الجِلْد)",
    partOfSpeech: "noun",
    phonetic: "ræʃ",
    pronunciationTip: "Short 'a' sound: 'RASH' (/ræʃ/).",
    collocations: ["skin rash", "itchy rash", "develop a rash", "treat a rash"],
    phrasalVerbs: [
      {
        phrase: "break out in",
        meaning: "develop sudden widespread skin eruptions",
        arabic: "يَظْهَرُ عَلَيْهِ طَفْحٌ جِلْدِيّ",
        example: "She broke out in a rash after touching poison ivy.",
      },
    ],
    sentences: [
      {
        context: "Dermatology",
        en: "The child developed an itchy red skin rash after accidentally brushing against stinging nettles.",
        ar: "أُصِيبَ الطِّفْلُ بِطَفْحٍ جِلْدِيٍّ أَحْمَرَ مُثِيرٍ لِلْحِكَّةِ بَعْدَ لَمْسِ نَبَاتِ القَرَّاصِ.",
      },
      {
        context: "Soothing Cream",
        en: "Applying a soothing calamine lotion and hydrocortisone cream relieves itching from allergic rashes.",
        ar: "يُهَدِّئُ دَهْنُ لُوشِن الكَالَامِين وَالكَرِيمِ الحِكَّةَ النَّاتِجَةَ عَنِ الطَّفْحِ الجِلْدِيِّ.",
      },
      {
        context: "Doctor Check",
        en: "Consult a dermatologist if an unexplained rash spreads rapidly or is accompanied by fever.",
        ar: "اسْتَشِرْ طَبِيبَ الجِلْدِيَّةِ إِذَا انْتَشَرَ الطَّفْحُ الجِلْدِيُّ أَوْ صَاحَبَتْهُ حُمَّى.",
      },
    ],
    exampleSentence:
      "The child developed an itchy red skin rash after accidentally brushing against stinging nettles.",
    exampleArabic:
      "أُصِيبَ الطِّفْلُ بِطَفْحٍ جِلْدِيٍّ أَحْمَرَ مُثِيرٍ لِلْحِكَّةِ بَعْدَ لَمْسِ نَبَاتِ القَرَّاصِ.",
  },
  "postage-stamp": {
    id: "postage-stamp",
    arabic: "طَابِعُ بَرِيد",
    partOfSpeech: "noun",
    collocations: ["use regularly", "check carefully", "keep handy"],
    sentences: [
      {
        context: "Adhesive Label",
        en: "Affix the collectible gummed sticker onto the top right corner.",
        ar: "أَلْصِقْ طَابِعَ البَرِيدِ فِي الزَّاوِيَةِ العُلْيَا اليُمْنَى مِنَ المَظْرُوف.",
      },
      {
        context: "Collector Stamp",
        en: "Philatelists value historical postage prints from the nineteenth century.",
        ar: "يُقَدِّرُ هُوَاةُ جَمْعِ الطَّوَابِعِ الإِصْدَارَاتِ التَّارِيخِيَّة.",
      },
      {
        context: "Mailing Fee",
        en: "The international airmail rate required two first-class stickers.",
        ar: "تَطَلَّبَتِ الرِّسَالَةُ الدَّوْلِيَّةُ طَابِعَيْ بَرِيدٍ مِنَ الدَّرَجَةِ الأُولَى.",
      },
    ],
    exampleSentence: "Affix the collectible gummed sticker onto the top right corner.",
    exampleArabic:
      "أَلْصِقْ طَابِعَ البَرِيدِ فِي الزَّاوِيَةِ العُلْيَا اليُمْنَى مِنَ المَظْرُوف.",
  },
  "package-scale": {
    id: "package-scale",
    arabic: "مِيزَانُ الطُّرُود",
    partOfSpeech: "noun",
    collocations: ["use regularly", "check carefully", "keep handy"],
    sentences: [
      {
        context: "Weight Measurement",
        en: "The postal clerk placed our box on the digital weighing platform.",
        ar: "وَضَعَ مُوَظَّفُ البَرِيدِ الصُّنْدُوقَ عَلَى مِيزَانِ الطُّرُودِ الرَّقْمِيّ.",
      },
      {
        context: "Postage Calculation",
        en: "The apparatus calculated exact shipping rates based on gross weight.",
        ar: "حَدَّدَ مِيزَانُ الطُّرُودِ التَّكْلِفَةَ بِنَاءً عَلَى الوَزْنِ الإِجْمَالِيّ.",
      },
      {
        context: "Accurate Balance",
        en: "Heavy parcels are weighed before receiving their transport barcode.",
        ar: "تُوزَنُ الطُّرُودُ الثَّقِيلَةُ عَلَى المِيزَانِ قَبْلَ طِبَاعَةِ الرَّمْز.",
      },
    ],
    exampleSentence: "The postal clerk placed our box on the digital weighing platform.",
    exampleArabic: "وَضَعَ مُوَظَّفُ البَرِيدِ الصُّنْدُوقَ عَلَى مِيزَانِ الطُّرُودِ الرَّقْمِيّ.",
  },
  runway: {
    id: "runway",
    arabic: "مُدَرَّجُ الطَّائِرَات",
    partOfSpeech: "noun",
    collocations: ["land on the runway", "taxi down the runway", "clear the runway"],
    sentences: [
      {
        context: "Travel & Hospitality",
        en: "The plane lands on the runway.",
        ar: "تَهْبِطُ الطَّائِرَةُ عَلَى مُدَرَّجِ الطَّائِرَات.",
      },
      {
        context: "Aviation",
        en: "The pilot taxied the aircraft down the long runway.",
        ar: "وَجَّهَ الطَّيَّارُ الطَّائِرَةَ عَلَى طُولِ المُدَرَّجِ الطَّوِيل.",
      },
      {
        context: "Airport Security",
        en: "Ground control must clear the runway before takeoff.",
        ar: "يَجِبُ عَلَى المُتَحَكِّمِ الأَرْضِيِّ إِخْلَاءُ المُدَرَّجِ قَبْلَ الإِقْلَاع.",
      },
    ],
    exampleSentence: "The plane lands on the runway.",
    exampleArabic: "تَهْبِطُ الطَّائِرَةُ عَلَى مُدَرَّجِ الطَّائِرَات.",
  },
};
