// Generated by scripts/shard_learning_content.mjs. Do not edit.
import type { LexiconEntry } from "../lexiconCore";
export const entries: Record<string, LexiconEntry> = {
  sponge: {
    id: "sponge",
    arabic: "إسفنجة",
    sentences: [],
    collocations: ["use the sponge", "clean the sponge", "buy a sponge"],
    phrasalVerbs: [],
    partOfSpeech: "noun",
    audio: "/audio/en-US/sponge.mp3",
    meanings: [
      {
        en: "A piece of soft, porous material used for washing or cleaning.",
        ar: "",
        sentences: [],
      },
    ],
  },
  laptop: {
    id: "laptop",
    arabic: "حَاسُوبٌ مَحْمُول (لَابْتُوب)",
    partOfSpeech: "noun",
    phonetic: "ˈlæp.tɑːp",
    pronunciationTip: "Compound word: 'LAP' (/læp/) + 'TOP' (/tɑːp/).",
    collocations: [
      "open the laptop",
      "work on a laptop",
      "laptop screen",
      "close the laptop",
      "portable laptop",
      "powerful laptop",
    ],
    phrasalVerbs: [
      {
        phrase: "boot up",
        meaning: "start a laptop operating system",
        arabic: "يُقْلِعُ / يُشَغِّلُ الجِهَاز",
        example: "Wait a few seconds for the laptop to boot up.",
      },
      {
        phrase: "shut down",
        meaning: "turn off a laptop completely",
        arabic: "يُغْلِقُ الحَاسُوب",
        example: "Remember to shut down your laptop before putting it in your bag.",
      },
      {
        phrase: "log into",
        meaning: "enter credentials to access computer",
        arabic: "يُسَجِّلُ الدُّخُول",
        example: "She logged into her laptop to join the morning video meeting.",
      },
    ],
    sentences: [
      {
        context: "Remote Work",
        en: "She opened her laptop at the desk to review the project report.",
        ar: "فَتَحَتْ حَاسُوبَهَا المَحْمُولَ عَلَى المَكْتَبِ لِمُرَاجَعَةِ تَقْرِيرِ المَشْرُوعِ.",
      },
      {
        context: "Mobility",
        en: "A lightweight laptop allows students to study easily anywhere on campus.",
        ar: "يُتِيحُ الحَاسُوبُ المَحْمُولُ الخَفِيفُ لِلْطُّلاَّبِ الدِّرَاسَةَ بِسُهُولَةٍ فِي أَيِّ مَكَانٍ.",
      },
      {
        context: "Maintenance",
        en: "Close your laptop lid gently and keep liquids away from the keyboard.",
        ar: "أَغْلِقْ غِطَاءَ حَاسُوبِكَ المَحْمُولِ بِرِفْقٍ وَأَبْعِدِ السَّوَائِلَ عَنْ لَوْحَةِ المَفَاتِيحِ.",
      },
    ],
    exampleSentence: "She opened her laptop at the desk to review the project report.",
    exampleArabic:
      "فَتَحَتْ حَاسُوبَهَا المَحْمُولَ عَلَى المَكْتَبِ لِمُرَاجَعَةِ تَقْرِيرِ المَشْرُوعِ.",
  },
  rabbit: {
    id: "rabbit",
    arabic: "أَرْنَب",
    partOfSpeech: "noun",
    phonetic: "ˈræb.ɪt",
    pronunciationTip: "Short 'a' vowel /æ/ as in 'rab', followed by short /ɪt/.",
    collocations: [
      "pet rabbit",
      "hop like a rabbit",
      "rabbit hutch",
      "wild rabbit",
      "fluffy rabbit",
      "rabbit ears",
    ],
    phrasalVerbs: [
      {
        phrase: "hop away",
        meaning: "jump quickly to escape",
        arabic: "يَقْفِزُ مُبْتَعِداً",
        example: "The wild rabbit hopped away into the tall clover when it saw us.",
      },
    ],
    sentences: [
      {
        context: "Garden Visitor",
        en: "A cute brown rabbit nibbled quietly on crisp dandelion leaves in the vegetable garden.",
        ar: "قَضَمَ أَرْنَبٌ بُنِّيٌّ لَطِيفٌ أَوْرَاقَ الهِنْدَبَاءِ فِي حَدِيقَةِ الخُضْرَاوَاتِ بِهُدُوءٍ.",
      },
      {
        context: "Pet Care",
        en: "Clean the rabbit hutch and provide fresh timothy hay and clean water daily.",
        ar: "نَظِّفْ قَفَصَ الأَرْنَبِ وَوَفِّرْ لَهُ قَشَّ التِّيمُوثِي الطَّازَجَ وَالمَاءَ النَّقِيَّ يَوْمِيّاً.",
      },
      {
        context: "Speed & Agility",
        en: "The rabbit zigzagged swiftly through the meadow to outrun the barking puppy.",
        ar: "جَرَى الأَرْنَبُ بِسُرْعَةٍ وَتَمَوُّجٍ عَبْرَ المَرْجِ لِيَسْبِقَ الجَرْوَ النَّابِحَ.",
      },
    ],
    exampleSentence:
      "A cute brown rabbit nibbled quietly on crisp dandelion leaves in the vegetable garden.",
    exampleArabic:
      "قَضَمَ أَرْنَبٌ بُنِّيٌّ لَطِيفٌ أَوْرَاقَ الهِنْدَبَاءِ فِي حَدِيقَةِ الخُضْرَاوَاتِ بِهُدُوءٍ.",
  },
  spatula: {
    id: "spatula",
    arabic: "مِلْعَقَةُ تَقْلِيب (سْبَاتْيُولا)",
    partOfSpeech: "noun",
    phonetic: "ˈspætʃ.ə.lə",
    pronunciationTip: "Three syllables: 'SPAT-chu-la' with primary stress on 'SPAT'.",
    collocations: [
      "silicone spatula",
      "metal spatula",
      "flip with a spatula",
      "scrape the bowl with a spatula",
      "heat-resistant spatula",
      "flexible spatula",
    ],
    phrasalVerbs: [
      {
        phrase: "scrape down",
        meaning: "clean the sides of a mixing bowl",
        arabic: "يَكْشِطُ جَوَانِبَ الوِعَاء",
        example: "Use the flexible spatula to scrape down the cake batter from the bowl.",
      },
      {
        phrase: "flip over",
        meaning: "turn food in a pan",
        arabic: "يَقْلِبُ",
        example: "Flip over the beef burger using a wide metal spatula.",
      },
    ],
    sentences: [
      {
        context: "Baking",
        en: "Use a flexible silicone spatula to scrape every bit of batter from the bowl.",
        ar: "اسْتَخْدِمْ مِلْعَقَةَ سْبَاتْيُولا مَرِنَةً لِكَشْطِ جَمِيعِ بَقَايَا العَجِينِ مِنَ الوِعَاءِ.",
      },
      {
        context: "Cooking Burgers",
        en: "He slid the wide spatula under the burger patty to flip it neatly.",
        ar: "مَرَّرَ السْبَاتْيُولا العَرِيضَةَ تَحْتَ قِطْعَةِ البُرْجَر لِقَلْبِهَا بِإِتْقَانٍ.",
      },
      {
        context: "Heat Safety",
        en: "Heat-resistant silicone spatulas will not melt when stirring hot sauces.",
        ar: "المَلاعِقُ السِّيلِيكُونِيَّةُ المُقَاوِمَةُ لِلْحَرَارَةِ لا تَذُوبُ عِنْدَ تَقْلِيبِ الصَّلْصَاتِ السَّاخِنَةِ.",
      },
    ],
    exampleSentence: "Use a flexible silicone spatula to scrape every bit of batter from the bowl.",
    exampleArabic:
      "اسْتَخْدِمْ مِلْعَقَةَ سْبَاتْيُولا مَرِنَةً لِكَشْطِ جَمِيعِ بَقَايَا العَجِينِ مِنَ الوِعَاءِ.",
  },
  "towel-rack": {
    id: "towel-rack",
    arabic: "حَامِلُ المَنَاشِف (عَلَّاقَةُ الفُوَط)",
    partOfSpeech: "noun",
    phonetic: "ˈtaʊəl ræk",
    pronunciationTip: "Pronounce 'towel' (/ˈtaʊ.əl/) followed by crisp 'rack' (/ræk/).",
    collocations: [
      "heated towel rack",
      "hang on the towel rack",
      "stainless steel towel rack",
      "wall-mounted towel rack",
      "double towel rack",
      "bathroom towel rack",
    ],
    phrasalVerbs: [
      {
        phrase: "hang up",
        meaning: "place a towel neatly over the rail",
        arabic: "يُعَلِّقُ الفُوطَة",
        example: "Hang up your damp bath sheet on the towel rack to air dry.",
      },
      {
        phrase: "take down",
        meaning: "remove a towel from the holder",
        arabic: "يُنْزِلُ الفُوطَة",
        example: "She took down a clean towel from the rack.",
      },
    ],
    sentences: [
      {
        context: "Bathroom Storage",
        en: "The heated towel rack keeps bath towels warm and dry after every shower.",
        ar: "يُحَافِظُ حَامِلُ المَنَاشِفِ المُدَفَّأُ عَلَى دِفْءِ وَجَفَافِ المَنَاشِفِ بَعْدَ كُلِّ اسْتِحْمَام.",
      },
      {
        context: "Tidiness",
        en: "Always hang your wet towel on the towel rack instead of leaving it on the floor.",
        ar: "عَلِّقْ مَنْشَفَتَكَ الرَّطْبَةَ دَائِمًا عَلَى حَامِلِ المَنَاشِفِ بَدَلًا مِنْ تَرْكِهَا عَلَى الأَرْض.",
      },
      {
        context: "Installation",
        en: "He installed a chrome towel rack right beside the glass shower door.",
        ar: "قَامَ بِتَرْكِيبِ حَامِلِ مَنَاشِفَ مَطْلِيٍّ بِالكُرُومِ بِجِوَارِ بَابِ الدُّشِّ الزُّجَاجِيِّ مُبَاشَرَةً.",
      },
    ],
    exampleSentence: "The heated towel rack keeps bath towels warm and dry after every shower.",
    exampleArabic:
      "يُحَافِظُ حَامِلُ المَنَاشِفِ المُدَفَّأُ عَلَى دِفْءِ وَجَفَافِ المَنَاشِفِ بَعْدَ كُلِّ اسْتِحْمَام.",
  },
  "hand-sanitizer": {
    id: "hand-sanitizer",
    arabic: "مُعَقِّمُ اليَدَيْن (مُطَهِّرُ اليَدَيْن)",
    partOfSpeech: "noun",
    phonetic: "ˈhænd ˌsænɪtaɪzər",
    pronunciationTip: "'Hand' (/hænd/) + 'SAN-i-ti-zer' (/ˈsæn.ɪ.taɪ.zər/).",
    collocations: [
      "alcohol hand sanitizer",
      "gel hand sanitizer",
      "pocket hand sanitizer",
      "apply hand sanitizer",
      "rub with hand sanitizer",
      "hand sanitizer dispenser",
    ],
    phrasalVerbs: [
      {
        phrase: "rub together",
        meaning: "spread disinfectant across palms",
        arabic: "يَفْرُكُ اليَدَيْن",
        example: "Rub hands together briskly until the alcohol sanitizer evaporates completely.",
      },
      {
        phrase: "wipe down",
        meaning: "sanitize surfaces or skin",
        arabic: "يُعَقِّمُ بِالمُطَهِّر",
        example: "Use hand sanitizer to disinfect your hands when soap and water are unavailable.",
      },
    ],
    sentences: [
      {
        context: "Public Hygiene",
        en: "Apply alcohol-based hand sanitizer to kill bacteria when soap and running water are unavailable.",
        ar: "ضَعْ مُعَقِّمَ اليَدَيْنِ القَائِمَ عَلَى الكُحُولِ لِلْقَضَاءِ عَلَى البَكْتِيرْيَا عِنْدَ عَدَمِ تَوَفُّرِ المَاءِ وَالصَّابُون.",
      },
      {
        context: "Travel",
        en: "He clipped a small travel-sized bottle of hand sanitizer to his backpack zipper.",
        ar: "عَلَّقَ قَارُورَةً صَغِيرَةً لِلسَّفَرِ مِنْ مُعَقِّمِ اليَدَيْنِ فِي سَحَّابِ حَقِيبَةِ ظَهْرِه.",
      },
      {
        context: "Effective Use",
        en: "Rub the hand sanitizer over all surfaces of both hands until they feel completely dry.",
        ar: "افْرُكْ مُعَقِّمَ اليَدَيْنِ عَلَى جَمِيعِ أَجْزَاءِ يَدَيْكَ حَتَّى تَجِفَّ تَمَامًا.",
      },
    ],
    exampleSentence:
      "Apply alcohol-based hand sanitizer to kill bacteria when soap and running water are unavailable.",
    exampleArabic:
      "ضَعْ مُعَقِّمَ اليَدَيْنِ القَائِمَ عَلَى الكُحُولِ لِلْقَضَاءِ عَلَى البَكْتِيرْيَا عِنْدَ عَدَمِ تَوَفُّرِ المَاءِ وَالصَّابُون.",
  },
  cloth: {
    id: "cloth",
    arabic: "قِمَاشَةُ تَنْظِيف (فُوطَةُ مَسْح)",
    partOfSpeech: "noun",
    phonetic: "klɔːθ",
    pronunciationTip: "Short open 'aw' sound /ɔː/ ending in soft unvoiced 'th' (/θ/).",
    collocations: [
      "microfiber cloth",
      "damp cloth",
      "cleaning cloth",
      "wipe with a cloth",
      "dusting cloth",
      "lint-free cloth",
    ],
    phrasalVerbs: [
      {
        phrase: "wipe down",
        meaning: "clean surfaces thoroughly with cloth",
        arabic: "يَمْسَحُ بِالقِمَاشَة",
        example: "Wipe down the chrome faucet and marble counter with a dry microfiber cloth.",
      },
      {
        phrase: "wring out",
        meaning: "squeeze excess water from wet rag",
        arabic: "يَعْصِرُ القِمَاشَة",
        example: "Wring out the wet cleaning cloth before polishing the mirrors.",
      },
    ],
    sentences: [
      {
        context: "Polishing Surfaces",
        en: "Use a dry microfiber cloth to buff chrome bathroom faucets to a brilliant shine.",
        ar: "اسْتَخْدِمْ قِمَاشَةَ مَايْكْرُوفَايْبِر جَافَّةً لِتَلْمِيعِ صَنَابِيرِ الحَمَّامِ المَطْلِيَّةِ بِالكُرُوم.",
      },
      {
        context: "Cleaning Routine",
        en: "Wipe down the bathroom counter every evening with a warm damp cloth.",
        ar: "امْسَحْ سَطْحَ خِزَانَةِ الحَمَّامِ كُلَّ مَسَاءٍ بِقِمَاشَةٍ رَطْبَةٍ وَدَافِئَة.",
      },
      {
        context: "Lint-Free Results",
        en: "A lint-free cleaning cloth leaves glass shower doors sparkling and streak-free.",
        ar: "تَتْرُكُ قِمَاشَةُ التَّنْظِيفِ الخَالِيَةُ مِنَ الوَبَرِ أَبْوَابَ الدُّشِّ الزُّجَاجِيَّةَ لاَمِعَةً دُونَ آثَار.",
      },
    ],
    exampleSentence:
      "Use a dry microfiber cloth to buff chrome bathroom faucets to a brilliant shine.",
    exampleArabic:
      "اسْتَخْدِمْ قِمَاشَةَ مَايْكْرُوفَايْبِر جَافَّةً لِتَلْمِيعِ صَنَابِيرِ الحَمَّامِ المَطْلِيَّةِ بِالكُرُوم.",
  },
  coach: {
    id: "coach",
    arabic: "مُدَرِّبٌ رِيَاضِيّ",
    partOfSpeech: "noun",
    phonetic: "koʊtʃ",
    pronunciationTip: "Long 'o' sound /oʊ/: 'KOHCH' (/koʊtʃ/).",
    collocations: [
      "soccer coach",
      "head coach",
      "team coach",
      "coach instructions",
      "coach whistle",
      "supportive coach",
    ],
    phrasalVerbs: [
      {
        phrase: "call up",
        meaning: "summon players from the sideline",
        arabic: "يَسْتَدْعِي اللَّاعِبِينَ",
        example: "Coach called up the substitutes for the second half.",
      },
    ],
    sentences: [
      {
        context: "Sports Practice",
        en: "The soccer coach gathered the young players around to explain the passing drill.",
        ar: "جَمَعَ مُدَرِّبُ كُرَةِ القَدَمِ اللَّاعِبِينَ الصِّغَارَ لِيَشْرَحَ لَهُمْ تَمْرِينَ التَّمْرِيرِ.",
      },
      {
        context: "Encouragement",
        en: "Our coach always gives constructive advice and motivates the team to do their best.",
        ar: "يُقَدِّمُ مُدَرِّبُنَا دَائِمًا نَصَائِحَ بَنَّاءَةً وَيُحَفِّزُ الفَرِيقَ لِبَذْلِ قُصَارَى جُهْدِهِمْ.",
      },
      {
        context: "Game Strategy",
        en: "During halftime, the coach drew tactics on a magnetic whiteboard.",
        ar: "خِلَالَ اسْتِرَاحَةِ الشَّوْطَيْنِ، رَسَمَ المُدَرِّبُ الخُطَطَ عَلَى لَوْحٍ مَغْنَاطِيسِيٍّ أَبْيَضَ.",
      },
    ],
    exampleSentence:
      "The soccer coach gathered the young players around to explain the passing drill.",
    exampleArabic:
      "جَمَعَ مُدَرِّبُ كُرَةِ القَدَمِ اللَّاعِبِينَ الصِّغَارَ لِيَشْرَحَ لَهُمْ تَمْرِينَ التَّمْرِيرِ.",
  },
  printer: {
    id: "printer",
    arabic: "طَابِعَة",
    partOfSpeech: "noun",
    phonetic: "ˈprɪntər",
    pronunciationTip: "Pronounce 'PRIN-ter' (/ˈprɪn.tər/).",
    collocations: [
      "laser printer",
      "color printer",
      "printer paper tray",
      "inkjet printer",
      "print from a printer",
      "wireless network printer",
    ],
    phrasalVerbs: [
      {
        phrase: "print out",
        meaning: "produce hard copies from computer files",
        arabic: "يَطْبَعُ وَرَقِيًّا",
        example:
          "The teacher will print out twenty copies of the study guide on the laser printer.",
      },
    ],
    sentences: [
      {
        context: "Class Handouts",
        en: "The teacher printed out thirty copies of the assignment on the high-speed laser printer.",
        ar: "طَبَعَ المُعَلِّمُ ثَلَاثِينَ نُسْخَةً مِنَ الفَرْضِ عَلَى طَابِعَةِ اللَّيْزَرِ سَرِيعَةِ الأَدَاءِ.",
      },
      {
        context: "Color Printing",
        en: "Students printed their colorful science diagrams on the shared library printer.",
        ar: "طَبَعَ الطُّلَّابُ مُخَطَّطَاتِهِمُ العِلْمِيَّةَ المُلَوَّنَةَ عَلَى طَابِعَةِ المَكْتَبَةِ المُشْتَرَكَةِ.",
      },
      {
        context: "Maintenance",
        en: "A blinking yellow light on the front panel indicates the printer needs more paper.",
        ar: "يُشِيرُ ضَوْءٌ أَصْفَرُ وَامِضٌ عَلَى اللَّوْحَةِ الأَمَامِيَّةِ إِلَى أَنَّ الطَّابِعَةَ بِحَاجَةٍ إِلَى مَزِيدٍ مِنَ الوَرَقِ.",
      },
    ],
    exampleSentence:
      "The teacher printed out thirty copies of the assignment on the high-speed laser printer.",
    exampleArabic:
      "طَبَعَ المُعَلِّمُ ثَلَاثِينَ نُسْخَةً مِنَ الفَرْضِ عَلَى طَابِعَةِ اللَّيْزَرِ سَرِيعَةِ الأَدَاءِ.",
  },
  "help-desk": {
    id: "help-desk",
    arabic: "مَكْتَبُ المُسَاعَدَةِ وَالاسْتِعْلَامَات",
    partOfSpeech: "noun",
    phonetic: "ˈhɛlp dɛsk",
    pronunciationTip: "Pronounce 'HELP desk' (/ˈhɛlp dɛsk/).",
    collocations: [
      "information help desk",
      "ask at the help desk",
      "library help desk staff",
      "front help desk",
      "technical help desk",
    ],
    phrasalVerbs: [
      {
        phrase: "inquire at",
        meaning: "seek information from attendants",
        arabic: "يَسْتَفْسِرُ عِنْدَ مَكْتَبِ المُسَاعَدَة",
        example: "You can inquire at the help desk if you cannot locate an archived manuscript.",
      },
    ],
    sentences: [
      {
        context: "Visitor Assistance",
        en: "He approached the help desk to ask how to print documents from his personal laptop.",
        ar: "تَوَجَّهَ إِلَى مَكْتَبِ المُسَاعَدَةِ لِيَسْأَلَ عَنْ كَيْفِيَّةِ طِبَاعَةِ المُسْتَنَدَاتِ مِنْ حَاسُوبِهِ المَحْمُولِ.",
      },
      {
        context: "Member Services",
        en: "Staff at the main help desk issue new membership cards and reset student passwords.",
        ar: "يُصْدِرُ المُوَظَّفُونَ فِي مَكْتَبِ المُسَاعَدَةِ الرَّئِيسِيِّ بِطَاقَاتِ عُضْوِيَّةٍ جَدِيدَةٍ وَيُعِيدُونَ ضَبْطَ كَلِمَاتِ المُرُورِ.",
      },
      {
        context: "Wayfinding",
        en: "Friendly attendants at the help desk provide floor maps to guide first-time visitors.",
        ar: "يُقَدِّمُ المُسَاعِدُونَ الوَدُودُونَ فِي مَكْتَبِ الاسْتِعْلَامَاتِ خَرَائِطَ لِلأَدْوَارِ لِإِرْشَادِ الزُّوَّارِ الجُدُدِ.",
      },
    ],
    exampleSentence:
      "He approached the help desk to ask how to print documents from his personal laptop.",
    exampleArabic:
      "تَوَجَّهَ إِلَى مَكْتَبِ المُسَاعَدَةِ لِيَسْأَلَ عَنْ كَيْفِيَّةِ طِبَاعَةِ المُسْتَنَدَاتِ مِنْ حَاسُوبِهِ المَحْمُولِ.",
  },
  apple: {
    id: "apple",
    arabic: "تُفَّاحَة",
    partOfSpeech: "noun",
    phonetic: "ˈæpəl",
    pronunciationTip: "Short 'a' sound /æ/: 'AP-ul' (/ˈæp.əl/).",
    collocations: [
      "crisp apple",
      "red apple",
      "green apple",
      "apple orchard",
      "bite into an apple",
      "apple pie",
    ],
    phrasalVerbs: [
      {
        phrase: "pick off",
        meaning: "harvest ripe fruit from branches",
        arabic: "يَقْطِفُ مِنَ الشَّجَرَة",
        example: "Children love to pick ripe apples off the orchard trees in autumn.",
      },
    ],
    sentences: [
      {
        context: "Market Stall",
        en: "She selected a bag of crisp red apples from the organic farm stall.",
        ar: "اخْتَارَتْ كِيسًا مِنَ التُّفَّاحِ الأَحْمَرِ المُقَرْمَشِ مِنْ كُشْكِ المَزْرَعَةِ العُضْوِيَّةِ.",
      },
      {
        context: "Healthy Snack",
        en: "Eating a fresh apple provides dietary fiber and essential vitamins.",
        ar: "تَنَاوُلُ تُفَّاحَةٍ طَازَجَةٍ يَمُدُّ الجِسْمَ بِالأَلْيَافِ الغِذَائِيَّةِ وَالفِيتَامِينَاتِ الأَسَاسِيَّةِ.",
      },
      {
        context: "Baking",
        en: "Grandmother sliced tart green apples to bake a fragrant cinnamon pie.",
        ar: "قَطَّعَتِ الجَدَّةُ التُّفَّاحَ الأَخْضَرَ الحَامِضَ لِخَبْزِ فَطِيرَةِ قِرْفَةٍ عَطِرَةٍ.",
      },
    ],
    exampleSentence: "She selected a bag of crisp red apples from the organic farm stall.",
    exampleArabic:
      "اخْتَارَتْ كِيسًا مِنَ التُّفَّاحِ الأَحْمَرِ المُقَرْمَشِ مِنْ كُشْكِ المَزْرَعَةِ العُضْوِيَّةِ.",
  },
  "sugar-cookie": {
    id: "sugar-cookie",
    arabic: "بَسْكُويْتُ السُّكَّر (كُوكِيز السُّكَّر)",
    partOfSpeech: "noun",
    phonetic: "ˈʃʊɡər ˈkʊki",
    pronunciationTip: "Pronounce 'SHOOG-er KOOK-ee' (/ˈʃʊɡ.ər ˈkʊk.i/).",
    collocations: [
      "decorated sugar cookies",
      "frosted sugar cookie",
      "holiday sugar cookies",
      "cutout sugar cookie",
      "sweet sugar cookie",
    ],
    phrasalVerbs: [
      {
        phrase: "cut out",
        meaning: "stamp shapes from rolled dough",
        arabic: "يُقَطِّعُ العَجِينَ بِقَوَالِبَ مُشَكَّلَة",
        example: "Children used metal star molds to cut out festive holiday sugar cookies.",
      },
    ],
    sentences: [
      {
        context: "Holiday Baking",
        en: "Children decorated star-shaped sugar cookies with pastel royal icing and shimmering sugar crystals.",
        ar: "زَيَّنَ الأَطْفَالُ بَسْكُويْتَ السُّكَّرِ عَلَى شَكْلِ نُجُومٍ بِصَلْصَةِ السُّكَّرِ وَالبِلَّوْرَاتِ اللَّامِعَةِ.",
      },
      {
        context: "Tender Texture",
        en: "A classic butter sugar cookie has a delicate crumb that snaps cleanly and melts on the tongue.",
        ar: "يَمْتَازُ بَسْكُويْتُ السُّكَّرِ بِالزُّبْدَةِ بِقَوَامٍ رَقِيقٍ يَنْكَسِرُ بِنُعُومَةٍ وَيَذُوبُ فِي الفَمِ.",
      },
      {
        context: "Bakery Treats",
        en: "The bakery counter showcased cheerful animal-shaped sugar cookies frosted in bright vibrant colors.",
        ar: "عَرَضَ كَاوَنْتَر المَخْبَزِ بَسْكُويْتَ سُكَّرٍ مَرِحًا عَلَى أَشْكَالِ حَيَوَانَاتٍ مُلَوَّنَةٍ.",
      },
    ],
    exampleSentence:
      "Children decorated star-shaped sugar cookies with pastel royal icing and shimmering sugar crystals.",
    exampleArabic:
      "زَيَّنَ الأَطْفَالُ بَسْكُويْتَ السُّكَّرِ عَلَى شَكْلِ نُجُومٍ بِصَلْصَةِ السُّكَّرِ وَالبِلَّوْرَاتِ اللَّامِعَةِ.",
  },
  bay: {
    id: "bay",
    arabic: "خَلِيج (جَوْنٌ بَحْرِيٌّ وَاسِع)",
    partOfSpeech: "noun",
    phonetic: "beɪ",
    pronunciationTip: "Long 'a' sound /eɪ/: 'BAY' (/beɪ/).",
    collocations: ["wide bay", "coastal bay", "sail across the bay", "harbor bay", "bay waters"],
    phrasalVerbs: [
      {
        phrase: "open out into",
        meaning: "expand into broader body of protected water",
        arabic: "يَنْفَتِحُ عَلَى خَلِيجٍ بَحْرِيّ",
        example: "The winding coastal estuary opened out into a wide, sparkling saltwater bay.",
      },
    ],
    sentences: [
      {
        context: "Geographic Feature",
        en: "The crescent-shaped bay provided calm, sheltered waters for yachts and fishing boats to dock.",
        ar: "وَفَّرَ الخَلِيجُ الهِلَالِيُّ الشَّكْلِ مِيَاهًا هَادِئَةً مَحْمِيَّةً لِرُسُوِّ اليُخُوتِ وَقَوَارِبِ الصَّيْدِ.",
      },
      {
        context: "Water Sports",
        en: "Kayakers and paddleboarders enjoy gliding across the placid surface of the sunlit bay.",
        ar: "يَسْتَمْتِعُ مُجَذِّفُو الكَايَاك وَأَلْوَاحِ التَّجْذِيفِ بِالانْزِلَاقِ عَبْرَ مِيَاهِ الخَلِيجِ الهَادِئَةِ.",
      },
      {
        context: "City Harbor",
        en: "A bustling waterfront promenade wraps around the natural bay, filled with seafood restaurants.",
        ar: "يَلْتَفُّ مَمْشَى سَاحِلِيٌّ حَيَوِيٌّ حَوْلَ الخَلِيجِ الطَّبِيعِيِّ، مَلِيئًا بِمَطَاعِمِ المَأْكُولَاتِ البَحْرِيَّةِ.",
      },
    ],
    exampleSentence:
      "The crescent-shaped bay provided calm, sheltered waters for yachts and fishing boats to dock.",
    exampleArabic:
      "وَفَّرَ الخَلِيجُ الهِلَالِيُّ الشَّكْلِ مِيَاهًا هَادِئَةً مَحْمِيَّةً لِرُسُوِّ اليُخُوتِ وَقَوَارِبِ الصَّيْدِ.",
  },
  prescription: {
    id: "prescription",
    arabic: "وَصْفَةٌ طِبِّيَّة (رُوشِتَّةُ العِلَاجِ وَالدَّوَاء)",
    partOfSpeech: "noun",
    phonetic: "prɪˈskrɪpʃən",
    pronunciationTip: "Pronounce 'pri-SKRIP-shun'.",
    collocations: ["write a prescription", "fill a prescription", "prescription medicine"],
    phrasalVerbs: [
      {
        phrase: "write out",
        meaning: "authorise medical drug in writing",
        arabic: "يَكْتُبُ وَصْفَةً طِبِّيَّة",
        example: "The doctor wrote out a prescription for antibiotics.",
      },
    ],
    sentences: [
      {
        context: "Pharmacy Order",
        en: "The physician wrote a prescription for daily blood pressure medication with three refills.",
        ar: "كَتَبَ الطَّبِيبُ وَصْفَةً طِبِّيَّةً لِدَوَاءِ ضَغْطِ الدَّمِ مَعَ إِمْكَانِيَّةِ التَّجْدِيدِ.",
      },
      {
        context: "Electronic Script",
        en: "The clinic sent the electronic prescription directly to my local neighborhood pharmacy.",
        ar: "أَرْسَلَتِ العِيَادَةُ الوَصْفَةَ الطِّبِّيَّةَ الإِلِكْتُرُونِيَّةَ إِلَى الصَّيْدَلِيَّةِ مُبَاشَرَةً.",
      },
      {
        context: "Instructions",
        en: "Always follow the dosage instructions printed on your prescription medicine label.",
        ar: "اتَّبِعْ دَائِمًا تَعْلِيمَاتِ الجُرْعَةِ المَطْبُوعَةِ عَلَى مُلْصَقِ الوَصْفَةِ الطِّبِّيَّةِ.",
      },
    ],
    exampleSentence:
      "The physician wrote a prescription for daily blood pressure medication with three refills.",
    exampleArabic:
      "كَتَبَ الطَّبِيبُ وَصْفَةً طِبِّيَّةً لِدَوَاءِ ضَغْطِ الدَّمِ مَعَ إِمْكَانِيَّةِ التَّجْدِيدِ.",
  },
  pills: {
    id: "pills",
    arabic: "حُبُوبُ الدَّوَاء (أَقْرَاصٌ عِلَاجِيَّةٌ أَوْ كَبْسُولَات)",
    partOfSpeech: "noun",
    phonetic: "pɪlz",
    pronunciationTip: "Short 'i' sound: 'PILZ' (/pɪlz/).",
    collocations: ["swallow pills", "take pills", "bottle of pills", "vitamin pills"],
    phrasalVerbs: [
      {
        phrase: "swallow with",
        meaning: "ingest oral tablets with water",
        arabic: "يَبْتَلِعُ الحُبُوبَ مَعَ المَاء",
        example: "He swallowed two pain relief pills with water.",
      },
    ],
    sentences: [
      {
        context: "Oral Medication",
        en: "The patient swallowed two pain relief pills with a full glass of water after dinner.",
        ar: "ابْتَلَعَ المَرِيضُ حَبَّتَيْنِ مِنْ مُسَكِّنِ الأَلَمِ مَعَ كَأْسِ مَاءٍ بَعْدَ العَشَاءِ.",
      },
      {
        context: "Organizer Box",
        en: "Elderly patients use daily pill organizer boxes with compartments to manage their doses.",
        ar: "يَسْتَخْدِمُ المَرْضَى عُلَبَ تَقْسِيمِ الحُبُوبِ اليَوْمِيَّةِ لِتَنْظِيمِ جُرُعَاتِهِمْ.",
      },
      {
        context: "Label Warnings",
        en: "The amber pill bottle was labeled with clear instructions to take one tablet every eight hours.",
        ar: "حَمَلَتْ عُلْبَةُ الحُبُوبِ تَعْلِيمَاتٍ وَاضِحَةً بِتَنَاوُلِ قُرْصٍ كُلَّ ٨ سَاعَاتٍ.",
      },
    ],
    exampleSentence:
      "The patient swallowed two pain relief pills with a full glass of water after dinner.",
    exampleArabic:
      "ابْتَلَعَ المَرِيضُ حَبَّتَيْنِ مِنْ مُسَكِّنِ الأَلَمِ مَعَ كَأْسِ مَاءٍ بَعْدَ العَشَاءِ.",
  },
  fryer: {
    id: "fryer",
    arabic: "قَلَّايَة (مِقْلَاةُ الزَّيْتِ العَمِيقَة)",
    partOfSpeech: "noun",
    phonetic: "ˈfraɪər",
    pronunciationTip: "Pronounce 'FRY-er' (/ˈfraɪ.ər/).",
    collocations: ["deep fryer", "commercial fryer", "air fryer"],
    phrasalVerbs: [
      {
        phrase: "fry in",
        meaning: "cook food submerged in bubbling oil",
        arabic: "يَقْلِي فِي الزَّيْت",
        example: "The line cook fried potato wedges in the deep fryer.",
      },
    ],
    sentences: [
      {
        context: "Fast Food",
        en: "The cook immersed baskets of freshly cut potatoes into the bubbling deep fryer.",
        ar: "غَمَسَ الطَّاهِي سِلَالَ البَطَاطِسِ المَقْطُوعَةِ فِي قَلَّايَةِ الزَّيْتِ السَّاخِنَةِ.",
      },
      {
        context: "Crispy Texture",
        en: "Chicken wings came out of the fryer golden, steaming hot, and delightfully crispy.",
        ar: "خَرَجَتْ أَجْنِحَةُ الدَّجَاجِ مِنَ القَلَّايَةِ ذَهَبِيَّةً وَسَاخِنَةً وَمُقَرْمَشَةً.",
      },
      {
        context: "Kitchen Cleaning",
        en: "Staff filtered the frying oil and scrubbed the stainless steel fryer daily.",
        ar: "قَامَ العُمَّالُ بِتَصْفِيَةِ زَيْتِ القَلْيِ وَتَنْظِيفِ القَلَّايَةِ يَوْمِيًّا.",
      },
    ],
    exampleSentence:
      "The cook immersed baskets of freshly cut potatoes into the bubbling deep fryer.",
    exampleArabic:
      "غَمَسَ الطَّاهِي سِلَالَ البَطَاطِسِ المَقْطُوعَةِ فِي قَلَّايَةِ الزَّيْتِ السَّاخِنَةِ.",
  },
  "station-clock": {
    id: "station-clock",
    arabic: "سَاعَةُ المَحَطَّة",
    partOfSpeech: "noun",
    collocations: ["use regularly", "check carefully", "keep handy"],
    sentences: [
      {
        context: "Synchronized Time",
        en: "The historic dial showed exactly two minutes before departure.",
        ar: "أَظْهَرَتْ سَاعَةُ المَحَطَّةِ التَّارِيخِيَّةُ دَقِيقَتَيْنِ قَبْلَ المُغَادَرَة.",
      },
      {
        context: "Concourse Meeting",
        en: "Friends agreed to meet beneath the giant four-sided timepiece.",
        ar: "اتَّفَقَ الأَصْدِقَاءُ عَلَى اللِّقَاءِ تَحْتَ السَّاعَةِ الكَبِيرَةِ فِي البَهْو.",
      },
      {
        context: "Accurate Punctuality",
        en: "All railway departures were synchronized with the central clock.",
        ar: "ضُبِطَتْ جَمِيعُ مُغَادَرَاتِ القِطَارَاتِ مَعَ السَّاعَةِ المَرْكَزِيَّة.",
      },
    ],
    exampleSentence: "The historic dial showed exactly two minutes before departure.",
    exampleArabic:
      "أَظْهَرَتْ سَاعَةُ المَحَطَّةِ التَّارِيخِيَّةُ دَقِيقَتَيْنِ قَبْلَ المُغَادَرَة.",
  },
  atm: {
    id: "atm",
    arabic: "صَرَّافٌ آلِيّ",
    partOfSpeech: "noun",
    collocations: ["use regularly", "check carefully", "keep handy"],
    sentences: [
      {
        context: "Cash Dispenser",
        en: "Insert your debit card to withdraw paper currency from the cash machine.",
        ar: "أَدْخِلْ بِطَاقَتَكَ لِسَحْبِ النُّقُودِ الوَرَقِيَّةِ مِنَ الصَّرَّافِ الآلِيّ.",
      },
      {
        context: "24-Hour Terminal",
        en: "The outdoor banking kiosk is accessible twenty-four hours a day.",
        ar: "يُمْكِنُ اسْتِخْدَامُ الصَّرَّافِ الآلِيِّ عَلَى مَدَارِ السَّاعَة.",
      },
      {
        context: "Touchscreen Machine",
        en: "Enter your four-digit secret PIN on the keypad to view balances.",
        ar: "أَدْخِلْ رَقْمَكَ السِّرِّيَّ فِي الصَّرَّافِ الآلِيِّ لِمَعْرِفَةِ الرَّصِيد.",
      },
    ],
    exampleSentence: "Insert your debit card to withdraw paper currency from the cash machine.",
    exampleArabic:
      "أَدْخِلْ بِطَاقَتَكَ لِسَحْبِ النُّقُودِ الوَرَقِيَّةِ مِنَ الصَّرَّافِ الآلِيّ.",
  },
};
