// Generated by scripts/shard_learning_content.mjs. Do not edit.
import type { LexiconEntry } from "../lexiconCore";
export const entries: Record<string, LexiconEntry> = {
  bookshelf: {
    id: "bookshelf",
    arabic: "رَفُّ الكُتُب / مَكْتَبَةٌ حَائِطِيَّة",
    partOfSpeech: "noun",
    phonetic: "ˈbʊk.ʃɛlf",
    pronunciationTip: "Compound word: 'BOOK' + 'SHELF'. Plural is 'bookshelves'.",
    collocations: [
      "fill the bookshelf",
      "wooden bookshelf",
      "on the bookshelf",
      "organize the bookshelf",
      "tall bookshelf",
      "dust the bookshelf",
    ],
    phrasalVerbs: [
      {
        phrase: "look through",
        meaning: "browse books on a shelf",
        arabic: "يَتَصَفَّحُ",
        example: "She looked through the bookshelf to find a dictionary.",
      },
      {
        phrase: "take down",
        meaning: "remove an item from a high shelf",
        arabic: "يُنْزِلُ شَيْئاً مِنْ مَكَانٍ عَالٍ",
        example: "He took down a heavy encyclopedia from the top bookshelf.",
      },
    ],
    sentences: [
      {
        context: "Reading Corner",
        en: "The tall bookshelf holds hundreds of historical and science novels.",
        ar: "تَحْمِلُ خِزَانَةُ الكُتُبِ الطَّوِيلَةُ مِئَاتِ الرِّوَايَاتِ التَّارِيخِيَّةِ وَالعِلْمِيَّةِ.",
      },
      {
        context: "Maintenance",
        en: "She spent Sunday afternoon dusting and organizing her bookshelf.",
        ar: "قَضَتْ بَعْدَ ظُهْرِ يَوْمِ الأَحَدِ فِي تَنْظِيفِ وَتَرْتِيبِ رَفِّ الكُتُبِ.",
      },
      {
        context: "Decor",
        en: "A small green plant looks lovely sitting on the middle bookshelf.",
        ar: "تَبْدُو النَّبْتَةُ الخَضْرَاءُ الصَّغِيرَةُ جَمِيلَةً عَلَى الرَّفِّ الأَوْسَطِ لِلْكُتُبِ.",
      },
    ],
    exampleSentence: "The tall bookshelf holds hundreds of historical and science novels.",
    exampleArabic:
      "تَحْمِلُ خِزَانَةُ الكُتُبِ الطَّوِيلَةُ مِئَاتِ الرِّوَايَاتِ التَّارِيخِيَّةِ وَالعِلْمِيَّةِ.",
  },
  cushion: {
    id: "cushion",
    arabic: "وِسَادَةُ زِينَة (خُدَّادِيَّة)",
    partOfSpeech: "noun",
    phonetic: "ˈkʊʃ.ən",
    pronunciationTip: "Short 'oo' sound /ʊ/ as in 'push' or 'book'.",
    collocations: [
      "soft cushion",
      "velvet cushion",
      "plump the cushion",
      "decorative cushion",
      "sofa cushion",
      "seat cushion",
    ],
    phrasalVerbs: [
      {
        phrase: "lean against",
        meaning: "rest your back against a cushion",
        arabic: "يَسْتَنِدُ عَلَى",
        example: "She leaned against the soft velvet cushion while watching TV.",
      },
      {
        phrase: "plump up",
        meaning: "fluff up a cushion",
        arabic: "يَنْفُشُ الوِسَادَة",
        example: "He plumped up the sofa cushions before the guests arrived.",
      },
    ],
    sentences: [
      {
        context: "Living Room Decor",
        en: "Colorful velvet cushions brighten up the neutral grey sofa.",
        ar: "تُضْفِي الخُدَّادِيَّاتُ المَخْمَلِيَّةُ المُلَوَّنَةُ حَيَوِيَّةً عَلَى الأَرِيكَةِ الرَّمَادِيَّةِ.",
      },
      {
        context: "Comfort",
        en: "Add a lumbar cushion to your office chair to relieve lower back pressure.",
        ar: "أَضِفْ وِسَادَةَ دَعْمِ الظَّهْرِ إِلَى كُرْسِيِّ المَكْتَبِ لِتَخْفِيفِ ضَغْطِ العَمُودِ الفِقْرِيِّ.",
      },
      {
        context: "Hospitality",
        en: "He arranged the embroidered cushions neatly across the daybed.",
        ar: "رَتَّبَ الوِسَادَاتِ المُطَرَّزَةَ بِأَنَاقَةٍ عَلَى سَرِيرِ الجُلُوسِ النَّهَارِيِّ.",
      },
    ],
    exampleSentence: "Colorful velvet cushions brighten up the neutral grey sofa.",
    exampleArabic:
      "تُضْفِي الخُدَّادِيَّاتُ المَخْمَلِيَّةُ المُلَوَّنَةُ حَيَوِيَّةً عَلَى الأَرِيكَةِ الرَّمَادِيَّةِ.",
  },
  pillow: {
    id: "pillow",
    arabic: "وِسَادَة / مِخَدَّة",
    partOfSpeech: "noun",
    phonetic: "ˈpɪl.oʊ",
    pronunciationTip: "Short 'i' sound followed by a soft 'low' (/oʊ/).",
    collocations: [
      "soft pillow",
      "fluff the pillow",
      "pillow fight",
      "feather pillow",
      "memory foam pillow",
      "rest on a pillow",
    ],
    phrasalVerbs: [
      {
        phrase: "rest on",
        meaning: "place one's head comfortably on a pillow",
        arabic: "يَسْتَرِيحُ عَلَى",
        example: "He rested his tired head on the soft feather pillow.",
      },
      {
        phrase: "prop up",
        meaning: "support with pillows",
        arabic: "يَسْنِدُ بِالوِسَادَة",
        example: "She propped herself up with two cushions to read in bed.",
      },
    ],
    sentences: [
      {
        context: "Bedtime Comfort",
        en: "He fluffed his pillow to get comfortable before falling asleep.",
        ar: "نَفَشَ وِسَادَتَهُ لِيَشْعُرَ بِالرَّاحَةِ قَبْلَ أَنْ يَسْتَغْرِقَ فِي النَّوْمِ.",
      },
      {
        context: "Sleep Health",
        en: "An orthopedic memory foam pillow supports neck alignment.",
        ar: "تُسَاعِدُ وِسَادَةُ الفُومِ الطِّبِّيَّةُ فِي دَعْمِ اسْتِقَامَةِ الرَّقَبَةِ.",
      },
      {
        context: "Bed Dressing",
        en: "Four decorative cushions and two sleeping pillows adorn the bed.",
        ar: "تُزَيِّنُ السَّرِيرَ أَرْبَعُ وِسَادَاتِ زِينَةٍ وَوِسَادَتَا نَوْمٍ مَرِيحَتَانِ.",
      },
    ],
    exampleSentence: "He fluffed his pillow to get comfortable before falling asleep.",
    exampleArabic:
      "نَفَشَ وِسَادَتَهُ لِيَشْعُرَ بِالرَّاحَةِ قَبْلَ أَنْ يَسْتَغْرِقَ فِي النَّوْمِ.",
  },
  highlighter: {
    id: "highlighter",
    arabic: "قَلَمُ تَمْيِيزٍ بَصَرِيّ (هَايْلَايْتَر)",
    partOfSpeech: "noun",
    phonetic: "ˈhaɪˌlaɪtər",
    pronunciationTip: "Pronounce 'HIGH-ly-ter' (/ˈhaɪˌlaɪ.tər/).",
    collocations: [
      "yellow highlighter",
      "fluorescent highlighter",
      "pastel highlighter",
      "highlight text",
      "chisel tip highlighter",
      "highlight important notes",
    ],
    phrasalVerbs: [
      {
        phrase: "stand out",
        meaning: "become prominent through bright coloring",
        arabic: "يَبْرُزُ بِمُسَاعَدَةِ التَّظْلِيل",
        example:
          "Using a neon highlighter makes key vocabulary terms stand out on the study guide.",
      },
    ],
    sentences: [
      {
        context: "Study Session",
        en: "She used a neon yellow highlighter to emphasize key vocabulary in her textbook.",
        ar: "اسْتَخْدَمَتْ قَلَمَ تَمْيِيزٍ نِيُونِيًّا أَصْفَرَ لِلتَّأْكِيدِ عَلَى المُفْرَدَاتِ الرَّئِيسِيَّةِ فِي كِتَابِهَا المَدْرَسِيِّ.",
      },
      {
        context: "Exam Preparation",
        en: "Highlighting major formulas helps you locate them quickly during review.",
        ar: "يُسَاعِدُ تَمْيِيزُ الصِّيَغِ الرَّئِيسِيَّةِ فِي العُثُورِ عَلَيْهَا بِسُرْعَةٍ خِلَالَ المُرَاجَعَةِ.",
      },
      {
        context: "Pastel Stationery",
        en: "Pastel highlighters provide soft, aesthetic colors that do not bleed through pages.",
        ar: "تُوَفِّرُ أَقْلَامُ التَّمْيِيزِ البَاسْتِيلِيَّةُ أَلْوَانًا نَاعِمَةً لَا تَنْفُذُ عَبْرَ الصَّفَحَاتِ.",
      },
    ],
    exampleSentence:
      "She used a neon yellow highlighter to emphasize key vocabulary in her textbook.",
    exampleArabic:
      "اسْتَخْدَمَتْ قَلَمَ تَمْيِيزٍ نِيُونِيًّا أَصْفَرَ لِلتَّأْكِيدِ عَلَى المُفْرَدَاتِ الرَّئِيسِيَّةِ فِي كِتَابِهَا المَدْرَسِيِّ.",
  },
  "mri-scan": {
    id: "mri-scan",
    arabic:
      "فَحْصُ الرَّنِينِ المَغْنَاطِيسِيّ (تَصْوِيرُ الرَّنِينِ المَغْنَاطِيسِيِّ عَالِي الدِّقَّة)",
    partOfSpeech: "noun",
    phonetic: "ˌɛm ɑːr ˈaɪ skæn",
    pronunciationTip: "Pronounce 'em-ar-EYE skan'.",
    collocations: ["brain MRI scan", "knee MRI scan", "schedule an MRI scan"],
    phrasalVerbs: [
      {
        phrase: "scan inside",
        meaning: "generate 3D magnetic cross-sectional bodily images",
        arabic: "يَفْحَصُ بِالرَّنِينِ المَغْنَاطِيسِيّ",
        example: "The specialist scanned inside the joint with MRI.",
      },
    ],
    sentences: [
      {
        context: "Advanced Diagnostics",
        en: "The doctor ordered a brain MRI scan to obtain crystal-clear cross-sectional images of the nerves.",
        ar: "طَلَبَ الطَّبِيبُ رَنِينًا مَغْنَاطِيسِيًّا لِلْمُخِّ لِلْحُصُولِ عَلَى صُوَرٍ شَدِيدَةِ الدِّقَّةِ.",
      },
      {
        context: "Procedure",
        en: "The patient lay completely still inside the cylindrical MRI scanner while it created detailed scans.",
        ar: "اسْتَلْقَى المَرِيضُ بِهُدُوءٍ دَاخِلَ جِهَازِ الرَّنِينِ لِإِنْشَاءِ صُوَرٍ مُفَصَّلَةٍ.",
      },
      {
        context: "Soft Tissue",
        en: "MRI scans excel at visualizing soft tissues including ligaments, cartilage, and spinal discs.",
        ar: "يَتَمَيَّزُ الرَّنِينُ المَغْنَاطِيسِيُّ بِإِظْهَارِ الأَرْبِطَةِ وَالغَضَارِيفِ وَأَقْرَاصِ الظَّهْرِ.",
      },
    ],
    exampleSentence:
      "The doctor ordered a brain MRI scan to obtain crystal-clear cross-sectional images of the nerves.",
    exampleArabic:
      "طَلَبَ الطَّبِيبُ رَنِينًا مَغْنَاطِيسِيًّا لِلْمُخِّ لِلْحُصُولِ عَلَى صُوَرٍ شَدِيدَةِ الدِّقَّةِ.",
  },
  crutches: {
    id: "crutches",
    arabic: "عَكَّازَات (عُكَّازَانِ لِمُسَاعَدَةِ المُصَابِينَ عَلَى المَشْي)",
    partOfSpeech: "noun",
    phonetic: "ˈkrʌtʃɪz",
    pronunciationTip: "Pronounce 'KRUTCH-iz' (/ˈkrʌtʃ.ɪz/).",
    collocations: [
      "walk on crutches",
      "pair of crutches",
      "aluminum crutches",
      "underarm crutches",
    ],
    phrasalVerbs: [
      {
        phrase: "walk along with",
        meaning: "move forward supporting weight on arm pads",
        arabic: "يَمْشِي عَلَى العَكَّازَات",
        example: "He walked along the hall with aluminum crutches.",
      },
    ],
    sentences: [
      {
        context: "Mobility Rehabilitation",
        en: "He walked carefully across the clinic hallway using a pair of lightweight aluminum crutches.",
        ar: "مَشَى بِحَذَرٍ فِي مَمَرِّ العِيَادَةِ مُسْتَخْدِمًا عَكَّازَيْنِ مِنَ الأَلُومِنْيُومِ الخَفِيفِ.",
      },
      {
        context: "Sprained Ankle",
        en: "The doctor adjusted the underarm crutches to match the height of the injured runner.",
        ar: "عَدَّلَ الطَّبِيبُ ارْتِفَاعَ العَكَّازَاتِ لِيُنَاسِبَ طُولَ العَدَّاءِ المُصَابِ.",
      },
      {
        context: "Non-Weight Bearing",
        en: "Using crutches allows a fractured leg bone to heal without bearing heavy body weight.",
        ar: "يُتِيحُ اسْتِخْدَامُ العَكَّازَاتِ لِعَظْمِ السَّاقِ المَكْسُورِ الِالْتِئَامَ دُونَ ضَغْطٍ.",
      },
    ],
    exampleSentence:
      "He walked carefully across the clinic hallway using a pair of lightweight aluminum crutches.",
    exampleArabic:
      "مَشَى بِحَذَرٍ فِي مَمَرِّ العِيَادَةِ مُسْتَخْدِمًا عَكَّازَيْنِ مِنَ الأَلُومِنْيُومِ الخَفِيفِ.",
  },
  timetable: {
    id: "timetable",
    arabic: "جَدْوَلُ المَوَاعِيد",
    partOfSpeech: "noun",
    collocations: ["check the timetable", "train timetable", "bus timetable"],
    sentences: [
      {
        context: "Travel & Hospitality",
        en: "Check the timetable for the next train departure.",
        ar: "تَحَقَّقْ مِنْ جَدْوَلِ المَوَاعِيدِ لِمُغَادَرَةِ القِطَارِ التَّالِي.",
      },
      {
        context: "Planning",
        en: "The new bus timetable will take effect on Monday.",
        ar: "سَيَدْخُلُ جَدْوَلُ مَوَاعِيدِ الحَافِلَاتِ الجَدِيدُ حَيِّزَ التَّنْفِيذِ يَوْمَ الاِثْنَيْن.",
      },
      {
        context: "Commuting",
        en: "He relies on the reliable train timetable to get to work.",
        ar: "يَعْتَمِدُ عَلَى جَدْوَلِ مَوَاعِيدِ القِطَارِ المُوَثَّقِ لِلذَّهَابِ إِلَى العَمَل.",
      },
    ],
    exampleSentence: "Check the timetable for the next train departure.",
    exampleArabic: "تَحَقَّقْ مِنْ جَدْوَلِ المَوَاعِيدِ لِمُغَادَرَةِ القِطَارِ التَّالِي.",
  },
};
