// Generated by scripts/shard_learning_content.mjs. Do not edit.
import type { LexiconEntry } from "../lexiconCore";
export const entries: Record<string, LexiconEntry> = {
  pot: {
    id: "pot",
    arabic: "قِدْر / حَلَّة",
    partOfSpeech: "noun",
    phonetic: "pɑːt",
    pronunciationTip: "Short open 'o' sound /ɑː/ as in 'hot' or 'not'.",
    collocations: [
      "cooking pot",
      "pot of soup",
      "heavy pot",
      "pot lid",
      "boil in a pot",
      "stainless steel pot",
    ],
    phrasalVerbs: [
      {
        phrase: "simmer away",
        meaning: "cook slowly in a pot",
        arabic: "يَنْضَجُ عَلَى نَارٍ هَادِئَة",
        example: "The beef stew simmered away in the large pot for three hours.",
      },
      {
        phrase: "stir up",
        meaning: "mix contents of a pot",
        arabic: "يُقَلِّبُ القِدْر",
        example: "Stir up the soup to prevent it from sticking to the bottom.",
      },
    ],
    sentences: [
      {
        context: "Family Dinner",
        en: "She simmered a large pot of aromatic lentil soup for the whole family.",
        ar: "طَبَخَتْ قِدْراً كَبِيراً مِنْ شُورْبَةِ العَدَسِ الشَّهِيَّةِ لِجَمِيعِ أَفْرَادِ العَائِلَةِ.",
      },
      {
        context: "Pasta Cooking",
        en: "Fill the deep pot with salted water and bring it to a rolling boil.",
        ar: "امْلَأِ القِدْرَ العَمِيقَ بِمَاءٍ مُمَلَّحٍ وَدَعْهُ يَصِلُ إِلَى دَرَجَةِ الغَلَيَانِ.",
      },
      {
        context: "Kitchen Equipment",
        en: "A cast-iron Dutch oven pot distributes heat evenly for slow braising.",
        ar: "يُوَزِّعُ قِدْرُ الزَّهْرِ الثَّقِيلُ الحَرَارَةَ بِالتَّسَاوِي لِلطَّهْيِ البَطِيءِ.",
      },
    ],
    exampleSentence: "She simmered a large pot of aromatic lentil soup for the whole family.",
    exampleArabic:
      "طَبَخَتْ قِدْراً كَبِيراً مِنْ شُورْبَةِ العَدَسِ الشَّهِيَّةِ لِجَمِيعِ أَفْرَادِ العَائِلَةِ.",
  },
  sunrise: {
    id: "sunrise",
    arabic: "شُرُوقُ الشَّمْس",
    partOfSpeech: "noun",
    phonetic: "ˈsʌn.raɪz",
    pronunciationTip: "Compound noun: 'SUN' (/sʌn/) + 'RISE' (/raɪz/).",
    collocations: [
      "at sunrise",
      "watch the sunrise",
      "golden sunrise",
      "before sunrise",
      "beautiful sunrise",
      "sunrise over the fields",
    ],
    phrasalVerbs: [
      {
        phrase: "rise up",
        meaning: "ascend into the sky",
        arabic: "تَشْرُقُ وَتَرْتَفِع",
        example: "The golden sun rose up above the eastern mountain ridge.",
      },
    ],
    sentences: [
      {
        context: "Morning Beauty",
        en: "The golden sunrise painted the morning sky in vibrant streaks of amber and rose.",
        ar: "لَوَّنَ شُرُوقُ الشَّمْسِ الذَّهَبِيُّ سَمَاءَ الصَّبَاحِ بِخُطُوطٍ بَدِيعَةٍ مِنَ العَنْبَرِ وَالوَرْدِيِّ.",
      },
      {
        context: "Farm Schedule",
        en: "The farmer starts his daily tractor chores at sunrise to beat the intense midday heat.",
        ar: "يَبْدَأُ المُزَارِعُ أَعْمَالَ الجَرَّارِ عِنْدَ الشُّرُوقِ لِتَفَادِي حَرَارَةِ الظَّهِيرَةِ الشَّدِيدَةِ.",
      },
      {
        context: "Birdsong",
        en: "Robins and songbirds began their melodious chorus the moment the first rays of sunrise appeared.",
        ar: "بَدَأَتِ العَصَافِيرُ تَغْرِيدَهَا العَذْبَ مَعَ ظُهُورِ أَوَّلِ خُيُوطِ شُرُوقِ الشَّمْسِ.",
      },
    ],
    exampleSentence:
      "The golden sunrise painted the morning sky in vibrant streaks of amber and rose.",
    exampleArabic:
      "لَوَّنَ شُرُوقُ الشَّمْسِ الذَّهَبِيُّ سَمَاءَ الصَّبَاحِ بِخُطُوطٍ بَدِيعَةٍ مِنَ العَنْبَرِ وَالوَرْدِيِّ.",
  },
  bat: {
    id: "bat",
    arabic: "مِضْرَبُ البَيْسْبُول (مِضْرَب)",
    partOfSpeech: "noun",
    phonetic: "bæt",
    pronunciationTip: "Short flat 'a' sound /æ/ as in 'cat': 'BAT' (/bæt/).",
    collocations: [
      "baseball bat",
      "wooden bat",
      "aluminum bat",
      "swing the bat",
      "grip the bat",
      "hit with a bat",
    ],
    phrasalVerbs: [
      {
        phrase: "bat away",
        meaning: "deflect or strike off",
        arabic: "يَصُدُّ بِالمِضْرَب",
        example: "The batter batted away foul pitches to stay in the count.",
      },
    ],
    sentences: [
      {
        context: "Baseball Practice",
        en: "He stepped up to home plate and gripped the smooth wooden bat.",
        ar: "تَقَدَّمَ إِلَى قَاعِدَةِ البِدَايَةِ وَأَمْسَكَ المِضْرَبَ الخَشَبِيَّ النَّاعِمَ بِإِحْكَامٍ.",
      },
      {
        context: "Game Highlight",
        en: "A powerful swing of the metal bat sent the ball flying into the outfield.",
        ar: "أَرْسَلَتْ ضَرْبَةٌ قَوِيَّةٌ بِالمِضْرَبِ المَعْدَنِيِّ الكُرَةَ مُحَلِّقَةً فِي المَلْعَبِ الخَارِجِيِّ.",
      },
      {
        context: "Safety",
        en: "Always wear a helmet when holding a bat near the batting cage.",
        ar: "ارْتَدِ دَائِمًا خُوذَةً عِنْدَ حَمْلِ المِضْرَبِ قُرْبَ قَفَصِ التَّدْرِيبِ.",
      },
    ],
    exampleSentence: "He stepped up to home plate and gripped the smooth wooden bat.",
    exampleArabic:
      "تَقَدَّمَ إِلَى قَاعِدَةِ البِدَايَةِ وَأَمْسَكَ المِضْرَبَ الخَشَبِيَّ النَّاعِمَ بِإِحْكَامٍ.",
  },
  lime: {
    id: "lime",
    arabic: "لَيْمُونٌ أَخْضَر (لَايْم)",
    partOfSpeech: "noun",
    phonetic: "laɪm",
    pronunciationTip: "Long 'i' sound /aɪ/: 'LYM' (/laɪm/).",
    collocations: [
      "tangy lime",
      "lime juice",
      "key lime pie",
      "slice of lime",
      "green lime",
      "lime wedge",
    ],
    phrasalVerbs: [
      {
        phrase: "drizzle with",
        meaning: "sprinkle citrus droplets lightly",
        arabic: "يَرُشُّ عَصِيرَ اللَّايْم",
        example: "Drizzle the fresh guacamole with freshly squeezed lime juice.",
      },
    ],
    sentences: [
      {
        context: "Market Stand",
        en: "He bought a basket of glossy green limes to season spicy chicken tacos.",
        ar: "اشْتَرَى سَلَّةً مِنْ لَيْمُونٍ أَخْضَرَ لَامِعٍ لِتَتْبِيلِ شَطَائِرِ التَّاكُو الحَارَّةِ.",
      },
      {
        context: "Refreshing Drinks",
        en: "Sparkling mineral water served with a slice of fresh lime makes an invigorating drink.",
        ar: "المِيَاهُ المَعْدِنِيَّةُ الفَوَّارَةُ المُقَدَّمَةُ مَعَ شَرِيحَةِ لَايْم طَازَجَةٍ مَشْرُوبٌ مُنْعِشٌ.",
      },
      {
        context: "Baking Specialty",
        en: "Key lime pie balances tart citrus juice with sweet condensed milk in a graham cracker crust.",
        ar: "تُوَازِنُ فَطِيرَةُ اللَّايْم بَيْنَ عَصِيرِ الحَمْضِيَّاتِ اللَّاذِعِ وَالحَلِيبِ المُحَلَّى فِي قَاعِدَةِ بَسْكُويْت.",
      },
    ],
    exampleSentence: "He bought a basket of glossy green limes to season spicy chicken tacos.",
    exampleArabic:
      "اشْتَرَى سَلَّةً مِنْ لَيْمُونٍ أَخْضَرَ لَامِعٍ لِتَتْبِيلِ شَطَائِرِ التَّاكُو الحَارَّةِ.",
  },
  swimsuit: {
    id: "swimsuit",
    arabic: "مَلَابِسُ السِّبَاحَة (مَايُوه / بَدْلَةُ السِّبَاحَة)",
    partOfSpeech: "noun",
    phonetic: "ˈswɪmsuːt",
    pronunciationTip: "Pronounce 'SWIM-soot' (/ˈswɪm.suːt/).",
    collocations: [
      "one-piece swimsuit",
      "wear a swimsuit",
      "damp swimsuit",
      "colorful swimsuit",
      "swimsuit cover-up",
    ],
    phrasalVerbs: [
      {
        phrase: "change into",
        meaning: "put on water garments before swimming",
        arabic: "يُبَدِّلُ مَلَابِسَهُ لِيَرْتَدِيَ المَايُوه",
        example: "They visited the bathhouse cabins to change into dry swimsuits.",
      },
    ],
    sentences: [
      {
        context: "Beach Preparation",
        en: "She packed a vibrant one-piece swimsuit and matching sunglasses for the coastal holiday.",
        ar: "حَزَمَتْ بَدْلَةَ سِبَاحَةٍ زَاهِيَةً مِنَ القِطْعَةِ الوَاحِدَةِ مَعَ نَظَّارَةٍ مُطَابِقَةٍ لِلْعُطْلَةِ.",
      },
      {
        context: "Water Aerobics",
        en: "Athletic swimsuits made of chlorine-resistant spandex provide freedom of movement in the waves.",
        ar: "تُوَفِّرُ مَلَابِسُ السِّبَاحَةِ الرِّيَاضِيَّةُ حُرِّيَّةَ الحَرَكَةِ بَيْنَ الأَمْوَاجِ.",
      },
      {
        context: "Post-Swim Care",
        en: "Hang wet swimsuits out on the balcony drying rack to air out after a day at the beach.",
        ar: "عَلِّقْ مَلَابِسَ السِّبَاحَةِ المُبَلَّلَةَ عَلَى حَبْلِ التَّجْفِيفِ لِتَتَهَوَّى بَعْدَ يَوْمِ الشَّاطِئِ.",
      },
    ],
    exampleSentence:
      "She packed a vibrant one-piece swimsuit and matching sunglasses for the coastal holiday.",
    exampleArabic:
      "حَزَمَتْ بَدْلَةَ سِبَاحَةٍ زَاهِيَةً مِنَ القِطْعَةِ الوَاحِدَةِ مَعَ نَظَّارَةٍ مُطَابِقَةٍ لِلْعُطْلَةِ.",
  },
  clam: {
    id: "clam",
    arabic: "مَحَار (مَحَارَة / رَخَوِيَّاتٌ ذَاتُ مِصْرَاعَيْن)",
    partOfSpeech: "noun",
    phonetic: "klæm",
    pronunciationTip: "Short 'a' sound /æ/: 'KLAM' (/klæm/).",
    collocations: ["giant clam", "clam shell", "fresh clams", "dig for clams", "clam chowder"],
    phrasalVerbs: [
      {
        phrase: "clam up",
        meaning: "close shell valves tightly shut against threat",
        arabic: "يُغْلِقُ صَدَفَتَهُ بِإِحْكَام",
        example: "The bivalve clammed up tightly as soon as a shadow passed overhead.",
      },
    ],
    sentences: [
      {
        context: "Bivalve Mollusk",
        en: "Digging in the wet tidal mudflats at low tide uncovered a bucketful of fresh hard-shell clams.",
        ar: "أَسْفَرَ الحَفْرُ فِي الطِّينِ عِنْدَ الجَزْرِ عَنْ جَمْعِ دَلْوٍ مَلِيءٍ بِمَحَارِ البَحْرِ الطَّازَجِ.",
      },
      {
        context: "Tropical Reef Wonder",
        en: "Giant clams with iridescent blue and green mantles grow up to four feet wide on tropical reefs.",
        ar: "يَنْمُو المَحَارُ العِمْلَاقُ ذُو الأَلْوَانِ الزَّرْقَاءِ وَالخَضْرَاءِ اللَّامِعَةِ لِيَصِلَ إِلى أَرْبَعَةِ أَقْدَامٍ.",
      },
      {
        context: "Culinary Favorite",
        en: "Steamed clams served with garlic butter and herbs are a quintessential coastal dinner delicacy.",
        ar: "يُعَدُّ المَحَارُ المَطْبُوخُ عَلَى البُخَارِ مَعَ زُبْدَةِ الثُّومِ وَالأَعْشَابِ وَجْبَةً سَاحِلِيَّةً لَذِيذَةً.",
      },
    ],
    exampleSentence:
      "Digging in the wet tidal mudflats at low tide uncovered a bucketful of fresh hard-shell clams.",
    exampleArabic:
      "أَسْفَرَ الحَفْرُ فِي الطِّينِ عِنْدَ الجَزْرِ عَنْ جَمْعِ دَلْوٍ مَلِيءٍ بِمَحَارِ البَحْرِ الطَّازَجِ.",
  },
  "diving-board": {
    id: "diving-board",
    arabic: "مِنَصَّةُ الغَوْص (لَوْحُ القَفْزِ إِلَى المَاءِ)",
    partOfSpeech: "noun",
    phonetic: "ˈdaɪvɪŋ bɔːrd",
    pronunciationTip: "Pronounce 'DY-ving bord'.",
    collocations: ["springboard diving board", "high diving board", "jump off the diving board"],
    phrasalVerbs: [
      {
        phrase: "spring off",
        meaning: "bounce off flexible board into pool",
        arabic: "يَقْفِزُ مِنْ لَوْحِ الغَوْص",
        example: "The diver sprang off the three-meter board.",
      },
    ],
    sentences: [
      {
        context: "Aquatic Sport",
        en: "The gymnast bounced on the high diving board before executing a double backflip.",
        ar: "قَفَزَ اللَّاعِبُ عَلَى لَوْحِ الغَوْصِ العَالِي قَبْلَ تَنْفِيذِ شِقْلَبَةٍ مُزْدَوَجَةٍ.",
      },
      {
        context: "Platform Heights",
        en: "The diving facility offers three-meter springboards and ten-meter concrete platforms.",
        ar: "تُوَفِّرُ مُنْشَأَةُ الغَوْصِ أَلْوَاحَ قَفْزٍ عَلَى ارْتِفَاعِ ٣ أَمْتَارٍ وَمِنَصَّاتِ ١٠ أَمْتَارٍ.",
      },
      {
        context: "Safety",
        en: "Swimmers must wait until the diving area below the board is completely clear.",
        ar: "يَجِبُ عَلَى السَّبَّاحِينَ الانْتِظَارُ حَتَّى تَمَامِ خُلُوِّ حَوْضِ الغَوْصِ.",
      },
    ],
    exampleSentence:
      "The gymnast bounced on the high diving board before executing a double backflip.",
    exampleArabic:
      "قَفَزَ اللَّاعِبُ عَلَى لَوْحِ الغَوْصِ العَالِي قَبْلَ تَنْفِيذِ شِقْلَبَةٍ مُزْدَوَجَةٍ.",
  },
  "admission-ticket": {
    id: "admission-ticket",
    arabic: "تَذْكِرَةُ دُخُول",
    partOfSpeech: "noun",
    collocations: ["use regularly", "check carefully", "keep handy"],
    sentences: [
      {
        context: "Entry Pass",
        en: "Scan the electronic barcode at the museum turnstile to enter.",
        ar: "امْسَحِ الرَّمْزَ الشَّرِيطِيَّ عَلَى تَذْكِرَةِ الدُّخُولِ لِعُبُورِ البَوَّابَة.",
      },
      {
        context: "Museum Voucher",
        en: "Students received discounted entry vouchers at the ticket desk.",
        ar: "حَصَلَ الطُّلَّابُ عَلَى خَصْمٍ عَلَى تَذْكِرَةِ دُخُولِ المَتْحَف.",
      },
      {
        context: "Exhibition Pass",
        en: "The universal pass granted all-day access to every floor and exhibit.",
        ar: "مَنَحَتْ تَذْكِرَةُ الدُّخُولِ الشَّامِلَةُ حَقَّ زِيَارَةِ جَمِيعِ المَعَارِض.",
      },
    ],
    exampleSentence: "Scan the electronic barcode at the museum turnstile to enter.",
    exampleArabic:
      "امْسَحِ الرَّمْزَ الشَّرِيطِيَّ عَلَى تَذْكِرَةِ الدُّخُولِ لِعُبُورِ البَوَّابَة.",
  },
};
