// Generated by scripts/shard_learning_content.mjs. Do not edit.
import type { LexiconEntry } from "../lexiconCore";
export const entries: Record<string, LexiconEntry> = {
  peeler: {
    id: "peeler",
    arabic: "قَشَّارَةُ خُضْرَاوَات",
    partOfSpeech: "noun",
    phonetic: "ˈpiː.lər",
    pronunciationTip: "Long 'ee' vowel /iː/ as in 'peel'.",
    collocations: [
      "potato peeler",
      "vegetable peeler",
      "sharp peeler",
      "swivel peeler",
      "Y-peeler",
      "peel with a peeler",
    ],
    phrasalVerbs: [
      {
        phrase: "peel off",
        meaning: "remove the skin of a fruit or vegetable",
        arabic: "يُقَشِّرُ القِشْرَة",
        example: "Peel off the skin of the apples before slicing them for the pie.",
      },
    ],
    sentences: [
      {
        context: "Prepping Potatoes",
        en: "She peeled five large russet potatoes quickly using a sharp swivel peeler.",
        ar: "قَشَّرَتْ خَمْسَ حَبَّاتِ بَطَاطِسَ كَبِيرَةٍ سَرِيعاً بِاسْتِخْدَامِ قَشَّارَةٍ حَادَّةٍ.",
      },
      {
        context: "Carrot Ribbons",
        en: "Use a vegetable peeler to shave thin, elegant ribbons of carrot for salads.",
        ar: "اسْتَخْدِمْ قَشَّارَةَ الخُضَارِ لِعَمَلِ شَرَائِطَ جَزَرٍ رَفِيعَةٍ وَأَنِيقَةٍ لِلسَّلَطَاتِ.",
      },
      {
        context: "Citrus Zest",
        en: "Remove wide strips of lemon peel with a peeler to infuse the syrup.",
        ar: "انْزِعْ شَرَائِطَ عَرِيضَةً مِنْ قِشْرِ اللَّيْمُونِ بِالقَشَّارَةِ لِتَنْكِيهِ القَطْرِ.",
      },
    ],
    exampleSentence: "She peeled five large russet potatoes quickly using a sharp swivel peeler.",
    exampleArabic:
      "قَشَّرَتْ خَمْسَ حَبَّاتِ بَطَاطِسَ كَبِيرَةٍ سَرِيعاً بِاسْتِخْدَامِ قَشَّارَةٍ حَادَّةٍ.",
  },
  rake: {
    id: "rake",
    arabic: "مِشْطُ حَدِيقَة (مِجْرَفَةُ أَوْرَاق)",
    partOfSpeech: "noun",
    phonetic: "reɪk",
    pronunciationTip: "Long 'a' vowel /eɪ/ as in 'make' or 'cake'.",
    collocations: [
      "leaf rake",
      "garden rake",
      "rake leaves",
      "pile of leaves with a rake",
      "steel garden rake",
      "smooth the soil with a rake",
    ],
    phrasalVerbs: [
      {
        phrase: "rake up",
        meaning: "gather leaves or debris into piles",
        arabic: "يَجْمَعُ بِالمِشْط",
        example: "Rake up the fallen autumn leaves across the lawn into piles.",
      },
      {
        phrase: "smooth out",
        meaning: "level soil using a metal rake",
        arabic: "يُسَوِّي الأَرْض",
        example: "Smooth out the garden bed before sowing flower seeds.",
      },
    ],
    sentences: [
      {
        context: "Autumn Cleanup",
        en: "The children had fun raking up golden autumn leaves into a gigantic pile to jump in.",
        ar: "اسْتَمْتَعَ الأَطْفَالُ بِجَمْعِ أَوْرَاقِ الخَرِيفِ الذَّهَبِيَّةِ بِالمِشْطِ فِي كَوْمَةٍ كَبِيرَةٍ.",
      },
      {
        context: "Soil Leveling",
        en: "He used a heavy steel garden rake to break up soil clods and level the seedbed.",
        ar: "اسْتَخْدَمَ مِشْطَ حَدِيقَةٍ صُلْباً لِتَفْتِيتِ كُتَلِ التُّرْبَةِ وَتَسْوِيَةِ مَهْدِ البُذُورِ.",
      },
      {
        context: "Gravel Driveways",
        en: "Smooth the gravel driveway with a wide rake to eliminate ruts after heavy rain.",
        ar: "سَوِّ مَمَرَّ الحَصَى بِمِشْطٍ عَرِيضٍ لِإِزَالَةِ الأَخَادِيدِ بَعْدَ هُطُولِ المَطَرِ.",
      },
    ],
    exampleSentence:
      "The children had fun raking up golden autumn leaves into a gigantic pile to jump in.",
    exampleArabic:
      "اسْتَمْتَعَ الأَطْفَالُ بِجَمْعِ أَوْرَاقِ الخَرِيفِ الذَّهَبِيَّةِ بِالمِشْطِ فِي كَوْمَةٍ كَبِيرَةٍ.",
  },
  saucer: {
    id: "saucer",
    arabic: "صَحْنُ الفِنْجَان",
    partOfSpeech: "noun",
    phonetic: "ˈsɔː.sər",
    pronunciationTip: "First syllable has the 'aw' vowel /ɔː/ as in 'saw' or 'autumn'.",
    collocations: [
      "cup and saucer",
      "place on the saucer",
      "matching saucer",
      "porcelain saucer",
      "teacup saucer",
      "spill onto the saucer",
    ],
    phrasalVerbs: [
      {
        phrase: "set down on",
        meaning: "place a cup safely on its saucer",
        arabic: "يَضَعُ الفِنْجَانَ عَلَى صَحْنِهِ",
        example: "She set down her teacup gently on the matching saucer.",
      },
    ],
    sentences: [
      {
        context: "Formal Tea",
        en: "The porcelain teacup rested neatly atop its matching gold-trimmed saucer.",
        ar: "اسْتَقَرَّ فِنْجَانُ الشَّايِ الخَزَفِيُّ بِأَنَاقَةٍ فَوْقَ صَحْنِهِ المُطَرَّزِ بِالذَّهَبِ.",
      },
      {
        context: "Preventing Spills",
        en: "A small saucer catches tea drips and protects fine wooden tabletops.",
        ar: "يَمْنَعُ صَحْنُ الفِنْجَانِ الصَّغِيرُ قَطَرَاتِ الشَّايِ مِنْ تَلْوِيثِ الطَّاوِلَةِ الخَشَبِيَّةِ.",
      },
      {
        context: "Hospitality",
        en: "The waiter served the espresso with a sugar cube placed on the saucer rim.",
        ar: "قَدَّمَ النَّادِلُ الإِسْبْرِيسُو مَعَ مُكَعَّبِ سُكَّرٍ مَوْضُوعٍ عَلَى حَافَّةِ صَحْنِ الفِنْجَانِ.",
      },
    ],
    exampleSentence: "The porcelain teacup rested neatly atop its matching gold-trimmed saucer.",
    exampleArabic:
      "اسْتَقَرَّ فِنْجَانُ الشَّايِ الخَزَفِيُّ بِأَنَاقَةٍ فَوْقَ صَحْنِهِ المُطَرَّزِ بِالذَّهَبِ.",
  },
  stem: {
    id: "stem",
    arabic: "سَاق (سَاقُ النَّبَات)",
    partOfSpeech: "noun",
    phonetic: "stɛm",
    pronunciationTip: "Short 'e' /ɛ/ as in 'bed' or 'red'.",
    collocations: [
      "flower stem",
      "sturdy stem",
      "green stem",
      "cut the stem",
      "woody stem",
      "hollow stem",
    ],
    phrasalVerbs: [
      {
        phrase: "stem from",
        meaning: "(figurative) originate or arise from",
        arabic: "يَنْبُعُ مِنْ",
        example:
          "Her passion for botanicals stems from childhood visits to her grandmother's garden.",
      },
    ],
    sentences: [
      {
        context: "Plant Physiology",
        en: "The upright green stem transports moisture and nutrients from roots to leaves.",
        ar: "يَنْقُلُ السَّاقُ الأَخْضَرُ القَائِمُ الرُّطُوبَةَ وَالمَوَادَّ الغِذَائِيَّةَ مِنَ الجُذُورِ إِلَى الأَوْرَاقِ.",
      },
      {
        context: "Vase Preparation",
        en: "Trim flower stems diagonally under cool running water before arranging them.",
        ar: "قُصَّ سِيقَانَ الزُّهُورِ مَائِلاً تَحْتَ مَاءٍ جَارٍ بَارِدٍ قَبْلَ تَنْسِيقِهَا.",
      },
      {
        context: "Structural Support",
        en: "A bamboo cane was tied alongside the fragile tomato stem to prevent snapping.",
        ar: "رُبِطَتْ عَصَا خَيْزُرَانٍ بِجَانِبِ سَاقِ الطَّمَاطِمِ الرَّقِيقِ لِمَنْعِ انْكِسَارِهِ.",
      },
    ],
    exampleSentence: "The sunflower possessed a thick hairy stem that supported its giant blossom.",
    exampleArabic:
      "تَمَيَّزَتْ زَهْرَةُ عَبَّادِ الشَّمْسِ بِسَاقٍ سَمِيكَةٍ مُشَعِّرَةٍ دَعَمَتْ زَهْرَتَهَا العِمْلاقَةَ.",
  },
  snail: {
    id: "snail",
    arabic: "حَلَزُون (بَزَّاق)",
    partOfSpeech: "noun",
    phonetic: "sneɪl",
    pronunciationTip: "Long 'a' diphthong /eɪ/ as in 'tail' or 'rail'.",
    collocations: [
      "garden snail",
      "snail shell",
      "snail trail",
      "slow as a snail",
      "snail pace",
      "spiral snail",
    ],
    phrasalVerbs: [
      {
        phrase: "creep along",
        meaning: "move forward very slowly",
        arabic: "يَزْحَفُ بِبُطْء",
        example: "The garden snail creeps along the damp garden wall.",
      },
    ],
    sentences: [
      {
        context: "Slow Movement",
        en: "A garden snail moved at a leisurely pace, leaving a glistening silvery trail behind.",
        ar: "تَحَرَّكَ حَلَزُونُ الحَدِيقَةِ بِبُطْءٍ تَارِكاً خَلْفَهُ أَثَراً فِضِّيّاً لَامِعاً.",
      },
      {
        context: "Protective Shell",
        en: "When touched gently, the cautious snail retreated completely inside its spiral shell.",
        ar: "عِنْدَ لَمْسِهِ بِلُطْفٍ، تَرَاجَعَ الحَلَزُونُ الحَذِرُ تَمَاماً دَاخِلَ قَوْقَعَتِهِ اللَّوْلَبِيَّةِ.",
      },
      {
        context: "Garden Foraging",
        en: "Snails venture out on damp humid evenings to feed on succulent hosta leaves.",
        ar: "تَخْرُجُ الحَلَازِينُ فِي الأَمْسِيَاتِ الرَّطْبَةِ لِلتَّغَذِّي عَلَى أَوْرَاقِ النَّبَاتَاتِ الغَضَّةِ.",
      },
    ],
    exampleSentence: "A small brown snail climbed slowly up the wet fence post.",
    exampleArabic: "تَسَلَّقَ حَلَزُونٌ بُنِّيٌّ صَغِيرٌ بِبُطْءٍ عَمُودَ السِّيَاجِ الرَّطْبَ.",
  },
  stapler: {
    id: "stapler",
    arabic: "دَبَّاسَة (دَبَّاسَةُ أَوْرَاق)",
    partOfSpeech: "noun",
    phonetic: "ˈsteɪplər",
    pronunciationTip: "Pronounce 'STAY-pler' (/ˈsteɪ.plər/).",
    collocations: [
      "desktop stapler",
      "box of staples",
      "stapler jam",
      "press the stapler",
      "staple papers together",
    ],
    phrasalVerbs: [
      {
        phrase: "staple together",
        meaning: "bind documents with metal clips",
        arabic: "يَدْبُسُ مَعًا",
        example: "Staple together the three pages of your research report.",
      },
    ],
    sentences: [
      {
        context: "Paper Organization",
        en: "The teacher pressed down on the desktop stapler to bind the multi-page exam.",
        ar: "ضَغَطَ المُعَلِّمُ عَلَى دَبَّاسَةِ المَكْتَبِ لِتَثْبِيتِ صَفَحَاتِ الاِمْتِحَانِ المُتَعَدِّدَةِ.",
      },
      {
        context: "Refilling Supplies",
        en: "She opened the metal hinge to reload a fresh row of wire staples.",
        ar: "فَتَحَتِ المِفْصَلَةَ المَعْدَنِيَّةَ لِإِعَادَةِ تَعْبِئَةِ صَفٍّ جَدِيدٍ مِنْ دَبَابِيسِ السِّلْكِ.",
      },
      {
        context: "Desk Setup",
        en: "A heavy-duty manual stapler sits beside the teacher's paper tray.",
        ar: "تَسْتَقِرُّ دَبَّاسَةٌ يَدَوِيَّةٌ شَدِيدَةُ التَّحَمُّلِ بِجَانِبِ دُرْجِ أَوْرَاقِ المُعَلِّمِ.",
      },
    ],
    exampleSentence: "The teacher pressed down on the desktop stapler to bind the multi-page exam.",
    exampleArabic:
      "ضَغَطَ المُعَلِّمُ عَلَى دَبَّاسَةِ المَكْتَبِ لِتَثْبِيتِ صَفَحَاتِ الاِمْتِحَانِ المُتَعَدِّدَةِ.",
  },
  "return-desk": {
    id: "return-desk",
    arabic: "مَكْتَبُ إِعَادَةِ الكُتُب",
    partOfSpeech: "noun",
    phonetic: "rɪˈtɜːrn dɛsk",
    pronunciationTip: "Pronounce 'rih-TURN desk' (/rɪˈtɜːrn dɛsk/).",
    collocations: [
      "book return desk",
      "drop off at return desk",
      "automated return desk",
      "return desk bin",
      "library return counter",
    ],
    phrasalVerbs: [
      {
        phrase: "drop off",
        meaning: "deliver borrowed materials back to the desk",
        arabic: "يُسَلِّمُ الكُتُبَ المُسْتَعَارَة",
        example:
          "Don't forget to drop off your checked-out books at the return desk before Friday.",
      },
    ],
    sentences: [
      {
        context: "Book Check-In",
        en: "She dropped her borrowed novels into the padded slot at the library return desk.",
        ar: "وَضَعَتْ رِوَايَاتِهَا المُسْتَعَارَةَ فِي الفَتْحَةِ المُبَطَّنَةِ عِنْدَ مَكْتَبِ إِعَادَةِ الكُتُبِ فِي المَكْتَبَةِ.",
      },
      {
        context: "Automated Check-in",
        en: "The automated return desk instantly scans RFID tags and clears the borrower's account.",
        ar: "يَمْسَحُ مَكْتَبُ الإِعَادَةِ الآلِيُّ شَرَائِحَ التَّعَرُّفِ اللَّاسِلْكِيَّةَ فَوْرِيًّا وَيُبْرِئُ ذِمَّةَ المُسْتَعِيرِ.",
      },
      {
        context: "Circulation Lobby",
        en: "The return counter is located conveniently near the main entrance for quick drop-offs.",
        ar: "يَقَعُ مَكْتَبُ الإِعَادَةِ بِمَوْقِعٍ مُلَائِمٍ بِالقُرْبِ مِنَ المَدْخَلِ الرَّئِيسِيِّ لِتَسْلِيمٍ سَرِيعٍ.",
      },
    ],
    exampleSentence:
      "She dropped her borrowed novels into the padded slot at the library return desk.",
    exampleArabic:
      "وَضَعَتْ رِوَايَاتِهَا المُسْتَعَارَةَ فِي الفَتْحَةِ المُبَطَّنَةِ عِنْدَ مَكْتَبِ إِعَادَةِ الكُتُبِ فِي المَكْتَبَةِ.",
  },
  onion: {
    id: "onion",
    arabic: "بَصَلَة",
    partOfSpeech: "noun",
    phonetic: "ˈʌnjən",
    pronunciationTip: "Pronounce 'UN-yun' (/ˈʌn.jən/).",
    collocations: [
      "chopped onion",
      "diced onion",
      "red onion",
      "yellow onion",
      "sweet onion",
      "caramelized onions",
    ],
    phrasalVerbs: [
      {
        phrase: "fry up",
        meaning: "sauté in a pan until golden and fragrant",
        arabic: "يُشَوِّحُ فِي الزَّيْتِ حَتَّى يَذْبُل",
        example: "Fry up the diced yellow onions until translucent and golden brown.",
      },
    ],
    sentences: [
      {
        context: "Culinary Staple",
        en: "He peeled and finely chopped a yellow onion to build the savory soup base.",
        ar: "قَشَّرَ وَفَرَمَ بَصَلَةً صَفْرَاءَ نَاعِمًا لِتَكْوِينِ قَاعِدَةِ الحَسَاءِ الشَّهِيَّةِ.",
      },
      {
        context: "Salad Topping",
        en: "Crisp red onion rings add color and a mild bite to fresh Mediterranean salads.",
        ar: "تُضِيفُ حَلَقَاتُ البَصَلِ الأَحْمَرِ المُقَرْمَشَةُ لَوْنًا وَمَذَاقًا حَيَوِيًّا لِلسَّلَطَاتِ.",
      },
      {
        context: "Caramelizing",
        en: "Slowly cooked in butter, sweet caramelized onions develop deep rich flavor.",
        ar: "عِنْدَ طَهْيِهِ بِبُطْءٍ فِي الزُّبْدَةِ، يَكْتَسِبُ البَصَلُ المُكَرْمَلُ الحُلْوُ نَكْهَةً غَنِيَّةً عَمِيقَةً.",
      },
    ],
    exampleSentence: "He peeled and finely chopped a yellow onion to build the savory soup base.",
    exampleArabic:
      "قَشَّرَ وَفَرَمَ بَصَلَةً صَفْرَاءَ نَاعِمًا لِتَكْوِينِ قَاعِدَةِ الحَسَاءِ الشَّهِيَّةِ.",
  },
  "credit-card": {
    id: "credit-card",
    arabic: "بِطَاقَةُ ائْتِمَان",
    partOfSpeech: "noun",
    collocations: ["use regularly", "check carefully", "keep handy"],
    sentences: [
      {
        context: "Plastic Payment",
        en: "I tapped the contactless payment card on the terminal to pay.",
        ar: "مَرَّرْتُ بِطَاقَةَ الائْتِمَانِ اللَّاتَلَامُسِيَّةَ عَلَى الجِهَازِ لِلدَّفْع.",
      },
      {
        context: "Secure Chip",
        en: "The embedded microchip protects transactions from fraudulent activity.",
        ar: "تَحْمِي الشَّرِيحَةُ الذَّكِيَّةُ فِي بِطَاقَةِ الائْتِمَانِ مِنَ الِاحْتِيَال.",
      },
      {
        context: "Monthly Limit",
        en: "My banking provider increased my monthly spending allowance.",
        ar: "رَفَعَ البَنْكُ الحَدَّ الِائْتِمَانِيَّ الشَّهْرِيَّ لِبِطَاقَةِ الائْتِمَان.",
      },
    ],
    exampleSentence: "I tapped the contactless payment card on the terminal to pay.",
    exampleArabic:
      "مَرَّرْتُ بِطَاقَةَ الائْتِمَانِ اللَّاتَلَامُسِيَّةَ عَلَى الجِهَازِ لِلدَّفْع.",
  },
  "oatmeal-cookie": {
    id: "oatmeal-cookie",
    arabic: "بَسْكُويْتُ الشُّوفَان (كُوكِيز الشُّوفَان)",
    partOfSpeech: "noun",
    phonetic: "ˈoʊtmiːl ˈkʊki",
    pronunciationTip: "Pronounce 'OHT-meel KOOK-ee' (/ˈoʊt.miːl ˈkʊk.i/).",
    collocations: [
      "oatmeal raisin cookie",
      "chewy oatmeal cookie",
      "cinnamon oatmeal cookie",
      "healthy oatmeal cookies",
      "batch of oatmeal cookies",
    ],
    phrasalVerbs: [
      {
        phrase: "stir into",
        meaning: "mix dry rolled oats into creamy butter batter",
        arabic: "يُقَلِّبُ الشُّوفَانَ دَاخِلَ الخَلِيط",
        example: "Stir rolled oats and plump raisins into the spiced cinnamon batter.",
      },
    ],
    sentences: [
      {
        context: "Home Baked",
        en: "She baked a warm batch of chewy oatmeal raisin cookies spiced with cinnamon and nutmeg.",
        ar: "خَبَزَتْ دُفْعَةً دَافِئَةً مِنْ كُوكِيز الشُّوفَانِ وَالزَّبِيبِ المَطَّاطِيِّ المُتَبَّلِ بِالقِرْفَةِ.",
      },
      {
        context: "Wholesome Snack",
        en: "Whole rolled oats provide healthy fiber, making oatmeal cookies a nourishing afternoon snack.",
        ar: "تَمُدُّ حُبُوبُ الشُّوفَانِ الكَامِلَةُ الجِسْمَ بِالأَلْيَافِ، مِمَّا يَجْعَلُ كُوكِيز الشُّوفَانِ وَجْبَةً مُغَذِّيَةً.",
      },
      {
        context: "Bakery Selection",
        en: "The bakery offers delicious oatmeal cookies packed with dried cranberries and toasted pecans.",
        ar: "يُقَدِّمُ المَخْبَزُ كُوكِيز شُوفَانٍ لَذِيذًا مَلِيئًا بِالتُّوتِ المُجَفَّفِ وَجَوْزِ البِيكَانِ المُحَمَّصِ.",
      },
    ],
    exampleSentence:
      "She baked a warm batch of chewy oatmeal raisin cookies spiced with cinnamon and nutmeg.",
    exampleArabic:
      "خَبَزَتْ دُفْعَةً دَافِئَةً مِنْ كُوكِيز الشُّوفَانِ وَالزَّبِيبِ المَطَّاطِيِّ المُتَبَّلِ بِالقِرْفَةِ.",
  },
  wafer: {
    id: "wafer",
    arabic: "وِيفَر (بَسْكُويْتٌ رَقِيقٌ هَشّ)",
    partOfSpeech: "noun",
    phonetic: "ˈweɪfər",
    pronunciationTip: "Pronounce 'WAY-fer' (/ˈweɪ.fər/).",
    collocations: [
      "chocolate wafer",
      "vanilla cream wafer",
      "crisp wafer biscuit",
      "ice cream wafer",
      "layered wafer",
    ],
    phrasalVerbs: [
      {
        phrase: "snap off",
        meaning: "break crisp thin biscuit into pieces",
        arabic: "يَقْصِمُ رَقَاقَةَ الوِيفَر",
        example: "He snapped off a piece of the chocolate-covered wafer stick.",
      },
    ],
    sentences: [
      {
        context: "Crispy Layers",
        en: "Crisp multilayered chocolate wafers filled with sweet hazelnut cream are light and crunchy.",
        ar: "تَمْتَازُ رَقَائِقُ الوِيفَر الشُّوكُولَاتِيَّةُ الهَشَّةُ المَحْشُوَّةُ بِكْرِيمَةِ البُنْدُقِ بِخِفَّتِهَا وَقَرْمَشَتِهَا.",
      },
      {
        context: "Ice Cream Garnish",
        en: "The sundae was served with a fan-shaped crisp vanilla wafer perched atop the whipped cream.",
        ar: "قُدِّمَتِ المُثَلَّجَاتُ مَعَ رَقَاقَةِ وِيفَر فَانِيلْيَا هَشَّةٍ عَلَى شَكْلِ مِرْوَحَةٍ فَوْقَ الكْرِيمَةِ.",
      },
      {
        context: "Snack Package",
        en: "Foil packaging preserves the delicate crunch and fresh aroma of thin sweet wafers.",
        ar: "تَحْفَظُ الأَغْلِفَةُ المَعْدَنِيَّةُ القَرْمَشَةَ الرَّقِيقَةَ وَالرَّائِحَةَ الطَّازَجَةَ لِرَقَائِقِ الوِيفَر.",
      },
    ],
    exampleSentence:
      "Crisp multilayered chocolate wafers filled with sweet hazelnut cream are light and crunchy.",
    exampleArabic:
      "تَمْتَازُ رَقَائِقُ الوِيفَر الشُّوكُولَاتِيَّةُ الهَشَّةُ المَحْشُوَّةُ بِكْرِيمَةِ البُنْدُقِ بِخِفَّتِهَا وَقَرْمَشَتِهَا.",
  },
  mixer: {
    id: "mixer",
    arabic: "خَلَّاط (عَجَّانَة / خَفَّاقَةٌ كَهْرَبَائِيَّة)",
    partOfSpeech: "noun",
    phonetic: "ˈmɪksər",
    pronunciationTip: "Pronounce 'MIK-ser' (/ˈmɪk.sər/).",
    collocations: [
      "electric stand mixer",
      "hand mixer",
      "mixer bowl",
      "mixer dough hook",
      "turn on the mixer",
    ],
    phrasalVerbs: [
      {
        phrase: "beat together",
        meaning: "blend ingredients thoroughly using spinning beaters",
        arabic: "يَخْفِقُ بِالعَجَّانَةِ الكَهْرَبَائِيَّة",
        example: "Use the stand mixer to beat together butter and sugar until pale and fluffy.",
      },
    ],
    sentences: [
      {
        context: "Kitchen Appliance",
        en: "The electric stand mixer effortlessly kneaded heavy bread dough with its spiral metal hook.",
        ar: "عَجَنَتِ العَجَّانَةُ الكَهْرَبَائِيَّةُ عَجِينَ الخُبْزِ الثَّقِيلَ بِسُهُولَةٍ بِخُطَّافِهَا المَعْدَنِيِّ.",
      },
      {
        context: "Whipping Cream",
        en: "She switched the mixer to high speed to whip egg whites into stiff glossy meringue peaks.",
        ar: "شَغَّلَتِ الخَفَّاقَةَ عَلَى سُرْعَةٍ عَالِيَةٍ لِخَفْقِ بَيَاضِ البَيْضِ إِلَى مِيرَانْغ بَرَّاقٍ.",
      },
      {
        context: "Bakery Workstation",
        en: "Commercial floor mixers handle fifty-pound batches of artisan pastry dough in industrial bakeries.",
        ar: "تَتَعَامَلُ الخَلَّاطَاتُ التِّجَارِيَّةُ الضَّخْمَةُ مَعَ دُفْعَاتٍ تَزِنُ خَمْسِينَ رَطْلًا فِي المَخَابِزِ.",
      },
    ],
    exampleSentence:
      "The electric stand mixer effortlessly kneaded heavy bread dough with its spiral metal hook.",
    exampleArabic:
      "عَجَنَتِ العَجَّانَةُ الكَهْرَبَائِيَّةُ عَجِينَ الخُبْزِ الثَّقِيلَ بِسُهُولَةٍ بِخُطَّافِهَا المَعْدَنِيِّ.",
  },
  "maternity-ward": {
    id: "maternity-ward",
    arabic: "جَنَاحُ الوِلَادَة (قِسْمُ رِعَايَةِ الأُمَّهَاتِ وَالمَوَالِيد)",
    partOfSpeech: "noun",
    phonetic: "məˈtɜːrnɪti wɔːrd",
    pronunciationTip: "Pronounce 'muh-TUR-ni-tee word'.",
    collocations: ["maternity ward staff", "visit the maternity ward", "hospital maternity ward"],
    phrasalVerbs: [
      {
        phrase: "welcome into",
        meaning: "bring new life into hospital nursery",
        arabic: "يَسْتَقْبِلُ المَوَالِيدَ فِي جَنَاحِ الوِلَادَة",
        example: "The family welcomed a new baby in the maternity ward.",
      },
    ],
    sentences: [
      {
        context: "Newborn Care",
        en: "The hospital maternity ward is designed to ensure comfort and bonding for new parents and babies.",
        ar: "صُمِّمَ جَنَاحُ الوِلَادَةِ لِتَوْفِيرِ الرَّاحَةِ وَالتَّرَابُطِ لِلأُمَّهَاتِ وَالمَوَالِيدِ.",
      },
      {
        context: "Family Joy",
        en: "Grandparents arrived at the maternity ward with colorful balloons to meet the newborn.",
        ar: "وَصَلَ الأَجْدَادُ إِلَى جَنَاحِ الوِلَادَةِ حَامِلِينَ بَالُونَاتٍ لِرُؤْيَةِ الحَفِيدِ.",
      },
      {
        context: "Specialized Staff",
        en: "Obstetricians and pediatric nurses provide attentive care across the maternity ward.",
        ar: "يُقَدِّمُ أَطِبَّاءُ النِّسَاءِ وَمُمَرِّضُو الأَطْفَالِ رِعَايَةً فَائِقَةً فِي جَنَاحِ الوِلَادَةِ.",
      },
    ],
    exampleSentence:
      "The hospital maternity ward is designed to ensure comfort and bonding for new parents and babies.",
    exampleArabic:
      "صُمِّمَ جَنَاحُ الوِلَادَةِ لِتَوْفِيرِ الرَّاحَةِ وَالتَّرَابُطِ لِلأُمَّهَاتِ وَالمَوَالِيدِ.",
  },
  sauce: {
    id: "sauce",
    arabic: "صَلْصَة (تَتْبِيلَةٌ سَائِلَةٌ مُنَكَّهَةٌ لِلأَطْبَاق)",
    partOfSpeech: "noun",
    phonetic: "sɔːs",
    pronunciationTip: "Pronounce 'SAWS' (/sɔːs/).",
    collocations: ["tomato sauce", "pasta sauce", "hot sauce", "dipping sauce"],
    phrasalVerbs: [
      {
        phrase: "pour over",
        meaning: "drizzle flavorful liquid over dish",
        arabic: "يَسْكُبُ الصَّلْصَةَ فَوْق",
        example: "The chef poured rich mushroom sauce over the chicken.",
      },
    ],
    sentences: [
      {
        context: "Flavoring Entree",
        en: "The chef poured a creamy mushroom sauce over the pan-seared chicken breast.",
        ar: "سَكَبَ الطَّاهِي صَلْصَةَ فِطْرٍ كَرِيمِيَّةً لَذِيذَةً فَوْقَ صَدْرِ الدَّجَاجِ المُحَمَّرِ.",
      },
      {
        context: "Dipping Condiment",
        en: "Crispy spring rolls were served with a sweet and spicy chili dipping sauce.",
        ar: "قُدِّمَتْ لَفَائِفُ السِّبْرِينْغ رُول مَعَ صَلْصَةِ فُلْفُلٍ حُلْوَةٍ وَحَارَّةٍ.",
      },
      {
        context: "Simmering",
        en: "A pot of authentic Italian marinara sauce simmered on the kitchen stove.",
        ar: "غَلَتْ صَلْصَةُ المَارِينَارَا الإِيطَالِيَّةُ بِبُطْءٍ عَلَى مَوْقِدِ المَطْبَخِ.",
      },
    ],
    exampleSentence: "The chef poured a creamy mushroom sauce over the pan-seared chicken breast.",
    exampleArabic:
      "سَكَبَ الطَّاهِي صَلْصَةَ فِطْرٍ كَرِيمِيَّةً لَذِيذَةً فَوْقَ صَدْرِ الدَّجَاجِ المُحَمَّرِ.",
  },
  "postal-worker": {
    id: "postal-worker",
    arabic: "عَامِلُ البَرِيد",
    partOfSpeech: "noun",
    collocations: ["use regularly", "check carefully", "keep handy"],
    sentences: [
      {
        context: "Mail Carrier",
        en: "The neighborhood carrier delivered packages in every kind of weather.",
        ar: "قَامَ عَامِلُ البَرِيدِ بِتَوْصِيلِ الطُّرُودِ فِي كُلِّ الظُّرُوفِ الجَوِّيَّة.",
      },
      {
        context: "Sorting Staff",
        en: "Dedicated logistics employees organize thousands of letters daily.",
        ar: "يُنَظِّمُ عَامِلُ البَرِيدِ فِي المَرْكَزِ آلَافَ الرَّسَائِلِ يَوْمِيًّا.",
      },
      {
        context: "Counter Clerk",
        en: "The clerk behind the postal counter weighed our heavy parcel.",
        ar: "قَامَ عَامِلُ البَرِيدِ خَلْفَ المِنْضَدَةِ بِوَزْنِ طَرْدِنَا الثَّقِيل.",
      },
    ],
    exampleSentence: "The neighborhood carrier delivered packages in every kind of weather.",
    exampleArabic:
      "قَامَ عَامِلُ البَرِيدِ بِتَوْصِيلِ الطُّرُودِ فِي كُلِّ الظُّرُوفِ الجَوِّيَّة.",
  },
  parcel: {
    id: "parcel",
    arabic: "طَرْد",
    partOfSpeech: "noun",
    collocations: ["use regularly", "check carefully", "keep handy"],
    sentences: [
      {
        context: "Cardboard Box",
        en: "The cardboard box contained birthday gifts wrapped in bubble plastic.",
        ar: "احْتَوَى الطَّرْدُ عَلَى هَدَايَا عِيدِ المِيلَادِ المَحْمِيَّةِ بِعِنَايَة.",
      },
      {
        context: "Package Delivery",
        en: "A courier delivered the registered shipping box to our doorstep.",
        ar: "سَلَّمَ السَّاعِي الطَّرْدَ المُسَجَّلَ إِلَى عَتَبَةِ بَابِنَا.",
      },
      {
        context: "Express Shipping",
        en: "Ensure the taped package is sealed securely before sending.",
        ar: "تَأَكَّدْ مِنْ إِغْلَاقِ الطَّرْدِ بِالشَّرِيطِ اللَّاصِقِ قَبْلَ إِرْسَالِه.",
      },
    ],
    exampleSentence: "The cardboard box contained birthday gifts wrapped in bubble plastic.",
    exampleArabic: "احْتَوَى الطَّرْدُ عَلَى هَدَايَا عِيدِ المِيلَادِ المَحْمِيَّةِ بِعِنَايَة.",
  },
};
