// Generated by scripts/shard_learning_content.mjs. Do not edit.
export const stories: Record<string, string> = {
  "hadith-niyyah-1":
    "In this section, you will learn about judged, motive niyyah, intend, migration hijrah, worldly, gain, marry.",
};
