// Generated by scripts/shard_learning_content.mjs. Do not edit.
export const stories: Record<string, string> = {
  "extended-family-1":
    "In this section, you will learn about Grandmother, Grandfather, Grandma, Grandpa, Great-Grandmother, Great-Grandfather, Nana, Papa, Granny, Grandparent, Aunt, Uncle, Cousin, First Cousin, Second Cousin. These are essential items to know.",
  "extended-family-2":
    "In this section, you will learn about Great-Aunt, Great-Uncle, Niece, Nephew, Cousin-in-Law, Mother-in-Law, Father-in-Law, Sister-in-Law, Brother-in-Law, Son-in-Law, Daughter-in-Law, In-Laws, Spouse's Family, Extended In-Laws, Family-in-Law. These are essential items to know.",
  "extended-family-3":
    "In this section, you will learn about Reunion, Holiday Dinner, Thanksgiving, Christmas, Easter, Birthday Celebration, Anniversary, Barbecue, Picnic, Family Wedding. These are essential items to know.",
};
