// Generated by scripts/shard_learning_content.mjs. Do not edit.
export const stories: Record<string, string> = {
  "student-life-1":
    "In this section, you will learn about Dorm Room, Roommate, Resident Advisor, Common Room, Laundry Room, Meal Plan, Dorm Key, Move-In, Move-Out, Off-Campus Housing, Club, Organization, Fraternity, Sorority, Student Government. These are essential items to know.",
  "student-life-2":
    "In this section, you will learn about Newspaper, Radio Station, Volunteer, Intramural Sports, Drama Club, Party, Concert, Game Day, Tailgate, Study Date, Coffee Shop, Food Court, Movie Night, Road Trip, Spring Formal. These are essential items to know.",
  "student-life-3":
    "In this section, you will learn about Tuition, Scholarship, Financial Aid, Student Loan, Work-Study, Part-Time Job, Budget, Textbook Cost, Student Discount, Grant. These are essential items to know.",
};
