// Generated by scripts/shard_learning_content.mjs. Do not edit.
export const stories: Record<string, string> = {
  "shades-tones-1":
    "In this section, you will learn about Crimson, Scarlet, Maroon, Rose, Blush, Burgundy, Ruby, Cherry, Raspberry, Fuchsia, Navy, Sky Blue, Royal Blue, Aqua, Mint. These are essential items to know.",
  "shades-tones-2":
    "In this section, you will learn about Emerald, Olive, Forest Green, Seafoam, Jade, Gold, Amber, Mustard, Honey, Lemon, Peach, Tangerine, Rust, Copper, Bronze. These are essential items to know.",
  "shades-tones-3":
    "In this section, you will learn about Ivory, Cream, Beige, Tan, Khaki, Taupe, Charcoal, Slate, Ash, Silver, Plum, Mauve, Lilac, Orchid, Wine. These are essential items to know.",
  "shades-tones-4":
    "In this section, you will learn about Eggplant, Periwinkle, Champagne, Sand, Smoke. These are essential items to know.",
};
