// Generated by scripts/shard_learning_content.mjs. Do not edit.
export const stories: Record<string, string> = {
  "bathroom-1":
    "In this section, you will learn about Bathtub, Shower, Toilet, Sink, Faucet, Drain, Mirror, Towel Rack, Cabinet, and Tiles. These are essential items to know.",
  "bathroom-2":
    "In this section, you will learn about Soap, Shampoo, Conditioner, Toothbrush, Toothpaste, Towel, Comb, Hairbrush, Lotion, and Deodorant. These are essential items to know.",
  "bathroom-3":
    "In this section, you will learn about Toilet Paper, Cotton Balls, Cotton Swab, Razor, Nail Clipper, Hair Dryer, Scale, Laundry Basket, First Aid Kit, and Thermometer. These are essential items to know.",
  "bathroom-4":
    "In this section, you will learn about Bath Mat, Shower Curtain, Shower Head, Bath Towel, Hand Towel, Washcloth, Soap Dish, Shampoo Bottle, Rubber Duck, and Shower Gel. These are essential items to know.",
  "bathroom-5":
    "In this section, you will learn about Face Cream, Sunscreen, Lip Balm, Hand Soap, Body Wash, Mouthwash, Dental Floss, Face Wash, Hand Sanitizer, and Wet Wipes. These are essential items to know.",
  "bathroom-6":
    "In this section, you will learn about Sponge, Brush, Bucket, Gloves, Spray Bottle, Cloth, Plunger, Squeegee, Tissue, Wash Hands, Brush Teeth, Take a Shower, Dry Off, Flush, Comb Hair, Apply Lotion, and Gargle. These are essential items to know.",
};
