// Generated by scripts/shard_learning_content.mjs. Do not edit.
export const stories: Record<string, string> = {
  "space-center-1":
    "In this section, you will learn about rocket, space shuttle, satellite, capsule, lander, rover, probe, booster, payload, launch pad, Sun, Mercury, Venus, Earth, Mars. These are essential items to know.",
  "space-center-2":
    "In this section, you will learn about Jupiter, Saturn, Uranus, Neptune, Moon, asteroid, comet, astronaut, spacesuit, helmet, mission control, countdown, liftoff, orbit, spacewalk. These are essential items to know.",
  "space-center-3":
    "In this section, you will learn about docking, re-entry, splashdown, telescope, star, galaxy, nebula, black hole, supernova, constellation, meteor, aurora, eclipse, cosmic dust, solar panel. These are essential items to know.",
  "space-center-4":
    "In this section, you will learn about antenna, radar, computer, fuel tank, thruster, heat shield, parachute, robotic arm, laboratory. These are essential items to know.",
};
