// Generated by scripts/shard_learning_content.mjs. Do not edit.
export const stories: Record<string, string> = {
  "bar-culture-1":
    "In this section, you will learn about Sports Bar, Dive Bar, Wine Bar, Speakeasy, Rooftop Bar, Tiki Bar, Pub, Tavern, Brewpub, Lounge, Happy Hour, Last Call, Tab, Tip, Round of Drinks. These are essential items to know.",
  "bar-culture-2":
    "In this section, you will learn about Toast, Cheers, Designated Driver, Bar Tab, Cover Charge, Live Music, Karaoke, Trivia Night, Dart Board, Pool Table, Jukebox, Comedy Night, Open Mic, Dance Floor, Big Screen. These are essential items to know.",
  "bar-culture-3":
    "In this section, you will learn about Moderation, Ride Share, Water Break, Know Your Limit, Pace Yourself, Eat Before, ID Check, Legal Age, Cut Off. These are essential items to know.",
};
