// Generated by scripts/shard_learning_content.mjs. Do not edit.
export const stories: Record<string, string> = {
  "bird-sanctuary-1":
    "In this section, you will learn about Robin, Sparrow, Blue Jay, Cardinal, Crow, Pigeon, Dove, Finch, Wren, Starling, Duck, Swan, Goose, Heron, Pelican. These are essential items to know.",
  "bird-sanctuary-2":
    "In this section, you will learn about Flamingo, Crane, Seagull, Kingfisher, Cormorant, Eagle, Hawk, Falcon, Owl, Osprey, Vulture, Kite, Harrier, Kestrel, Condor. These are essential items to know.",
  "bird-sanctuary-3":
    "In this section, you will learn about Beak, Feather, Wing, Talon, Crest, Tail, Breast, Egg, Nest, Perch, Fly, Sing, Migrate, Nest Building, Feed. These are essential items to know.",
  "bird-sanctuary-4":
    "In this section, you will learn about Preen, Soar, Dive, Flock, Roost, Tree, Branch, Birdhouse, Feeder, Bath, Pond, Wetland, Meadow, Cliff, Hedge. These are essential items to know.",
};
