// Generated by scripts/shard_learning_content.mjs. Do not edit.
export const stories: Record<string, string> = {
  "dentist-1":
    "In this section, you will learn about Dental Mirror, Probe, Scaler, Dental Drill, Suction Tube, Polisher, Dental Pick, Tweezers, Syringe, Filling Tool, Excavator, Burnisher, Amalgam Carrier, Dental Spatula, Rubber Dam. These are essential items to know.",
  "dentist-2":
    "In this section, you will learn about Bite Block, Matrix Band, Dental Chair, Overhead Light, Rinse Bowl, Tray Table, Monitor, X-Ray Machine, Dental Lamp, Foot Pedal, Armrest, Headrest, Cuspidor, Instrument Panel, Air/Water Syringe. These are essential items to know.",
  "dentist-3":
    "In this section, you will learn about Dental Stool, Sterilizer, Autoclave, Toothbrush, Toothpaste, Dental Floss, Mouthwash, Fluoride Gel, Dental Wax, Retainer, Braces, Mouth Guard, Whitening Strip, Interdental Brush, Denture Cleaner. These are essential items to know.",
  "dentist-4":
    "In this section, you will learn about Desensitizing Paste, Dental Cement, Temporary Filling, Night Guard, Dentist, Dental Hygienist, Dental Assistant, Receptionist, Oral Surgeon, Orthodontist, Dental Technician, Patient, Child Patient, Parent, Periodontist. These are essential items to know.",
  "dentist-5":
    "In this section, you will learn about Prosthodontist, Endodontist, Pediatric Dentist, Dental Nurse, Dental Radiographer, Tooth, Molar, Canine, Incisor, Gum, Tongue, Jaw, Root, Enamel, Crown. These are essential items to know.",
  "dentist-6":
    "In this section, you will learn about Premolar, Wisdom Tooth, Baby Tooth, Palate, Uvula, Dentin, Cementum, Periodontal Ligament, Waiting Room, Reception Desk, Magazine, Fish Tank, Certificate, Poster, Appointment Card. These are essential items to know.",
  "dentist-7":
    "In this section, you will learn about Insurance Form, Clipboard, Toy Box, Sterilization Room, X-Ray Room, Consultation Room, Dental Records, Consent Form, Treatment Plan, Mirror, Drill, Suction, Light, Tray, Filling. These are essential items to know.",
  "dentist-8":
    "In this section, you will learn about Mouthguard, Floss, Cleaning, Checkup, Cavity, Extraction, Whitening, Sealant, Impression, Anesthesia. These are essential items to know.",
};
