// Generated by scripts/shard_learning_content.mjs. Do not edit.
export const stories: Record<string, string> = {
  "bicycle-shop-1":
    "In this section, you will learn about Road Bike, Mountain Bike, Hybrid, Bmx, Cruiser, Folding Bike, Electric Bike, Tandem, Kids Bike, Cargo Bike, Wheel, Tire, Chain, Pedal, Handlebar. These are essential items to know.",
  "bicycle-shop-2":
    "In this section, you will learn about Seat, Brake, Gear, Spoke, Frame, Helmet, Lock, Light, Bell, Mirror, Basket, Rack, Pump, Water Bottle, Phone Mount. These are essential items to know.",
  "bicycle-shop-3":
    "In this section, you will learn about Jersey, Shorts, Gloves, Shoes, Sunglasses, Rain Jacket, Reflective Vest, Cap, Arm Warmers, Leg Warmers, Wrench, Tire Lever, Patch Kit, Multi Tool, Chain Tool. These are essential items to know.",
  "bicycle-shop-4":
    "In this section, you will learn about Grease, Stand, Spoke Wrench, Cable, Brake Pad, Bike Lane, Trail, Path, Hill, Turn, Signal, Stop, Park, Lock Up, Flat Tire. These are essential items to know.",
};
