// Generated by scripts/shard_learning_content.mjs. Do not edit.
export const stories: Record<string, string> = {
  "research-study-1":
    "In this section, you will learn about Textbook, Journal, Database, Search Engine, Bibliography, Citation, Footnote, Index, Abstract, Peer Review, Essay, Thesis, Dissertation, Paper, Report. These are essential items to know.",
  "research-study-2":
    "In this section, you will learn about Literature Review, Methodology, Conclusion, Introduction, Appendix, Note-Taking, Flashcard, Mind Map, Outline, Highlight, Summarize, Review, Memorize, Practice Test, Study Group. These are essential items to know.",
  "research-study-3":
    "In this section, you will learn about Plagiarism, Reference, Original Work, Paraphrase, Quote, Source, Academic Honesty, Turnitin, Honor Code. These are essential items to know.",
};
