// Generated by scripts/shard_learning_content.mjs. Do not edit.
export const stories: Record<string, string> = {
  "beverages-1":
    "In this section, you will learn about Coffee, Tea, Hot Chocolate, Espresso, Cappuccino, Latte, Mocha, Herbal Tea, Green Tea, Chai, Water, Iced Tea, Lemonade, Iced Coffee, Milkshake. These are essential items to know.",
  "beverages-2":
    "In this section, you will learn about Smoothie, Slushie, Sparkling Water, Tonic Water, Cold Brew, Orange Juice, Apple Juice, Grape Juice, Cranberry Juice, Tomato Juice, Carrot Juice, Pineapple Juice, Mango Juice, Pomegranate Juice, Fresh Squeeze. These are essential items to know.",
  "beverages-3":
    "In this section, you will learn about Soda, Cola, Ginger Ale, Root Beer, Cream Soda, Lemon-Lime, Energy Drink, Sports Drink, Kombucha, Coconut Water, Beer, Wine, Champagne, Whiskey, Vodka. These are essential items to know.",
  "beverages-4":
    "In this section, you will learn about Gin, Rum, Tequila, Brandy, Cocktail. These are essential items to know.",
};
