// Generated by scripts/shard_learning_content.mjs. Do not edit.
export const stories: Record<string, string> = {
  "reptile-house-1":
    "In this section, you will learn about Cobra, Python, Rattlesnake, Boa, Viper, Corn Snake, King Snake, Anaconda, Mamba, Garter Snake, Gecko, Iguana, Chameleon, Monitor, Skink. These are essential items to know.",
  "reptile-house-2":
    "In this section, you will learn about Bearded Dragon, Anole, Komodo Dragon, Basilisk, Horned Lizard, Turtle, Tortoise, Sea Turtle, Snapping Turtle, Crocodile, Alligator, Caiman, Terrapin, Softshell, Gharial. These are essential items to know.",
  "reptile-house-3":
    "In this section, you will learn about Scale, Shell, Fang, Tongue, Tail, Claw, Eye, Jaw, Skin, Venom, Terrarium, Heat Lamp, Water Dish, Branch, Rock. These are essential items to know.",
  "reptile-house-4":
    "In this section, you will learn about Sand, Moss, Hide, Log, Misting System, Shed, Bask, Hunt, Swim, Burrow, Climb, Camouflage, Hiss, Strike, Coil. These are essential items to know.",
};
