// Generated by scripts/shard_learning_content.mjs. Do not edit.
export const stories: Record<string, string> = {
  "giving-directions-1":
    "In this section, you will learn about Left, Right, Straight, Forward, Backward, Up, Down, Turn, Stop, Go, North, South, East, West, Northeast. These are essential items to know.",
  "giving-directions-2":
    "In this section, you will learn about Northwest, Southeast, Southwest, Compass, Direction, Near, Far, Close, Nearby, Distant, Here, There, Everywhere, Nowhere, Somewhere. These are essential items to know.",
  "giving-directions-3":
    "In this section, you will learn about Intersection, Corner, Block, Crosswalk, Traffic Light, Roundabout, One-Way, Dead End, Highway, Sidewalk, Building, Bridge, Monument, Fountain, Statue. These are essential items to know.",
  "giving-directions-4":
    "In this section, you will learn about Tower, Church, Park, School, Hospital. These are essential items to know.",
};
