// Generated by scripts/shard_learning_content.mjs. Do not edit.
export const stories: Record<string, string> = {
  "freelancing-remote-work-1":
    "In this section, you will learn about Freelancer, Contractor, Consultant, Gig, Portfolio, Client, Project, Proposal, Rate, Retainer, Zoom, Slack, Trello, Notion, Google Drive. These are essential items to know.",
  "freelancing-remote-work-2":
    "In this section, you will learn about Dropbox, Figma, Miro, Asana, Calendly, Home Office, Routine, Boundaries, Breaks, Exercise, Ergonomics, Time Zone, Flexibility, Isolation, Burnout. These are essential items to know.",
  "freelancing-remote-work-3":
    "In this section, you will learn about Invoice, Contract, Tax Deduction, Self-Employment Tax, Health Insurance, Retirement Planning, LLC, 1099, Scope Creep, Non-Disclosure, Pomodoro, Time Blocking, Deep Work, Focus Mode, Do Not Disturb. These are essential items to know.",
  "freelancing-remote-work-4":
    "In this section, you will learn about Batch Processing, Automation, Template, Shortcut, Review. These are essential items to know.",
};
