// Generated by scripts/shard_learning_content.mjs. Do not edit.
export const stories: Record<string, string> = {
  "hospital-1":
    "In this section, you will learn about doctor, nurse, surgeon, paramedic, receptionist, pharmacist, anesthesiologist, radiologist, pediatrician, psychiatrist, midwife, orderly, ophthalmologist, dermatologist, cardiologist. These are essential items to know.",
  "hospital-2":
    "In this section, you will learn about neurologist, orthopedist, ENT specialist, urologist, oncologist, gastroenterologist, pulmonologist, physiotherapist, dietitian, lab technician, EMT, emergency room, waiting room, operating room, recovery room. These are essential items to know.",
  "hospital-3":
    "In this section, you will learn about patient room, intensive care unit, maternity ward, nursery, laboratory, radiology, cafeteria, pharmacy, consulting room, triage area, burn unit, dialysis unit, isolation room, sterilization room, rehabilitation room. These are essential items to know.",
  "hospital-4":
    "In this section, you will learn about blood bank, stethoscope, syringe, thermometer, blood pressure monitor, IV drip, wheelchair, stretcher, oxygen mask, defibrillator, scalpel, bandage, cast, ventilator, catheter. These are essential items to know.",
  "hospital-5":
    "In this section, you will learn about pulse oximeter, ECG machine, nebulizer, tourniquet, surgical mask, reflex hammer, heart, lungs, brain, bone, blood, pulse, fever, infection, injury. These are essential items to know.",
  "hospital-6":
    "In this section, you will learn about fracture, allergy, rash, liver, kidneys, spine, stomach, intestines, muscles, arteries, appendix, inflammation, nausea, examination, diagnosis. These are essential items to know.",
  "hospital-7":
    "In this section, you will learn about prescription, surgery, X-ray, blood test, injection, vaccination, ultrasound, MRI scan, stitches, physical therapy, biopsy, dialysis, transfusion, chemotherapy, endoscopy. These are essential items to know.",
  "hospital-8":
    "In this section, you will learn about CT scan, colonoscopy, transplant, hospital bed, pillow, blanket, gown, chart, clipboard, medicine, pills, ointment, crutches, walker, ambulance. These are essential items to know.",
  "hospital-9":
    "In this section, you will learn about face shield, hand sanitizer, sharps container, bedpan, patient wristband, call button, IV pole, oxygen tank. These are essential items to know.",
};
