// Generated by scripts/shard_learning_content.mjs. Do not edit.
export const stories: Record<string, string> = {
  "skeleton-1":
    "In this section, you will learn about Skull, Cranium, Jaw Bone, Cheekbone, Eye Socket, Nasal Bone, Temple Bone, Foramen Magnum, Mandible, Maxilla, Spine, Vertebra, Cervical Spine, Thoracic Spine, Lumbar Spine. These are essential items to know.",
  "skeleton-2":
    "In this section, you will learn about Sacrum, Coccyx, Rib, Sternum, Ribcage, Clavicle, Scapula, Humerus, Radius, Ulna, Carpals, Metacarpals, Phalanges, Shoulder Joint, Elbow Joint. These are essential items to know.",
  "skeleton-3":
    "In this section, you will learn about Pelvis, Femur, Patella, Tibia, Fibula, Tarsals, Metatarsals, Toe Bones, Hip Joint, Knee Joint, Joint, Cartilage, Ligament, Tendon, Bone Marrow. These are essential items to know.",
  "skeleton-4":
    "In this section, you will learn about Periosteum, Synovial Fluid, Disc, Meniscus, Bursa, Calcium, Vitamin D, Osteoporosis, Fracture, X-Ray, Cast, Splint, Bone Density, Growth Plate, Skeleton Model. These are essential items to know.",
};
