// Generated by scripts/shard_learning_content.mjs. Do not edit.
export const stories: Record<string, string> = {
  "car-wash-1":
    "In this section, you will learn about Automatic Wash, Hand Wash, Self Service, Touchless, Foam Wash, Wax Wash, Undercarriage, Wheel Wash, Rinse, Dry, Pressure Washer, Foam Cannon, Brush, Roller, Dryer. These are essential items to know.",
  "car-wash-2":
    "In this section, you will learn about Vacuum, Air Freshener, Towel, Sponge, Bucket, Car Soap, Wax, Tire Shine, Glass Cleaner, Interior Cleaner, Polish, Clay Bar, Microfiber, Degreaser, Protectant. These are essential items to know.",
  "car-wash-3":
    "In this section, you will learn about Hood, Roof, Door, Trunk, Bumper, Mirror, Wheel, Tire, Windshield, Headlight, Bay, Track, Conveyor, Coin Machine, Token. These are essential items to know.",
  "car-wash-4":
    "In this section, you will learn about Timer, Drain, Sign, Menu Board, Waiting Area, Pre Rinse, Soap Spray, Scrub, Wax Coat, Blow Dry, Hand Dry, Vacuum Interior, Wipe Dash, Freshen. These are essential items to know.",
};
