// Generated by scripts/shard_learning_content.mjs. Do not edit.
export const stories: Record<string, string> = {
  "festival-1":
    "In this section, you will learn about Banner, Bunting, Balloon, Streamer, Lantern, Garland, Flag, Ribbon, Confetti, Piñata, Wreath, Paper Flower, Barbecue, Kebab, Pizza Slice. These are essential items to know.",
  "festival-2":
    "In this section, you will learn about Taco, Samosa, Spring Roll, Waffle, Crepe, Fruit Skewer, Roasted Corn, Doughnut, Fried Chicken, Lemonade, Smoothie, Hot Chocolate, Milkshake, Juice Box, Cotton Candy. These are essential items to know.",
  "festival-3":
    "In this section, you will learn about Caramel Apple, Popcorn, Churro, Ice Cream, Stage, Band, Singer, DJ Booth, Speaker, Dance Floor, Fire Dancer, Acrobat, Stilt Walker, Face Painter, Parade. These are essential items to know.",
  "festival-4":
    "In this section, you will learn about Carnival Game, Photo Booth, Arts and Crafts, Puppet Show, Magic Show, Talent Contest, Treasure Hunt, Costume Contest, Raffle, Ticket, Wristband, Map, Folding Chair, Blanket, Sunscreen. These are essential items to know.",
  "festival-5":
    "In this section, you will learn about Water Bottle, Backpack, Rain Poncho, Portable Charger, String Lights, Fireworks, Live Music, Dance, Magician, Face Paint, Clown, Corn Dog, Funnel Cake, Pretzel, Candy Apple. These are essential items to know.",
};
