// Generated by scripts/shard_learning_content.mjs. Do not edit.
export const stories: Record<string, string> = {
  "river-1":
    "In this section, you will learn about Current, Rapids, Waterfall, Pool, Bend, Delta, Tributary, Bank, Bed, Estuary, Fish, Frog, Turtle, Heron, Otter. These are essential items to know.",
  "river-2":
    "In this section, you will learn about Beaver, Dragonfly, Duck, Salmon, Crayfish, Reed, Lily Pad, Cattail, Algae, Willow, Duckweed, Water Lily, Moss, Riverside Grass, Mangrove. These are essential items to know.",
  "river-3":
    "In this section, you will learn about Canoe, Kayak, Raft, Rowboat, Motorboat, Paddleboard, Inner Tube, Pontoon, Sailboat, Fishing Boat, Paddle, Life Jacket, Fishing Rod, Tackle Box, Net. These are essential items to know.",
  "river-4":
    "In this section, you will learn about Bucket, Waders, Anchor, Rope, Cooler, Fishing, Swimming, Kayaking, Rafting, Canoeing, Tubing, Wading, Bird Watching, Picnic, Skipping Stones. These are essential items to know.",
};
