// Generated by scripts/shard_learning_content.mjs. Do not edit.
export const stories: Record<string, string> = {
  "cocktail-bar-1":
    "In this section, you will learn about Bar Counter, Bar Stool, Back Bar, Draft Taps, Bottle Display, Ice Well, Speed Rail, Garnish Tray, Bar Mat, Lounge Area, Cocktail Glass, Highball Glass, Rocks Glass, Shot Glass, Wine Glass. These are essential items to know.",
  "cocktail-bar-2":
    "In this section, you will learn about Champagne Flute, Beer Mug, Collins Glass, Coupe Glass, Snifter, Cocktail Shaker, Jigger, Muddler, Bar Spoon, Strainer, Ice Tongs, Bottle Opener, Corkscrew, Citrus Press, Zester. These are essential items to know.",
  "cocktail-bar-3":
    "In this section, you will learn about Bartender, Barback, Mixologist, Bouncer, Host, Cocktail Waitress, Manager, Sommelier, DJ, Promoter. These are essential items to know.",
};
